.TH abduco
.PP
.RS
Terminal session manager.
More information: \[la]http://www.brain-dump.org/projects/abduco/\[ra]\&.
.RE
.RS
.IP \(bu 2
List sessions:
.RE
.PP
\fB\fCabduco\fR
.RS
.IP \(bu 2
Attach to a session, creating it if it doesn't exist:
.RE
.PP
\fB\fCabduco \-A {{name}} {{bash}}\fR
.RS
.IP \(bu 2
Attach to a session with \fB\fCdvtm\fR, creating it if it doesn't exist:
.RE
.PP
\fB\fCabduco \-A {{name}}\fR
.RS
.IP \(bu 2
Detach from a session:
.RE
.PP
\fB\fCCtrl + \\\fR
.RS
.IP \(bu 2
Attach to a session in read\-only mode:
.RE
.PP
\fB\fCabduco \-Ar {{name}}\fR
