.TH ac
.PP
.RS
Print statistics on how long users have been connected.
More information: \[la]https://man.openbsd.org/ac\[ra]\&.
.RE
.RS
.IP \(bu 2
Print how long the current user has been connected in hours:
.RE
.PP
\fB\fCac\fR
.RS
.IP \(bu 2
Print how long users have been connected in hours:
.RE
.PP
\fB\fCac \-p\fR
.RS
.IP \(bu 2
Print how long a particular user has been connected in hours:
.RE
.PP
\fB\fCac \-p {{username}}\fR
.RS
.IP \(bu 2
Print how long a particular user has been connected in hours per day (with total):
.RE
.PP
\fB\fCac \-dp {{username}}\fR
