.TH acyclic
.PP
.RS
Make a directed graph acyclic by reversing some edges.
Graphviz filters: \fB\fCacyclic\fR, \fB\fCbcomps\fR, \fB\fCcomps\fR, \fB\fCedgepaint\fR, \fB\fCgvcolor\fR, \fB\fCgvpack\fR, \fB\fCmingle\fR, \fB\fCnop\fR, \fB\fCsccmap\fR, \fB\fCtred\fR, & \fB\fCunflatten\fR\&.
More information: \[la]https://graphviz.org/pdf/acyclic.1.pdf\[ra]\&.
.RE
.RS
.IP \(bu 2
Make a directed graph acyclic by reversing some edges:
.RE
.PP
\fB\fCacyclic {{path/to/input.gv}} > {{path/to/output.gv}}\fR
.RS
.IP \(bu 2
Print if a graph is acyclic, has a cycle, or is undirected, producing no output graph:
.RE
.PP
\fB\fCacyclic \-v \-n {{path/to/input.gv}}\fR
.RS
.IP \(bu 2
Display help for \fB\fCacyclic\fR:
.RE
.PP
\fB\fCacyclic \-?\fR
