.TH AdGuardHome
.PP
.RS
A network\-wide software for blocking ads & tracking.
More information: \[la]https://github.com/AdguardTeam/AdGuardHome\[ra]\&.
.RE
.RS
.IP \(bu 2
Run AdGuard Home:
.RE
.PP
\fB\fCAdGuardHome\fR
.RS
.IP \(bu 2
Run AdGuard Home with a specific config:
.RE
.PP
\fB\fCAdGuardHome \-\-config {{path/to/AdGuardHome.yaml}}\fR
.RS
.IP \(bu 2
Set the work directory for data to be stored in:
.RE
.PP
\fB\fCAdGuardHome \-\-work\-dir {{path/to/directory}}\fR
.RS
.IP \(bu 2
Install or uninstall AdGuard Home as a service:
.RE
.PP
\fB\fCAdGuardHome \-\-service {{install|uninstall}}\fR
.RS
.IP \(bu 2
Start the AdGuard Home service:
.RE
.PP
\fB\fCAdGuardHome \-\-service start\fR
.RS
.IP \(bu 2
Reload the configuration for the AdGuard Home service:
.RE
.PP
\fB\fCAdGuardHome \-\-service reload\fR
.RS
.IP \(bu 2
Stop or restart the AdGuard Home service:
.RE
.PP
\fB\fCAdGuardHome \-\-service {{stop|restart}}\fR
