.TH afconvert
.PP
.RS
Convert between AFF and raw file formats.
More information: \[la]https://manned.org/afconvert.1\[ra]\&.
.RE
.RS
.IP \(bu 2
Use a specific extension (default: \fB\fCaff\fR):
.RE
.PP
\fB\fCafconvert \-a {{extension}} {{path/to/input_file}} {{path/to/output_file1 path/to/output_file2 ...}}\fR
.RS
.IP \(bu 2
Use a specific compression level (default: \fB\fC7\fR):
.RE
.PP
\fB\fCafconvert \-X{{0..7}} {{path/to/input_file}} {{path/to/output_file1 path/to/output_file2 ...}}\fR
