.TH agate
.PP
.RS
A simple server for the Gemini network protocol.
More information: \[la]https://github.com/mbrubeck/agate\[ra]\&.
.RE
.RS
.IP \(bu 2
Run and generate a private key and certificate:
.RE
.PP
\fB\fCagate \-\-content {{path/to/content/}} \-\-addr {{[::]:1965}} \-\-addr {{0.0.0.0:1965}} \-\-hostname {{example.com}} \-\-lang {{en\-US}}\fR
.RS
.IP \(bu 2
Run server:
.RE
.PP
\fB\fCagate {{path/to/file}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCagate \-h\fR
