.TH aireplay\-ng
.PP
.RS
Inject packets into a wireless network.
Part of \fB\fCaircrack\-ng\fR\&.
More information: \[la]https://www.aircrack-ng.org/doku.php?id=aireplay-ng\[ra]\&.
.RE
.RS
.IP \(bu 2
Send a specific number of disassociate packets given an access point's MAC address, a client's MAC address and an interface:
.RE
.PP
\fB\fCsudo aireplay\-ng \-\-deauth {{count}} \-\-bssid {{ap_mac}} \-\-dmac {{client_mac}} {{interface}}\fR
