.TH amass
.PP
.RS
In\-depth Attack Surface Mapping and Asset Discovery tool.
Some subcommands such as \fB\fCamass db\fR have their own usage documentation.
More information: \[la]https://github.com/OWASP/Amass\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute an Amass subcommand:
.RE
.PP
\fB\fCamass {{subcommand}}\fR
.RS
.IP \(bu 2
Show general help:
.RE
.PP
\fB\fCamass \-help\fR
.RS
.IP \(bu 2
Show help on an Amass subcommand (like \fB\fCintel\fR, \fB\fCenum\fR, etc.):
.RE
.PP
\fB\fCamass \-help {{subcommand}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCamass \-version\fR
