.TH ani\-cli
.PP
.RS
A cli to browse and watch anime.
More information: \[la]https://github.com/pystardust/ani-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Search anime by name:
.RE
.PP
\fB\fCani\-cli "{{anime_name}}"\fR
.RS
.IP \(bu 2
Download episode:
.RE
.PP
\fB\fCani\-cli \-d "{{anime_name}}"\fR
.RS
.IP \(bu 2
Use VLC as the media player:
.RE
.PP
\fB\fCani\-cli \-v "{{anime_name}}"\fR
.RS
.IP \(bu 2
Specify episode to watch:
.RE
.PP
\fB\fCani\-cli \-a {{episode_number}} "{{anime_name}}"\fR
.RS
.IP \(bu 2
Continue watching anime from history:
.RE
.PP
\fB\fCani\-cli \-c\fR
.RS
.IP \(bu 2
Update \fB\fCani\-cli\fR:
.RE
.PP
\fB\fCani\-cli \-U\fR
