.TH anki
.PP
.RS
Powerful, intelligent flashcard program.
More information: \[la]https://docs.ankiweb.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch \fB\fCanki\fR:
.RE
.PP
\fB\fCanki\fR
.RS
.IP \(bu 2
Launch \fB\fCanki\fR with a specific profile:
.RE
.PP
\fB\fCanki \-p {{profile_name}}\fR
.RS
.IP \(bu 2
Launch \fB\fCanki\fR in a specific language:
.RE
.PP
\fB\fCanki \-l {{language}}\fR
.RS
.IP \(bu 2
Launch \fB\fCanki\fR from a specific directory instead of the default (\fB\fC~/Anki\fR):
.RE
.PP
\fB\fCanki \-b {{path/to/directory}}\fR
