.TH antibody
.PP
.RS
"The fastest" shell plugin manager.
More information: \[la]https://getantibody.github.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Bundle all plugins for static loading:
.RE
.PP
\fB\fCantibody bundle < {{~/.zsh_plugins.txt}} > {{~/.zsh_plugins.sh}}\fR
.RS
.IP \(bu 2
Update all bundles:
.RE
.PP
\fB\fCantibody update\fR
.RS
.IP \(bu 2
List all installed plugins:
.RE
.PP
\fB\fCantibody list\fR
