.TH anytopnm
.PP
.RS
Converts an arbitrary type of image file to common image formats.
More information: \[la]https://netpbm.sourceforge.net/doc/anytopnm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert an input image to PBM, PGM, or PPM format irrespective of the input type:
.RE
.PP
\fB\fCanytopnm {{path/to/input}} > {{path/to/output.pnm}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCanytopnm \-version\fR
