.TH apktool
.PP
.RS
Reverse engineer APK files.
More information: \[la]https://ibotpeaches.github.io/Apktool/\[ra]\&.
.RE
.RS
.IP \(bu 2
Decode an APK file:
.RE
.PP
\fB\fCapktool d {{path/to/file.apk}}\fR
.RS
.IP \(bu 2
Build an APK file from a directory:
.RE
.PP
\fB\fCapktool b {{path/to/directory}}\fR
.RS
.IP \(bu 2
Install and store a framework:
.RE
.PP
\fB\fCapktool if {{path/to/framework.apk}}\fR
