.TH apm
.PP
.RS
Atom editor Package Manager.
See \fB\fCatom\fR\&.
More information: \[la]https://github.com/atom/apm\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a package from \[la]http://atom.io/packages\[ra] or a theme from \[la]http://atom.io/themes\[ra]:
.RE
.PP
\fB\fCapm install {{package}}\fR
.RS
.IP \(bu 2
Remove a package/theme:
.RE
.PP
\fB\fCapm remove {{package}}\fR
.RS
.IP \(bu 2
Upgrade a package/theme:
.RE
.PP
\fB\fCapm upgrade {{package}}\fR
