.TH apropos
.PP
.RS
Search the manual pages for names and descriptions.
More information: \[la]https://manned.org/apropos\[ra]\&.
.RE
.RS
.IP \(bu 2
Search for a keyword using a regular expression:
.RE
.PP
\fB\fCapropos {{regular_expression}}\fR
.RS
.IP \(bu 2
Search without restricting the output to the terminal width:
.RE
.PP
\fB\fCapropos \-l {{regular_expression}}\fR
.RS
.IP \(bu 2
Search for pages that contain all the expressions given:
.RE
.PP
\fB\fCapropos {{regular_expression_1}} \-a {{regular_expression_2}} \-a {{regular_expression_3}}\fR
