.TH arc
.PP
.RS
Arcanist: A CLI for Phabricator.
More information: \[la]https://secure.phabricator.com/book/phabricator/article/arcanist/\[ra]\&.
.RE
.RS
.IP \(bu 2
Send the changes to Differential for review:
.RE
.PP
\fB\fCarc diff\fR
.RS
.IP \(bu 2
Show pending revision information:
.RE
.PP
\fB\fCarc list\fR
.RS
.IP \(bu 2
Update Git commit messages after review:
.RE
.PP
\fB\fCarc amend\fR
.RS
.IP \(bu 2
Push Git changes:
.RE
.PP
\fB\fCarc land\fR
