.TH arp\-scan
.PP
.RS
Send ARP packets to hosts (specified as IP addresses or hostnames) to scan the local network.
More information: \[la]https://github.com/royhills/arp-scan\[ra]\&.
.RE
.RS
.IP \(bu 2
Scan the current local network:
.RE
.PP
\fB\fCarp\-scan \-\-localnet\fR
.RS
.IP \(bu 2
Scan an IP network with a custom bitmask:
.RE
.PP
\fB\fCarp\-scan {{192.168.1.1}}/{{24}}\fR
.RS
.IP \(bu 2
Scan an IP network within a custom range:
.RE
.PP
\fB\fCarp\-scan {{127.0.0.0}}\-{{127.0.0.31}}\fR
.RS
.IP \(bu 2
Scan an IP network with a custom net mask:
.RE
.PP
\fB\fCarp\-scan {{10.0.0.0}}:{{255.255.255.0}}\fR
