.TH arp
.PP
.RS
Show and manipulate your system's ARP cache.
More information: \[la]https://manned.org/arp\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the current ARP table:
.RE
.PP
\fB\fCarp \-a\fR
.RS
.IP \(bu 2
Delete a specific entry:
.RE
.PP
\fB\fCarp \-d {{address}}\fR
.RS
.IP \(bu 2
Create an entry in the ARP table:
.RE
.PP
\fB\fCarp \-s {{address}} {{mac_address}}\fR
