.TH astronomer
.PP
.RS
Tool that detects illegitimate stars from bot accounts on GitHub projects.
More information: \[la]https://github.com/Ullaakut/astronomer\[ra]\&.
.RE
.RS
.IP \(bu 2
Scan a repository:
.RE
.PP
\fB\fCastronomer {{tldr\-pages/tldr\-node\-client}}\fR
.RS
.IP \(bu 2
Scan the maximum amount of stars in the repository:
.RE
.PP
\fB\fCastronomer {{tldr\-pages/tldr\-node\-client}} \-\-stars {{50}}\fR
.RS
.IP \(bu 2
Scan a repository including comparative reports:
.RE
.PP
\fB\fCastronomer {{tldr\-pages/tldr\-node\-client}} \-\-verbose\fR
