.TH atoum
.PP
.RS
A simple, modern and intuitive unit testing framework for PHP.
More information: \[la]http://atoum.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a configuration file:
.RE
.PP
\fB\fCatoum \-\-init\fR
.RS
.IP \(bu 2
Run all tests:
.RE
.PP
\fB\fCatoum\fR
.RS
.IP \(bu 2
Run tests using the specified configuration file:
.RE
.PP
\fB\fCatoum \-c {{path/to/file}}\fR
.RS
.IP \(bu 2
Run a specific test file:
.RE
.PP
\fB\fCatoum \-f {{path/to/file}}\fR
.RS
.IP \(bu 2
Run a specific directory of tests:
.RE
.PP
\fB\fCatoum \-d {{path/to/directory}}\fR
.RS
.IP \(bu 2
Run all tests under a specific namespace:
.RE
.PP
\fB\fCatoum \-ns {{namespace}}\fR
.RS
.IP \(bu 2
Run all tests with a specific tag:
.RE
.PP
\fB\fCatoum \-t {{tag}}\fR
.RS
.IP \(bu 2
Load a custom bootstrap file before running tests:
.RE
.PP
\fB\fCatoum \-\-bootstrap\-file {{path/to/file}}\fR
