.TH atrm
.PP
.RS
Remove jobs scheduled by \fB\fCat\fR or \fB\fCbatch\fR commands.
To find job numbers use \fB\fCatq\fR\&.
More information: \[la]https://manned.org/atrm\[ra]\&.
.RE
.RS
.IP \(bu 2
Remove job number 10:
.RE
.PP
\fB\fCatrm {{10}}\fR
.RS
.IP \(bu 2
Remove many jobs, separated by spaces:
.RE
.PP
\fB\fCatrm {{15}} {{17}} {{22}}\fR
