.TH audacious
.PP
.RS
An open\-source audio player.
More information: \[la]https://audacious-media-player.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the program:
.RE
.PP
\fB\fCaudacious\fR
.RS
.IP \(bu 2
Enqueue a specific directory of audio files:
.RE
.PP
\fB\fCaudacious \-\-enqueue {{path/to/directory}}\fR
.RS
.IP \(bu 2
Start or stop playback:
.RE
.PP
\fB\fCaudacious \-\-play\-pause\fR
.RS
.IP \(bu 2
Skip forwards or backwards in the playlist:
.RE
.PP
\fB\fCaudacious \-\-{{fwd|rew}}\fR
.RS
.IP \(bu 2
Stop playback:
.RE
.PP
\fB\fCaudacious \-\-stop\fR
.RS
.IP \(bu 2
Start a headless version:
.RE
.PP
\fB\fCaudacious \-\-headless\fR
.RS
.IP \(bu 2
Exit as soon as playback stops or there is nothing to playback:
.RE
.PP
\fB\fCaudacious \-\-quit\-after\-play\fR
