.TH auditd
.PP
.RS
This responds to requests from the audit utility and notifications from the kernel.
It should not be invoked manually.
More information: \[la]https://manned.org/auditd\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the daemon:
.RE
.PP
\fB\fCauditd\fR
.RS
.IP \(bu 2
Start the daemon in debug mode:
.RE
.PP
\fB\fCauditd \-d\fR
.RS
.IP \(bu 2
Start the daemon on\-demand from launchd:
.RE
.PP
\fB\fCauditd \-l\fR
