.TH autojump
.PP
.RS
Quickly jump among the directories you visit the most.
Aliases like j or jc are provided for even less typing.
More information: \[la]https://github.com/wting/autojump\[ra]\&.
.RE
.RS
.IP \(bu 2
Jump to a directory that contains the given pattern:
.RE
.PP
\fB\fCj {{pattern}}\fR
.RS
.IP \(bu 2
Jump to a sub\-directory (child) of the current directory that contains the given pattern:
.RE
.PP
\fB\fCjc {{pattern}}\fR
.RS
.IP \(bu 2
Open a directory that contains the given pattern in the operating system file manager:
.RE
.PP
\fB\fCjo {{pattern}}\fR
.RS
.IP \(bu 2
Remove non\-existing directories from the autojump database:
.RE
.PP
\fB\fCj \-\-purge\fR
.RS
.IP \(bu 2
Show the entries in the autojump database:
.RE
.PP
\fB\fCj \-s\fR
