.TH avo
.PP
.RS
The official command\-line interface for Avo.
More information: \[la]https://www.avo.app/docs/implementation/cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a workspace in the current directory:
.RE
.PP
\fB\fCavo init\fR
.RS
.IP \(bu 2
Log into the Avo platform:
.RE
.PP
\fB\fCavo login\fR
.RS
.IP \(bu 2
Switch to an existing Avo branch:
.RE
.PP
\fB\fCavo checkout {{branch_name}}\fR
.RS
.IP \(bu 2
Pull analytics wrappers for the current path:
.RE
.PP
\fB\fCavo pull\fR
.RS
.IP \(bu 2
Display the status of the Avo implementation:
.RE
.PP
\fB\fCavo status\fR
.RS
.IP \(bu 2
Resolve Git conflicts in Avo files:
.RE
.PP
\fB\fCavo conflict\fR
.RS
.IP \(bu 2
Open the current Avo workspace in the default web browser:
.RE
.PP
\fB\fCavo edit\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCavo {{subcommand}} \-\-help\fR
