.TH aws secretsmanager
.PP
.RS
Store, manage, and retrieve secrets.
More information: \[la]https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/\[ra]\&.
.RE
.RS
.IP \(bu 2
Show secrets stored by the secrets manager in the current account:
.RE
.PP
\fB\fCaws secretsmanager list\-secrets\fR
.RS
.IP \(bu 2
Create a secret:
.RE
.PP
\fB\fCaws secretsmanager create\-secret \-\-name {{name}} \-\-description "{{secret_description}}" \-\-secret\-string {{secret}}\fR
.RS
.IP \(bu 2
Delete a secret:
.RE
.PP
\fB\fCaws secretsmanager delete\-secret \-\-secret\-id {{name_or_arn}}\fR
.RS
.IP \(bu 2
View details of a secret except for secret text:
.RE
.PP
\fB\fCaws secretsmanager describe\-secret \-\-secret\-id {{name_or_arn}}\fR
.RS
.IP \(bu 2
Retrieve the value of a secret (to get the latest version of the secret omit \fB\fC\-\-version\-stage\fR):
.RE
.PP
\fB\fCaws secretsmanager get\-secret\-value \-\-secret\-id {{name_or_arn}} \-\-version\-stage {{version_of_secret}}\fR
.RS
.IP \(bu 2
Rotate the secret immediately using a Lambda function:
.RE
.PP
\fB\fCaws secretsmanager rotate\-secret \-\-secret\-id {{name_or_arn}} \-\-rotation\-lambda\-arn {{arn_of_lambda_function}}\fR
.RS
.IP \(bu 2
Rotate the secret automatically every 30 days using a Lambda function:
.RE
.PP
\fB\fCaws secretsmanager rotate\-secret \-\-secret\-id {{name_or_arn}} \-\-rotation\-lambda\-arn {{arn_of_lambda_function}} \-\-rotation\-rules AutomaticallyAfterDays={{30}}\fR
