.TH aws codecommit
.PP
.RS
AWS CodeCommit is a managed source control service that hosts private Git repositories.
More information: \[la]https://docs.aws.amazon.com/cli/latest/reference/codecommit/\[ra]\&.
.RE
.RS
.IP \(bu 2
Display help for a specific command:
.RE
.PP
\fB\fCaws codecommit {{command}} help\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCaws codecommit help\fR
