.TH aws help
.PP
.RS
Display help information about the AWS CLI.
More information: \[la]https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCaws help\fR
.RS
.IP \(bu 2
List all available topics:
.RE
.PP
\fB\fCaws help topics\fR
.RS
.IP \(bu 2
Display help about a specific topic:
.RE
.PP
\fB\fCaws help {{topic_name}}\fR
