.TH aws history
.PP
.RS
Print the command\-line history for AWS CLI commands (the record of history of AWS CLI commands must be enabled).
More information: \[la]https://docs.aws.amazon.com/cli/latest/reference/history/\[ra]\&.
.RE
.RS
.IP \(bu 2
List commands history with command IDs:
.RE
.PP
\fB\fCaws history list\fR
.RS
.IP \(bu 2
Display events related to a specific command given a command ID:
.RE
.PP
\fB\fCaws history show {{command_id}}\fR
