.TH awslogs
.PP
.RS
Queries groups, streams and events from Amazon CloudWatch logs.
More information: \[la]https://github.com/jorgebastida/awslogs\[ra]\&.
.RE
.RS
.IP \(bu 2
List log groups:
.RE
.PP
\fB\fCawslogs groups\fR
.RS
.IP \(bu 2
List existing streams for the specified group:
.RE
.PP
\fB\fCawslogs streams {{/var/log/syslog}}\fR
.RS
.IP \(bu 2
Get logs for any streams in the specified group between 1 and 2 hours ago:
.RE
.PP
\fB\fCawslogs get {{/var/log/syslog}} \-\-start='{{2h ago}}' \-\-end='{{1h ago}}'\fR
.RS
.IP \(bu 2
Get logs that match a specific CloudWatch Logs Filter pattern:
.RE
.PP
\fB\fCawslogs get {{/aws/lambda/my_lambda_group}} \-\-filter\-pattern='{{ERROR}}'\fR
.RS
.IP \(bu 2
Watch logs for any streams in the specified group:
.RE
.PP
\fB\fCawslogs get {{/var/log/syslog}} ALL \-\-watch\fR
