.TH axel
.PP
.RS
Download accelerator.
Supports HTTP, HTTPS, and FTP.
More information: \[la]https://github.com/axel-download-accelerator/axel\[ra]\&.
.RE
.RS
.IP \(bu 2
Download a URL to a file:
.RE
.PP
\fB\fCaxel {{url}}\fR
.RS
.IP \(bu 2
Download and specify filename:
.RE
.PP
\fB\fCaxel {{url}} \-o {{path/to/file}}\fR
.RS
.IP \(bu 2
Download with multiple connections:
.RE
.PP
\fB\fCaxel \-n {{connections_num}} {{url}}\fR
.RS
.IP \(bu 2
Search for mirrors:
.RE
.PP
\fB\fCaxel \-S {{mirrors_num}} {{url}}\fR
.RS
.IP \(bu 2
Limit download speed (bytes per second):
.RE
.PP
\fB\fCaxel \-s {{speed}} {{url}}\fR
