.TH az bicep
.PP
.RS
Bicep CLI command group.
Part of \fB\fCazure\-cli\fR (also known as \fB\fCaz\fR).
More information: \[la]https://learn.microsoft.com/cli/azure/bicep\[ra]\&.
.RE
.RS
.IP \(bu 2
Install Bicep CLI:
.RE
.PP
\fB\fCaz bicep install\fR
.RS
.IP \(bu 2
Build a Bicep file:
.RE
.PP
\fB\fCaz bicep build \-\-file {{path/to/file.bicep}}\fR
.RS
.IP \(bu 2
Attempt to decompile an ARM template file to a Bicep file:
.RE
.PP
\fB\fCaz bicep decompile \-\-file {{path/to/template_file.json}}\fR
.RS
.IP \(bu 2
Upgrade Bicep CLI to the latest version:
.RE
.PP
\fB\fCaz bicep upgrade\fR
.RS
.IP \(bu 2
Display the installed version of Bicep CLI:
.RE
.PP
\fB\fCaz bicep version\fR
.RS
.IP \(bu 2
List all available versions of Bicep CLI:
.RE
.PP
\fB\fCaz bicep list\-versions\fR
.RS
.IP \(bu 2
Uninstall Bicep CLI:
.RE
.PP
\fB\fCaz bicep uninstall\fR
