.TH az feedback
.PP
.RS
Send feedback to the Azure CLI Team.
Part of \fB\fCazure\-cli\fR (also known as \fB\fCaz\fR).
More information: \[la]https://learn.microsoft.com/cli/azure/reference-index#az_feedback\[ra]\&.
.RE
.RS
.IP \(bu 2
Send feedback to the Azure CLI Team:
.RE
.PP
\fB\fCaz feedback\fR
