.TH az logout
.PP
.RS
Log out from an Azure subscription.
Part of \fB\fCazure\-cli\fR (also known as \fB\fCaz\fR).
More information: \[la]https://learn.microsoft.com/cli/azure/reference-index#az_logout\[ra]\&.
.RE
.RS
.IP \(bu 2
Log out from the active account:
.RE
.PP
\fB\fCaz logout\fR
.RS
.IP \(bu 2
Log out a specific username:
.RE
.PP
\fB\fCaz logout \-\-username {{alias@somedomain.com}}\fR
