.TH az upgrade
.PP
.RS
Upgrade Azure CLI and Extensions.
Part of \fB\fCazure\-cli\fR (also known as \fB\fCaz\fR).
More information: \[la]https://learn.microsoft.com/cli/azure/reference-index?view=azure-cli-latest#az-upgrade\[ra]\&.
.RE
.RS
.IP \(bu 2
Upgrade Azure CLI:
.RE
.PP
\fB\fCaz upgrade\fR
.RS
.IP \(bu 2
Upgrade Azure CLI and Extensions:
.RE
.PP
\fB\fCaz upgrade \-\-all\fR
.RS
.IP \(bu 2
Upgrade Azure CLI and Extensions without prompting for confirmation:
.RE
.PP
\fB\fCaz version \-\-all \-\-yes\fR
