.TH az version
.PP
.RS
Shows the current version of Azure CLI modules and extensions.
Part of \fB\fCazure\-cli\fR (also known as \fB\fCaz\fR).
More information: \[la]https://learn.microsoft.com/cli/azure/reference-index?view=azure-cli-latest#az-version\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the current version of Azure CLI modules and extensions in JSON format:
.RE
.PP
\fB\fCaz version\fR
.RS
.IP \(bu 2
Show the current version of Azure CLI modules and extensions in a given format:
.RE
.PP
\fB\fCaz version \-\-output {{json|table|tsv}}\fR
