.TH az
.PP
.RS
The official CLI tool for Microsoft Azure.
Some subcommands such as \fB\fCaz login\fR have their own usage documentation.
More information: \[la]https://learn.microsoft.com/cli/azure\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in to Azure:
.RE
.PP
\fB\fCaz login\fR
.RS
.IP \(bu 2
Manage azure subscription information:
.RE
.PP
\fB\fCaz account\fR
.RS
.IP \(bu 2
List all Azure Managed Disks:
.RE
.PP
\fB\fCaz disk list\fR
.RS
.IP \(bu 2
List all Azure virtual machines:
.RE
.PP
\fB\fCaz vm list\fR
.RS
.IP \(bu 2
Manage Azure Kubernetes Services:
.RE
.PP
\fB\fCaz aks\fR
.RS
.IP \(bu 2
Manage Azure Network resources:
.RE
.PP
\fB\fCaz network\fR
