.TH bandwhich
.PP
.RS
Display the current network utilization by process, connection or remote IP/hostname.
More information: \[la]https://github.com/imsnif/bandwhich\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the remote addresses table only:
.RE
.PP
\fB\fCbandwhich \-\-addresses\fR
.RS
.IP \(bu 2
Show DNS queries:
.RE
.PP
\fB\fCbandwhich \-\-show\-dns\fR
.RS
.IP \(bu 2
Show total (cumulative) usage:
.RE
.PP
\fB\fCbandwhich \-\-total\-utilization\fR
.RS
.IP \(bu 2
Show the network utilization for a specific network interface:
.RE
.PP
\fB\fCbandwhich \-\-interface {{eth0}}\fR
.RS
.IP \(bu 2
Show DNS queries with a given DNS server:
.RE
.PP
\fB\fCbandwhich \-\-show\-dns \-\-dns\-server {{dns_server_ip}}\fR
