.TH basename
.PP
.RS
Remove leading directory portions from a path.
More information: \[la]https://www.gnu.org/software/coreutils/basename\[ra]\&.
.RE
.RS
.IP \(bu 2
Show only the file name from a path:
.RE
.PP
\fB\fCbasename {{path/to/file}}\fR
.RS
.IP \(bu 2
Show only the rightmost directory name from a path:
.RE
.PP
\fB\fCbasename {{path/to/directory/}}\fR
.RS
.IP \(bu 2
Show only the file name from a path, with a suffix removed:
.RE
.PP
\fB\fCbasename {{path/to/file}} {{suffix}}\fR
