.TH bashmarks
.PP
.RS
Save and jump to commonly used directories using 1 character commands.
More information: \[la]https://github.com/huyng/bashmarks\[ra]\&.
.RE
.RS
.IP \(bu 2
List available bookmarks:
.RE
.PP
\fB\fCl\fR
.RS
.IP \(bu 2
Save the current directory as "bookmark_name":
.RE
.PP
\fB\fCs {{bookmark_name}}\fR
.RS
.IP \(bu 2
Go to a bookmarked directory:
.RE
.PP
\fB\fCg {{bookmark_name}}\fR
.RS
.IP \(bu 2
Print a bookmarked directory's contents:
.RE
.PP
\fB\fCp {{bookmark_name}}\fR
.RS
.IP \(bu 2
Delete a bookmark:
.RE
.PP
\fB\fCd {{bookmark_name}}\fR
