.TH bastet
.PP
.RS
Clone of the game Tetris in the terminal.
More information: \[la]https://fph.altervista.org/prog/bastet.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a Tetris game:
.RE
.PP
\fB\fCbastet\fR
.RS
.IP \(bu 2
Navigate the piece horizontally:
.RE
.PP
\fB\fC{{Left|Right}} arrow key\fR
.RS
.IP \(bu 2
Rotate the piece clockwise or counterclockwise:
.RE
.PP
\fB\fC{{Spacebar|Up arrow key}}\fR
.RS
.IP \(bu 2
Soft drop the piece:
.RE
.PP
\fB\fCDown arrow key\fR
.RS
.IP \(bu 2
Hard drop the piece:
.RE
.PP
\fB\fCEnter\fR
.RS
.IP \(bu 2
Pause the game:
.RE
.PP
\fB\fCp\fR
.RS
.IP \(bu 2
Quit the game:
.RE
.PP
\fB\fCCtrl + C\fR
