.TH bazel
.PP
.RS
Open\-source build and test tool similar to Make, Maven, and Gradle.
More information: \[la]https://bazel.build/reference/command-line-reference\[ra]\&.
.RE
.RS
.IP \(bu 2
Build the specified target in the workspace:
.RE
.PP
\fB\fCbazel build {{target}}\fR
.RS
.IP \(bu 2
Remove output files and stop the server if running:
.RE
.PP
\fB\fCbazel clean\fR
.RS
.IP \(bu 2
Stop the bazel server:
.RE
.PP
\fB\fCbazel shutdown\fR
.RS
.IP \(bu 2
Display runtime info about the bazel server:
.RE
.PP
\fB\fCbazel info\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCbazel help\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCbazel version\fR
