.TH bcomps
.PP
.RS
Decompose graphs into their biconnected components.
Graphviz filters: \fB\fCacyclic\fR, \fB\fCbcomps\fR, \fB\fCcomps\fR, \fB\fCedgepaint\fR, \fB\fCgvcolor\fR, \fB\fCgvpack\fR, \fB\fCmingle\fR, \fB\fCnop\fR, \fB\fCsccmap\fR, \fB\fCtred\fR, & \fB\fCunflatten\fR\&.
More information: \[la]https://graphviz.org/pdf/bcomps.1.pdf\[ra]\&.
.RE
.RS
.IP \(bu 2
Decompose one or more graphs into their biconnected components:
.RE
.PP
\fB\fCbcomps {{path/to/input1.gv}} {{path/to/input2.gv ...}} > {{path/to/output.gv}}\fR
.RS
.IP \(bu 2
Print the number of blocks and cutvertices in one or more graphs:
.RE
.PP
\fB\fCbcomps \-v \-s {{path/to/input1.gv}} {{path/to/input2.gv ...}}\fR
.RS
.IP \(bu 2
Write each block and block\-cutvertex tree to multiple numbered filenames based on \fB\fCoutput.gv\fR:
.RE
.PP
\fB\fCbcomps \-x \-o {{path/to/output.gv}} {{path/to/input1.gv}} {{path/to/input2.gv ...}}\fR
.RS
.IP \(bu 2
Display help for \fB\fCbcomps\fR:
.RE
.PP
\fB\fCbcomps \-?\fR
