.TH behat
.PP
.RS
A PHP framework for Behaviour\-Driven Development.
More information: \[la]https://behat.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new Behat project:
.RE
.PP
\fB\fCbehat \-\-init\fR
.RS
.IP \(bu 2
Run all tests:
.RE
.PP
\fB\fCbehat\fR
.RS
.IP \(bu 2
Run all tests from the specified suite:
.RE
.PP
\fB\fCbehat \-\-suite={{suite_name}}\fR
.RS
.IP \(bu 2
Run tests with a specific output formatter:
.RE
.PP
\fB\fCbehat \-\-format {{pretty|progress}}\fR
.RS
.IP \(bu 2
Run tests and output results to a file:
.RE
.PP
\fB\fCbehat \-\-out {{path/to/file}}\fR
.RS
.IP \(bu 2
Display a list of definitions in your test suites:
.RE
.PP
\fB\fCbehat \-\-definitions\fR
