.TH betty
.PP
.RS
Use natural language to execute commands.
More information: \[la]https://github.com/pickhardt/betty\[ra]\&.
.RE
.RS
.IP \(bu 2
Ask Betty something:
.RE
.PP
\fB\fCbetty {{what time is it}}\fR
.RS
.IP \(bu 2
Download a file:
.RE
.PP
\fB\fCbetty download {{https://example.com/file.ext}} to {{path/to/output_file.ext}}\fR
.RS
.IP \(bu 2
Compress a file or directory to one of the support archive formats:
.RE
.PP
\fB\fCbetty {{zip}} {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Extract an archive into the current directory:
.RE
.PP
\fB\fCbetty {{unzip}} {{archive.tar.gz}}\fR
.RS
.IP \(bu 2
Extract an archive into a specific directory:
.RE
.PP
\fB\fCbetty unarchive {{archive.tar.gz}} to {{path/to/directory}}\fR
.RS
.IP \(bu 2
Play Spotify:
.RE
.PP
\fB\fCbetty play {{Spotify}}\fR
.RS
.IP \(bu 2
Drive Betty to madness:
.RE
.PP
\fB\fCbetty go crazy\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCbetty version\fR
