.TH bg
.PP
.RS
Resumes jobs that have been suspended (e.g. using \fB\fCCtrl + Z\fR), and keeps them running in the background.
More information: \[la]https://manned.org/bg\[ra]\&.
.RE
.RS
.IP \(bu 2
Resume the most recently suspended job and run it in the background:
.RE
.PP
\fB\fCbg\fR
.RS
.IP \(bu 2
Resume a specific job (use \fB\fCjobs \-l\fR to get its ID) and run it in the background:
.RE
.PP
\fB\fCbg %{{job_id}}\fR
