.TH bird
.PP
.RS
BIRD Internet Routing Daemon.
Routing daemon with support for BGP, OSPF, Babel and others.
More information: \[la]https://bird.network.cz/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Bird with a specific configuration file:
.RE
.PP
\fB\fCbird \-c {{path/to/bird.conf}}\fR
.RS
.IP \(bu 2
Start Bird as a specific user and group:
.RE
.PP
\fB\fCbird \-u {{username}} \-g {{group}}\fR
