.TH blockout2
.PP
.RS
Tetris like game in 3D.
More information: \[la]http://www.blockout.net/blockout2/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a new game:
.RE
.PP
\fB\fCblockout2\fR
.RS
.IP \(bu 2
Navigate the current piece on a 2D plane:
.RE
.PP
\fB\fC{{Up|Down|Left|Right}} arrow key\fR
.RS
.IP \(bu 2
Rotate the piece on its axis:
.RE
.PP
\fB\fC{{Q|W|E|A|S|D}}\fR
.RS
.IP \(bu 2
Hard drop the current piece:
.RE
.PP
\fB\fCSpacebar\fR
.RS
.IP \(bu 2
Pause/unpause the game:
.RE
.PP
\fB\fCp\fR
