.TH bmptopnm
.PP
.RS
Convert a BMP file into a PBM, PGM, or PNM image.
More information: \[la]https://netpbm.sourceforge.net/doc/bmptopnm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate the PBM, PGM, or PNM image as output, for Windows or OS/2 BMP file as input:
.RE
.PP
\fB\fCbmptopnm {{path/to/file.bmp}}\fR
.RS
.IP \(bu 2
Report contents of the BMP header to \fB\fCstderr\fR:
.RE
.PP
\fB\fCbmptopnm \-verbose {{path/to/file.bmp}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCbmptopnm \-version\fR
