.TH bpytop
.PP
.RS
A resource monitor that shows information about the CPU, memory, disks, network and processes.
A Python version of \fB\fCbashtop\fR\&.
More information: \[la]https://github.com/aristocratos/bpytop\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCbpytop\fR:
.RE
.PP
\fB\fCbpytop\fR
.RS
.IP \(bu 2
Start in minimal mode without memory and networking boxes:
.RE
.PP
\fB\fCbpytop \-m\fR
.RS
.IP \(bu 2
Show version:
.RE
.PP
\fB\fCbpytop \-v\fR
.RS
.IP \(bu 2
Toggle minimal mode:
.RE
.PP
\fB\fCm\fR
.RS
.IP \(bu 2
Search for running programs or processes:
.RE
.PP
\fB\fCf\fR
.RS
.IP \(bu 2
Change settings:
.RE
.PP
\fB\fCM\fR
