.TH brushtopbm
.PP
.RS
Convert a Xerox doodle brush file into a PBM image.
More information: \[la]https://netpbm.sourceforge.net/doc/brushtopbm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a PBM file as output for a Xerox doodle brush file as input:
.RE
.PP
\fB\fCbrushtopbm {{path/to/file.brush}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCbrushtopbm \-version\fR
