.TH bshell
.PP
.RS
A GUI tool for browsing for SSH/VNC servers on the local network.
See also: \fB\fCbssh\fR and \fB\fCbvnc\fR\&.
More information: \[la]https://linux.extremeoverclocking.com/man/1/bssh\[ra]\&.
.RE
.RS
.IP \(bu 2
Browse for both SSH and VNC servers:
.RE
.PP
\fB\fCbshell\fR
.RS
.IP \(bu 2
Browse for SSH servers only:
.RE
.PP
\fB\fCbshell \-\-ssh\fR
.RS
.IP \(bu 2
Browse for VNC servers only:
.RE
.PP
\fB\fCbshell \-\-vnc\fR
.RS
.IP \(bu 2
Browse for both SSH and VNC servers in a specified domain:
.RE
.PP
\fB\fCbshell \-\-domain={{domain}}\fR
