.TH bssh
.PP
.RS
A GUI tool for browsing for SSH/VNC servers on the local network.
See also: \fB\fCbvnc\fR and \fB\fCbshell\fR\&.
More information: \[la]https://linux.extremeoverclocking.com/man/1/bssh\[ra]\&.
.RE
.RS
.IP \(bu 2
Browse for SSH servers:
.RE
.PP
\fB\fCbssh\fR
.RS
.IP \(bu 2
Browse for VNC servers:
.RE
.PP
\fB\fCbssh \-\-vnc\fR
.RS
.IP \(bu 2
Browse for both SSH and VNC servers:
.RE
.PP
\fB\fCbssh \-\-shell\fR
.RS
.IP \(bu 2
Browse for SSH servers in a specified domain:
.RE
.PP
\fB\fCbssh \-\-domain={{domain}}\fR
