.TH btm
.PP
.RS
An alternative to \fB\fCtop\fR\&.
Aims to be lightweight, cross\-platform and more graphical than \fB\fCtop\fR\&.
More information: \[la]https://github.com/ClementTsang/bottom\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the default layout (CPU, memory, temperatures, disk, network, and processes):
.RE
.PP
\fB\fCbtm\fR
.RS
.IP \(bu 2
Enable basic mode, removing charts and condensing data (similar to \fB\fCtop\fR):
.RE
.PP
\fB\fCbtm \-\-basic\fR
.RS
.IP \(bu 2
Use big dots instead of small ones in charts:
.RE
.PP
\fB\fCbtm \-\-dot_marker\fR
.RS
.IP \(bu 2
Show also battery charge and health status:
.RE
.PP
\fB\fCbtm \-\-battery\fR
.RS
.IP \(bu 2
Refresh every 250 milliseconds and show the last 30 seconds in the charts:
.RE
.PP
\fB\fCbtm \-\-rate 250 \-\-default_time_value 30000\fR
