.TH btop
.PP
.RS
A resource monitor that shows information about the CPU, memory, disks, network and processes.
A C++ version of \fB\fCbpytop\fR\&.
More information: \[la]https://github.com/aristocratos/btop\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCbtop\fR:
.RE
.PP
\fB\fCbtop\fR
.RS
.IP \(bu 2
Start \fB\fCbtop\fR with the specified settings preset:
.RE
.PP
\fB\fCbtop \-\-preset {{0..9}}\fR
