.TH bundletool validate
.PP
.RS
Command\-line tool to manipulate Android Application Bundles.
More information: \[la]https://developer.android.com/studio/command-line/bundletool\[ra]\&.
.RE
.RS
.IP \(bu 2
Verify a bundle and display detailed information about it:
.RE
.PP
\fB\fCbundletool validate \-\-bundle={{path/to/bundle.aab}}\fR
