.TH bundler
.PP
.RS
Dependency manager for the Ruby programming language.
\fB\fCbundler\fR is a common name for the command \fB\fCbundle\fR, but not a command itself.
More information: \[la]https://bundler.io/man/bundle.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
View documentation for the original command:
.RE
.PP
\fB\fCtldr bundle\fR
