.TH buzzphrase
.PP
.RS
Node.js command\-line tool to output a random buzzphrase.
More information: \[la]https://github.com/atomantic/buzzphrase\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a string of three random phrases containing an adjective, a past tense verb and a plural noun:
.RE
.PP
\fB\fCbuzzphrase\fR
.RS
.IP \(bu 2
Output a phrase formatted as [i]mperative verb + past tense [v]erb + [a]djective + plural [N]oun:
.RE
.PP
\fB\fCbuzzphrase {{'{i} {v} {a} {N}'}}\fR
.RS
.IP \(bu 2
Output 4 phrases formatted as present participle [V]erb + [a]djective + singular [n]oun + [f]inal:
.RE
.PP
\fB\fCbuzzphrase {{4 '{V} {a} {n} {f}'}}\fR
