.TH bvnc
.PP
.RS
A GUI tool for browsing for SSH/VNC servers on the local network.
See also: \fB\fCbssh\fR and \fB\fCbshell\fR\&.
More information: \[la]https://linux.extremeoverclocking.com/man/1/bssh\[ra]\&.
.RE
.RS
.IP \(bu 2
Browse for VNC servers:
.RE
.PP
\fB\fCbvnc\fR
.RS
.IP \(bu 2
Browse for SSH servers:
.RE
.PP
\fB\fCbvnc \-\-ssh\fR
.RS
.IP \(bu 2
Browse for both VNC and SSH servers:
.RE
.PP
\fB\fCbvnc \-\-shell\fR
.RS
.IP \(bu 2
Browse for VNC servers in a specified domain:
.RE
.PP
\fB\fCbvnc \-\-domain={{domain}}\fR
