.TH cake
.PP
.RS
The command\-line processor for the CakePHP framework.
More information: \[la]https://cakephp.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Display basic information about the current app and available commands:
.RE
.PP
\fB\fCcake\fR
.RS
.IP \(bu 2
Display a list of available routes:
.RE
.PP
\fB\fCcake routes\fR
.RS
.IP \(bu 2
Clear configuration caches:
.RE
.PP
\fB\fCcake cache clear_all\fR
.RS
.IP \(bu 2
Build the metadata cache:
.RE
.PP
\fB\fCcake schema_cache build \-\-connection {{connection}}\fR
.RS
.IP \(bu 2
Clear the metadata cache:
.RE
.PP
\fB\fCcake schema_cache clear\fR
.RS
.IP \(bu 2
Clear a single cache table:
.RE
.PP
\fB\fCcake schema_cache clear {{table_name}}\fR
.RS
.IP \(bu 2
Start a development web server (defaults to port 8765):
.RE
.PP
\fB\fCcake server\fR
.RS
.IP \(bu 2
Start a REPL (interactive shell):
.RE
.PP
\fB\fCcake console\fR
