.TH calendar
.PP
.RS
Display upcoming events from a calendar file.
More information: \[la]https://www.commandlinux.com/man-page/man1/calendar.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Show events for today and tomorrow (or the weekend on Friday) from the default calendar:
.RE
.PP
\fB\fCcalendar\fR
.RS
.IP \(bu 2
Look [A]head, showing events for the next 30 days:
.RE
.PP
\fB\fCcalendar \-A {{30}}\fR
.RS
.IP \(bu 2
Look [B]ack, showing events for the previous 7 days:
.RE
.PP
\fB\fCcalendar \-B {{7}}\fR
.RS
.IP \(bu 2
Show events from a custom calendar [f]ile:
.RE
.PP
\fB\fCcalendar \-f {{path/to/file}}\fR
