.TH calligraflow
.PP
.RS
Calligra's flowchart and diagram application.
See also: \fB\fCcalligrastage\fR, \fB\fCcalligrawords\fR, \fB\fCcalligrasheets\fR\&.
More information: \[la]https://manned.org/calligraflow\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the flowchart and diagram application:
.RE
.PP
\fB\fCcalligraflow\fR
.RS
.IP \(bu 2
Open a specific file:
.RE
.PP
\fB\fCcalligraflow {{path/to/file}}\fR
.RS
.IP \(bu 2
Display help or version:
.RE
.PP
\fB\fCcalligraflow \-\-{{help|version}}\fR
