.TH calligrawords
.PP
.RS
Calligra's word processor application.
See also: \fB\fCcalligraflow\fR, \fB\fCcalligrastage\fR, \fB\fCcalligrasheets\fR\&.
More information: \[la]https://manned.org/calligrawords\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the word processor application:
.RE
.PP
\fB\fCcalligrawords\fR
.RS
.IP \(bu 2
Open a specific document:
.RE
.PP
\fB\fCcalligrawords {{path/to/document}}\fR
.RS
.IP \(bu 2
Display help or version:
.RE
.PP
\fB\fCcalligrawords \-\-{{help|version}}\fR
