.TH calligrastage
.PP
.RS
Calligra's presentation application.
See also: \fB\fCcalligraflow\fR, \fB\fCcalligrawords\fR, \fB\fCcalligrasheets\fR\&.
More information: \[la]https://manned.org/calligrastage\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the presentation application:
.RE
.PP
\fB\fCcalligrastage\fR
.RS
.IP \(bu 2
Open a specific presentation:
.RE
.PP
\fB\fCcalligrastage {{path/to/presentation}}\fR
.RS
.IP \(bu 2
Display help or version:
.RE
.PP
\fB\fCcalligrastage \-\-{{help|version}}\fR
