.TH calligrasheets
.PP
.RS
Calligra's spreadsheet application.
See also: \fB\fCcalligraflow\fR, \fB\fCcalligrastage\fR, \fB\fCcalligrawords\fR\&.
More information: \[la]https://manned.org/calligrasheets\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the spreadsheet application:
.RE
.PP
\fB\fCcalligrasheets\fR
.RS
.IP \(bu 2
Open a specific spreadsheet:
.RE
.PP
\fB\fCcalligrasheets {{path/to/spreadsheet}}\fR
.RS
.IP \(bu 2
Display help or version:
.RE
.PP
\fB\fCcalligrasheets \-\-{{help|version}}\fR
