.TH cargo new
.PP
.RS
Create a new Cargo package.
Equivalent of \fB\fCcargo init\fR, but specifiying a directory is required.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-new.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Rust project with a binary target:
.RE
.PP
\fB\fCcargo new {{path/to/directory}}\fR
