.TH cargo verify\-project
.PP
.RS
Check the correctness of the \fB\fCCargo.toml\fR manifest and print the result as a JSON object.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-verify-project.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the correctness of the current project's manifest:
.RE
.PP
\fB\fCcargo verify\-project\fR
.RS
.IP \(bu 2
Check the correctness of the specified manifest file:
.RE
.PP
\fB\fCcargo verify\-project \-\-manifest\-path {{path/to/Cargo.toml}}\fR
