.TH cargo report
.PP
.RS
Display various kinds of reports.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-report.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a report:
.RE
.PP
\fB\fCcargo report {{future\-incompatibilities|...}}\fR
.RS
.IP \(bu 2
Display a report with the specified Cargo\-generated id:
.RE
.PP
\fB\fCcargo report {{future\-incompatibilities|...}} \-\-id {{id}}\fR
.RS
.IP \(bu 2
Display a report for the specified package:
.RE
.PP
\fB\fCcargo report {{future\-incompatibilities|...}} \-\-package {{package}}\fR
