.TH cargo pkgid
.PP
.RS
Print the fully qualified package ID specifier for a package or dependency in the current workspace.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-pkgid.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the fully qualified package specification for the current project:
.RE
.PP
\fB\fCcargo pkgid\fR
.RS
.IP \(bu 2
Print the fully qualified package specification for the specified package:
.RE
.PP
\fB\fCcargo pkgid {{partial_pkgspec}}\fR
