.TH cargo help
.PP
.RS
Display help on \fB\fCcargo\fR and its subcommands.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-help.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display general help:
.RE
.PP
\fB\fCcargo help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCcargo help {{subcommand}}\fR
