.TH cargo version
.PP
.RS
Display \fB\fCcargo\fR version information.
More information: \[la]https://doc.rust-lang.org/cargo/commands/cargo-version.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the version of \fB\fCcargo\fR:
.RE
.PP
\fB\fCcargo version\fR
.RS
.IP \(bu 2
Display additional build information:
.RE
.PP
\fB\fCcargo version \-\-verbose\fR
