.TH cbonsai
.PP
.RS
Cbonsai is a beautifully random bonsai tree CLI generator.
More information: \[la]https://gitlab.com/jallbrit/cbonsai\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a bonsai in live mode:
.RE
.PP
\fB\fCcbonsai \-l\fR
.RS
.IP \(bu 2
Generate a bonsai in infinite mode:
.RE
.PP
\fB\fCcbonsai \-i\fR
.RS
.IP \(bu 2
Append a message to the bonsai:
.RE
.PP
\fB\fCcbonsai \-m "{{message}}"\fR
.RS
.IP \(bu 2
Display extra information about the bonsai:
.RE
.PP
\fB\fCcbonsai \-v\fR
.RS
.IP \(bu 2
Display cbonsai help:
.RE
.PP
\fB\fCcbonsai \-h\fR
