.TH cd
.PP
.RS
Change the current working directory.
More information: \[la]https://manned.org/cd\[ra]\&.
.RE
.RS
.IP \(bu 2
Go to the specified directory:
.RE
.PP
\fB\fCcd {{path/to/directory}}\fR
.RS
.IP \(bu 2
Go up to the parent of the current directory:
.RE
.PP
\fB\fCcd ..\fR
.RS
.IP \(bu 2
Go to the home directory of the current user:
.RE
.PP
\fB\fCcd\fR
.RS
.IP \(bu 2
Go to the home directory of the specified user:
.RE
.PP
\fB\fCcd ~{{username}}\fR
.RS
.IP \(bu 2
Go to the previously chosen directory:
.RE
.PP
\fB\fCcd \-\fR
.RS
.IP \(bu 2
Go to the root directory:
.RE
.PP
\fB\fCcd /\fR
