.TH cheat
.PP
.RS
Create and view interactive cheat sheets.
More information: \[la]https://github.com/cheat/cheat\[ra]\&.
.RE
.RS
.IP \(bu 2
Show example usage of a command:
.RE
.PP
\fB\fCcheat {{command}}\fR
.RS
.IP \(bu 2
Edit the cheat sheet for a command:
.RE
.PP
\fB\fCcheat \-e {{command}}\fR
.RS
.IP \(bu 2
List the available cheat sheets:
.RE
.PP
\fB\fCcheat \-l\fR
.RS
.IP \(bu 2
Search available the cheat sheets for a specified command name:
.RE
.PP
\fB\fCcheat \-s {{command}}\fR
.RS
.IP \(bu 2
Get the current cheat version:
.RE
.PP
\fB\fCcheat \-v\fR
