.TH choose
.PP
.RS
A human\-friendly and fast alternative to cut and (sometimes) awk.
More information: \[la]https://github.com/theryangeary/choose\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the 5th item from a line (starting from 0):
.RE
.PP
\fB\fCchoose {{4}}\fR
.RS
.IP \(bu 2
Print the first, 3rd, and 5th item from a line, where items are separated by ':' instead of whitespace:
.RE
.PP
\fB\fCchoose \-\-field\-separator '{{:}}' {{0}} {{2}} {{4}}\fR
.RS
.IP \(bu 2
Print everything from the 2nd to 5th item on the line, including the 5th:
.RE
.PP
\fB\fCchoose {{1}}:{{4}}\fR
.RS
.IP \(bu 2
Print everything from the 2nd to 5th item on the line, excluding the 5th:
.RE
.PP
\fB\fCchoose \-\-exclusive {{1}}:{{4}}\fR
.RS
.IP \(bu 2
Print the beginning of the line to the 3rd item:
.RE
.PP
\fB\fCchoose :{{2}}\fR
.RS
.IP \(bu 2
Print all items from the beginning of the line until the 3rd item (exclusive):
.RE
.PP
\fB\fCchoose \-\-exclusive :{{2}}\fR
.RS
.IP \(bu 2
Print all items from the 3rd to the end of the line:
.RE
.PP
\fB\fCchoose {{2}}:\fR
.RS
.IP \(bu 2
Print the last item from a line:
.RE
.PP
\fB\fCchoose {{\-1}}\fR
