.TH chroma
.PP
.RS
A general\-purpose syntax highlighter.
The \fB\fC\-\-lexer\fR option is usually unnecessary, as it will be automatically determined based on the file extension.
More information: \[la]https://github.com/alecthomas/chroma\[ra]\&.
.RE
.RS
.IP \(bu 2
Highlight source code from a file with the Python lexer and output to \fB\fCstdout\fR:
.RE
.PP
\fB\fCchroma \-\-lexer {{python}} {{path/to/source_file.py}}\fR
.RS
.IP \(bu 2
Highlight source code from a file with the Go lexer and output to an HTML file:
.RE
.PP
\fB\fCchroma \-\-lexer {{go}} \-\-formatter {{html}} {{path/to/source_file.go}} > {{path/to/target_file.html}}\fR
.RS
.IP \(bu 2
Highlight source code from \fB\fCstdin\fR with the C++ lexer and output to an SVG file, using the Monokai style:
.RE
.PP
\fB\fC{{command}} | chroma \-\-lexer {{c++}} \-\-formatter {{svg}} \-\-style {{monokai}} > {{path/to/target_file.svg}}\fR
.RS
.IP \(bu 2
List available lexers, styles and formatters:
.RE
.PP
\fB\fCchroma \-\-list\fR
