.TH chsh
.PP
.RS
Change user's login shell.
More information: \[la]https://manned.org/chsh\[ra]\&.
.RE
.RS
.IP \(bu 2
Set a specific login shell for the current user interactively:
.RE
.PP
\fB\fCchsh\fR
.RS
.IP \(bu 2
Set a specific login [s]hell for the current user:
.RE
.PP
\fB\fCchsh \-s {{path/to/shell}}\fR
.RS
.IP \(bu 2
Set a login [s]hell for a specific user:
.RE
.PP
\fB\fCchsh \-s {{path/to/shell}} {{username}}\fR
.RS
.IP \(bu 2
[l]ist available shells:
.RE
.PP
\fB\fCchsh \-l\fR
