.TH cksum
.PP
.RS
Calculates CRC checksums and byte counts of a file.
Note, on old UNIX systems the CRC implementation may differ.
More information: \[la]https://www.gnu.org/software/coreutils/cksum\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a 32\-bit checksum, size in bytes and filename:
.RE
.PP
\fB\fCcksum {{path/to/file}}\fR
