.TH ClamAV
.PP
.RS
Open\-source anti\-virus program.
ClamAV isn't a command, but a set of commands.
More information: \[la]https://www.clamav.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the tldr page for scan files using the \fB\fCclamd\fR daemon:
.RE
.PP
\fB\fCtldr clamdscan\fR
.RS
.IP \(bu 2
Show the tldr page for scan files without the \fB\fCclamd\fR daemon running:
.RE
.PP
\fB\fCtldr clamscan\fR
.RS
.IP \(bu 2
Show the tldr page for update the virus definitions:
.RE
.PP
\fB\fCtldr freshclam\fR
