.TH clangd
.PP
.RS
Language server that provides IDE\-like features to editors.
It should be used via an editor plugin rather than invoked directly.
More information: \[la]https://clangd.llvm.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Display available options:
.RE
.PP
\fB\fCclangd \-\-help\fR
.RS
.IP \(bu 2
List of available options:
.RE
.PP
\fB\fCclangd \-\-help\-list\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCclangd \-\-version\fR
