.TH clang\-format
.PP
.RS
Tool to auto\-format C/C++/Java/JavaScript/Objective\-C/Protobuf/C# code.
More information: \[la]https://clang.llvm.org/docs/ClangFormat.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Format a file and print the result to \fB\fCstdout\fR:
.RE
.PP
\fB\fCclang\-format {{path/to/file}}\fR
.RS
.IP \(bu 2
Format a file in\-place:
.RE
.PP
\fB\fCclang\-format \-i {{path/to/file}}\fR
.RS
.IP \(bu 2
Format a file using a predefined coding style:
.RE
.PP
\fB\fCclang\-format \-\-style={{LLVM|GNU|Google|Chromium|Microsoft|Mozilla|WebKit}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Format a file using the \fB\fC\&.clang\-format\fR file in one of the parent directories of the source file:
.RE
.PP
\fB\fCclang\-format \-\-style=file {{path/to/file}}\fR
.RS
.IP \(bu 2
Generate a custom \fB\fC\&.clang\-format\fR file:
.RE
.PP
\fB\fCclang\-format \-\-style={{LLVM|GNU|Google|Chromium|Microsoft|Mozilla|WebKit}} \-\-dump\-config > {{.clang\-format}}\fR
