.TH clash
.PP
.RS
A rule\-based tunnel in Go.
More information: \[la]https://github.com/Dreamacro/clash/wiki\[ra]\&.
.RE
.RS
.IP \(bu 2
Specify a configuration [d]irectory:
.RE
.PP
\fB\fCclash \-d {{path/to/directory}}\fR
.RS
.IP \(bu 2
Specify a configuration [f]ile:
.RE
.PP
\fB\fCclash \-f {{path/to/configuration_file}}\fR
