.TH clementine
.PP
.RS
A modern music player and library organizer.
More information: \[la]https://www.clementine-player.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Open Clementine:
.RE
.PP
\fB\fCclementine\fR
.RS
.IP \(bu 2
Start playing a music file:
.RE
.PP
\fB\fCclementine {{url/or/path/to/file.ext}}\fR
.RS
.IP \(bu 2
Toggle between pausing and playing:
.RE
.PP
\fB\fCclementine \-\-play\-pause\fR
.RS
.IP \(bu 2
Stop playback:
.RE
.PP
\fB\fCclementine \-\-stop\fR
.RS
.IP \(bu 2
Skip to the next track:
.RE
.PP
\fB\fCclementine \-\-next\fR
.RS
.IP \(bu 2
Skip to the previous track:
.RE
.PP
\fB\fCclementine \-\-previous\fR
.RS
.IP \(bu 2
Load a playlist file:
.RE
.PP
\fB\fCclementine \-\-load {{path/to/playlist.ext}}\fR
.RS
.IP \(bu 2
Play the 5th track in the currently loaded playlist:
.RE
.PP
\fB\fCclementine \-\-play\-track {{5}}\fR
