.TH clido
.PP
.RS
Save\-state TODO app for the terminal.
More information: \[la]https://codeberg.org/Oglo12/clido/wiki\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a list:
.RE
.PP
\fB\fCclido \-\-new {{name}}\fR
.RS
.IP \(bu 2
Load a list:
.RE
.PP
\fB\fCclido \-\-load {{name}}\fR
.RS
.IP \(bu 2
Delete a list:
.RE
.PP
\fB\fCclido \-\-remove {{name}}\fR
.RS
.IP \(bu 2
List all lists:
.RE
.PP
\fB\fCclido \-\-lists\fR
.RS
.IP \(bu 2
Toggle autowrite:
.RE
.PP
\fB\fCclido toggle\-autowrite\fR
.RS
.IP \(bu 2
Open a list in a text editor:
.RE
.PP
\fB\fCclido edit {{text_editor}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCclido \-v\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCclido \-h\fR
