.TH clifm
.PP
.RS
The command\-line file manager.
More information: \[la]https://github.com/leo-arch/clifm\[ra]\&.
.RE
.RS
.IP \(bu 2
Start CliFM:
.RE
.PP
\fB\fCclifm\fR
.RS
.IP \(bu 2
Open the file or directory whose ELN (entry list number) is 12:
.RE
.PP
\fB\fC12\fR
.RS
.IP \(bu 2
Create a new file and a new directory:
.RE
.PP
\fB\fCn file dir/\fR
.RS
.IP \(bu 2
Search for PDF files in the current directory:
.RE
.PP
\fB\fC/*.pdf\fR
.RS
.IP \(bu 2
Select all PNG files in the current directory:
.RE
.PP
\fB\fCs *.png\fR
.RS
.IP \(bu 2
Remove the previously selected files (use \fB\fCt\fR to send the files to the recycle bin instead):
.RE
.PP
\fB\fCr sel\fR
.RS
.IP \(bu 2
Display detailed help:
.RE
.PP
\fB\fC?\fR
.RS
.IP \(bu 2
Exit CliFM:
.RE
.PP
\fB\fCq\fR
