.TH clockwork\-cli
.PP
.RS
A command\-line interface for the Clockwork PHP debugging framework.
More information: \[la]https://github.com/ptrofimov/clockwork-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Monitor Clockwork logs for the current project:
.RE
.PP
\fB\fCclockwork\-cli\fR
.RS
.IP \(bu 2
Monitor Clockwork logs for a specific project:
.RE
.PP
\fB\fCclockwork\-cli {{path/to/directory}}\fR
.RS
.IP \(bu 2
Monitor Clockwork logs for multiple projects:
.RE
.PP
\fB\fCclockwork\-cli {{path/to/directory1 path/to/directory2 …}}\fR
