.TH cmatrix
.PP
.RS
Shows a scrolling Matrix like screen in the terminal.
More information: \[la]https://github.com/abishekvashok/cmatrix\[ra]\&.
.RE
.RS
.IP \(bu 2
Enable asynchronous scrolling:
.RE
.PP
\fB\fCcmatrix \-a\fR
.RS
.IP \(bu 2
Display red text:
.RE
.PP
\fB\fCcmatrix \-C {{red}}\fR
.RS
.IP \(bu 2
Enable rainbow mode:
.RE
.PP
\fB\fCcmatrix \-r\fR
.RS
.IP \(bu 2
Set screen update delay to 2 centiseconds (20 milliseconds):
.RE
.PP
\fB\fCcmatrix \-u {{2}}\fR
