.TH colorls
.PP
.RS
A Ruby gem that beautifies the terminal's ls command, with color and font\-awesome icons.
More information: \[la]https://github.com/athityakumar/colorls\[ra]\&.
.RE
.RS
.IP \(bu 2
List files one per line:
.RE
.PP
\fB\fCcolorls \-1\fR
.RS
.IP \(bu 2
List all files, including hidden files:
.RE
.PP
\fB\fCcolorls \-\-all\fR
.RS
.IP \(bu 2
Long format list (permissions, ownership, size, and modification date) of all files:
.RE
.PP
\fB\fCcolorls \-\-long \-\-all\fR
.RS
.IP \(bu 2
Only list directories:
.RE
.PP
\fB\fCcolorls \-\-dirs\fR
