.TH comm
.PP
.RS
Select or reject lines common to two files. Both files must be sorted.
More information: \[la]https://www.gnu.org/software/coreutils/comm\[ra]\&.
.RE
.RS
.IP \(bu 2
Produce three tab\-separated columns: lines only in first file, lines only in second file and common lines:
.RE
.PP
\fB\fCcomm {{file1}} {{file2}}\fR
.RS
.IP \(bu 2
Print only lines common to both files:
.RE
.PP
\fB\fCcomm \-12 {{file1}} {{file2}}\fR
.RS
.IP \(bu 2
Print only lines common to both files, reading one file from \fB\fCstdin\fR:
.RE
.PP
\fB\fCcat {{file1}} | comm \-12 \- {{file2}}\fR
.RS
.IP \(bu 2
Get lines only found in first file, saving the result to a third file:
.RE
.PP
\fB\fCcomm \-23 {{file1}} {{file2}} > {{file1_only}}\fR
.RS
.IP \(bu 2
Print lines only found in second file, when the files aren't sorted:
.RE
.PP
\fB\fCcomm \-13 <(sort {{file1}}) <(sort {{file2}})\fR
