.TH composer\-require\-checker
.PP
.RS
Analyze Composer dependencies for soft dependencies.
More information: \[la]https://github.com/maglnet/ComposerRequireChecker\[ra]\&.
.RE
.RS
.IP \(bu 2
Analyze a Composer JSON file:
.RE
.PP
\fB\fCcomposer\-require\-checker check {{path/to/composer.json}}\fR
.RS
.IP \(bu 2
Analyze a Composer JSON file with a specific configuration:
.RE
.PP
\fB\fCcomposer\-require\-checker check \-\-config\-file {{path/to/config.json}} {{path/to/composer.json}}\fR
