.TH consul
.PP
.RS
Distributed key\-value store with health checking and service discovery.
Some subcommands such as \fB\fCconsul kv\fR have their own usage documentation.
More information: \[la]https://www.consul.io/commands\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the Consul version:
.RE
.PP
\fB\fCconsul \-\-version\fR
.RS
.IP \(bu 2
Show general help:
.RE
.PP
\fB\fCconsul \-\-help\fR
.RS
.IP \(bu 2
Show help for a sub\-command:
.RE
.PP
\fB\fCconsul {{sub\-command}} \-\-help\fR
