.TH cordova
.PP
.RS
Mobile apps with HTML, CSS & JS.
More information: \[la]https://cordova.apache.org/docs/en/latest/guide/cli/\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a Cordova project:
.RE
.PP
\fB\fCcordova create {{path/to/directory}} {{package}} {{project_name}}\fR
.RS
.IP \(bu 2
Display the current workspace status:
.RE
.PP
\fB\fCcordova info\fR
.RS
.IP \(bu 2
Add a Cordova platform:
.RE
.PP
\fB\fCcordova platform add {{platform}}\fR
.RS
.IP \(bu 2
Remove a Cordova platform:
.RE
.PP
\fB\fCcordova platform remove {{platform}}\fR
.RS
.IP \(bu 2
Add a Cordova plugin:
.RE
.PP
\fB\fCcordova plugin add {{pluginid}}\fR
.RS
.IP \(bu 2
Remove a Cordova plugin:
.RE
.PP
\fB\fCcordova plugin remove {{pluginid}}\fR
