.TH couchdb
.PP
.RS
Command\-line interface for Apache CouchDB database server.
More information: \[la]https://couchdb.apache.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start CouchDB:
.RE
.PP
\fB\fCcouchdb\fR
.RS
.IP \(bu 2
Start CouchDB interactive shell:
.RE
.PP
\fB\fCcouchdb \-i\fR
.RS
.IP \(bu 2
Start CouchDB as a background process:
.RE
.PP
\fB\fCcouchdb \-b\fR
.RS
.IP \(bu 2
Kill the background process (Note: It will respawn if needed):
.RE
.PP
\fB\fCcouchdb \-k\fR
.RS
.IP \(bu 2
Shutdown the background process:
.RE
.PP
\fB\fCcouchdb \-d\fR
