.TH cp
.PP
.RS
Copy files and directories.
More information: \[la]https://www.gnu.org/software/coreutils/cp\[ra]\&.
.RE
.RS
.IP \(bu 2
Copy a file to another location:
.RE
.PP
\fB\fCcp {{path/to/source_file.ext}} {{path/to/target_file.ext}}\fR
.RS
.IP \(bu 2
Copy a file into another directory, keeping the filename:
.RE
.PP
\fB\fCcp {{path/to/source_file.ext}} {{path/to/target_parent_directory}}\fR
.RS
.IP \(bu 2
Recursively copy a directory's contents to another location (if the destination exists, the directory is copied inside it):
.RE
.PP
\fB\fCcp \-R {{path/to/source_directory}} {{path/to/target_directory}}\fR
.RS
.IP \(bu 2
Copy a directory recursively, in verbose mode (shows files as they are copied):
.RE
.PP
\fB\fCcp \-vR {{path/to/source_directory}} {{path/to/target_directory}}\fR
.RS
.IP \(bu 2
Copy multiple files at once to a directory:
.RE
.PP
\fB\fCcp \-t {{path/to/destination_directory}} {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Copy text files to another location, in interactive mode (prompts user before overwriting):
.RE
.PP
\fB\fCcp \-i {{*.txt}} {{path/to/target_directory}}\fR
.RS
.IP \(bu 2
Follow symbolic links before copying:
.RE
.PP
\fB\fCcp \-L {{link}} {{path/to/target_directory}}\fR
.RS
.IP \(bu 2
Use the first argument as the destination directory (useful for \fB\fCxargs ... | cp \-t <DEST_DIR>\fR):
.RE
.PP
\fB\fCcp \-t {{path/to/target_directory}} {{path/to/file_or_directory1 path/to/file_or_directory2 ...}}\fR
