.TH cradle install
.PP
.RS
Installs the Cradle PHP framework components.
More information: \[la]https://cradlephp.github.io/docs/3.B.-Reference-Command-Line-Tools.html#install\[ra]\&.
.RE
.RS
.IP \(bu 2
Install Cradle's components (User will be prompted for further details):
.RE
.PP
\fB\fCcradle install\fR
.RS
.IP \(bu 2
Forcefully overwrite files:
.RE
.PP
\fB\fCcradle install \-\-force\fR
.RS
.IP \(bu 2
Skip running SQL migrations:
.RE
.PP
\fB\fCcradle install \-\-skip\-sql\fR
.RS
.IP \(bu 2
Skip running package updates:
.RE
.PP
\fB\fCcradle install \-\-skip\-versioning\fR
.RS
.IP \(bu 2
Use specific database details:
.RE
.PP
\fB\fCcradle install \-h {{hostname}} \-u {{username}} \-p {{password}}\fR
