.TH cradle
.PP
.RS
The Cradle PHP framework.
Some subcommands such as \fB\fCcradle install\fR have their own usage documentation.
More information: \[la]https://cradlephp.github.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Connect to a server:
.RE
.PP
\fB\fCcradle connect {{server_name}}\fR
.RS
.IP \(bu 2
Display general help:
.RE
.PP
\fB\fCcradle help\fR
.RS
.IP \(bu 2
Display help for a specific command:
.RE
.PP
\fB\fCcradle {{command}} help\fR
.RS
.IP \(bu 2
Execute a Cradle command:
.RE
.PP
\fB\fCcradle {{command}}\fR
