.TH cradle package
.PP
.RS
Manage packages for a Cradle instance.
More information: \[la]https://cradlephp.github.io/docs/3.B.-Reference-Command-Line-Tools.html#package\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a list of available packages:
.RE
.PP
\fB\fCcradle package list\fR
.RS
.IP \(bu 2
Search for a package:
.RE
.PP
\fB\fCcradle package search {{package}}\fR
.RS
.IP \(bu 2
Install a package from Packagist:
.RE
.PP
\fB\fCcradle package install {{package}}\fR
.RS
.IP \(bu 2
Install a specific version of a package:
.RE
.PP
\fB\fCcradle package install {{package}} {{version}}\fR
.RS
.IP \(bu 2
Update a package:
.RE
.PP
\fB\fCcradle package update {{package}}\fR
.RS
.IP \(bu 2
Update a package to a specific version:
.RE
.PP
\fB\fCcradle package update {{package}} {{version}}\fR
.RS
.IP \(bu 2
Remove a specific package:
.RE
.PP
\fB\fCcradle package remove {{package}}\fR
