.TH cs install
.PP
.RS
Install an application in the installation directory onfigured when installing \fB\fCcs\fR (to enable the binary to be loaded add to your \fB\fC\&.bash_profile\fR the \fB\fC$ eval "$(cs install \-\-env)"\fR command).
More information: \[la]https://get-coursier.io/docs/cli-install\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a specific application:
.RE
.PP
\fB\fCcs install {{application_name}}\fR
.RS
.IP \(bu 2
Install a specific version of an application:
.RE
.PP
\fB\fCcs install {{application_name}}:{{application_version}}\fR
.RS
.IP \(bu 2
Search an application by a specific name:
.RE
.PP
\fB\fCcs search {{application_partial_name}}\fR
.RS
.IP \(bu 2
Update a specific application if available:
.RE
.PP
\fB\fCcs update {{application_name}}\fR
.RS
.IP \(bu 2
Update all the installed applications:
.RE
.PP
\fB\fCcs update\fR
.RS
.IP \(bu 2
Uninstall a specific application:
.RE
.PP
\fB\fCcs uninstall {{application_name}}\fR
.RS
.IP \(bu 2
List all installed applications:
.RE
.PP
\fB\fCcs list\fR
.RS
.IP \(bu 2
Pass specific java options to an installed application:
.RE
.PP
\fB\fC{{application_name}} {{\-Jjava_option_name1=value1 \-Jjava_option_name2=value2 ...}}\fR
