.TH cs resolve
.PP
.RS
Resolve lists the transitive dependencies of one or more other dependencies.
More information: \[la]https://get-coursier.io/docs/cli-resolve\[ra]\&.
.RE
.RS
.IP \(bu 2
Resolve lists of transitive dependencies of two dependencies:
.RE
.PP
\fB\fCcs resolve {{group_id1}}:{{artifact_id1}}:{{artifact_version1}} {{group_id2}}:{{artifact_id2}}:{{artifact_version2}}\fR
.RS
.IP \(bu 2
Resolve lists of transitive dependencies of a package by the dependency tree:
.RE
.PP
\fB\fCcs resolve \-\-tree {{group_id}}:{{artifact_id}}:{{artifact_version}}\fR
.RS
.IP \(bu 2
Resolve dependency tree in a reverse order (from a dependency to its dependencies):
.RE
.PP
\fB\fCcs resolve \-\-reverse\-tree {{group_id}}:{{artifact_id}}:{{artifact_version}\fR
.RS
.IP \(bu 2
Print all the libraries that depends on a specific library:
.RE
.PP
\fB\fCcs resolve {{group_id}}:{{artifact_id}}:{{artifact_version}} \-\-what\-depends\-on {{searched_group_id}}:{{searched_artifact_id}}\fR
.RS
.IP \(bu 2
Print all the libraries that depends on a specific library version:
.RE
.PP
\fB\fCcs resolve {{group_id}}:{{artifact_id}}:{{artifact_version}} \-\-what\-depends\-on {{searched_group_id}}:{{searched_artifact_id}}{{searched_artifact_version}}\fR
.RS
.IP \(bu 2
Print eventual conflicts between a set of packages:
.RE
.PP
\fB\fCcs resolve \-\-conflicts {{group_id1:artifact_id1:artifact_version1 group_id2:artifact_id2:artifact_version2 ...}}\fR
