.TH coursier
.PP
.RS
Application and artifact manager for the Scala language, it can install Scala applications and setup your Scala development environment.
Some subcommands such as \fB\fCinstall\fR, \fB\fClaunch\fR, \fB\fCjava\fR, \fB\fCfetch\fR, \fB\fCresolve\fR, \fB\fCcomplete\-dep\fR, etc. have their own usage documentation.
More information: \[la]https://get-coursier.io/docs/overview\[ra]\&.
.RE
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCcs version\fR
.RS
.IP \(bu 2
Show a list of the installed applications:
.RE
.PP
\fB\fCcs list\fR
.RS
.IP \(bu 2
Install a specific application:
.RE
.PP
\fB\fCcs install {{application_name}}\fR
.RS
.IP \(bu 2
Uninstall a specific application:
.RE
.PP
\fB\fCcs uninstall {{application_name}}\fR
.RS
.IP \(bu 2
Setup machine for the Scala development:
.RE
.PP
\fB\fCcs setup\fR
.RS
.IP \(bu 2
Update all the installed applications:
.RE
.PP
\fB\fCcs update\fR
