.TH csh
.PP
.RS
The shell (command interpreter) with C\-like syntax.
See also: \fB\fCtcsh\fR\&.
More information: \[la]https://www.mkssoftware.com/docs/man1/csh.1.asp\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive shell session:
.RE
.PP
\fB\fCcsh\fR
.RS
.IP \(bu 2
Start an interactive shell session without loading startup configs:
.RE
.PP
\fB\fCcsh \-f\fR
.RS
.IP \(bu 2
Execute specific [c]ommands:
.RE
.PP
\fB\fCcsh \-c "{{echo 'csh is executed'}}"\fR
.RS
.IP \(bu 2
Execute a specific script:
.RE
.PP
\fB\fCcsh {{path/to/script.csh}}\fR
