.TH csvclean
.PP
.RS
Finds and cleans common syntax errors in CSV files.
Included in csvkit.
More information: \[la]https://csvkit.readthedocs.io/en/latest/scripts/csvclean.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Clean a CSV file:
.RE
.PP
\fB\fCcsvclean {{bad.csv}}\fR
.RS
.IP \(bu 2
List locations of syntax errors in a CSV file:
.RE
.PP
\fB\fCcsvclean \-n {{bad.csv}}\fR
