.TH csvpy
.PP
.RS
Loads a CSV file into a Python shell.
Included in csvkit.
More information: \[la]https://csvkit.readthedocs.io/en/latest/scripts/csvpy.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Load a CSV file into a \fB\fCCSVKitReader\fR object:
.RE
.PP
\fB\fCcsvpy {{data.csv}}\fR
.RS
.IP \(bu 2
Load a CSV file into a \fB\fCCSVKitDictReader\fR object:
.RE
.PP
\fB\fCcsvpy \-\-dict {{data.csv}}\fR
