.TH cups\-config
.PP
.RS
Show technical information about your CUPS print server installation.
More information: \[la]https://www.cups.org/doc/man-cups-config.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the currently installed version of CUPS:
.RE
.PP
\fB\fCcups\-config \-\-version\fR
.RS
.IP \(bu 2
Show where CUPS is currently installed:
.RE
.PP
\fB\fCcups\-config \-\-serverbin\fR
.RS
.IP \(bu 2
Show the location of CUPS' configuration directory:
.RE
.PP
\fB\fCcups\-config \-\-serverroot\fR
.RS
.IP \(bu 2
Show the location of CUPS' data directory:
.RE
.PP
\fB\fCcups\-config \-\-datadir\fR
.RS
.IP \(bu 2
Display all available options:
.RE
.PP
\fB\fCcups\-config \-\-help\fR
