.TH d8
.PP
.RS
Developer shell for the V8 JavaScript engine.
More information: \[la]https://v8.dev/docs/d8\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a REPL (interactive shell):
.RE
.PP
\fB\fCd8\fR
.RS
.IP \(bu 2
Run a JavaScript file:
.RE
.PP
\fB\fCd8 {{path/to/file.js}}\fR
.RS
.IP \(bu 2
Evaluate a JavaScript expression:
.RE
.PP
\fB\fCd8 \-e "{{code}}\fR
