.TH dcg
.PP
.RS
Drupal code generator.
More information: \[la]https://github.com/Chi-teck/drupal-code-generator\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a wizard to choose what kind of code (e.g. module, service, form, etc.) to generate:
.RE
.PP
\fB\fCdcg\fR
.RS
.IP \(bu 2
Directly specify the kind of code to generate:
.RE
.PP
\fB\fCdcg {{service|plugin|theme|module|form}}\fR
.RS
.IP \(bu 2
Generate the code in a specific directory:
.RE
.PP
\fB\fCdcg \-\-directory {{path/to/directory}}\fR
