.TH ddgr
.PP
.RS
Search DuckDuckGo (HTML version) from the terminal.
More information: \[la]https://github.com/jarun/ddgr\[ra]\&.
.RE
.RS
.IP \(bu 2
Start in interactive mode:
.RE
.PP
\fB\fCddgr\fR
.RS
.IP \(bu 2
Search DuckDuckGo for a keyword:
.RE
.PP
\fB\fCddgr {{keyword}}\fR
.RS
.IP \(bu 2
Limit the number of search results to \fB\fCN\fR:
.RE
.PP
\fB\fCddgr \-n {{N}} {{keyword}}\fR
.RS
.IP \(bu 2
Display the complete URL in search results:
.RE
.PP
\fB\fCddgr \-x {{keyword}}\fR
.RS
.IP \(bu 2
Search DuckDuckGo for a keyword and open the first result in the browser:
.RE
.PP
\fB\fCddgr !w {{keyword}}\fR
.RS
.IP \(bu 2
Perform a website\-specific search:
.RE
.PP
\fB\fCddgr \-w {{site}} {{keyword}}\fR
.RS
.IP \(bu 2
Search for a specific file type:
.RE
.PP
\fB\fCddgr {{keyword}} filetype:{{filetype}}\fR
.RS
.IP \(bu 2
Display help in interactive mode:
.RE
.PP
\fB\fC?\fR
