.TH deluged
.PP
.RS
A daemon process for the Deluge BitTorrent client.
More information: \[la]https://deluge-torrent.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the Deluge daemon:
.RE
.PP
\fB\fCdeluged\fR
.RS
.IP \(bu 2
Start the Deluge daemon on a specific port:
.RE
.PP
\fB\fCdeluged \-p {{port}}\fR
.RS
.IP \(bu 2
Start the Deluge daemon using a specific configuration file:
.RE
.PP
\fB\fCdeluged \-c {{path/to/configuration_file}}\fR
.RS
.IP \(bu 2
Start the Deluge daemon and output the log to a file:
.RE
.PP
\fB\fCdeluged \-l {{path/to/log_file}}\fR
