.TH dfc
.PP
.RS
Gives an overview of the filesystem disk space usage with colors and graphs.
More information: \[la]https://projects.gw-computing.net/projects/dfc/wiki\[ra]\&.
.RE
.RS
.IP \(bu 2
Display filesystems and their disk usage in human\-readable form with colors and graphs:
.RE
.PP
\fB\fCdfc\fR
.RS
.IP \(bu 2
Display all filesystems including pseudo, duplicate and inaccessible filesystems:
.RE
.PP
\fB\fCdfc \-a\fR
.RS
.IP \(bu 2
Display filesystems without color:
.RE
.PP
\fB\fCdfc \-c never\fR
.RS
.IP \(bu 2
Display filesystems containing "ext" in the filesystem type:
.RE
.PP
\fB\fCdfc \-t ext\fR
