.TH dhclient
.PP
.RS
DHCP client.
More information: \[la]https://manned.org/dhclient\[ra]\&.
.RE
.RS
.IP \(bu 2
Get an IP address for the \fB\fCeth0\fR interface:
.RE
.PP
\fB\fCsudo dhclient {{eth0}}\fR
.RS
.IP \(bu 2
Release an IP address for the \fB\fCeth0\fR interface:
.RE
.PP
\fB\fCsudo dhclient \-r {{eth0}}\fR
