.TH diffstat
.PP
.RS
Create a histogram from the output of the \fB\fCdiff\fR command.
More information: \[la]https://manned.org/diffstat\[ra]\&.
.RE
.RS
.IP \(bu 2
Display changes in a histogram:
.RE
.PP
\fB\fCdiff {{file1}} {{file2}} | diffstat\fR
.RS
.IP \(bu 2
Display inserted, deleted and modified changes as a table:
.RE
.PP
\fB\fCdiff {{file1}} {{file2}} | diffstat \-t\fR
