.TH dillo
.PP
.RS
A lightweight web browser intended for slow computers.
More information: \[la]https://www.dillo.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch Dillo:
.RE
.PP
\fB\fCdillo\fR
.RS
.IP \(bu 2
Launch Dillo with a specific window size and screen location:
.RE
.PP
\fB\fCdillo \-\-geometry {{width}}x{{height}}+{{x_position}}+{{y_position}}\fR
.RS
.IP \(bu 2
Launch Dillo and open a specific URL:
.RE
.PP
\fB\fCdillo {{duckduckgo.com}}\fR
.RS
.IP \(bu 2
Launch Dillo and open a file or directory:
.RE
.PP
\fB\fCdillo {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Launch Dillo in full\-screen mode:
.RE
.PP
\fB\fCdillo \-\-fullwindow\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCdillo \-\-version\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdillo \-\-help\fR
