.TH dircolors
.PP
.RS
Output commands to set the LS_COLOR environment variable and style \fB\fCls\fR, \fB\fCdir\fR, etc.
More information: \[la]https://www.gnu.org/software/coreutils/dircolors\[ra]\&.
.RE
.RS
.IP \(bu 2
Output commands to set LS_COLOR using default colors:
.RE
.PP
\fB\fCdircolors\fR
.RS
.IP \(bu 2
Output commands to set LS_COLOR using colors from a file:
.RE
.PP
\fB\fCdircolors {{path/to/file}}\fR
.RS
.IP \(bu 2
Output commands for Bourne shell:
.RE
.PP
\fB\fCdircolors \-\-bourne\-shell\fR
.RS
.IP \(bu 2
Output commands for C shell:
.RE
.PP
\fB\fCdircolors \-\-c\-shell\fR
.RS
.IP \(bu 2
View the default colors for file types and extensions:
.RE
.PP
\fB\fCdircolors \-\-print\-data\fR
