.TH diskonaut
.PP
.RS
Terminal disk space navigator, written in Rust.
More information: \[la]https://github.com/imsnif/diskonaut\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCdiskonaut\fR in the current directory:
.RE
.PP
\fB\fCdiskonaut\fR
.RS
.IP \(bu 2
Start \fB\fCdiskonaut\fR in a specific directory:
.RE
.PP
\fB\fCdiskonaut {{path/to/directory}}\fR
.RS
.IP \(bu 2
Show file sizes rather than their block usage on the disk:
.RE
.PP
\fB\fCdiskonaut \-\-apparent\-size {{path/to/directory}}\fR
.RS
.IP \(bu 2
Disable deletion confirmation:
.RE
.PP
\fB\fCdiskonaut \-\-disable\-delete\-confirmation\fR
