.TH dive
.PP
.RS
A tool for exploring a Docker image, layer contents, and discovering ways to shrink it.
More information: \[la]https://github.com/wagoodman/dive\[ra]\&.
.RE
.RS
.IP \(bu 2
Analyze a Docker image:
.RE
.PP
\fB\fCdive {{your_image_tag}}\fR
.RS
.IP \(bu 2
Build an image and start analyzing it:
.RE
.PP
\fB\fCdive build \-t {{some_tag}}\fR
