.TH dmd
.PP
.RS
Official D compiler.
More information: \[la]https://dlang.org/dmd.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Build a D source file:
.RE
.PP
\fB\fCdmd {{path/to/source.d}}\fR
.RS
.IP \(bu 2
Generate code for all template instantiations:
.RE
.PP
\fB\fCdmd \-allinst\fR
.RS
.IP \(bu 2
Control bounds checking:
.RE
.PP
\fB\fCdmd \-boundscheck={{on|safeonly|off}}\fR
.RS
.IP \(bu 2
List information on all available checks:
.RE
.PP
\fB\fCdmd \-check={{h|help|?}}\fR
.RS
.IP \(bu 2
Turn on colored console output:
.RE
.PP
\fB\fCdmd \-color\fR
