.TH docker secret
.PP
.RS
Manage Docker swarm secrets.
More information: \[la]https://docs.docker.com/engine/reference/commandline/secret/\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new secret from \fB\fCstdin\fR:
.RE
.PP
\fB\fC{{command}} | docker secret create {{secret_name}} \-\fR
.RS
.IP \(bu 2
Create a new secret from a file:
.RE
.PP
\fB\fCdocker secret create {{secret_name}} {{path/to/file}}\fR
.RS
.IP \(bu 2
List all secrets:
.RE
.PP
\fB\fCdocker secret ls\fR
.RS
.IP \(bu 2
Display detailed information on one or multiple secrets in a human friendly format:
.RE
.PP
\fB\fCdocker secret inspect \-\-pretty {{secret_name1 secret_name2 ...}}\fR
.RS
.IP \(bu 2
Remove one or more secrets:
.RE
.PP
\fB\fCdocker secret rm {{secret_name1 secret_name2 ...}}\fR
