.TH docker tag
.PP
.RS
Assign tags to existing Docker images.
More information: \[la]https://docs.docker.com/engine/reference/commandline/tag/\[ra]\&.
.RE
.RS
.IP \(bu 2
Assign a name and tag to a specific image ID:
.RE
.PP
\fB\fCdocker tag {{id}} {{name}}:{{tag}}\fR
.RS
.IP \(bu 2
Assign a tag to a specific image:
.RE
.PP
\fB\fCdocker tag {{image}}:{{current_tag}} {{image}}:{{new_tag}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdocker tag\fR
