.TH docker rename
.PP
.RS
Rename a container.
More information: \[la]https://docs.docker.com/engine/reference/commandline/rename\[ra]\&.
.RE
.RS
.IP \(bu 2
Rename a container:
.RE
.PP
\fB\fCdocker rename {{container}} {{new_name}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdocker rename \-\-help\fR
