.TH docker diff
.PP
.RS
Inspect changes to files or directories on a container's filesystem.
More information: \[la]https://docs.docker.com/engine/reference/commandline/diff\[ra]\&.
.RE
.RS
.IP \(bu 2
Inspect the changes to a container since it was created:
.RE
.PP
\fB\fCdocker diff {{container}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdocker diff \-\-help\fR
