.TH docsify
.PP
.RS
Initialize and serve markdown documentation.
More information: \[la]https://cli.docsifyjs.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new documentation in the current directory:
.RE
.PP
\fB\fCdocsify init\fR
.RS
.IP \(bu 2
Initialize a new documentation in the specified directory:
.RE
.PP
\fB\fCdocsify init {{path/to/directory}}\fR
.RS
.IP \(bu 2
Serve local documentation on \fB\fClocalhost:3000\fR with live reload:
.RE
.PP
\fB\fCdocsify serve {{path/to/directory}}\fR
.RS
.IP \(bu 2
Serve local documentation on \fB\fClocalhost\fR at the specified port:
.RE
.PP
\fB\fCdocsify serve \-\-port {{80}} {{path/to/directory}}\fR
.RS
.IP \(bu 2
Generate a sidebar markdown file in the specified directory:
.RE
.PP
\fB\fCdocsify generate {{path/to/directory}}\fR
