.TH doctum
.PP
.RS
A PHP API documentation generator.
More information: \[la]https://github.com/code-lts/doctum\[ra]\&.
.RE
.RS
.IP \(bu 2
Parse a project:
.RE
.PP
\fB\fCdoctum parse\fR
.RS
.IP \(bu 2
Render a project:
.RE
.PP
\fB\fCdoctum render\fR
.RS
.IP \(bu 2
Parse then render a project:
.RE
.PP
\fB\fCdoctum update\fR
.RS
.IP \(bu 2
Parse and render only a specific version of a project:
.RE
.PP
\fB\fCdoctum update \-\-only\-version={{version}}\fR
.RS
.IP \(bu 2
Parse and render a project using a specific configuration:
.RE
.PP
\fB\fCdoctum update {{path/to/config.php}}\fR
