.TH doctl account
.PP
.RS
Retrieve information about Digital Ocean accounts.
More information: \[la]https://docs.digitalocean.com/reference/doctl/reference/account/\[ra]\&.
.RE
.RS
.IP \(bu 2
Display account info:
.RE
.PP
\fB\fCdoctl account get\fR
.RS
.IP \(bu 2
Show the hourly API limit, progress towards it, and when the rate limit resets:
.RE
.PP
\fB\fCdoctl account ratelimit\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdoctl account \-\-help\fR
