.TH doctl kubernetes options
.PP
.RS
Provides values available for use with doctl's Kubernetes commands.
More information: \[la]https://docs.digitalocean.com/reference/doctl/reference/kubernetes/options/\[ra]\&.
.RE
.RS
.IP \(bu 2
List regions that support Kubernetes clusters:
.RE
.PP
\fB\fCdoctl kubernetes options regions\fR
.RS
.IP \(bu 2
List machine sizes that can be used in a Kubernetes cluster:
.RE
.PP
\fB\fCdoctl kubernetes options sizes\fR
.RS
.IP \(bu 2
List Kubernetes versions that can be used with DigitalOcean clusters:
.RE
.PP
\fB\fCdoctl kubernetes options versions\fR
