.TH doctl serverless
.PP
.RS
Manage serverless functions.
More information: \[la]https://docs.digitalocean.com/reference/doctl/reference/serverless/\[ra]\&.
.RE
.RS
.IP \(bu 2
Connect local serverless support to a functions namespace:
.RE
.PP
\fB\fCdoctl serverless connect\fR
.RS
.IP \(bu 2
Deploy a functions project to your functions namespace:
.RE
.PP
\fB\fCdoctl serverless deploy\fR
.RS
.IP \(bu 2
Obtain metadata of a functions project:
.RE
.PP
\fB\fCdoctl serverless get\-metadata\fR
.RS
.IP \(bu 2
Provide information about serverless support:
.RE
.PP
\fB\fCdoctl serverless status\fR
