.TH doctl balance
.PP
.RS
Show the balance of a Digital Ocean account.
More information: \[la]https://docs.digitalocean.com/reference/doctl/reference/balance/\[ra]\&.
.RE
.RS
.IP \(bu 2
Get balance of the account associated with the current context:
.RE
.PP
\fB\fCdoctl balance get\fR
.RS
.IP \(bu 2
Get the balance of an account associated with an access token:
.RE
.PP
\fB\fCdoctl balance get \-\-access\-token {{access_token}}\fR
.RS
.IP \(bu 2
Get the balance of an account associated with a specified context:
.RE
.PP
\fB\fCdoctl balance get \-\-context\fR
