.TH dolt add
.PP
.RS
Add the contents of a table to the list of Dolt staged tables.
More information: \[la]https://github.com/dolthub/dolt\[ra]\&.
.RE
.RS
.IP \(bu 2
Add a table to the list of staged tables (stage a table):
.RE
.PP
\fB\fCdolt add {{table}}\fR
.RS
.IP \(bu 2
Stage all tables:
.RE
.PP
\fB\fCdolt add \-\-all\fR
