.TH dolt
.PP
.RS
Dolt is an SQL database that you can fork, clone, branch, merge, push and pull just like a Git repository.
Some subcommands such as \fB\fCdolt commit\fR have their own usage documentation.
More information: \[la]https://github.com/dolthub/dolt\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute a dolt subcommand:
.RE
.PP
\fB\fCdolt {{subcommand}}\fR
.RS
.IP \(bu 2
List available subcommands:
.RE
.PP
\fB\fCdolt help\fR
