.TH dolt merge
.PP
.RS
Join two or more development histories together.
More information: \[la]https://github.com/dolthub/dolt\[ra]\&.
.RE
.RS
.IP \(bu 2
Incorporate changes from the named commits into the current branch:
.RE
.PP
\fB\fCdolt merge {{branch_name}}\fR
.RS
.IP \(bu 2
Incorporate changes from the named commits into the current branch without updating the commit history:
.RE
.PP
\fB\fCdolt merge \-\-squash {{branch_name}}\fR
.RS
.IP \(bu 2
Merge a branch and create a merge commit even when the merge resolves as a fast\-forward:
.RE
.PP
\fB\fCdolt merge \-\-no\-ff {{branch_name}}\fR
.RS
.IP \(bu 2
Merge a branch and create a merge commit with a specific commit message:
.RE
.PP
\fB\fCdolt merge \-\-no\-ff \-m "{{message}}" {{branch_name}}\fR
.RS
.IP \(bu 2
Abort the current conflict resolution process:
.RE
.PP
\fB\fCdolt merge \-\-abort\fR
