.TH dolt init
.PP
.RS
Create an empty Dolt data repository.
More information: \[la]https://docs.dolthub.com/cli-reference/cli#dolt-init\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new Dolt data repository in the current directory:
.RE
.PP
\fB\fCdolt init\fR
.RS
.IP \(bu 2
Initialize a new Dolt data repository creating a commit with the specified metadata:
.RE
.PP
\fB\fCdolt init \-\-name "{{name}}" \-\-email "{{email}}" \-\-date "{{2021\-12\-31T00:00:00}}" \-b "{{branch_name}}"\fR
