.TH dolt blame
.PP
.RS
Displays commit information for each row of a Dolt table.
More information: \[la]http://github.com/dolthub/dolt\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the latest commit for each row of a table:
.RE
.PP
\fB\fCdolt blame {{table}}\fR
.RS
.IP \(bu 2
Display the latest commits for each row of a table when the specified commit was made:
.RE
.PP
\fB\fCdolt blame {{commit}} {{table}}\fR
.RS
.IP \(bu 2
View help:
.RE
.PP
\fB\fCdolt blame \-\-help\fR
