.TH dolt fetch
.PP
.RS
Download objects and refs from another repository.
More information: \[la]https://github.com/dolthub/dolt\[ra]\&.
.RE
.RS
.IP \(bu 2
Fetch the latest changes from the default remote upstream repository (origin):
.RE
.PP
\fB\fCdolt fetch\fR
.RS
.IP \(bu 2
Fetch latest changes from a specific remote upstream repository:
.RE
.PP
\fB\fCdolt fetch {{remote_name}}\fR
.RS
.IP \(bu 2
Update branches with the current state of the remote, overwriting any conflicting history:
.RE
.PP
\fB\fCdolt fetch \-f\fR
