.TH dotnet add reference
.PP
.RS
Add .NET project\-to\-project references.
More information: \[la]https://learn.microsoft.com/dotnet/core/tools/dotnet-add-reference\[ra]\&.
.RE
.RS
.IP \(bu 2
Add a reference to the project in the current directory:
.RE
.PP
\fB\fCdotnet add reference {{path/to/reference.csproj}}\fR
.RS
.IP \(bu 2
Add a reference to the specific project:
.RE
.PP
\fB\fCdotnet add {{path/to/project.csproj}} reference {{path/to/reference.csproj}}\fR
