.TH doxygen
.PP
.RS
A documentation system for various programming languages.
More information: \[la]http://www.doxygen.nl\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a default template configuration file \fB\fCDoxyfile\fR:
.RE
.PP
\fB\fCdoxygen \-g\fR
.RS
.IP \(bu 2
Generate a template configuration file:
.RE
.PP
\fB\fCdoxygen \-g {{path/to/config_file}}\fR
.RS
.IP \(bu 2
Generate documentation using an existing configuration file:
.RE
.PP
\fB\fCdoxygen {{path/to/config_file}}\fR
