.TH drupal
.PP
.RS
Generate boilerplate code, interact with and debug Drupal projects.
Some subcommands such as \fB\fCdrupal check\fR have their own usage documentation.
More information: \[la]https://drupalconsole.com/\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a module:
.RE
.PP
\fB\fCdrupal module:install {{module_name}}\fR
.RS
.IP \(bu 2
Uninstall a module:
.RE
.PP
\fB\fCdrupal module:uninstall {{module_name}}\fR
.RS
.IP \(bu 2
Clear all caches:
.RE
.PP
\fB\fCdrupal cache:rebuild\fR
.RS
.IP \(bu 2
View current Drupal installation status:
.RE
.PP
\fB\fCdrupal site:status\fR
