.TH drush
.PP
.RS
A command\-line shell and scripting interface for Drupal.
More information: \[la]https://www.drush.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Enable module "foo":
.RE
.PP
\fB\fCdrush en {{foo}}\fR
.RS
.IP \(bu 2
Uninstall module "foo":
.RE
.PP
\fB\fCdrush pmu {{foo}}\fR
.RS
.IP \(bu 2
Clear all caches:
.RE
.PP
\fB\fCdrush cr\fR
.RS
.IP \(bu 2
Clear CSS and JavaScript caches:
.RE
.PP
\fB\fCdrush cc css\-js\fR
