.TH dub
.PP
.RS
Package manager for D packages.
More information: \[la]https://dub.pm/commandline\[ra]\&.
.RE
.RS
.IP \(bu 2
Interactively create a new D project:
.RE
.PP
\fB\fCdub init {{project_name}}\fR
.RS
.IP \(bu 2
Non\-interactively create a new D project:
.RE
.PP
\fB\fCdub init {{project_name}} \-n\fR
.RS
.IP \(bu 2
Build and run a D project:
.RE
.PP
\fB\fCdub\fR
.RS
.IP \(bu 2
Install dependencies specified in a D project's \fB\fCdub.json\fR or \fB\fCdub.sdl\fR file:
.RE
.PP
\fB\fCdub fetch\fR
.RS
.IP \(bu 2
Update the dependencies in a D project:
.RE
.PP
\fB\fCdub upgrade\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCdub \-\-help\fR
