.TH dune
.PP
.RS
A build system for OCaml programs.
More information: \[la]https://dune.build\[ra]\&.
.RE
.RS
.IP \(bu 2
Build all targets:
.RE
.PP
\fB\fCdune build\fR
.RS
.IP \(bu 2
Clean up the workspace:
.RE
.PP
\fB\fCdune clean\fR
.RS
.IP \(bu 2
Run all tests:
.RE
.PP
\fB\fCdune runtest\fR
.RS
.IP \(bu 2
Start the utop REPL with compiled modules automatically loaded into it, to remove the need to load them by hand:
.RE
.PP
\fB\fCdune utop\fR
