.TH dvc init
.PP
.RS
Initialize a new local DVC repository.
More information: \[la]https://dvc.org/doc/command-reference/init\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new local repository:
.RE
.PP
\fB\fCdvc init\fR
.RS
.IP \(bu 2
Initialize DVC without Git:
.RE
.PP
\fB\fCdvc init \-\-no\-scm\fR
.RS
.IP \(bu 2
Initialize DVC in a subdirectory:
.RE
.PP
\fB\fCcd {{path/to/subdir}} && dvc init \-\-sudir\fR
