.TH dvc destroy
.PP
.RS
Remove all DVC files and directories from a DVC project.
More information: \[la]https://dvc.org/doc/command-reference/destroy\[ra]\&.
.RE
.RS
.IP \(bu 2
Destroy the current project:
.RE
.PP
\fB\fCdvc destroy\fR
.RS
.IP \(bu 2
Force destroy the current project:
.RE
.PP
\fB\fCdvc destroy \-\-force\fR
