.TH dvc
.PP
.RS
Data Version Control: like \fB\fCgit\fR for data.
Some subcommands such as \fB\fCdvc commit\fR have their own usage documentation.
More information: \[la]https://dvc.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the DVC version:
.RE
.PP
\fB\fCdvc \-\-version\fR
.RS
.IP \(bu 2
Display general help:
.RE
.PP
\fB\fCdvc \-\-help\fR
.RS
.IP \(bu 2
Display help about a specific subcommand:
.RE
.PP
\fB\fCdvc {{subcommand}} \-\-help\fR
.RS
.IP \(bu 2
Execute a DVC subcommand:
.RE
.PP
\fB\fCdvc {{subcommand}}\fR
