.TH elinks
.PP
.RS
A text based browser similar to \fB\fClynx\fR\&.
More information: \[la]http://elinks.or.cz\[ra]\&.
.RE
.RS
.IP \(bu 2
Start ELinks:
.RE
.PP
\fB\fCelinks\fR
.RS
.IP \(bu 2
Quit elinks:
.RE
.PP
\fB\fCCtrl + C\fR
.RS
.IP \(bu 2
Dump output of webpage to console, colorizing the text with ANSI control codes:
.RE
.PP
\fB\fCelinks \-dump \-dump\-color\-mode {{1}} {{url}}\fR
