.TH elixir
.PP
.RS
Elixir programming language interpreter.
More information: \[la]https://elixir-lang.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Run an Elixir file:
.RE
.PP
\fB\fCelixir {{path/to/file}}\fR
.RS
.IP \(bu 2
Evaluate Elixir code by passing it as an argument:
.RE
.PP
\fB\fCelixir \-e "{{code}}"\fR
