.TH elvish
.PP
.RS
Expressive programming language and a versatile interactive shell.
See also: \fB\fCnu\fR\&.
More information: \[la]https://elv.sh\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive shell session:
.RE
.PP
\fB\fCelvish\fR
.RS
.IP \(bu 2
Execute specific [c]ommands:
.RE
.PP
\fB\fCelvish \-c "{{echo 'elvish is executed'}}"\fR
.RS
.IP \(bu 2
Execute a specific script:
.RE
.PP
\fB\fCelvish {{path/to/script.elv}}\fR
