.TH ember
.PP
.RS
The Ember.js command\-line utility.
Used for creating and maintaining Ember.js applications.
More information: \[la]https://cli.emberjs.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Ember application:
.RE
.PP
\fB\fCember new {{my_new_app}}\fR
.RS
.IP \(bu 2
Create a new Ember addon:
.RE
.PP
\fB\fCember addon {{my_new_addon}}\fR
.RS
.IP \(bu 2
Build the project:
.RE
.PP
\fB\fCember build\fR
.RS
.IP \(bu 2
Build the project in production mode:
.RE
.PP
\fB\fCember build \-prod\fR
.RS
.IP \(bu 2
Run the development server:
.RE
.PP
\fB\fCember serve\fR
.RS
.IP \(bu 2
Run the test suite:
.RE
.PP
\fB\fCember test\fR
.RS
.IP \(bu 2
Run a blueprint to generate something like a route or component:
.RE
.PP
\fB\fCember generate {{type}} {{name}}\fR
.RS
.IP \(bu 2
Install an ember\-cli addon:
.RE
.PP
\fB\fCember install {{name_of_addon}}\fR
