.TH eslint
.PP
.RS
A pluggable linting utility for JavaScript and JSX.
More information: \[la]https://eslint.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Create the ESLint config file:
.RE
.PP
\fB\fCeslint \-\-init\fR
.RS
.IP \(bu 2
Lint one or more files:
.RE
.PP
\fB\fCeslint {{path/to/file1.js path/to/file2.js ...}}\fR
.RS
.IP \(bu 2
Fix lint issues:
.RE
.PP
\fB\fCeslint \-\-fix\fR
.RS
.IP \(bu 2
Lint using the specified config:
.RE
.PP
\fB\fCeslint \-c {{path/to/config_file}} {{path/to/file1.js path/to/file2.js}}\fR
