.TH exercism
.PP
.RS
Download and solve problems.
More information: \[la]https://exercism.org/docs/using/solving-exercises/working-locally\[ra]\&.
.RE
.RS
.IP \(bu 2
Configure the application token and the preferred workspace for Exercism:
.RE
.PP
\fB\fCexercism configure \-\-token={{your\-application\-token}} \-\-workspace={{/path/to/preferred/workspace}}\fR
.RS
.IP \(bu 2
Download a specific exercise:
.RE
.PP
\fB\fCexercism download \-\-exercise={{exercise_slug}} \-\-track={{track_slug}}\fR
.RS
.IP \(bu 2
Submit an exercise:
.RE
.PP
\fB\fCexercism submit {{path/to/file}}\fR
.RS
.IP \(bu 2
Print the path to the solution workspace:
.RE
.PP
\fB\fCexercism workspace\fR
