.TH exfatlabel
.PP
.RS
Get or set an exFAT filesystem label.
More information: \[la]https://manned.org/exfatlabel\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the current filesystem label:
.RE
.PP
\fB\fCexfatlabel {{/dev/sda}}\fR
.RS
.IP \(bu 2
Set the filesystem label:
.RE
.PP
\fB\fCexfatlabel {{/dev/sda}} {{new_label}}\fR
