.TH expose
.PP
.RS
An open source tunnel application for sharing websites.
More information: \[la]https://beyondco.de/docs/expose\[ra]\&.
.RE
.RS
.IP \(bu 2
Register your authentication token:
.RE
.PP
\fB\fCexpose token {{token}}\fR
.RS
.IP \(bu 2
Share the current working directory:
.RE
.PP
\fB\fCexpose\fR
.RS
.IP \(bu 2
Share the current working directory with a specific subdomain:
.RE
.PP
\fB\fCexpose \-\-subdomain={{subdomain}}\fR
.RS
.IP \(bu 2
Share a local URL:
.RE
.PP
\fB\fCexpose share {{url}}\fR
.RS
.IP \(bu 2
Run the Expose server:
.RE
.PP
\fB\fCexpose serve\fR
.RS
.IP \(bu 2
Run the Expose server with a specific hostname:
.RE
.PP
\fB\fCexpose serve {{hostname}}\fR
