.TH f3read
.PP
.RS
Validate .h2w files to test the real capacity of the drive.
See also \fB\fCf3write\fR, \fB\fCf3probe\fR, \fB\fCf3fix\fR\&.
More information: \[la]http://oss.digirati.com.br/f3/\[ra]\&.
.RE
.RS
.IP \(bu 2
Validate a device by checking the files in a given directory:
.RE
.PP
\fB\fCf3read {{path/to/mount_point}}\fR
