.TH factor
.PP
.RS
Prints the prime factorization of a number.
More information: \[la]https://www.gnu.org/software/coreutils/factor\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the prime\-factorization of a number:
.RE
.PP
\fB\fCfactor {{number}}\fR
.RS
.IP \(bu 2
Take the input from \fB\fCstdin\fR if no argument is specified:
.RE
.PP
\fB\fCecho {{number}} | factor\fR
