.TH fastfetch
.PP
.RS
Display information about your operating system, software and hardware.
More information: \[la]https://github.com/LinusDierheimer/fastfetch\[ra]\&.
.RE
.RS
.IP \(bu 2
Display system information:
.RE
.PP
\fB\fCfastfetch\fR
.RS
.IP \(bu 2
Set the structure of the fetch:
.RE
.PP
\fB\fCfastfetch \-\-structure {{structure}}\fR
.RS
.IP \(bu 2
Load a custom config file:
.RE
.PP
\fB\fCfastfetch \-\-load\-config {{path/to/config_file}}\fR
.RS
.IP \(bu 2
Set the logo to use:
.RE
.PP
\fB\fCfastfetch \-\-logo {{logo}}\fR
.RS
.IP \(bu 2
Set the color of the keys and title:
.RE
.PP
\fB\fCfastfetch \-\-color {{blue}}\fR
