.TH fast
.PP
.RS
Test your download and upload speed using fast.com.
More information: \[la]https://github.com/sindresorhus/fast-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Measure the current download speed:
.RE
.PP
\fB\fCfast\fR
.RS
.IP \(bu 2
Measure the current upload speed in addition to download speed:
.RE
.PP
\fB\fCfast \-\-upload\fR
.RS
.IP \(bu 2
Display results on a single line to reduce spacing:
.RE
.PP
\fB\fCfast \-\-single\-line\fR
