.TH fc\-cache
.PP
.RS
Scan font directories to build font cache files.
More information: \[la]https://manned.org/fc-cache\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate font cache files:
.RE
.PP
\fB\fCfc\-cache\fR
.RS
.IP \(bu 2
Force a rebuild of all font cache files, without checking if cache is up\-to\-date:
.RE
.PP
\fB\fCfc\-cache \-f\fR
.RS
.IP \(bu 2
Erase font cache files, then generate new font cache files:
.RE
.PP
\fB\fCfc\-cache \-r\fR
