.TH fc\-list
.PP
.RS
List available fonts installed on the system.
More information: \[la]https://manned.org/fc-list\[ra]\&.
.RE
.RS
.IP \(bu 2
Return a list of installed fonts in your system:
.RE
.PP
\fB\fCfc\-list\fR
.RS
.IP \(bu 2
Return a list of installed fonts with given name:
.RE
.PP
\fB\fCfc\-list | grep '{{DejaVu Serif}}'\fR
.RS
.IP \(bu 2
Return the number of installed fonts in your system:
.RE
.PP
\fB\fCfc\-list | wc \-l\fR
