.TH fc\-pattern
.PP
.RS
Shows information about a font matching a pattern.
More information: \[la]https://manned.org/fc-pattern\[ra]\&.
.RE
.RS
.IP \(bu 2
Display default information about a font:
.RE
.PP
\fB\fCfc\-pattern \-\-default '{{DejaVu Serif}}'\fR
.RS
.IP \(bu 2
Display config information about a font:
.RE
.PP
\fB\fCfc\-pattern \-\-config '{{DejaVu Serif}}'\fR
