.TH fc
.PP
.RS
Open the most recent command and edit it.
More information: \[la]https://manned.org/fc\[ra]\&.
.RE
.RS
.IP \(bu 2
Open in the default system editor:
.RE
.PP
\fB\fCfc\fR
.RS
.IP \(bu 2
Specify an editor to open with:
.RE
.PP
\fB\fCfc \-e {{'emacs'}}\fR
.RS
.IP \(bu 2
List recent commands from history:
.RE
.PP
\fB\fCfc \-l\fR
.RS
.IP \(bu 2
List recent commands in reverse order:
.RE
.PP
\fB\fCfc \-l \-r\fR
.RS
.IP \(bu 2
List commands in a given interval:
.RE
.PP
\fB\fCfc '{{416}}' '{{420}}'\fR
