.TH fdp
.PP
.RS
Render an image of a \fB\fCforce\-directed\fR network graph from a \fB\fCgraphviz\fR file.
Layouts: \fB\fCdot\fR, \fB\fCneato\fR, \fB\fCtwopi\fR, \fB\fCcirco\fR, \fB\fCfdp\fR, \fB\fCsfdp\fR, \fB\fCosage\fR & \fB\fCpatchwork\fR\&.
More information: \[la]https://graphviz.org/doc/info/command.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Render a \fB\fCpng\fR image with a filename based on the input filename and output format (uppercase \-O):
.RE
.PP
\fB\fCfdp \-T png \-O {{path/to/input.gv}}\fR
.RS
.IP \(bu 2
Render a \fB\fCsvg\fR image with the specified output filename (lowercase \-o):
.RE
.PP
\fB\fCfdp \-T svg \-o {{path/to/image.svg}} {{path/to/input.gv}}\fR
.RS
.IP \(bu 2
Render the output in a specific format:
.RE
.PP
\fB\fCfdp \-T {{ps|pdf|svg|fig|png|gif|jpg|json|dot}} \-O {{path/to/input.gv}}\fR
.RS
.IP \(bu 2
Render a \fB\fCgif\fR image using \fB\fCstdin\fR and \fB\fCstdout\fR:
.RE
.PP
\fB\fCecho "{{digraph {this \-> that} }}" | fdp \-T gif > {{path/to/image.gif}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCfdp \-?\fR
