.TH fdroidcl
.PP
.RS
F\-Droid CLI client.
More information: \[la]https://github.com/mvdan/fdroidcl\[ra]\&.
.RE
.RS
.IP \(bu 2
Fetch the F\-Droid index:
.RE
.PP
\fB\fCfdroidcl update\fR
.RS
.IP \(bu 2
Display info about an app:
.RE
.PP
\fB\fCfdroidcl show {{app_id}}\fR
.RS
.IP \(bu 2
Download an APK file:
.RE
.PP
\fB\fCfdroidcl download {{app_id}}\fR
.RS
.IP \(bu 2
Search for an app in the index:
.RE
.PP
\fB\fCfdroidcl search {{search_pattern}}\fR
.RS
.IP \(bu 2
Install an app on a connected device:
.RE
.PP
\fB\fCfdroidcl install {{app_id}}\fR
