.TH ffsend
.PP
.RS
Easily and securely share files.
More information: \[la]https://gitlab.com/timvisee/ffsend\[ra]\&.
.RE
.RS
.IP \(bu 2
Upload a file:
.RE
.PP
\fB\fCffsend upload {{path/to/file}}\fR
.RS
.IP \(bu 2
Download a file:
.RE
.PP
\fB\fCffsend download {{url}}\fR
.RS
.IP \(bu 2
Upload a file with password:
.RE
.PP
\fB\fCffsend upload {{path/to/file}} \-p {{password}}\fR
.RS
.IP \(bu 2
Download a file protected by password:
.RE
.PP
\fB\fCffsend download {{path/to/file}} \-p {{password}}\fR
.RS
.IP \(bu 2
Upload a file and allow 4 downloads:
.RE
.PP
\fB\fCffsend upload {{path/to/file}} \-d {{4}}\fR
