.TH fin
.PP
.RS
Docksal command\-line utility.
More information: \[la]https://docs.docksal.io/fin/fin/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the project in the current directory:
.RE
.PP
\fB\fCfin project start\fR
.RS
.IP \(bu 2
Stop the project in the current directory:
.RE
.PP
\fB\fCfin project stop\fR
.RS
.IP \(bu 2
Open a shell into a specific container:
.RE
.PP
\fB\fCfin bash {{container_name}}\fR
.RS
.IP \(bu 2
Display logs of a specific container:
.RE
.PP
\fB\fCfin logs {{container_name}}\fR
.RS
.IP \(bu 2
Display logs of a specific container and follow the log:
.RE
.PP
\fB\fCfin logs \-f {{container_name}}\fR
