.TH finger
.PP
.RS
User information lookup program.
More information: \[la]https://manned.org/finger\[ra]\&.
.RE
.RS
.IP \(bu 2
Display information about currently logged in users:
.RE
.PP
\fB\fCfinger\fR
.RS
.IP \(bu 2
Display information about a specific user:
.RE
.PP
\fB\fCfinger {{username}}\fR
.RS
.IP \(bu 2
Display the user's login name, real name, terminal name, and other information:
.RE
.PP
\fB\fCfinger \-s\fR
.RS
.IP \(bu 2
Produce multiline output format displaying same information as \fB\fC\-s\fR as well as user's home directory, home phone number, login shell, mail status, etc.:
.RE
.PP
\fB\fCfinger \-l\fR
.RS
.IP \(bu 2
Prevent matching against user's names and only use login names:
.RE
.PP
\fB\fCfinger \-m\fR
