.TH firebase
.PP
.RS
Test, manage, and deploy Firebase projects.
More information: \[la]https://github.com/firebase/firebase-tools\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in to \[la]https://console.firebase.google.com\[ra]:
.RE
.PP
\fB\fCfirebase login\fR
.RS
.IP \(bu 2
List existing Firebase projects:
.RE
.PP
\fB\fCfirebase projects:list\fR
.RS
.IP \(bu 2
Start an interactive wizard to create a Firebase project in the current directory:
.RE
.PP
\fB\fCfirebase init\fR
.RS
.IP \(bu 2
Deploy code and assets to the current Firebase project:
.RE
.PP
\fB\fCfirebase deploy\fR
.RS
.IP \(bu 2
Start a local server to statically host the current Firebase project's assets:
.RE
.PP
\fB\fCfirebase serve\fR
.RS
.IP \(bu 2
Start an interactive wizard to open one of many links of the current Firebase project in the default web browser:
.RE
.PP
\fB\fCfirebase open\fR
