.TH fkill
.PP
.RS
Fabulously kill processes. Cross\-platform.
More information: \[la]https://github.com/sindresorhus/fkill\[ra]\&.
.RE
.RS
.IP \(bu 2
Run without arguments to use the interactive interface:
.RE
.PP
\fB\fCfkill\fR
.RS
.IP \(bu 2
Kill the process by PID, name or port:
.RE
.PP
\fB\fCfkill {{pid|name|:port}}\fR
