.TH flake8
.PP
.RS
Tool to check the style and quality of Python code.
More information: \[la]https://flake8.pycqa.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Lint a file or directory recursively:
.RE
.PP
\fB\fCflake8 {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Lint a file or directory recursively and show the line on which each error occurred:
.RE
.PP
\fB\fCflake8 \-\-show\-source {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Lint a file or directory recursively and ignore a list of rules. (All available rules can be found at flake8rules.com):
.RE
.PP
\fB\fCflake8 \-\-ignore {{rule1,rule2}} {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Lint a file or directory recursively but exclude files matching the given globs or substrings:
.RE
.PP
\fB\fCflake8 \-\-exclude {{substring1,glob2}} {{path/to/file_or_directory}}\fR
