.TH flask
.PP
.RS
A general utility script for Flask applications. Loads the application defined in the \fB\fCFLASK_APP\fR environment variable.
More information: \[la]https://flask.palletsprojects.com/en/1.1.x/cli/\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a development server:
.RE
.PP
\fB\fCflask run\fR
.RS
.IP \(bu 2
Show the routes for the app:
.RE
.PP
\fB\fCflask routes\fR
.RS
.IP \(bu 2
Run a Python interactive shell in the app's context:
.RE
.PP
\fB\fCflask shell\fR
