.TH fnm
.PP
.RS
Fast Node.js version manager.
Install, uninstall or switch between Node.js versions.
More information: \[la]https://github.com/Schniz/fnm\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a specific version of Node.js:
.RE
.PP
\fB\fCfnm install {{node_version}}\fR
.RS
.IP \(bu 2
List all available Node.js versions and highlight the default one:
.RE
.PP
\fB\fCfnm list\fR
.RS
.IP \(bu 2
Use a specific version of Node.js in the current shell:
.RE
.PP
\fB\fCfnm use {{node_version}}\fR
.RS
.IP \(bu 2
Set the default Node.js version:
.RE
.PP
\fB\fCfnm default {{node_version}}\fR
.RS
.IP \(bu 2
Uninstall a given Node.js version:
.RE
.PP
\fB\fCfnm uninstall {{node_version}}\fR
