.TH forever
.PP
.RS
Server\-side JavaScript application that makes sure Node.js applications run indefinitely (restarts after exit).
More information: \[la]https://github.com/foreversd/forever\[ra]\&.
.RE
.RS
.IP \(bu 2
Start running a file forever (as a daemon):
.RE
.PP
\fB\fCforever {{script}}\fR
.RS
.IP \(bu 2
List running "forever" processes (along with IDs and other details of "forever" processes):
.RE
.PP
\fB\fCforever list\fR
.RS
.IP \(bu 2
Stop a running "forever" process:
.RE
.PP
\fB\fCforever stop {{ID|pid|script}}\fR
