.TH fortune
.PP
.RS
Print a random quotation (fortune\-cookie style).
More information: \[la]https://manned.org/fortune\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a quotation:
.RE
.PP
\fB\fCfortune\fR
.RS
.IP \(bu 2
Print an offensive quotation:
.RE
.PP
\fB\fCfortune \-o\fR
.RS
.IP \(bu 2
Print a long quotation:
.RE
.PP
\fB\fCfortune \-l\fR
.RS
.IP \(bu 2
Print a short quotation:
.RE
.PP
\fB\fCfortune \-s\fR
.RS
.IP \(bu 2
List the available quotation database files:
.RE
.PP
\fB\fCfortune \-f\fR
.RS
.IP \(bu 2
Print a quotation from one of the database files listed by \fB\fCfortune \-f\fR:
.RE
.PP
\fB\fCfortune {{path/to/file}}\fR
