.TH fossil add
.PP
.RS
Put files or directories under Fossil version control.
More information: \[la]https://fossil-scm.org/home/help/add\[ra]\&.
.RE
.RS
.IP \(bu 2
Put a file or directory under version control, so it will be in the current checkout:
.RE
.PP
\fB\fCfossil add {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Remove all added files from the current checkout:
.RE
.PP
\fB\fCfossil add \-\-reset\fR
