.TH fossa
.PP
.RS
CLI for the Fossa service \- Generate realtime license audits, vulnerability scans and reports about dependencies licenses.
More information: \[la]https://github.com/fossas/fossa-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a \fB\fC\&.fossa.yml\fR configuration file:
.RE
.PP
\fB\fCfossa init\fR
.RS
.IP \(bu 2
Run a default project build:
.RE
.PP
\fB\fCfossa build\fR
.RS
.IP \(bu 2
Analyze built dependencies:
.RE
.PP
\fB\fCfossa analyze\fR
.RS
.IP \(bu 2
Generate reports:
.RE
.PP
\fB\fCfossa report\fR
.RS
.IP \(bu 2
Test current revision against the FOSSA scan status and exit with errors if issues are found:
.RE
.PP
\fB\fCfossa test\fR
