.TH from
.PP
.RS
Prints mail header lines from the current user's mailbox.
More information: \[la]https://mailutils.org/manual/html_chapter/Programs.html#frm-and-from\[ra]\&.
.RE
.RS
.IP \(bu 2
List mail:
.RE
.PP
\fB\fCfrom\fR
.RS
.IP \(bu 2
Display the number of messages stored:
.RE
.PP
\fB\fCfrom \-\-count\fR
.RS
.IP \(bu 2
List mail in the specified mailbox directory:
.RE
.PP
\fB\fCMAIL={{path/to/mailbox}} from\fR
.RS
.IP \(bu 2
Print the mail from the specified address:
.RE
.PP
\fB\fCfrom \-\-sender={{me@example.com}}\fR
