.TH fswebcam
.PP
.RS
Small and simple webcam for *nix.
More information: \[la]https://www.sanslogic.co.uk/fswebcam\[ra]\&.
.RE
.RS
.IP \(bu 2
Take a picture:
.RE
.PP
\fB\fCfswebcam {{filename}}\fR
.RS
.IP \(bu 2
Take a picture with custom resolution:
.RE
.PP
\fB\fCfswebcam \-r {{width}}x{{height}} {{filename}}\fR
.RS
.IP \(bu 2
Take a picture from selected device(Default is \fB\fC/dev/video0\fR):
.RE
.PP
\fB\fCfswebcam \-d {{device}} {{filename}}\fR
.RS
.IP \(bu 2
Take a picture with timestamp(timestamp string is formatted by strftime):
.RE
.PP
\fB\fCfswebcam \-\-timestamp {{timestamp}} {{filename}}\fR
