.TH fusermount
.PP
.RS
Mount and unmount FUSE filesystems.
More information: \[la]https://manned.org/fusermount\[ra]\&.
.RE
.RS
.IP \(bu 2
Unmount a FUSE filesystem:
.RE
.PP
\fB\fCfusermount \-u {{path/to/mount_point}}\fR
.RS
.IP \(bu 2
Unmount a FUSE filesystem as soon as it becomes unused:
.RE
.PP
\fB\fCfusermount \-z {{path/to/mount_point}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCfusermount \-\-version\fR
