.TH gacutil
.PP
.RS
Global Assembly Cache (CAG) management utility.
More information: \[la]https://manned.org/gacutil\[ra]\&.
.RE
.RS
.IP \(bu 2
Install the specified assembly into GAC:
.RE
.PP
\fB\fCgacutil \-i {{path/to/assembly.dll}}\fR
.RS
.IP \(bu 2
Uninstall the specified assembly from GAC:
.RE
.PP
\fB\fCgacutil \-i {{assembly_display_name}}\fR
.RS
.IP \(bu 2
Print the content of GAC:
.RE
.PP
\fB\fCgacutil \-l\fR
