.TH gatsby
.PP
.RS
Static site generator for React.
More information: \[la]https://gatsbyjs.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new site:
.RE
.PP
\fB\fCgatsby new {{site_name}}\fR
.RS
.IP \(bu 2
Create a new site with a Gatsby 'starter':
.RE
.PP
\fB\fCgatsby new {{site_name}} {{url_of_starter_github_repo}}\fR
.RS
.IP \(bu 2
Start a live\-reloading local development server:
.RE
.PP
\fB\fCgatsby develop\fR
.RS
.IP \(bu 2
Perform a production build and generate static HTML:
.RE
.PP
\fB\fCgatsby build\fR
.RS
.IP \(bu 2
Start a local server which serves the production build:
.RE
.PP
\fB\fCgatsby serve\fR
