.TH gcal
.PP
.RS
Displays calendar.
More information: \[la]https://www.gnu.org/software/gcal\[ra]\&.
.RE
.RS
.IP \(bu 2
Display calendar for the current month:
.RE
.PP
\fB\fCgcal\fR
.RS
.IP \(bu 2
Display calendar for the month of February of the year 2010:
.RE
.PP
\fB\fCgcal {{2}} {{2010}}\fR
.RS
.IP \(bu 2
Provide calendar sheet with week numbers:
.RE
.PP
\fB\fCgcal \-\-with\-week\-number\fR
.RS
.IP \(bu 2
Change starting day of week to 1st day of the week (Monday):
.RE
.PP
\fB\fCgcal \-\-starting\-day={{1}}\fR
.RS
.IP \(bu 2
Display the previous, current and next month surrounding today:
.RE
.PP
\fB\fCgcal .\fR
