.TH gdaldem
.PP
.RS
Tool to analyze and visualize digital elevation models (DEM).
More information: \[la]https://gdal.org/programs/gdaldem\[ra]\&.
.RE
.RS
.IP \(bu 2
Compute the hillshade of a DEM:
.RE
.PP
\fB\fCgdaldem hillshade {{path/to/input.tif}} {{path/to/output.tif}}\fR
.RS
.IP \(bu 2
Compute the slope of a DEM:
.RE
.PP
\fB\fCgdaldem slope {{path/to/input.tif}} {{path/to/output.tif}}\fR
.RS
.IP \(bu 2
Compute the aspect of a DEM:
.RE
.PP
\fB\fCgdaldem aspect {{path/to/input.tif}} {{path/to/output.tif}}\fR
