.TH Get\-NodeVersions
.PP
.RS
List installed and available Node.js versions for \fB\fCps\-nvm\fR\&.
Part of \fB\fCps\-nvm\fR and can only be run under PowerShell.
More information: \[la]https://github.com/aaronpowell/ps-nvm\[ra]\&.
.RE
.RS
.IP \(bu 2
List all installed Node.js versions:
.RE
.PP
\fB\fCGet\-NodeVersions\fR
.RS
.IP \(bu 2
List all available Node.js versions:
.RE
.PP
\fB\fCGet\-NodeVersions \-Remote\fR
.RS
.IP \(bu 2
List all available Node.js 20.x versions:
.RE
.PP
\fB\fCGet\-NodeVersions \-Remote \-Filter ">=20.0.0 <21.0.0"\fR
