.TH geth
.PP
.RS
The go\-ethereum command\-line interface.
More information: \[la]https://geth.ethereum.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Connect to the main Ethereum network and automatically download the full node:
.RE
.PP
\fB\fCgeth\fR
.RS
.IP \(bu 2
Connect to the Ropsten test network:
.RE
.PP
\fB\fCgeth \-\-testnet\fR
.RS
.IP \(bu 2
Create a new account:
.RE
.PP
\fB\fCgeth account new\fR
.RS
.IP \(bu 2
Enable mining:
.RE
.PP
\fB\fCgeth \-\-mine\fR
