.TH gh formatting
.PP
.RS
Formatting options for JSON data exported from gh GitHub CLI command.
More information: \[la]https://cli.github.com/manual/gh_help_formatting\[ra]\&.
.RE
.RS
.IP \(bu 2
Display help about formatting JSON output from \fB\fCgh\fR using \fB\fCjq\fR:
.RE
.PP
\fB\fCgh formatting\fR
