.TH gh help
.PP
.RS
Display help about the GitHub CLI command.
More information: \[la]https://cli.github.com/manual/gh_help\[ra]\&.
.RE
.RS
.IP \(bu 2
Display general help:
.RE
.PP
\fB\fCgh help\fR
.RS
.IP \(bu 2
Display help for the \fB\fCgh help\fR subcommand:
.RE
.PP
\fB\fCgh help \-\-help\fR
.RS
.IP \(bu 2
Display help about environment variables that can be used with \fB\fCgh\fR:
.RE
.PP
\fB\fCgh help environment\fR
.RS
.IP \(bu 2
Display a markdown reference of all \fB\fCgh\fR commands:
.RE
.PP
\fB\fCgh help reference\fR
.RS
.IP \(bu 2
Display help about formatting JSON output from \fB\fCgh\fR using \fB\fCjq\fR:
.RE
.PP
\fB\fCgh help formatting\fR
.RS
.IP \(bu 2
Display help about using \fB\fCgh\fR with MinTTY:
.RE
.PP
\fB\fCgh help mintty\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCgh help {{subcommand}}\fR
.RS
.IP \(bu 2
Display help for a subcommand action:
.RE
.PP
\fB\fCgh help {{pr}} {{create}}\fR
