.TH gh release
.PP
.RS
Manage GitHub releases.
More information: \[la]https://cli.github.com/manual/gh_release\[ra]\&.
.RE
.RS
.IP \(bu 2
List releases in a GitHub repository, limited to 30 items:
.RE
.PP
\fB\fCgh release list\fR
.RS
.IP \(bu 2
Display information about a specific release:
.RE
.PP
\fB\fCgh release view {{tag}}\fR
.RS
.IP \(bu 2
Create a new release:
.RE
.PP
\fB\fCgh release create {{tag}}\fR
.RS
.IP \(bu 2
Delete a specific release:
.RE
.PP
\fB\fCgh release delete {{tag}}\fR
.RS
.IP \(bu 2
Download assets from a specific release:
.RE
.PP
\fB\fCgh release download {{tag}}\fR
.RS
.IP \(bu 2
Upload assets to a specific release:
.RE
.PP
\fB\fCgh release upload {{tag}} {{path/to/file1 path/to/file2 ...}}\fR
