.TH gifdiff
.PP
.RS
Compare two GIFs for identical visual appearance.
See also: \fB\fCgifsicle\fR\&.
More information: \[la]https://www.lcdf.org/gifsicle\[ra]\&.
.RE
.RS
.IP \(bu 2
Check how GIFs differ:
.RE
.PP
\fB\fCgifdiff {{path/to/first.gif}} {{path/to/second.gif}}\fR
.RS
.IP \(bu 2
Check if GIFs differ:
.RE
.PP
\fB\fCgifdiff \-\-brief {{path/to/first.gif}} {{path/to/second.gif}}\fR
