.TH giftopnm
.PP
.RS
Convert a GIF file into a PNM image.
More information: \[la]https://netpbm.sourceforge.net/doc/giftopnm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert a GIF image to a Netpbm image pixel\-for\-pixel:
.RE
.PP
\fB\fCgiftopnm {{path/to/input.gif}} > {{path/to/output.pnm}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCgiftopnm \-version\fR
