.TH git clear\-soft
.PP
.RS
Clear a Git working directory as if it was freshly cloned with the current branch excluding files in \fB\fC\&.gitignore\fR\&.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-clear-soft\[ra]\&.
.RE
.RS
.IP \(bu 2
Reset all tracked files and delete all untracked files:
.RE
.PP
\fB\fCgit clear\-soft\fR
