.TH git rebase\-patch
.PP
.RS
Find the commit the patch applies to and do a rebase.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-rebase-patch\[ra]\&.
.RE
.RS
.IP \(bu 2
Find the commit the patch applies to and do a rebase:
.RE
.PP
\fB\fCgit rebase\-patch {{patch_file}}\fR
