.TH git unlock
.PP
.RS
Unlock a file in a Git repository so it can be modified by a commit.
Part of \fB\fCgit\-extras\fR\&. See also \fB\fCgit lock\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-unlock\[ra]\&.
.RE
.RS
.IP \(bu 2
Enable the ability to commit changes of a previously\-locked local file:
.RE
.PP
\fB\fCgit unlock {{path/to/file}}\fR
