.TH git revert
.PP
.RS
Create new commits which reverse the effect of earlier ones.
More information: \[la]https://git-scm.com/docs/git-revert\[ra]\&.
.RE
.RS
.IP \(bu 2
Revert the most recent commit:
.RE
.PP
\fB\fCgit revert {{HEAD}}\fR
.RS
.IP \(bu 2
Revert the 5th last commit:
.RE
.PP
\fB\fCgit revert HEAD~{{4}}\fR
.RS
.IP \(bu 2
Revert a specific commit:
.RE
.PP
\fB\fCgit revert {{0c01a9}}\fR
.RS
.IP \(bu 2
Revert multiple commits:
.RE
.PP
\fB\fCgit revert {{branch_name~5..branch_name~2}}\fR
.RS
.IP \(bu 2
Don't create new commits, just change the working tree:
.RE
.PP
\fB\fCgit revert \-n {{0c01a9..9a1743}}\fR
