.TH git blame\-someone\-else
.PP
.RS
Blame someone else for your bad code.
More information: \[la]https://github.com/jayphelps/git-blame-someone-else\[ra]\&.
.RE
.RS
.IP \(bu 2
Change the committer and author of a commit:
.RE
.PP
\fB\fCgit blame\-someone\-else "{{author <someone@example.com>}}" {{commit}}\fR
