.TH git cola
.PP
.RS
A powerful Git GUI with a slick and intuitive user interface.
More information: \[la]https://git-cola.readthedocs.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Start git cola:
.RE
.PP
\fB\fCgit cola\fR
.RS
.IP \(bu 2
Start git cola in amend mode:
.RE
.PP
\fB\fCgit cola \-\-amend\fR
.RS
.IP \(bu 2
Prompt for a Git repository. Defaults to the current directory:
.RE
.PP
\fB\fCgit cola \-\-prompt\fR
.RS
.IP \(bu 2
Open the Git repository at mentioned path:
.RE
.PP
\fB\fCgit cola \-\-repo {{path/to/git\-repository}}\fR
.RS
.IP \(bu 2
Apply the path filter to the status widget:
.RE
.PP
\fB\fCgit cola \-\-status\-filter {{filter}}\fR
