.TH git sizer
.PP
.RS
Computes various Git repository size metrics and alerts you to any that might cause problems or inconvenience.
More information: \[la]https://github.com/github/git-sizer\[ra]\&.
.RE
.RS
.IP \(bu 2
Report only statistics that have a level of concern greater than 0:
.RE
.PP
\fB\fCgit sizer\fR
.RS
.IP \(bu 2
Report all statistics:
.RE
.PP
\fB\fCgit sizer \-v\fR
.RS
.IP \(bu 2
See additional options:
.RE
.PP
\fB\fCgit sizer \-h\fR
