.TH git reset\-file
.PP
.RS
Revert a file to HEAD or a specific commit.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-reset-file\[ra]\&.
.RE
.RS
.IP \(bu 2
Reset a file to HEAD:
.RE
.PP
\fB\fCgit reset\-file {{path/to/file}}\fR
.RS
.IP \(bu 2
Reset a file to a specific commit:
.RE
.PP
\fB\fCgit reset\-file {{path/to/file}} {{commit_hash}}\fR
