.TH git info
.PP
.RS
Display Git repository information.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-info\[ra]\&.
.RE
.RS
.IP \(bu 2
Display remote locations, remote and local branches, most recent commit data and \fB\fC\&.git/config\fR settings:
.RE
.PP
\fB\fCgit info\fR
.RS
.IP \(bu 2
Display remote locations, remote and local branches and most recent commit data:
.RE
.PP
\fB\fCgit info \-\-no\-config\fR
