.TH git var
.PP
.RS
Prints a Git logical variable's value.
See \fB\fCgit config\fR, which is preferred over \fB\fCgit var\fR\&.
More information: \[la]https://git-scm.com/docs/git-var\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the value of a Git logical variable:
.RE
.PP
\fB\fCgit var {{GIT_AUTHOR_IDENT|GIT_COMMITTER_IDENT|GIT_EDITOR|GIT_PAGER}}\fR
.RS
.IP \(bu 2
[l]ist all Git logical variables:
.RE
.PP
\fB\fCgit var \-l\fR
