.TH git merge\-repo
.PP
.RS
Merge two repository histories.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-merge-repo\[ra]\&.
.RE
.RS
.IP \(bu 2
Merge a repository's branch into the current repository's directory:
.RE
.PP
\fB\fCgit merge\-repo {{path/to/repo}} {{branch_name}} {{path/to/directory}}\fR
.RS
.IP \(bu 2
Merge a remote repository's branch into the current repository's directory, not preserving history:
.RE
.PP
\fB\fCgit merge\-repo {{path/to/remote_repo}} {{branch_name}} .\fR
