.TH git add
.PP
.RS
Adds changed files to the index.
More information: \[la]https://git-scm.com/docs/git-add\[ra]\&.
.RE
.RS
.IP \(bu 2
Add a file to the index:
.RE
.PP
\fB\fCgit add {{path/to/file}}\fR
.RS
.IP \(bu 2
Add all files (tracked and untracked):
.RE
.PP
\fB\fCgit add \-A\fR
.RS
.IP \(bu 2
Only add already tracked files:
.RE
.PP
\fB\fCgit add \-u\fR
.RS
.IP \(bu 2
Also add ignored files:
.RE
.PP
\fB\fCgit add \-f\fR
.RS
.IP \(bu 2
Interactively stage parts of files:
.RE
.PP
\fB\fCgit add \-p\fR
.RS
.IP \(bu 2
Interactively stage parts of a given file:
.RE
.PP
\fB\fCgit add \-p {{path/to/file}}\fR
.RS
.IP \(bu 2
Interactively stage a file:
.RE
.PP
\fB\fCgit add \-i\fR
