.TH git pr
.PP
.RS
Check out GitHub pull requests locally.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-pr\[ra]\&.
.RE
.RS
.IP \(bu 2
Check out a specific pull request:
.RE
.PP
\fB\fCgit pr {{pr_number}}\fR
.RS
.IP \(bu 2
Check out a pull request from a specific remote:
.RE
.PP
\fB\fCgit pr {{pr_number}} {{remote}}\fR
.RS
.IP \(bu 2
Check out a pull request from its URL:
.RE
.PP
\fB\fCgit pr {{url}}\fR
.RS
.IP \(bu 2
Clean up old pull request branches:
.RE
.PP
\fB\fCgit pr clean\fR
