.TH git touch
.PP
.RS
Create new files and add them to the index.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-touch\[ra]\&.
.RE
.RS
.IP \(bu 2
Create new files and add them to the index:
.RE
.PP
\fB\fCgit touch {{path/to/file1 path/to/file2 ...}}\fR
