.TH git missing
.PP
.RS
Show commits which aren't shared between two branches.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-missing\[ra]\&.
.RE
.RS
.IP \(bu 2
Show commits which aren't shared between the currently checked\-out branch and another branch:
.RE
.PP
\fB\fCgit missing {{branch}}\fR
.RS
.IP \(bu 2
Show commits which aren't shared between two branches:
.RE
.PP
\fB\fCgit missing {{branch_1}} {{branch_2}}\fR
