.TH git secret
.PP
.RS
Bash tool which stores private data inside a Git repository.
More information: \[la]https://github.com/sobolevn/git-secret\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize \fB\fCgit\-secret\fR in a local repository:
.RE
.PP
\fB\fCgit secret init\fR
.RS
.IP \(bu 2
Grant access to the current Git user's email:
.RE
.PP
\fB\fCgit secret tell \-m\fR
.RS
.IP \(bu 2
Grant access by email:
.RE
.PP
\fB\fCgit secret tell {{email}}\fR
.RS
.IP \(bu 2
Revoke access by email:
.RE
.PP
\fB\fCgit secret killperson {{email}}\fR
.RS
.IP \(bu 2
List emails with access to secrets:
.RE
.PP
\fB\fCgit secret whoknows\fR
.RS
.IP \(bu 2
Register a secret file:
.RE
.PP
\fB\fCgit secret add {{path/to/file}}\fR
.RS
.IP \(bu 2
Encrypt secrets:
.RE
.PP
\fB\fCgit secret hide\fR
.RS
.IP \(bu 2
Decrypt secret files:
.RE
.PP
\fB\fCgit secret reveal\fR
