.TH git cvsexportcommit
.PP
.RS
Export a single \fB\fCGit\fR commit to a CVS checkout.
More information: \[la]https://git-scm.com/docs/git-cvsexportcommit\[ra]\&.
.RE
.RS
.IP \(bu 2
Merge a specific patch into CVS:
.RE
.PP
\fB\fCgit cvsexportcommit \-v \-c \-w {{path/to/project_cvs_checkout}} {{commit_sha1}}\fR
