.TH git status
.PP
.RS
Show the changes to files in a Git repository.
Lists changed, added and deleted files compared to the currently checked\-out commit.
More information: \[la]https://git-scm.com/docs/git-status\[ra]\&.
.RE
.RS
.IP \(bu 2
Show changed files which are not yet added for commit:
.RE
.PP
\fB\fCgit status\fR
.RS
.IP \(bu 2
Give output in [s]hort format:
.RE
.PP
\fB\fCgit status \-\-short\fR
.RS
.IP \(bu 2
Show the [b]ranch and tracking info:
.RE
.PP
\fB\fCgit status \-\-branch\fR
.RS
.IP \(bu 2
Show output in [s]hort format along with [b]ranch info:
.RE
.PP
\fB\fCgit status \-\-short \-\-branch\fR
.RS
.IP \(bu 2
Show the number of entries currently stashed away:
.RE
.PP
\fB\fCgit status \-\-show\-stash\fR
.RS
.IP \(bu 2
Don't show untracked files in the output:
.RE
.PP
\fB\fCgit status \-\-untracked\-files=no\fR
