.TH git utimes
.PP
.RS
Change files modification time to their last commit date. Does not touch files that are in the working tree or index.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-utimes\[ra]\&.
.RE
.RS
.IP \(bu 2
Change all files modification time to their last commit date:
.RE
.PP
\fB\fCgit utimes\fR
.RS
.IP \(bu 2
Change files modification time that are newer than their last commit date, preserving original modification time of files that were committed from the local repository:
.RE
.PP
\fB\fCgit utimes \-\-newer\fR
