.TH git unpack\-file
.PP
.RS
Create a temporary file with a blob's contents.
More information: \[la]https://git-scm.com/docs/git-unpack-file\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a file holding the contents of the blob specified by its ID then print the name of the temporary file:
.RE
.PP
\fB\fCgit unpack\-file {{blob_id}}\fR
