.TH git delete\-merged\-branches
.PP
.RS
Delete branches that are listed in \fB\fCgit branch \-\-merged\fR excluding master.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-delete-merged-branches\[ra]\&.
.RE
.RS
.IP \(bu 2
Delete merged branches:
.RE
.PP
\fB\fCgit delete\-merged\-branches\fR
