.TH git mr
.PP
.RS
Check out GitLab merge requests locally.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-mr\[ra]\&.
.RE
.RS
.IP \(bu 2
Check out a specific merge request:
.RE
.PP
\fB\fCgit mr {{mr_number}}\fR
.RS
.IP \(bu 2
Check out a merge request from a specific remote:
.RE
.PP
\fB\fCgit mr {{mr_number}} {{remote}}\fR
.RS
.IP \(bu 2
Checkout a merge request from its URL:
.RE
.PP
\fB\fCgit mr {{url}}\fR
.RS
.IP \(bu 2
Clean up old merge request branches:
.RE
.PP
\fB\fCgit mr clean\fR
