.TH git rename\-branch
.PP
.RS
Rename a Git branch.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-rename-branch\[ra]\&.
.RE
.RS
.IP \(bu 2
Rename the branch you are currently on:
.RE
.PP
\fB\fCgit rename\-branch {{new_branch_name}}\fR
.RS
.IP \(bu 2
Rename a specific branch:
.RE
.PP
\fB\fCgit rename\-branch {{old_branch_name}} {{new_branch_name}}\fR
