.TH git fork
.PP
.RS
Fork the given GitHub repo. Like \fB\fCgit clone\fR but forks first.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-fork\[ra]\&.
.RE
.RS
.IP \(bu 2
Fork and clone a GitHub repository by its URL:
.RE
.PP
\fB\fCgit fork {{https://github.com/tldr\-pages/tldr}}\fR
.RS
.IP \(bu 2
Fork and clone a GitHub repository by its slug:
.RE
.PP
\fB\fCgit fork {{tldr\-pages/tldr}}\fR
