.TH git contrib
.PP
.RS
Display commits from a specific author.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-contrib\[ra]\&.
.RE
.RS
.IP \(bu 2
Display all commit hashes and their corresponding commit messages from a specific author:
.RE
.PP
\fB\fCgit contrib {{author}}\fR
