.TH git browse
.PP
.RS
View an upstream repository in the default browser.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-browse\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the first upstream in the default browser:
.RE
.PP
\fB\fCgit browse\fR
.RS
.IP \(bu 2
Open a specific upstream in the default browser:
.RE
.PP
\fB\fCgit browse {{upstream}}\fR
