.TH git browse\-ci
.PP
.RS
Open the current \fB\fCgit\fR repository's CI website in the default web browser.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-browse-ci\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the current repository's CI configuration on its upstream website:
.RE
.PP
\fB\fCgit browse\-ci\fR
.RS
.IP \(bu 2
Open the current repository's CI configuration on its upstream website for a specific remote:
.RE
.PP
\fB\fCgit browse\-ci {{remote}}\fR
