.TH git show\-unmerged\-branches
.PP
.RS
Print all branches which are not merged into the current HEAD.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-show-unmerged-branches\[ra]\&.
.RE
.RS
.IP \(bu 2
Print all branches which are not merged into the current HEAD:
.RE
.PP
\fB\fCgit show\-unmerged\-branches\fR
