.TH git credential\-cache
.PP
.RS
Git helper to temporarily store passwords in memory.
More information: \[la]https://git-scm.com/docs/git-credential-cache\[ra]\&.
.RE
.RS
.IP \(bu 2
Store Git credentials for a specific amount of time:
.RE
.PP
\fB\fCgit config credential.helper 'cache \-\-timeout={{time_in_seconds}}'\fR
