.TH git rename\-tag
.PP
.RS
Rename a Git tag.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-rename-tag\[ra]\&.
.RE
.RS
.IP \(bu 2
Rename an existing Git tag locally and remotely:
.RE
.PP
\fB\fCgit rename\-tag {{old_tag_name}} {{new_tag_name}}\fR
