.TH git whatchanged
.PP
.RS
Show what has changed with recent commits or files.
See also \fB\fCgit log\fR\&.
More information: \[la]https://git-scm.com/docs/git-whatchanged\[ra]\&.
.RE
.RS
.IP \(bu 2
Display logs and changes for recent commits:
.RE
.PP
\fB\fCgit whatchanged\fR
.RS
.IP \(bu 2
Display logs and changes for recent commits within the specified time frame:
.RE
.PP
\fB\fCgit whatchanged \-\-since="{{2 hours ago}}"\fR
.RS
.IP \(bu 2
Display logs and changes for recent commits for specific files or directories:
.RE
.PP
\fB\fCgit whatchanged {{path/to/file_or_directory}}\fR
