.TH git credential
.PP
.RS
Retrieve and store user credentials.
More information: \[la]https://git-scm.com/docs/git-credential\[ra]\&.
.RE
.RS
.IP \(bu 2
Display credential information, retrieving the username and password from configuration files:
.RE
.PP
\fB\fCecho "{{url=http://example.com}}" | git credential fill\fR
.RS
.IP \(bu 2
Send credential information to all configured credential helpers to store for later use:
.RE
.PP
\fB\fCecho "{{url=http://example.com}}" | git credential approve\fR
.RS
.IP \(bu 2
Erase the specified credential information from all the configured credential helpers:
.RE
.PP
\fB\fCecho "{{url=http://example.com}}" | git credential reject\fR
