.TH git diff\-files
.PP
.RS
Compare files using their sha1 hashes and modes.
More information: \[la]https://git-scm.com/docs/git-diff-files\[ra]\&.
.RE
.RS
.IP \(bu 2
Compare all changed files:
.RE
.PP
\fB\fCgit diff\-files\fR
.RS
.IP \(bu 2
Compare only specified files:
.RE
.PP
\fB\fCgit diff\-files {{path/to/file}}\fR
.RS
.IP \(bu 2
Show only the names of changed files:
.RE
.PP
\fB\fCgit diff\-files \-\-name\-only\fR
.RS
.IP \(bu 2
Output a summary of extended header information:
.RE
.PP
\fB\fCgit diff\-files \-\-summary\fR
