.TH git delta
.PP
.RS
List files that differ from another branch.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-delta\[ra]\&.
.RE
.RS
.IP \(bu 2
List files from the current checked out branch that differ from the \fB\fCmain\fR branch:
.RE
.PP
\fB\fCgit delta {{main}}\fR
.RS
.IP \(bu 2
List files from a specific branch that differ from another specific branch:
.RE
.PP
\fB\fCgit delta {{branch_1}} {{branch_2}}\fR
