.TH git clear
.PP
.RS
Clear a Git working directory as if it was freshly cloned with the current branch including files in \fB\fC\&.gitignore\fR\&.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-clear\[ra]\&.
.RE
.RS
.IP \(bu 2
Reset all tracked files and delete all untracked files even if they are included in the \fB\fC\&.gitignore\fR:
.RE
.PP
\fB\fCgit clear\fR
