.TH git count
.PP
.RS
Print the total number of commits.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-count\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the total number of commits:
.RE
.PP
\fB\fCgit count\fR
.RS
.IP \(bu 2
Print the number of commits per contributor and the total number of commits:
.RE
.PP
\fB\fCgit count \-\-all\fR
