.TH git repl
.PP
.RS
Git REPL (read\-evaluate\-print\-loop) \- an interactive Git shell.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-repl\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive Git shell:
.RE
.PP
\fB\fCgit repl\fR
.RS
.IP \(bu 2
Run a Git command while in the interactive Git shell:
.RE
.PP
\fB\fC{{git_subcommand}} {{command_arguments}}\fR
.RS
.IP \(bu 2
Run an external (non\-Git) command while in the interactive Git shell:
.RE
.PP
\fB\fC!{{command}} {{command_arguments}}\fR
.RS
.IP \(bu 2
Exit the interactive Git shell (or press Ctrl + D):
.RE
.PP
\fB\fCexit\fR
