.TH git ls\-files
.PP
.RS
Show information about files in the index and the working tree.
More information: \[la]https://git-scm.com/docs/git-ls-files\[ra]\&.
.RE
.RS
.IP \(bu 2
Show deleted files:
.RE
.PP
\fB\fCgit ls\-files \-\-deleted\fR
.RS
.IP \(bu 2
Show modified and deleted files:
.RE
.PP
\fB\fCgit ls\-files \-\-modified\fR
.RS
.IP \(bu 2
Show ignored and untracked files:
.RE
.PP
\fB\fCgit ls\-files \-\-others\fR
.RS
.IP \(bu 2
Show untracked files, not ignored:
.RE
.PP
\fB\fCgit ls\-files \-\-others \-\-exclude\-standard\fR
