.TH git root
.PP
.RS
Print the root directory of the current Git repository.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-root\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the absolute path of the current Git repository:
.RE
.PP
\fB\fCgit root\fR
.RS
.IP \(bu 2
Print the current working directory relative to the root of the current Git repository:
.RE
.PP
\fB\fCgit root \-\-relative\fR
