.TH git delete\-branch
.PP
.RS
Delete local and remote Git branches.
Part of \fB\fCgit\-extras\fR\&. If deleting the checked out branch, only the remote branch will be deleted.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-delete-branch\[ra]\&.
.RE
.RS
.IP \(bu 2
Delete a local and remote Git branch:
.RE
.PP
\fB\fCgit delete\-branch {{branch_name}}\fR
.RS
.IP \(bu 2
Delete multiple local and remote Git branches:
.RE
.PP
\fB\fCgit delete\-branch {{branch_name1 branch_name2 ...}}\fR
