.TH git log
.PP
.RS
Show a history of commits.
More information: \[la]https://git-scm.com/docs/git-log\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the sequence of commits starting from the current one, in reverse chronological order of the Git repository in the current working directory:
.RE
.PP
\fB\fCgit log\fR
.RS
.IP \(bu 2
Show the history of a particular file or directory, including differences:
.RE
.PP
\fB\fCgit log \-p {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Show an overview of which 
.BR file (s) 
changed in each commit:
.RE
.PP
\fB\fCgit log \-\-stat\fR
.RS
.IP \(bu 2
Show a graph of commits in the current branch using only the first line of each commit message:
.RE
.PP
\fB\fCgit log \-\-oneline \-\-graph\fR
.RS
.IP \(bu 2
Show a graph of all commits, tags and branches in the entire repo:
.RE
.PP
\fB\fCgit log \-\-oneline \-\-decorate \-\-all \-\-graph\fR
.RS
.IP \(bu 2
Show only commits whose messages include a given string (case\-insensitively):
.RE
.PP
\fB\fCgit log \-i \-\-grep {{search_string}}\fR
.RS
.IP \(bu 2
Show the last N commits from a certain author:
.RE
.PP
\fB\fCgit log \-n {{number}} \-\-author={{author}}\fR
.RS
.IP \(bu 2
Show commits between two dates (yyyy\-mm\-dd):
.RE
.PP
\fB\fCgit log \-\-before="{{2017\-01\-29}}" \-\-after="{{2017\-01\-17}}"\fR
