.TH git pull\-request
.PP
.RS
Create a pull request for a project on GitHub.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-pull-request\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a pull request for a project on GitHub:
.RE
.PP
\fB\fCgit pull\-request {{target_branch}}\fR
