.TH git merge\-into
.PP
.RS
Merge one branch into another branch.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-merge-into\[ra]\&.
.RE
.RS
.IP \(bu 2
Merge a source branch into a specific destination branch:
.RE
.PP
\fB\fCgit merge\-into {{source_branch}} {{destination_branch}}\fR
.RS
.IP \(bu 2
Merge current branch into a specific destination branch:
.RE
.PP
\fB\fCgit merge\-into {{destination_branch}}\fR
