.TH git delete\-submodule
.PP
.RS
Delete a specific submodule from a \fB\fCgit\fR repository.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-delete-submodule\[ra]\&.
.RE
.RS
.IP \(bu 2
Delete a specific submodule:
.RE
.PP
\fB\fCgit delete\-submodule {{path/to/submodule}}\fR
