.TH git count\-objects
.PP
.RS
Count the number of unpacked objects and their disk consumption.
More information: \[la]https://git-scm.com/docs/git-count-objects\[ra]\&.
.RE
.RS
.IP \(bu 2
Count all objects and display the total disk usage:
.RE
.PP
\fB\fCgit count\-objects\fR
.RS
.IP \(bu 2
Display a count of all objects and their total disk usage, displaying sizes in human\-readable units:
.RE
.PP
\fB\fCgit count\-objects \-\-human\-readable\fR
.RS
.IP \(bu 2
Display more verbose information:
.RE
.PP
\fB\fCgit count\-objects \-\-verbose\fR
.RS
.IP \(bu 2
Display more verbose information, displaying sizes in human\-readable units:
.RE
.PP
\fB\fCgit count\-objects \-\-human\-readable \-\-verbose\fR
