.TH git rev\-parse
.PP
.RS
Display metadata related to specific revisions.
More information: \[la]https://git-scm.com/docs/git-rev-parse\[ra]\&.
.RE
.RS
.IP \(bu 2
Get the commit hash of a branch:
.RE
.PP
\fB\fCgit rev\-parse {{branch_name}}\fR
.RS
.IP \(bu 2
Get the current branch name:
.RE
.PP
\fB\fCgit rev\-parse \-\-abbrev\-ref {{HEAD}}\fR
.RS
.IP \(bu 2
Get the absolute path to the root directory:
.RE
.PP
\fB\fCgit rev\-parse \-\-show\-toplevel\fR
