.TH git show\-tree
.PP
.RS
Show a decorated tree graph with all branches of a Git repository, showing annotations.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-show-tree\[ra]\&.
.RE
.RS
.IP \(bu 2
Show a decorated tree graph for all branches annotated with tags and branch names:
.RE
.PP
\fB\fCgit show\-tree\fR
