.TH git push
.PP
.RS
Push commits to a remote repository.
More information: \[la]https://git-scm.com/docs/git-push\[ra]\&.
.RE
.RS
.IP \(bu 2
Send local changes in the current branch to its default remote counterpart:
.RE
.PP
\fB\fCgit push\fR
.RS
.IP \(bu 2
Send changes from a specific local branch to its remote counterpart:
.RE
.PP
\fB\fCgit push {{remote_name}} {{local_branch}}\fR
.RS
.IP \(bu 2
Send changes from a specific local branch to its remote counterpart, and set the remote one as the default push/pull target of the local one:
.RE
.PP
\fB\fCgit push \-u {{remote_name}} {{local_branch}}\fR
.RS
.IP \(bu 2
Send changes from a specific local branch to a specific remote branch:
.RE
.PP
\fB\fCgit push {{remote_name}} {{local_branch}}:{{remote_branch}}\fR
.RS
.IP \(bu 2
Send changes on all local branches to their counterparts in a given remote repository:
.RE
.PP
\fB\fCgit push \-\-all {{remote_name}}\fR
.RS
.IP \(bu 2
Delete a branch in a remote repository:
.RE
.PP
\fB\fCgit push {{remote_name}} \-\-delete {{remote_branch}}\fR
.RS
.IP \(bu 2
Remove remote branches that don't have a local counterpart:
.RE
.PP
\fB\fCgit push \-\-prune {{remote_name}}\fR
.RS
.IP \(bu 2
Publish tags that aren't yet in the remote repository:
.RE
.PP
\fB\fCgit push \-\-tags\fR
