.TH git rscp
.PP
.RS
Reverse \fB\fCgit scp\fR \- copy files from the working directory of a remote repository to the current working tree.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-scp\[ra]\&.
.RE
.RS
.IP \(bu 2
Copy specific files from a remote:
.RE
.PP
\fB\fCgit rscp {{remote_name}} {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Copy a specific directory from a remote:
.RE
.PP
\fB\fCgit rscp {{remote_name}} {{path/to/directory}}\fR
