.TH git release
.PP
.RS
Create a Git tag for a release.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-release\[ra]\&.
.RE
.RS
.IP \(bu 2
Create and push a release:
.RE
.PP
\fB\fCgit release {{tag_name}}\fR
.RS
.IP \(bu 2
Create and push a signed release:
.RE
.PP
\fB\fCgit release {{tag_name}} \-s\fR
.RS
.IP \(bu 2
Create and push a release with a message:
.RE
.PP
\fB\fCgit release {{{tag_name}}} \-m "{{message}}"\fR
