.TH git undo
.PP
.RS
Undo recent commits.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-undo\[ra]\&.
.RE
.RS
.IP \(bu 2
Remove the most recent commit:
.RE
.PP
\fB\fCgit undo\fR
.RS
.IP \(bu 2
Remove a specific number of the most recent commits:
.RE
.PP
\fB\fCgit undo {{3}}\fR
