.TH git archive\-file
.PP
.RS
Export all the files of the current Git branch into a zip archive.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-archive-file\[ra]\&.
.RE
.RS
.IP \(bu 2
Pack the currently checked out commit into a zip archive:
.RE
.PP
\fB\fCgit archive\-file\fR
