.TH git delete\-squashed\-branches
.PP
.RS
Delete branches that have been "squashed\-merged" into a specified branch and checkout. If no branch is specified, default to the currently checked out branch.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-delete-squashed-branches\[ra]\&.
.RE
.RS
.IP \(bu 2
Delete all branches that were "squash\-merged" into the current checked out branch:
.RE
.PP
\fB\fCgit delete\-squashed\-branches\fR
.RS
.IP \(bu 2
Delete all branches that were "squash\-merged" into a specific branch:
.RE
.PP
\fB\fCgit delete\-squashed\-branches {{branch_name}}\fR
