.TH git local\-commits
.PP
.RS
Show local commits that haven't been pushed to origin. Any additional arguments will be passed directly to \fB\fCgit log\fR\&.
Part of `git\-extras.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-local-commits\[ra]\&.
.RE
.RS
.IP \(bu 2
Show commits that haven't been pushed:
.RE
.PP
\fB\fCgit local\-commits\fR
