.TH git lock
.PP
.RS
Lock a file in a Git repository from being modified by a commit.
Part of \fB\fCgit\-extras\fR\&. See also \fB\fCgit\-unlock\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-lock\[ra]\&.
.RE
.RS
.IP \(bu 2
Disable the ability to commit changes of a local file:
.RE
.PP
\fB\fCgit lock {{path/to/file}}\fR
