.TH git rename\-remote
.PP
.RS
Change remote for pulling and pushing.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-rename-remote\[ra]\&.
.RE
.RS
.IP \(bu 2
Change the upstream remote to origin:
.RE
.PP
\fB\fCgit rename\-remote {{upstream}} {{origin}}\fR
