.TH git show\-merged\-branches
.PP
.RS
Print all branches which are merged into the current head.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-show-merged-branches\[ra]\&.
.RE
.RS
.IP \(bu 2
Print all branches which are merged into the current head:
.RE
.PP
\fB\fCgit show\-merged\-branches\fR
