.TH git setup
.PP
.RS
Create a Git repository in a specific directory and commit all files.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-setup\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a Git repository in the current directory and commit all files:
.RE
.PP
\fB\fCgit setup\fR
.RS
.IP \(bu 2
Create a Git repository in a specific directory and commit all files:
.RE
.PP
\fB\fCgit setup {{path/to/directory}}\fR
