.TH git show\-ref
.PP
.RS
Git command for listing references.
More information: \[la]https://git-scm.com/docs/git-show-ref\[ra]\&.
.RE
.RS
.IP \(bu 2
Show all refs in the repository:
.RE
.PP
\fB\fCgit show\-ref\fR
.RS
.IP \(bu 2
Show only heads references:
.RE
.PP
\fB\fCgit show\-ref \-\-heads\fR
.RS
.IP \(bu 2
Show only tags references:
.RE
.PP
\fB\fCgit show\-ref \-\-tags\fR
.RS
.IP \(bu 2
Verify that a given reference exists:
.RE
.PP
\fB\fCgit show\-ref \-\-verify {{path/to/ref}}\fR
