.TH git help
.PP
.RS
Display help information about Git.
More information: \[la]https://git-scm.com/docs/git-help\[ra]\&.
.RE
.RS
.IP \(bu 2
Display help about a specific Git subcommand:
.RE
.PP
\fB\fCgit help {{subcommand}}\fR
.RS
.IP \(bu 2
Display help about a specific Git subcommand in a web browser:
.RE
.PP
\fB\fCgit help \-\-web {{subcommand}}\fR
.RS
.IP \(bu 2
Display a list of all available Git subcommands:
.RE
.PP
\fB\fCgit help \-\-all\fR
.RS
.IP \(bu 2
List the available guides:
.RE
.PP
\fB\fCgit help \-\-guide\fR
.RS
.IP \(bu 2
List all possible configuration variables:
.RE
.PP
\fB\fCgit help \-\-config\fR
