.TH git paste
.PP
.RS
Send commits to a pastebin site using \fB\fCpastebinit\fR\&.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-paste\[ra]\&.
.RE
.RS
.IP \(bu 2
Send the patches between the current branch and its upstream to a pastebin using \fB\fCpastebinit\fR:
.RE
.PP
\fB\fCgit paste\fR
.RS
.IP \(bu 2
Pass options to \fB\fCgit format\-patch\fR in order to select a different set of commits (\fB\fC@^\fR selects the parent of HEAD, and so the currently checked out commit is sent):
.RE
.PP
\fB\fCgit paste {{@^}}\fR
