.TH git cp
.PP
.RS
Copy an existing file to a new location, preserving history.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-cp\[ra]\&.
.RE
.RS
.IP \(bu 2
Copy an existing file in a Git repo, staying in the same directory:
.RE
.PP
\fB\fCgit cp {{file}} {{new_file}}\fR
.RS
.IP \(bu 2
Copy an existing file in a Git repo and place it elsewhere:
.RE
.PP
\fB\fCgit cp {{path/to/file}} {{path/to/new_file}}\fR
