.TH git check\-mailmap
.PP
.RS
Show canonical names and email addresses of contacts.
More information: \[la]https://git-scm.com/docs/git-check-mailmap\[ra]\&.
.RE
.RS
.IP \(bu 2
Look up the canonical name associated with an email address:
.RE
.PP
\fB\fCgit check\-mailmap "<{{email@example.com}}>"\fR
