.TH git update\-index
.PP
.RS
Git command for manipulating the index.
More information: \[la]https://git-scm.com/docs/git-update-index\[ra]\&.
.RE
.RS
.IP \(bu 2
Pretend that a modified file is unchanged (\fB\fCgit status\fR will not show this as changed):
.RE
.PP
\fB\fCgit update\-index \-\-skip\-worktree {{path/to/modified_file}}\fR
