.TH git extras
.PP
.RS
Git extension pack.
More information: \[la]https://github.com/tj/git-extras\[ra]\&.
.RE
.RS
.IP \(bu 2
Install or upgrade \fB\fCgit\-extras\fR commands:
.RE
.PP
\fB\fCgit extras update\fR
.RS
.IP \(bu 2
Display help and subcommands:
.RE
.PP
\fB\fCgit extras \-\-help\fR
.RS
.IP \(bu 2
Print the version of installed \fB\fCgit\-extras\fR:
.RE
.PP
\fB\fCgit extras \-\-version\fR
