.TH git repack
.PP
.RS
Pack unpacked objects in a Git repository.
More information: \[la]https://git-scm.com/docs/git-repack\[ra]\&.
.RE
.RS
.IP \(bu 2
Pack unpacked objects in the current directory:
.RE
.PP
\fB\fCgit repack\fR
.RS
.IP \(bu 2
Also remove redundant objects after packing:
.RE
.PP
\fB\fCgit repack \-d\fR
