.TH git commit\-tree
.PP
.RS
Low level utility to create commit objects.
See also: \fB\fCgit commit\fR\&.
More information: \[la]https://git-scm.com/docs/git-commit-tree\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a commit object with the specified message:
.RE
.PP
\fB\fCgit commit\-tree {{tree}} \-m "{{message}}"\fR
.RS
.IP \(bu 2
Create a commit object reading the message from a file (use \fB\fC\-\fR for \fB\fCstdin\fR):
.RE
.PP
\fB\fCgit commit\-tree {{tree}} \-F {{path/to/file}}\fR
.RS
.IP \(bu 2
Create a GPG\-signed commit object:
.RE
.PP
\fB\fCgit commit\-tree {{tree}} \-m "{{message}}" \-\-gpg\-sign\fR
.RS
.IP \(bu 2
Create a commit object with the specified parent commit object:
.RE
.PP
\fB\fCgit commit\-tree {{tree}} \-m "{{message}}" \-p {{parent_commit_sha}}\fR
