.TH git obliterate
.PP
.RS
Delete specific files and erase their history from a Git repository.
Part of \fB\fCgit\-extras\fR\&.
More information: \[la]https://github.com/tj/git-extras/blob/master/Commands.md#git-obliterate\[ra]\&.
.RE
.RS
.IP \(bu 2
Erase the existence of specific files:
.RE
.PP
\fB\fCgit obliterate {{file_1 file_2 ...}}\fR
.RS
.IP \(bu 2
Erase the existence of specific files between 2 commits:
.RE
.PP
\fB\fCgit obliterate {{file_1 file_2 ...}} \-\- {{commit_hash_1}}..{{commit_hash_2}}\fR
