.TH gitmoji
.PP
.RS
An interactive command\-line tool for using emojis on commits.
More information: \[la]https://github.com/carloscuesta/gitmoji-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the commit wizard:
.RE
.PP
\fB\fCgitmoji \-\-commit\fR
.RS
.IP \(bu 2
Initialize the git hook (so \fB\fCgitmoji\fR will be run every time \fB\fCgit commit\fR is run):
.RE
.PP
\fB\fCgitmoji \-\-init\fR
.RS
.IP \(bu 2
Remove the git hook:
.RE
.PP
\fB\fCgitmoji \-\-remove\fR
.RS
.IP \(bu 2
List all available emojis and their descriptions:
.RE
.PP
\fB\fCgitmoji \-\-list\fR
.RS
.IP \(bu 2
Search emoji list for a list of keywords:
.RE
.PP
\fB\fCgitmoji \-\-search {{keyword1}} {{keyword2}}\fR
.RS
.IP \(bu 2
Update cached list of emojis from main repository:
.RE
.PP
\fB\fCgitmoji \-\-update\fR
.RS
.IP \(bu 2
Configure global preferences:
.RE
.PP
\fB\fCgitmoji \-\-config\fR
