.TH gitui
.PP
.RS
Terminal UI for Git.
More information: \[la]https://github.com/extrawurst/gitui\[ra]\&.
.RE
.RS
.IP \(bu 2
Set the color theme (defaults to \fB\fCtheme.ron\fR):
.RE
.PP
\fB\fCgitui \-\-theme {{theme}}\fR
.RS
.IP \(bu 2
Store logging output into a cache directory:
.RE
.PP
\fB\fCgitui \-\-logging\fR
.RS
.IP \(bu 2
Use notify\-based file system watcher instead of tick\-based update:
.RE
.PP
\fB\fCgitui \-\-watcher\fR
.RS
.IP \(bu 2
Generate a bug report:
.RE
.PP
\fB\fCgitui \-\-bugreport\fR
.RS
.IP \(bu 2
Set the Git directory:
.RE
.PP
\fB\fCgitui \-\-directory {{path/to/directory}}\fR
.RS
.IP \(bu 2
Set the working directory:
.RE
.PP
\fB\fCgitui \-\-workdir {{path/to/directory}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCgitui \-\-help\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCgitui \-\-version\fR
