.TH glab auth
.PP
.RS
Authenticate with a GitLab host.
More information: \[la]https://glab.readthedocs.io/en/latest/auth\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in with interactive prompt:
.RE
.PP
\fB\fCglab auth login\fR
.RS
.IP \(bu 2
Log in with a token:
.RE
.PP
\fB\fCglab auth login \-\-token {{token}}\fR
.RS
.IP \(bu 2
Check authentication status:
.RE
.PP
\fB\fCglab auth status\fR
.RS
.IP \(bu 2
Log in to a specific GitLab instance:
.RE
.PP
\fB\fCglab auth login \-\-hostname {{gitlab.example.com}}\fR
