.TH glab
.PP
.RS
Work seamlessly with GitLab.
Some subcommands such as \fB\fCglab config\fR have their own usage documentation.
More information: \[la]https://github.com/profclems/glab\[ra]\&.
.RE
.RS
.IP \(bu 2
Clone a GitLab repository locally:
.RE
.PP
\fB\fCglab repo clone {{owner}}/{{repository}}\fR
.RS
.IP \(bu 2
Create a new issue:
.RE
.PP
\fB\fCglab issue create\fR
.RS
.IP \(bu 2
View and filter the open issues of the current repository:
.RE
.PP
\fB\fCglab issue list\fR
.RS
.IP \(bu 2
View an issue in the default browser:
.RE
.PP
\fB\fCglab issue view \-\-web {{issue_number}}\fR
.RS
.IP \(bu 2
Create a merge request:
.RE
.PP
\fB\fCglab mr create\fR
.RS
.IP \(bu 2
View a pull request in the default web browser:
.RE
.PP
\fB\fCglab mr view \-\-web {{pr_number}}\fR
.RS
.IP \(bu 2
Check out a specific pull request locally:
.RE
.PP
\fB\fCglab mr checkout {{pr_number}}\fR
