.TH glab mr merge
.PP
.RS
Merge GitLab merge requests.
More information: \[la]https://glab.readthedocs.io/en/latest/mr/merge.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Merge the merge request associated with the current branch interactively:
.RE
.PP
\fB\fCglab mr merge\fR
.RS
.IP \(bu 2
Merge the specified merge request, interactively:
.RE
.PP
\fB\fCglab mr merge {{mr_number}}\fR
.RS
.IP \(bu 2
Merge the merge request, removing the branch on both the local and the remote:
.RE
.PP
\fB\fCglab mr merge \-\-remove\-source\-branch\fR
.RS
.IP \(bu 2
Squash the current merge request into one commit with the message body and merge:
.RE
.PP
\fB\fCglab mr merge \-\-squash \-\-message="{{commit_message_body}}"\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCglab mr merge \-\-help\fR
