.TH glances
.PP
.RS
A cross\-platform system monitoring tool.
More information: \[la]https://nicolargo.github.io/glances/\[ra]\&.
.RE
.RS
.IP \(bu 2
Run in terminal:
.RE
.PP
\fB\fCglances\fR
.RS
.IP \(bu 2
Run in web server mode to show results in browser:
.RE
.PP
\fB\fCglances \-w\fR
.RS
.IP \(bu 2
Run in server mode to allow connections from other Glances clients:
.RE
.PP
\fB\fCglances \-s\fR
.RS
.IP \(bu 2
Connect to a Glances server:
.RE
.PP
\fB\fCglances \-c {{hostname}}\fR
.RS
.IP \(bu 2
Require a password in (web) server mode:
.RE
.PP
\fB\fCglances \-s \-\-password\fR
