.TH glow
.PP
.RS
Render Markdown in the terminal.
More information: \[la]https://github.com/charmbracelet/glow\[ra]\&.
.RE
.RS
.IP \(bu 2
Run glow and select a file to view:
.RE
.PP
\fB\fCglow\fR
.RS
.IP \(bu 2
Render a Markdown file to the terminal:
.RE
.PP
\fB\fCglow {{path/to/file}}\fR
.RS
.IP \(bu 2
View a Markdown file using a paginator:
.RE
.PP
\fB\fCglow \-p {{path/to/file}}\fR
.RS
.IP \(bu 2
View a file from a URL:
.RE
.PP
\fB\fCglow {{https://example.com/file.md}}\fR
.RS
.IP \(bu 2
View a GitHub/GitLab README:
.RE
.PP
\fB\fCglow {{github.com/owner/repository}}\fR
