.TH gnucash
.PP
.RS
Personal and small\-business financial\-accounting software.
More information: \[la]https://gnucash.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch GnuCash and load the previously opened file:
.RE
.PP
\fB\fCgnucash\fR
.RS
.IP \(bu 2
Launch GnuCash and load the specified file:
.RE
.PP
\fB\fCgnucash {{path/to/file.gnucash}}\fR
.RS
.IP \(bu 2
Launch GnuCash and load an empty file:
.RE
.PP
\fB\fCgnucash \-\-nofile\fR
