.TH go run
.PP
.RS
Compile and run Go code without saving a binary.
More information: \[la]https://pkg.go.dev/cmd/go#hdr-Compile_and_run_Go_program\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a Go file:
.RE
.PP
\fB\fCgo run {{path/to/file.go}}\fR
.RS
.IP \(bu 2
Run a main Go package:
.RE
.PP
\fB\fCgo run {{path/to/package}}\fR
