.TH go tool
.PP
.RS
Run a specific Go tool or command.
Execute a Go command as a stand\-alone binary, typically for debugging.
More information: \[la]https://pkg.go.dev/cmd/go#hdr-Run_specified_go_tool\[ra]\&.
.RE
.RS
.IP \(bu 2
List available tools:
.RE
.PP
\fB\fCgo tool\fR
.RS
.IP \(bu 2
Run the go link tool:
.RE
.PP
\fB\fCgo tool link {{path/to/main.o}}\fR
.RS
.IP \(bu 2
Print the command that would be executed, but do not execute it (similar to \fB\fCwhereis\fR):
.RE
.PP
\fB\fCgo tool \-n {{command}} {{arguments}}\fR
.RS
.IP \(bu 2
Display documentation for a specified tool:
.RE
.PP
\fB\fCgo tool {{command}} \-\-help\fR
