.TH go version
.PP
.RS
Print Go version.
More information: \[la]https://golang.org/cmd/go/#hdr-Print_Go_version\[ra]\&.
.RE
.RS
.IP \(bu 2
Print Go version:
.RE
.PP
\fB\fCgo version\fR
.RS
.IP \(bu 2
Print the Go version used to build the named executable file:
.RE
.PP
\fB\fCgo version {{path/to/executable}}\fR
