.TH googler
.PP
.RS
Search Google from command\-line.
More information: \[la]https://github.com/jarun/googler\[ra]\&.
.RE
.RS
.IP \(bu 2
Search Google for a keyword:
.RE
.PP
\fB\fCgoogler {{keyword}}\fR
.RS
.IP \(bu 2
Search Google and open the first result in web browser:
.RE
.PP
\fB\fCgoogler \-j {{keyword}}\fR
.RS
.IP \(bu 2
Show N search results (default 10):
.RE
.PP
\fB\fCgoogler \-n {{N}} {{keyword}}\fR
.RS
.IP \(bu 2
Disable automatic spelling correction:
.RE
.PP
\fB\fCgoogler \-x {{keyword}}\fR
.RS
.IP \(bu 2
Search one site for a keyword:
.RE
.PP
\fB\fCgoogler \-w {{site}} {{keyword}}\fR
.RS
.IP \(bu 2
Show Google search result in JSON format:
.RE
.PP
\fB\fCgoogler \-\-json {{keyword}}\fR
.RS
.IP \(bu 2
Perform in\-place self\-upgrade:
.RE
.PP
\fB\fCgoogler \-u\fR
.RS
.IP \(bu 2
For more help in interactive mode:
.RE
.PP
\fB\fC?\fR
