.TH gotelemetry
.PP
.RS
A tool for managing Go telemetry data and settings.
More information: \[la]https://telemetry.go.dev/privacy#collection\[ra]\&.
.RE
.RS
.IP \(bu 2
Enable telemetry uploading:
.RE
.PP
\fB\fCgotelemetry on\fR
.RS
.IP \(bu 2
Disable telemetry uploading:
.RE
.PP
\fB\fCgotelemetry off\fR
.RS
.IP \(bu 2
Run a Web Viewer for local telemetry data:
.RE
.PP
\fB\fCgotelemetry view\fR
.RS
.IP \(bu 2
Print the current telemetry environment:
.RE
.PP
\fB\fCgotelemetry env\fR
.RS
.IP \(bu 2
Show details about any subcommand:
.RE
.PP
\fB\fCgotelemetry help {{subcommand}}\fR
