.TH gotty
.PP
.RS
Share your terminal as a web application.
More information: \[la]https://github.com/yudai/gotty\[ra]\&.
.RE
.RS
.IP \(bu 2
Share result of command:
.RE
.PP
\fB\fCgotty {{command}}\fR
.RS
.IP \(bu 2
Share with write permission:
.RE
.PP
\fB\fCgotty \-w {{shell}}\fR
.RS
.IP \(bu 2
Share with credential (Basic Auth):
.RE
.PP
\fB\fCgotty \-w \-c {{username}}:{{password}} {{shell}}\fR
