.TH gpg\-tui
.PP
.RS
Terminal user interface for GNU Public Guard.
More information: \[la]https://github.com/orhun/gpg-tui\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCgpg\-tui\fR:
.RE
.PP
\fB\fCgpg\-tui\fR
.RS
.IP \(bu 2
Start \fB\fCgpg\-tui\fR with color and ASCII armored output:
.RE
.PP
\fB\fCgpg\-tui \-\-style {{colored}} \-\-armor\fR
.RS
.IP \(bu 2
Show help in \fB\fCgpg\-tui\fR:
.RE
.PP
\fB\fC?\fR
.RS
.IP \(bu 2
Quit \fB\fCgpg\-tui\fR:
.RE
.PP
\fB\fCq\fR
.RS
.IP \(bu 2
Interactively generate a new key:
.RE
.PP
\fB\fCg\fR
.RS
.IP \(bu 2
Export the selected key:
.RE
.PP
\fB\fCx\fR
.RS
.IP \(bu 2
Set the detail level for the selected key:
.RE
.PP
\fB\fC1|2|3\fR
.RS
.IP \(bu 2
Refresh \fB\fCgpg\-tui\fR:
.RE
.PP
\fB\fCr\fR
