.TH grafana\-cli
.PP
.RS
A small executable that is bundled with Grafana serve.
More information: \[la]https://grafana.com/docs/grafana/latest/cli/\[ra]\&.
.RE
.RS
.IP \(bu 2
Install, update, or remove specific plugins:
.RE
.PP
\fB\fCgrafana\-cli plugins {{install|update|remove}} {{plugin_id1 plugin_id2 ...}}\fR
.RS
.IP \(bu 2
List all installed plugins:
.RE
.PP
\fB\fCgrafana\-cli plugins ls\fR
