.TH grip
.PP
.RS
Preview GitHub\-flavoured Markdown files locally.
More information: \[la]https://github.com/joeyespo/grip\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the server and serve the rendered \fB\fCREADME\fR file of a current directory:
.RE
.PP
\fB\fCgrip\fR
.RS
.IP \(bu 2
Start the server and serve a specific Markdown file:
.RE
.PP
\fB\fCgrip {{path/to/file.md}}\fR
.RS
.IP \(bu 2
Start the server and open the \fB\fCREADME\fR file of the current directory in the browser:
.RE
.PP
\fB\fCgrip \-\-browser\fR
.RS
.IP \(bu 2
Start the server in the specified port and serve the rendered \fB\fCREADME\fR file of the current directory:
.RE
.PP
\fB\fCgrip {{port}}\fR
