.TH groups
.PP
.RS
Print group memberships for a user.
See also: \fB\fCgroupadd\fR, \fB\fCgroupdel\fR, \fB\fCgroupmod\fR\&.
More information: \[la]https://www.gnu.org/software/coreutils/groups\[ra]\&.
.RE
.RS
.IP \(bu 2
Print group memberships for the current user:
.RE
.PP
\fB\fCgroups\fR
.RS
.IP \(bu 2
Print group memberships for a list of users:
.RE
.PP
\fB\fCgroups {{username1 username2 ...}}\fR
