.TH grumphp
.PP
.RS
A PHP Composer plugin that enables source code quality checks.
More information: \[la]https://github.com/phpro/grumphp\[ra]\&.
.RE
.RS
.IP \(bu 2
Register the Git hooks:
.RE
.PP
\fB\fCgrumphp git:init\fR
.RS
.IP \(bu 2
Trigger the pre\-commit hook manually:
.RE
.PP
\fB\fCgrumphp git:pre\-commit\fR
.RS
.IP \(bu 2
Check every versioned file:
.RE
.PP
\fB\fCgrumphp run\fR
