.TH grunt
.PP
.RS
A JavaScript task runner for automating processes.
More information: \[la]https://github.com/gruntjs/grunt-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Run the default task process:
.RE
.PP
\fB\fCgrunt\fR
.RS
.IP \(bu 2
Run one or more specific space\-separated 
.BR task (s):
.RE
.PP
\fB\fCgrunt {{task_name}}\fR
.RS
.IP \(bu 2
Specify an alternative configuration file:
.RE
.PP
\fB\fCgrunt \-\-gruntfile {{path/to/file}}\fR
.RS
.IP \(bu 2
Specify an alternative base path for relative files:
.RE
.PP
\fB\fCgrunt \-\-base {{path/to/directory}}\fR
.RS
.IP \(bu 2
Specify an additional directory to scan for tasks in:
.RE
.PP
\fB\fCgrunt \-\-tasks {{path/to/directory}}\fR
.RS
.IP \(bu 2
Perform a dry\-run without writing any files:
.RE
.PP
\fB\fCgrunt \-\-no\-write\fR
.RS
.IP \(bu 2
List all available options:
.RE
.PP
\fB\fCgrunt \-\-help\fR
