.TH gst\-inspect\-1.0
.PP
.RS
Print information on GStreamer plugins.
More information: \[la]https://gstreamer.freedesktop.org/documentation/tools/gst-inspect.html?gi-language=c\[ra]\&.
.RE
.RS
.IP \(bu 2
Print information on a plugin:
.RE
.PP
\fB\fCgst\-inspect\-1.0 {{plugin}}\fR
.RS
.IP \(bu 2
List hardware transcoding capabilities of your device:
.RE
.PP
\fB\fCgst\-inspect\-1.0 {{vaapi|nvcodec}}\fR
