.TH gtop
.PP
.RS
System monitoring dashboard for the terminal.
More information: \[la]https://github.com/aksakalli/gtop\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the system stats dashboard:
.RE
.PP
\fB\fCgtop\fR
.RS
.IP \(bu 2
Sort by CPU usage:
.RE
.PP
\fB\fCc\fR
.RS
.IP \(bu 2
Sort by memory usage:
.RE
.PP
\fB\fCm\fR
