.TH gulp
.PP
.RS
JavaScript task runner and streaming build system.
Tasks are defined within \fB\fCgulpfile.js\fR at the project root.
More information: \[la]https://github.com/gulpjs/gulp-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Run the default task:
.RE
.PP
\fB\fCgulp\fR
.RS
.IP \(bu 2
Run individual tasks:
.RE
.PP
\fB\fCgulp {{task}} {{othertask}}\fR
.RS
.IP \(bu 2
Print the task dependency tree for the loaded gulpfile:
.RE
.PP
\fB\fCgulp \-\-tasks\fR
