.TH hakyll\-init
.PP
.RS
Generate a new Hakyll sample blog.
More information: \[la]https://github.com/jaspervdj/hakyll-init\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a new Hakyll sample blog:
.RE
.PP
\fB\fChakyll\-init {{path/to/directory}}\fR
.RS
.IP \(bu 2
Show help for \fB\fChakyll\-init\fR:
.RE
.PP
\fB\fChakyll\-init \-\-help\fR
