.TH hangups
.PP
.RS
Third party command\-line client for Google Hangouts.
More information: \[la]https://github.com/tdryer/hangups\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fChangups\fR:
.RE
.PP
\fB\fChangups\fR
.RS
.IP \(bu 2
View troubleshooting information and help:
.RE
.PP
\fB\fChangups \-h\fR
.RS
.IP \(bu 2
Set a refresh token for hangups:
.RE
.PP
\fB\fChangups \-\-token\-path {{path/to/token}}\fR
