.TH haxelib
.PP
.RS
Haxe Library Manager.
More information: \[la]https://lib.haxe.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Search for a Haxe library:
.RE
.PP
\fB\fChaxelib search {{keyword}}\fR
.RS
.IP \(bu 2
Install a Haxe library:
.RE
.PP
\fB\fChaxelib install {{libname}}\fR
.RS
.IP \(bu 2
Install a specific version of a Haxe library:
.RE
.PP
\fB\fChaxelib install {{libname}} {{version}}\fR
.RS
.IP \(bu 2
Upgrade all installed Haxe libraries:
.RE
.PP
\fB\fChaxelib upgrade\fR
.RS
.IP \(bu 2
Install the development version of a library from a Git repository:
.RE
.PP
\fB\fChaxelib git {{libname}} {{git_url}}\fR
.RS
.IP \(bu 2
Uninstall a Haxe library:
.RE
.PP
\fB\fChaxelib remove {{libname}}\fR
.RS
.IP \(bu 2
Print a tree of locally installed Haxe libraries:
.RE
.PP
\fB\fChaxelib list\fR
