.TH hello
.PP
.RS
Print "Hello, world!", "hello, world" or a customizable text.
More information: \[la]https://www.gnu.org/software/hello/\[ra]\&.
.RE
.RS
.IP \(bu 2
Print "Hello, world!":
.RE
.PP
\fB\fChello\fR
.RS
.IP \(bu 2
Print "hello, world", the traditional type:
.RE
.PP
\fB\fChello \-\-traditional\fR
.RS
.IP \(bu 2
Print a text message:
.RE
.PP
\fB\fChello \-\-greeting="{{greeting_text}}"\fR
