.TH hg branch
.PP
.RS
Create or show a branch name.
More information: \[la]https://www.mercurial-scm.org/doc/hg.1.html#branch\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the name of the currently active branch:
.RE
.PP
\fB\fChg branch\fR
.RS
.IP \(bu 2
Create a new branch for the next commit:
.RE
.PP
\fB\fChg branch {{branch_name}}\fR
