.TH hg init
.PP
.RS
Create a new repository in the specified directory.
More information: \[la]https://www.mercurial-scm.org/doc/hg.1.html#init\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new repository in the current directory:
.RE
.PP
\fB\fChg init\fR
.RS
.IP \(bu 2
Initialize a new repository in the specified directory:
.RE
.PP
\fB\fChg init {{path/to/directory}}\fR
