.TH hg root
.PP
.RS
Display the root location of a Hg repository.
More information: \[la]https://www.mercurial-scm.org/doc/hg.1.html#root\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the root location of the current repository:
.RE
.PP
\fB\fChg root\fR
.RS
.IP \(bu 2
Display the root location of the specified repository:
.RE
.PP
\fB\fChg root \-\-cwd {{path/to/directory}}\fR
