.TH hg serve
.PP
.RS
Start a standalone Mercurial web server for browsing repositories.
More information: \[la]https://www.mercurial-scm.org/doc/hg.1.html#serve\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a web server instance:
.RE
.PP
\fB\fChg serve\fR
.RS
.IP \(bu 2
Start a web server instance on the specified port:
.RE
.PP
\fB\fChg serve \-\-port {{port}}\fR
.RS
.IP \(bu 2
Start a web server instance on the specified listening address:
.RE
.PP
\fB\fChg serve \-\-address {{address}}\fR
.RS
.IP \(bu 2
Start a web server instance with a specific identifier:
.RE
.PP
\fB\fChg serve \-\-name {{name}}\fR
.RS
.IP \(bu 2
Start a web server instance using the specified theme (see the templates directory):
.RE
.PP
\fB\fChg serve \-\-style {{style}}\fR
.RS
.IP \(bu 2
Start a web server instance using the specified SSL certificate bundle:
.RE
.PP
\fB\fChg serve \-\-certificate {{path/to/certificate}}\fR
