.TH hg update
.PP
.RS
Update the working directory to a specified changeset.
More information: \[la]https://www.mercurial-scm.org/doc/hg.1.html#update\[ra]\&.
.RE
.RS
.IP \(bu 2
Update to the tip of the current branch:
.RE
.PP
\fB\fChg update\fR
.RS
.IP \(bu 2
Update to the specified revision:
.RE
.PP
\fB\fChg update \-\-rev {{revision}}\fR
.RS
.IP \(bu 2
Update and discard uncommitted changes:
.RE
.PP
\fB\fChg update \-\-clean\fR
.RS
.IP \(bu 2
Update to the last commit matching a specified date:
.RE
.PP
\fB\fChg update \-\-date {{dd\-mm\-yyyy}}\fR
