.TH hg
.PP
.RS
Mercurial \- a distributed source control management system.
Some subcommands such as \fB\fChg commit\fR have their own usage documentation.
More information: \[la]https://www.mercurial-scm.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute a Mercurial command:
.RE
.PP
\fB\fChg {{command}}\fR
.RS
.IP \(bu 2
Call general help:
.RE
.PP
\fB\fChg help\fR
.RS
.IP \(bu 2
Call help on a command:
.RE
.PP
\fB\fChg help {{command}}\fR
.RS
.IP \(bu 2
Check the Mercurial version:
.RE
.PP
\fB\fChg \-\-version\fR
