.TH hn
.PP
.RS
Command\-line interface for Hacker News.
More information: \[la]https://github.com/rafaelrinaldi/hn-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
View stories on Hacker News:
.RE
.PP
\fB\fChn\fR
.RS
.IP \(bu 2
View \fInumber\fP of stories on Hacker News:
.RE
.PP
\fB\fChn \-\-limit {{number}}\fR
.RS
.IP \(bu 2
View stories on Hacker News, and keep the list open after selecting a link:
.RE
.PP
\fB\fChn \-\-keep\-open\fR
.RS
.IP \(bu 2
View stories on Hacker News sorted by submission date:
.RE
.PP
\fB\fChn \-\-latest\fR
