.TH home\-manager
.PP
.RS
Manage a user environment using Nix.
More information: \[la]https://github.com/rycee/home-manager\[ra]\&.
.RE
.RS
.IP \(bu 2
Activate the configuration defined in \fB\fC~/.config/nixpkgs/home.nix\fR:
.RE
.PP
\fB\fChome\-manager build\fR
.RS
.IP \(bu 2
Activate the configuration and switch to it:
.RE
.PP
\fB\fChome\-manager switch\fR
