.TH hostname
.PP
.RS
Show or set the system's host name.
More information: \[la]https://manned.org/hostname\[ra]\&.
.RE
.RS
.IP \(bu 2
Show current host name:
.RE
.PP
\fB\fChostname\fR
.RS
.IP \(bu 2
Show the network address of the host name:
.RE
.PP
\fB\fChostname \-i\fR
.RS
.IP \(bu 2
Show all network addresses of the host:
.RE
.PP
\fB\fChostname \-I\fR
.RS
.IP \(bu 2
Show the FQDN (Fully Qualified Domain Name):
.RE
.PP
\fB\fChostname \-\-fqdn\fR
.RS
.IP \(bu 2
Set current host name:
.RE
.PP
\fB\fChostname {{new_hostname}}\fR
