.TH hr
.PP
.RS
Print a horizontal rule in the terminal.
More information: \[la]https://github.com/LuRsT/hr\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a horizontal rule:
.RE
.PP
\fB\fChr\fR
.RS
.IP \(bu 2
Print a horizontal rule with a custom string:
.RE
.PP
\fB\fChr {{string}}\fR
.RS
.IP \(bu 2
Print a multiline horizontal rule:
.RE
.PP
\fB\fChr {{string_a}} {{string_b}} {{string_c}}\fR
