.TH htop
.PP
.RS
Display dynamic real\-time information about running processes. An enhanced version of \fB\fCtop\fR\&.
More information: \[la]https://htop.dev/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fChtop\fR:
.RE
.PP
\fB\fChtop\fR
.RS
.IP \(bu 2
Start \fB\fChtop\fR displaying processes owned by a specific user:
.RE
.PP
\fB\fChtop \-\-user {{username}}\fR
.RS
.IP \(bu 2
Sort processes by a specified \fB\fCsort_item\fR (use \fB\fChtop \-\-sort help\fR for available options):
.RE
.PP
\fB\fChtop \-\-sort {{sort_item}}\fR
.RS
.IP \(bu 2
Start \fB\fChtop\fR with the specified delay between updates, in tenths of a second (i.e. 50 = 5 seconds):
.RE
.PP
\fB\fChtop \-\-delay {{50}}\fR
.RS
.IP \(bu 2
See interactive commands while running htop:
.RE
.PP
\fB\fC?\fR
.RS
.IP \(bu 2
Switch to a different tab:
.RE
.PP
\fB\fCtab\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fChtop \-\-help\fR
