.TH htpasswd
.PP
.RS
Create and manage htpasswd files to protect web server directories using basic authentication.
More information: \[la]https://httpd.apache.org/docs/current/programs/htpasswd.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Create/overwrite htpasswd file:
.RE
.PP
\fB\fChtpasswd \-c {{path/to/file}} {{username}}\fR
.RS
.IP \(bu 2
Add user to htpasswd file or update existing user:
.RE
.PP
\fB\fChtpasswd {{path/to/file}} {{username}}\fR
.RS
.IP \(bu 2
Add user to htpasswd file in batch mode without an interactive password prompt (for script usage):
.RE
.PP
\fB\fChtpasswd \-b {{path/to/file}} {{username}} {{password}}\fR
.RS
.IP \(bu 2
Delete user from htpasswd file:
.RE
.PP
\fB\fChtpasswd \-D {{path/to/file}} {{username}}\fR
.RS
.IP \(bu 2
Verify user password:
.RE
.PP
\fB\fChtpasswd \-v {{path/to/file}} {{username}}\fR
.RS
.IP \(bu 2
Display a string with username (plain text) and password (md5):
.RE
.PP
\fB\fChtpasswd \-nbm {{username}} {{password}}\fR
