.TH hub clone
.PP
.RS
Clone an existing repository.
More information: \[la]https://hub.github.com/hub-clone.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Clone an existing repository to current directory (If run into authentication problem, try full ssh path):
.RE
.PP
\fB\fChub clone {{remote_repository_location}}\fR
