.TH hub ci\-status
.PP
.RS
Display status of GitHub checks.
More information: \[la]https://hub.github.com/hub-ci-status.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the CI status for this branch:
.RE
.PP
\fB\fChub ci\-status \-\-verbose\fR
.RS
.IP \(bu 2
Display status of GitHub checks for a commit:
.RE
.PP
\fB\fChub ci\-status \-\-verbose {{commit_SHA}}\fR
