.TH hub browse
.PP
.RS
Open a GitHub repository in the browser or print the URL.
More information: \[la]https://cli.github.com/manual/hub_browse\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the homepage of the current repository in the default web browser:
.RE
.PP
\fB\fChub browse\fR
.RS
.IP \(bu 2
Open the homepage of a specific repository in the default web browser:
.RE
.PP
\fB\fChub browse {{owner}}/{{repository}}\fR
.RS
.IP \(bu 2
Open the subpage of a specific repository in the default web browser, subpage can be "wiki", "commits", "issues", or other (default: "tree"):
.RE
.PP
\fB\fChub browse {{owner}}/{{repository}} {{subpage}}\fR
