.TH hunspell
.PP
.RS
Check spelling.
More information: \[la]https://github.com/hunspell/hunspell\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the spelling of a file:
.RE
.PP
\fB\fChunspell {{path/to/file}}\fR
.RS
.IP \(bu 2
Check the spelling of a file with the en_US dictionary:
.RE
.PP
\fB\fChunspell \-d {{en_US}} {{path/to/file}}\fR
.RS
.IP \(bu 2
List misspelled words in a file:
.RE
.PP
\fB\fChunspell \-l {{path/to/file}}\fR
