.TH ibmcloud
.PP
.RS
A command\-line tool for managing IBM Cloud apps and services.
More information: \[la]https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Update \fB\fCibmcloud\fR to the latest version:
.RE
.PP
\fB\fCibmcloud update\fR
.RS
.IP \(bu 2
Install the Cloud Foundry module for accessing Cloud Foundry services:
.RE
.PP
\fB\fCibmcloud cf install\fR
.RS
.IP \(bu 2
List all available IBM Cloud regions:
.RE
.PP
\fB\fCibmcloud regions\fR
.RS
.IP \(bu 2
Display \fB\fCibmcloud\fR version:
.RE
.PP
\fB\fCibmcloud version\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCibmcloud help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCibmcloud help {{subcommand}}\fR
