.TH ical
.PP
.RS
A Hirji/Islamic calendar and converter for the terminal.
More information: \[la]https://manned.org/ical\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the current month's calendar:
.RE
.PP
\fB\fCical\fR
.RS
.IP \(bu 2
Convert a Gregorian date to a Hijri date:
.RE
.PP
\fB\fCical \-\-gregorian {{yyyymmdd}}\fR
.RS
.IP \(bu 2
Convert a Hirji date to a Gregorian date:
.RE
.PP
\fB\fCical \-\-hijri {{yyyymmdd}}\fR
