.TH id3tag
.PP
.RS
Tool for reading, writing, and manipulating ID3v1 and ID3v2 tags of MP3 files.
More information: \[la]https://manned.org/id3tag\[ra]\&.
.RE
.RS
.IP \(bu 2
Set artist and title tag of an MP3 file:
.RE
.PP
\fB\fCid3tag \-\-artist={{artist}} \-\-title={{title}} {{path/to/file.mp3}}\fR
.RS
.IP \(bu 2
Set album title of all MP3 files in the current directory:
.RE
.PP
\fB\fCid3tag \-\-album={{album}} {{*.mp3}}\fR
.RS
.IP \(bu 2
Get more help:
.RE
.PP
\fB\fCid3tag \-\-help\fR
