.TH iex
.PP
.RS
IEx is the interactive shell for Elixir.
More information: \[la]https://hexdocs.pm/iex\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive session:
.RE
.PP
\fB\fCiex\fR
.RS
.IP \(bu 2
Start a session that remembers history:
.RE
.PP
\fB\fCiex \-\-erl "\-kernel shell_history enabled"\fR
.RS
.IP \(bu 2
Start and load Mix project files:
.RE
.PP
\fB\fCiex \-S mix\fR
