.TH ignite
.PP
.RS
A CLI for React Native boilerplates, plugins, generators, and more.
More information: \[la]https://infinite.red/ignite\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new React Native project:
.RE
.PP
\fB\fCignite new {{project_name}}\fR
.RS
.IP \(bu 2
Generate file from a plugin:
.RE
.PP
\fB\fCignite generate {{plugin_name}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Add an Ignite plugin to the project:
.RE
.PP
\fB\fCignite add {{plugin_name}}\fR
.RS
.IP \(bu 2
Remove an Ignite plugin from the project:
.RE
.PP
\fB\fCignite remove {{plugin_name}}\fR
