.TH imapsync
.PP
.RS
Email IMAP tool for syncing, copying and migrating email mailboxes between two IMAP servers, one way, and without duplicates.
More information: \[la]https://imapsync.lamiral.info\[ra]\&.
.RE
.RS
.IP \(bu 2
Synchronize IMAP account between host1 and host2:
.RE
.PP
\fB\fCimapsync \-\-host1 {{host1}} \-\-user1 {{user1}} \-\-password1 {{secret1}} \-\-host2 {{host2}} \-\-user2 {{user2}} \-\-password2 {{secret2}}\fR
