.TH imgtoppm
.PP
.RS
Converts various image file formats to the PPM (Portable Pixmap) format.
More information: \[la]https://netpbm.sourceforge.net/doc/imgtoppm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert an input image to PPM format:
.RE
.PP
\fB\fCimgtoppm {{path/to/input}} > {{path/to/output.ppm}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCimgtoppm \-version\fR
