.TH in\-toto\-run
.PP
.RS
Generating link metadata while carrying out a supply chain step.
More information: \[la]https://in-toto.readthedocs.io/en/latest/command-line-tools/in-toto-run.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Tag a git repo and signing the resulting link file:
.RE
.PP
\fB\fCin\-toto\-run \-n {{tag}} \-\-products {{.}} \-k {{key_file}} \-\- {{git tag v1.0}}\fR
.RS
.IP \(bu 2
Create a tarball, storing files as materials and the tarball as product:
.RE
.PP
\fB\fCin\-toto\-run \-n {{package}} \-m {{project}} \-p {{project.tar.gz}} \-\- {{tar czf project.tar.gz project}}\fR
.RS
.IP \(bu 2
Generate signed attestations for review work:
.RE
.PP
\fB\fCin\-toto\-run \-n {{review}} \-k {{key_file}} \-m {{document.pdf}} \-x\fR
.RS
.IP \(bu 2
Scan the image using Trivy and generate link file:
.RE
.PP
\fB\fCin\-toto\-run \-n {{scan}} \-k {{key_file}} \-p {{report.json}} \-\- {{/bin/sh \-c "trivy \-o report.json \-f json <IMAGE>"}}\fR
