.TH info
.PP
.RS
Reads documentation stored in the info format.
More information: \[la]https://en.wikipedia.org/wiki/
.BR Info_ (Unix)\[ra]\&.
.RE
.RS
.IP \(bu 2
Start reading top\-level directory menu:
.RE
.PP
\fB\fCinfo\fR
.RS
.IP \(bu 2
Start reading at given menu item node from top\-level directory:
.RE
.PP
\fB\fCinfo {{menu_item}}\fR
.RS
.IP \(bu 2
Start reading at second menu item within first menu item manual:
.RE
.PP
\fB\fCinfo {{first_menu_item}} {{second_menu_item}}\fR
