.TH inkview
.PP
.RS
Inkscape graphical SVG previewer.
Also functions as a slideshow viewer.
More information: \[la]http://wiki.inkscape.org/wiki/index.php/Inkview\[ra]\&.
.RE
.RS
.IP \(bu 2
Preview an SVG:
.RE
.PP
\fB\fCinkview {{path/to/file.svg}}\fR
.RS
.IP \(bu 2
Preview multiple SVGs (use arrow keys to navigate):
.RE
.PP
\fB\fCinkview {{path/to/file_a.svg}} {{path/to/file_b.svg}} {{path/to/file_c.svg}}\fR
