.TH install\-tl
.PP
.RS
TeX Live cross\-platform installer.
More information: \[la]https://tug.org/texlive/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the text\-based installer (default on Unix systems):
.RE
.PP
\fB\fCinstall\-tl \-no\-gui\fR
.RS
.IP \(bu 2
Start the GUI installer (default on macOS and Windows, requires Tcl/Tk):
.RE
.PP
\fB\fCinstall\-tl \-gui\fR
.RS
.IP \(bu 2
Install TeX Live as defined in a specific profile file:
.RE
.PP
\fB\fCinstall\-tl \-profile {{path/to/texlive.profile}}\fR
.RS
.IP \(bu 2
Start the installer with the settings from a specific profile file:
.RE
.PP
\fB\fCinstall\-tl \-init\-from\-file {{path/to/texlive.profile}}\fR
.RS
.IP \(bu 2
Start the installer for installation on a portable device, like a USB stick:
.RE
.PP
\fB\fCinstall\-tl \-portable\fR
.RS
.IP \(bu 2
Show help for \fB\fCinstall\-tl\fR:
.RE
.PP
\fB\fCinstall\-tl \-help\fR
