.TH interdiff
.PP
.RS
Show differences between two diff files.
More information: \[la]http://freshmeat.sourceforge.net/projects/patchutils\[ra]\&.
.RE
.RS
.IP \(bu 2
Compare diff files:
.RE
.PP
\fB\fCinterdiff {{old_file}} {{new_file}}\fR
.RS
.IP \(bu 2
Compare diff files, ignoring whitespace:
.RE
.PP
\fB\fCinterdiff \-w {{old_file}} {{new_file}}\fR
