.TH ionic
.PP
.RS
A framework to build hybrid mobile apps.
More information: \[la]https://ionicframework.com/docs/cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new project:
.RE
.PP
\fB\fCionic start\fR
.RS
.IP \(bu 2
Start a local dev server for app dev/testing:
.RE
.PP
\fB\fCionic serve\fR
.RS
.IP \(bu 2
Generate new app component, directive, page, pipe, provider or tabs:
.RE
.PP
\fB\fCionic g {{page}}\fR
.RS
.IP \(bu 2
Show versions of Ionic, Cordova, environment, etc.:
.RE
.PP
\fB\fCionic info\fR
.RS
.IP \(bu 2
Run app on an Android/iOS device:
.RE
.PP
\fB\fCionic cordova run {{android|ios}} \-\-device\fR
.RS
.IP \(bu 2
Check the health of an Ionic app:
.RE
.PP
\fB\fCionic doctor {{check}}\fR
