.TH ipcs
.PP
.RS
Display information about resources used in IPC (Inter\-process Communication).
More information: \[la]https://manned.org/ipcs\[ra]\&.
.RE
.RS
.IP \(bu 2
Specific information about the Message Queue which has the ID 32768:
.RE
.PP
\fB\fCipcs \-qi 32768\fR
.RS
.IP \(bu 2
General information about all the IPC:
.RE
.PP
\fB\fCipcs \-a\fR
