.TH IPython
.PP
.RS
A Python shell with automatic history, dynamic object introspection, easier configuration, command completion, access to the system shell and more.
More information: \[la]https://ipython.readthedocs.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a REPL (interactive shell):
.RE
.PP
\fB\fCipython\fR
.RS
.IP \(bu 2
Enter an interactive IPython session after running a Python script:
.RE
.PP
\fB\fCipython \-i {{script.py}}\fR
.RS
.IP \(bu 2
Create default IPython profile:
.RE
.PP
\fB\fCipython profile create\fR
.RS
.IP \(bu 2
Print the path to the directory for the default IPython profile:
.RE
.PP
\fB\fCipython locate profile\fR
.RS
.IP \(bu 2
Clear the IPython history database, deleting all entries:
.RE
.PP
\fB\fCipython history clear\fR
