.TH irssi
.PP
.RS
Text based IRC client.
More information: \[la]https://irssi.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Open Irssi and connect to a server with a nickname:
.RE
.PP
\fB\fCirssi \-n {{nickname}} \-c {{irc.example.com}}\fR
.RS
.IP \(bu 2
Open Irssi and connect with a specific server on a given port:
.RE
.PP
\fB\fCirssi \-c {{irc.example.com}} \-p {{port}}\fR
.RS
.IP \(bu 2
View the help:
.RE
.PP
\fB\fCirssi \-\-help\fR
.RS
.IP \(bu 2
Join a channel:
.RE
.PP
\fB\fC/join {{#channelname}}\fR
.RS
.IP \(bu 2
Change active window (starts at 1):
.RE
.PP
\fB\fC/win {{window_number}}\fR
.RS
.IP \(bu 2
Exit the application cleanly and quitting any 
.BR server (s):
.RE
.PP
\fB\fC/quit\fR
