.TH ivpn
.PP
.RS
Command\-line interface for the IVPN client.
More information: \[la]https://www.ivpn.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the current state of IVPN, including the connection and firewall status:
.RE
.PP
\fB\fCivpn status\fR
.RS
.IP \(bu 2
Print a list of available servers to connect to:
.RE
.PP
\fB\fCivpn servers\fR
