.TH jadx
.PP
.RS
Dex to Java decompiler.
Produces Java source code from Android Dex and APK files.
More information: \[la]https://github.com/skylot/jadx\[ra]\&.
.RE
.RS
.IP \(bu 2
Decompile a Dex file into a directory:
.RE
.PP
\fB\fCjadx {{path/to/file}}\fR
.RS
.IP \(bu 2
Decompile a Dex file into a specific directory:
.RE
.PP
\fB\fCjadx \-\-output\-dir {{path/to/directory}} {{path/to/file}}\fR
