.TH jcal
.PP
.RS
Display calendar information in the Jalali format, with the current day highlighted.
More information: \[la]http://www.nongnu.org/jcal/\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a calendar for the current month:
.RE
.PP
\fB\fCjcal\fR
.RS
.IP \(bu 2
Display the previous, current, and next months:
.RE
.PP
\fB\fCjcal \-3\fR
.RS
.IP \(bu 2
Display a calendar for a specific year (4 digits):
.RE
.PP
\fB\fCjcal {{year}}\fR
.RS
.IP \(bu 2
Display a calendar for a specific month and year:
.RE
.PP
\fB\fCjcal {{year}} {{month}}\fR
