.TH jetifier
.PP
.RS
Jetifier AndroidX transition tool in npm format, with a react\-native compatible style.
More information: \[la]https://github.com/mikehardy/jetifier\[ra]\&.
.RE
.RS
.IP \(bu 2
Migrate project dependencies to the AndroidX format:
.RE
.PP
\fB\fCjetifier\fR
.RS
.IP \(bu 2
Migrate project dependencies from the AndroidX format:
.RE
.PP
\fB\fCjetifier reverse\fR
