.TH jf
.PP
.RS
Interact with JFrog products like Artifactory, Xray, Distribution, Pipelines and Mission Control.
More information: \[la]https://jfrog.com/help/r/jfrog-cli/usage\[ra]\&.
.RE
.RS
.IP \(bu 2
Add a new configuration:
.RE
.PP
\fB\fCjf config add\fR
.RS
.IP \(bu 2
Show the current configuration:
.RE
.PP
\fB\fCjf config show\fR
.RS
.IP \(bu 2
Search for artifacts within the given repository and directory:
.RE
.PP
\fB\fCjf rt search \-\-recursive {{repostiory_name}}/{{path}}/\fR
