.TH jhipster
.PP
.RS
Web application generator using either monolithic or microservices architecture.
More information: \[la]https://www.jhipster.tech/\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a simple full\-stack project (monolithic or microservices):
.RE
.PP
\fB\fCjhipster\fR
.RS
.IP \(bu 2
Generate a simple frontend project:
.RE
.PP
\fB\fCjhipster \-\-skip\-server\fR
.RS
.IP \(bu 2
Generate a simple backend project:
.RE
.PP
\fB\fCjhipster \-\-skip\-client\fR
.RS
.IP \(bu 2
Apply latest JHipster updates to the project:
.RE
.PP
\fB\fCjhipster upgrade\fR
.RS
.IP \(bu 2
Add a new entity to a generated project:
.RE
.PP
\fB\fCjhipster entity {{entity_name}}\fR
.RS
.IP \(bu 2
Import a JDL file to configure your application (see: \[la]https://start.jhipster.tech/jdl-studio/\[ra]):
.RE
.PP
\fB\fCjhipster import\-jdl {{first_file.jh second_file.jh ... n_file.jh}}\fR
.RS
.IP \(bu 2
Generate a CI/CD pipeline for your application:
.RE
.PP
\fB\fCjhipster ci\-cd\fR
.RS
.IP \(bu 2
Generate a Kubernetes configuration for your application:
.RE
.PP
\fB\fCjhipster kubernetes\fR
