.TH jigsaw
.PP
.RS
A Laravel\-based static site builder for PHP.
More information: \[la]https://jigsaw.tighten.co\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a project:
.RE
.PP
\fB\fCjigsaw init\fR
.RS
.IP \(bu 2
Initialize a project using a starter template:
.RE
.PP
\fB\fCjigsaw init {{template_name}}\fR
.RS
.IP \(bu 2
Build the site for development:
.RE
.PP
\fB\fCjigsaw build\fR
.RS
.IP \(bu 2
Preview the site from the "build_local" directory:
.RE
.PP
\fB\fCjigsaw serve\fR
.RS
.IP \(bu 2
Build the site for production:
.RE
.PP
\fB\fCjigsaw build production\fR
.RS
.IP \(bu 2
Preview the site from the "build_production" directory:
.RE
.PP
\fB\fCjigsaw serve {{build_production}}\fR
