.TH jobs
.PP
.RS
Display status of jobs in the current session.
More information: \[la]https://manned.org/jobs\[ra]\&.
.RE
.RS
.IP \(bu 2
Show status of all jobs:
.RE
.PP
\fB\fCjobs\fR
.RS
.IP \(bu 2
Show status of a particular job:
.RE
.PP
\fB\fCjobs %{{job_id}}\fR
.RS
.IP \(bu 2
Show status and process IDs of all jobs:
.RE
.PP
\fB\fCjobs \-l\fR
.RS
.IP \(bu 2
Show process IDs of all jobs:
.RE
.PP
\fB\fCjobs \-p\fR
