.TH joe
.PP
.RS
Joe's own text editor.
More information: \[la]https://joe-editor.sourceforge.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a new file in JOE:
.RE
.PP
\fB\fCjoe\fR
.RS
.IP \(bu 2
Open a specific file:
.RE
.PP
\fB\fCjoe {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a specific file, positioning the cursor at the specified line:
.RE
.PP
\fB\fCjoe +{{line}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a specific file in read\-only mode:
.RE
.PP
\fB\fCjoe \-rdonly {{path/to/file}}\fR
