.TH josm
.PP
.RS
Extensible OpenStreetMap editor for Java 8+.
More information: \[la]https://josm.openstreetmap.de/\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch JOSM:
.RE
.PP
\fB\fCjosm\fR
.RS
.IP \(bu 2
Launch JOSM in maximized mode:
.RE
.PP
\fB\fCjosm \-\-maximize\fR
.RS
.IP \(bu 2
Launch JOSM and set a specific language:
.RE
.PP
\fB\fCjosm \-\-language {{de}}\fR
.RS
.IP \(bu 2
Launch JOSM and reset all preferences to their default values:
.RE
.PP
\fB\fCjosm \-\-reset\-preferences\fR
.RS
.IP \(bu 2
Launch JOSM and download a specific bounding box:
.RE
.PP
\fB\fCjosm \-\-download {{minlat,minlon,maxlat,maxlon}}\fR
.RS
.IP \(bu 2
Launch JOSM and download a specific bounding box as raw GPS:
.RE
.PP
\fB\fCjosm \-\-downloadgps {{minlat,minlon,maxlat,maxlon}}\fR
.RS
.IP \(bu 2
Launch JOSM without plugins:
.RE
.PP
\fB\fCjosm \-\-skip\-plugins\fR
