.TH jpegtopnm
.PP
.RS
Converts a JPEG/JFIF file to the PPM or PGM format.
More information: \[la]https://netpbm.sourceforge.net/doc/jpegtopnm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert JPEG/JFIF image to a PPM or PGM image:
.RE
.PP
\fB\fCjpegtopnm {{path/to/file.jpg}} > {{path/to/file.pnm}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCjpegtopnm \-version\fR
