.TH jps
.PP
.RS
Show JVM process status of current user.
More information: \[la]https://docs.oracle.com/en/java/javase/20/docs/specs/man/jps.html\[ra]\&.
.RE
.RS
.IP \(bu 2
List all JVM processes:
.RE
.PP
\fB\fCjps\fR
.RS
.IP \(bu 2
List all JVM processes with only PID:
.RE
.PP
\fB\fCjps \-q\fR
.RS
.IP \(bu 2
Display the arguments passed to the processes:
.RE
.PP
\fB\fCjps \-m\fR
.RS
.IP \(bu 2
Display the full package name of all processes:
.RE
.PP
\fB\fCjps \-l\fR
.RS
.IP \(bu 2
Display the arguments passed to the JVM:
.RE
.PP
\fB\fCjps \-v\fR
