.TH k8s\-unused\-secret\-detector
.PP
.RS
Command\-line interface tool for detecting unused Kubernetes secrets.
More information: \[la]https://github.com/dtan4/k8s-unused-secret-detector\[ra]\&.
.RE
.RS
.IP \(bu 2
Detect unused secrets:
.RE
.PP
\fB\fCk8s\-unused\-secret\-detector\fR
.RS
.IP \(bu 2
Detect unused secrets in a specific namespace:
.RE
.PP
\fB\fCk8s\-unused\-secret\-detector \-n {{namespace}}\fR
.RS
.IP \(bu 2
Delete unused secrets in a specific namespace:
.RE
.PP
\fB\fCk8s\-unused\-secret\-detector \-n {{namespace}} | kubectl delete secret \-n {{namespace}}\fR
