.TH kaggle
.PP
.RS
Official CLI for Kaggle implemented in Python 3.
More information: \[la]https://github.com/Kaggle/kaggle-api\[ra]\&.
.RE
.RS
.IP \(bu 2
View current configuration values:
.RE
.PP
\fB\fCkaggle config view\fR
.RS
.IP \(bu 2
Download a specific file from a competition dataset:
.RE
.PP
\fB\fCkaggle competitions download {{competition}} \-f {{filename}}\fR
