.TH kahlan
.PP
.RS
A unit and Behaviour Driven Development test framework for PHP.
More information: \[la]https://kahlan.github.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Run all specifications in the "spec" directory:
.RE
.PP
\fB\fCkahlan\fR
.RS
.IP \(bu 2
Run specifications using a specific configuration file:
.RE
.PP
\fB\fCkahlan \-\-config={{path/to/configuration_file}}\fR
.RS
.IP \(bu 2
Run specifications and output using a reporter:
.RE
.PP
\fB\fCkahlan \-\-reporter={{dot|bar|json|tap|verbose}}\fR
.RS
.IP \(bu 2
Run specifications with code coverage (detail can be between 0 and 4):
.RE
.PP
\fB\fCkahlan \-\-coverage={{detail_level}}\fR
