.TH kdenlive
.PP
.RS
KDE's non\-linear video editor.
More information: \[la]https://manned.org/kdenlive\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the video editor:
.RE
.PP
\fB\fCkdenlive\fR
.RS
.IP \(bu 2
Open a specific file:
.RE
.PP
\fB\fCkdenlive {{path/to/file}}.kdenlive\fR
.RS
.IP \(bu 2
Set a specific path for an MLT environment:
.RE
.PP
\fB\fCkdenlive \-\-mlt\-path {{path/to/directory}}\fR
.RS
.IP \(bu 2
Set a specific log level for an MLT environment:
.RE
.PP
\fB\fCkdenlive \-\-mlt\-log {{verbose|debug}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCkdenlive \-\-help\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCkdenlive \-\-version\fR
