.TH keepass2
.PP
.RS
A light\-weight password manager.
More information: \[la]https://keepass.info\[ra]\&.
.RE
.RS
.IP \(bu 2
Start KeePass 2, opening the most recently opened password database:
.RE
.PP
\fB\fCkeepass2\fR
.RS
.IP \(bu 2
Start KeePass 2, opening a specific password database:
.RE
.PP
\fB\fCkeepass2 {{path/to/database.kbdx}}\fR
.RS
.IP \(bu 2
Use a specific key file to open a password database:
.RE
.PP
\fB\fCkeepass2 {{path/to/database.kbdx}} \-keyfile:{{path/to/key/file.key}}\fR
