.TH kiwi\-ng
.PP
.RS
KIWI NG is an OS image and appliance builder.
More information: \[la]https://osinside.github.io/kiwi/\[ra]\&.
.RE
.RS
.IP \(bu 2
Build an appliance:
.RE
.PP
\fB\fCkiwi\-ng system build \-\-description={{path/to/directory}} \-\-target\-dir={{path/to/directory}}\fR
.RS
.IP \(bu 2
Show build result of built appliance:
.RE
.PP
\fB\fCkiwi\-ng result list \-\-target\-dir={{path/to/directory}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCkiwi\-ng help\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCkiwi\-ng \-v\fR
