.TH krita
.PP
.RS
A sketching and painting program designed for digital artists.
See also: \fB\fCgimp\fR\&.
More information: \[la]https://docs.krita.org/en/reference_manual/linux_command_line.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Krita:
.RE
.PP
\fB\fCkrita\fR
.RS
.IP \(bu 2
Open specific files:
.RE
.PP
\fB\fCkrita {{path/to/image1 path/to/image2 ...}}\fR
.RS
.IP \(bu 2
Start without a splash screen:
.RE
.PP
\fB\fCkrita \-\-nosplash\fR
.RS
.IP \(bu 2
Start with a specific workspace:
.RE
.PP
\fB\fCkrita \-\-workspace {{Animation}}\fR
.RS
.IP \(bu 2
Start in fullscreen mode:
.RE
.PP
\fB\fCkrita \-\-fullscreen\fR
