.TH kubectx
.PP
.RS
Utility to manage and switch between \fB\fCkubectl\fR contexts.
More information: \[la]https://github.com/ahmetb/kubectx\[ra]\&.
.RE
.RS
.IP \(bu 2
List the contexts:
.RE
.PP
\fB\fCkubectx\fR
.RS
.IP \(bu 2
Switch to a named context:
.RE
.PP
\fB\fCkubectx {{name}}\fR
.RS
.IP \(bu 2
Switch to the previous context:
.RE
.PP
\fB\fCkubectx \-\fR
.RS
.IP \(bu 2
Delete a named context:
.RE
.PP
\fB\fCkubectx \-d {{name}}\fR
