.TH kubens
.PP
.RS
Utility to switch between Kubernetes namespaces.
More information: \[la]https://github.com/ahmetb/kubectx\[ra]\&.
.RE
.RS
.IP \(bu 2
List the namespaces:
.RE
.PP
\fB\fCkubens\fR
.RS
.IP \(bu 2
Change the active namespace:
.RE
.PP
\fB\fCkubens {{name}}\fR
.RS
.IP \(bu 2
Switch to the previous namespace:
.RE
.PP
\fB\fCkubens \-\fR
