.TH lambo
.PP
.RS
A super\-powered \fB\fClaravel new\fR for Laravel and Valet.
See also \fB\fClambo new\fR for additional command flags.
More information: \[la]https://github.com/tighten/lambo\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Laravel application:
.RE
.PP
\fB\fClambo new {{app_name}}\fR
.RS
.IP \(bu 2
Open the configuration in your default editor:
.RE
.PP
\fB\fClambo edit\-config\fR
.RS
.IP \(bu 2
Open the configuration in a specific editor:
.RE
.PP
\fB\fClambo edit\-config \-\-editor="{{path/to/editor}}"\fR
.RS
.IP \(bu 2
Open the configuration file that is run after new applications have been scaffolded:
.RE
.PP
\fB\fClambo edit\-after\fR
