.TH lando
.PP
.RS
Local development environment and DevOps tool built on Docker.
More information: \[la]https://docs.lando.dev/cli/\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize code for use with \fB\fClando\fR:
.RE
.PP
\fB\fClando init\fR
.RS
.IP \(bu 2
Print information about your app:
.RE
.PP
\fB\fClando info\fR
.RS
.IP \(bu 2
Start your app:
.RE
.PP
\fB\fClando start\fR
.RS
.IP \(bu 2
Stop your app:
.RE
.PP
\fB\fClando stop\fR
.RS
.IP \(bu 2
Restart your app:
.RE
.PP
\fB\fClando restart\fR
.RS
.IP \(bu 2
Rebuild your app from scratch, preserving data:
.RE
.PP
\fB\fClando rebuild\fR
.RS
.IP \(bu 2
Display logs for your app:
.RE
.PP
\fB\fClando logs\fR
.RS
.IP \(bu 2
Destroy your app:
.RE
.PP
\fB\fClando destroy\fR
