.TH laravel
.PP
.RS
A command\-line installer for the Laravel framework.
More information: \[la]https://laravel.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Laravel application:
.RE
.PP
\fB\fClaravel new {{name}}\fR
.RS
.IP \(bu 2
Use the latest development release:
.RE
.PP
\fB\fClaravel new {{name}} \-\-dev\fR
.RS
.IP \(bu 2
Overwrite if the directory already exists:
.RE
.PP
\fB\fClaravel new {{name}} \-\-force\fR
.RS
.IP \(bu 2
Install the Laravel Jetstream scaffolding:
.RE
.PP
\fB\fClaravel new {{name}} \-\-jet\fR
.RS
.IP \(bu 2
Install the Laravel Jetstream scaffolding with a specific stack:
.RE
.PP
\fB\fClaravel new {{name}} \-\-jet \-\-stack {{livewire|inertia}}\fR
.RS
.IP \(bu 2
Install the Laravel Jetstream scaffolding with support for teams:
.RE
.PP
\fB\fClaravel new {{name}} \-\-jet \-\-teams\fR
.RS
.IP \(bu 2
List the available installer commands:
.RE
.PP
\fB\fClaravel list\fR
