.TH latex
.PP
.RS
Compile a DVI document from LaTeX source files.
More information: \[la]https://www.latex-project.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Compile a DVI document:
.RE
.PP
\fB\fClatex {{source.tex}}\fR
.RS
.IP \(bu 2
Compile a DVI document, specifying an output directory:
.RE
.PP
\fB\fClatex \-output\-directory={{path/to/directory}} {{source.tex}}\fR
.RS
.IP \(bu 2
Compile a DVI document, exiting on each error:
.RE
.PP
\fB\fClatex \-halt\-on\-error {{source.tex}}\fR
