.TH laydown
.PP
.RS
Command line application to prepare for Daily Standup.
More information: \[la]https://github.com/badjr13/laydown\[ra]\&.
.RE
.RS
.IP \(bu 2
Add an item to DID section:
.RE
.PP
\fB\fClaydown did {{item}}\fR
.RS
.IP \(bu 2
Add an item to DOING section:
.RE
.PP
\fB\fClaydown doing {{item}}\fR
.RS
.IP \(bu 2
Clear all items:
.RE
.PP
\fB\fClaydown clear\fR
.RS
.IP \(bu 2
Use an editor to edit current data:
.RE
.PP
\fB\fClaydown edit\fR
.RS
.IP \(bu 2
Archive and clear current data:
.RE
.PP
\fB\fClaydown archive\fR
