.TH lb
.PP
.RS
A tool for managing a blog contained in the current directory.
Drafts and posts to operate on are selected interactively when running the commands.
More information: \[la]https://github.com/LukeSmithxyz/lb\[ra]\&.
.RE
.RS
.IP \(bu 2
Make a new draft:
.RE
.PP
\fB\fClb new\fR
.RS
.IP \(bu 2
Edit a draft:
.RE
.PP
\fB\fClb edit\fR
.RS
.IP \(bu 2
Delete a draft:
.RE
.PP
\fB\fClb trash\fR
.RS
.IP \(bu 2
Publish a draft:
.RE
.PP
\fB\fClb publish\fR
.RS
.IP \(bu 2
Delete a published post:
.RE
.PP
\fB\fClb delete\fR
.RS
.IP \(bu 2
Unpublish a published post to edit it as a draft again:
.RE
.PP
\fB\fClb revise\fR
