.TH ldapsearch
.PP
.RS
Query an LDAP directory.
More information: \[la]https://docs.ldap.com/ldap-sdk/docs/tool-usages/ldapsearch.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Query an LDAP server for all items that are a member of the given group and return the object's displayName value:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} \-b {{base_ou}} '{{memberOf=group1}}' displayName\fR
.RS
.IP \(bu 2
Query an LDAP server with a no\-newline password file for all items that are a member of the given group and return the object's displayName value:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-y '{{password_file}}' \-h {{ldap_host}} \-b {{base_ou}} '{{memberOf=group1}}' displayName\fR
.RS
.IP \(bu 2
Return 5 items that match the given filter:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} \-b {{base_ou}} '{{memberOf=group1}}' \-z 5 displayName\fR
.RS
.IP \(bu 2
Wait up to 7 seconds for a response:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} \-b {{base_ou}} '{{memberOf=group1}}' \-l 7 displayName\fR
.RS
.IP \(bu 2
Invert the filter:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} \-b {{base_ou}} '(!(memberOf={{group1}}))' displayName\fR
.RS
.IP \(bu 2
Return all items that are part of multiple groups, returning the display name for each item:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} '(&({{memberOf=group1}})({{memberOf=group2}})({{memberOf=group3}}))' "displayName"\fR
.RS
.IP \(bu 2
Return all items that are members of at least 1 of the specified groups:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} '(|({{memberOf=group1}})({{memberOf=group1}})({{memberOf=group3}}))' displayName\fR
.RS
.IP \(bu 2
Combine multiple boolean logic filters:
.RE
.PP
\fB\fCldapsearch \-D '{{admin_DN}}' \-w '{{password}}' \-h {{ldap_host}} '(&({{memberOf=group1}})({{memberOf=group2}})(!({{memberOf=group3}})))' displayName\fR
