.TH leaftoppm
.PP
.RS
Convert an Interleaf image to a PPM image.
More information: \[la]https://netpbm.sourceforge.net/doc/leaftoppm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a PPM image file as output for an Interleaf image file as input:
.RE
.PP
\fB\fCleaftoppm {{path/to/file.pl}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCleaftoppm \-version\fR
