.TH less
.PP
.RS
Open a file for interactive reading, allowing scrolling and search.
More information: \[la]https://greenwoodsoftware.com/less/\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a file:
.RE
.PP
\fB\fCless {{source_file}}\fR
.RS
.IP \(bu 2
Page down/up:
.RE
.PP
\fB\fC<Space> (down), b (up)\fR
.RS
.IP \(bu 2
Go to end/start of file:
.RE
.PP
\fB\fCG (end), g (start)\fR
.RS
.IP \(bu 2
Forward search for a string (press \fB\fCn\fR/\fB\fCN\fR to go to next/previous match):
.RE
.PP
\fB\fC/{{something}}\fR
.RS
.IP \(bu 2
Backward search for a string (press \fB\fCn\fR/\fB\fCN\fR to go to next/previous match):
.RE
.PP
\fB\fC?{{something}}\fR
.RS
.IP \(bu 2
Follow the output of the currently opened file:
.RE
.PP
\fB\fCF\fR
.RS
.IP \(bu 2
Open the current file in an editor:
.RE
.PP
\fB\fCv\fR
.RS
.IP \(bu 2
Exit:
.RE
.PP
\fB\fCq\fR
