.TH light\-arionum\-cli
.PP
.RS
The PHP light wallet for the Arionum cryptocurrency.
More information: \[la]https://github.com/arionum/lightWalletCLI\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a new public/private key pair:
.RE
.PP
\fB\fClight\-arionum\-cli\fR
.RS
.IP \(bu 2
Display the balance of the current address:
.RE
.PP
\fB\fClight\-arionum\-cli balance\fR
.RS
.IP \(bu 2
Display the balance of the specified address:
.RE
.PP
\fB\fClight\-arionum\-cli balance {{address}}\fR
.RS
.IP \(bu 2
Send a transaction with an optional message:
.RE
.PP
\fB\fClight\-arionum\-cli send {{address}} {{value}} {{optional_message}}\fR
.RS
.IP \(bu 2
Export the current wallet information:
.RE
.PP
\fB\fClight\-arionum\-cli export\fR
.RS
.IP \(bu 2
Display information about the current block:
.RE
.PP
\fB\fClight\-arionum\-cli block\fR
.RS
.IP \(bu 2
Display information about the current address' transactions:
.RE
.PP
\fB\fClight\-arionum\-cli transactions\fR
.RS
.IP \(bu 2
Display information about a specific transaction:
.RE
.PP
\fB\fClight\-arionum\-cli transaction {{transaction_id}}\fR
