.TH lima
.PP
.RS
This command is an alias of \fB\fClimactl shell\fR for the default VM instance.
You can also set the \fB\fC$LIMA_INSTANCE\fR environment variable to work on a different instance.
More information: \[la]https://github.com/lima-vm/lima\[ra]\&.
.RE
.RS
.IP \(bu 2
View documentation for the original command:
.RE
.PP
\fB\fCtldr limactl\fR
