.TH link
.PP
.RS
Create a hard link to an existing file.
For more options, see the \fB\fCln\fR command.
More information: \[la]https://www.gnu.org/software/coreutils/link\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a hard link from a new file to an existing file:
.RE
.PP
\fB\fClink {{path/to/existing_file}} {{path/to/new_file}}\fR
