.TH linode\-cli account
.PP
.RS
Manage Linode accounts.
See also: \fB\fClinode\-cli\fR\&.
More information: \[la]https://www.linode.com/docs/products/tools/cli/guides/account/\[ra]\&.
.RE
.RS
.IP \(bu 2
View account:
.RE
.PP
\fB\fClinode\-cli account view\fR
.RS
.IP \(bu 2
View account settings:
.RE
.PP
\fB\fClinode\-cli account settings\fR
.RS
.IP \(bu 2
Make a payment:
.RE
.PP
\fB\fClinode\-cli account payment\-create \-\-cvv {{cvv}} \-\-usd {{amount_in_dollars}}\fR
.RS
.IP \(bu 2
View account notifications:
.RE
.PP
\fB\fClinode\-cli account notifications\-list\fR
