.TH linode\-cli events
.PP
.RS
Manage Linode events.
See also: \fB\fClinode\-cli\fR\&.
More information: \[la]https://www.linode.com/docs/products/tools/cli/guides/events/\[ra]\&.
.RE
.RS
.IP \(bu 2
View a list of events on your account:
.RE
.PP
\fB\fClinode\-cli events list\fR
.RS
.IP \(bu 2
View details about a specific event:
.RE
.PP
\fB\fClinode\-cli events view {{event_id}}\fR
.RS
.IP \(bu 2
Mark an event as read:
.RE
.PP
\fB\fClinode\-cli events mark\-read {{event_id}}\fR
