.TH linode\-cli
.PP
.RS
Manage Linode cloud services.
Some subcommands such as \fB\fCevents\fR have their own usage documentation.
More information: \[la]https://www.linode.com/docs/products/tools/cli/get-started/\[ra]\&.
.RE
.RS
.IP \(bu 2
List all Linodes:
.RE
.PP
\fB\fClinode\-cli linodes list\fR
.RS
.IP \(bu 2
View docmentation for managing Linode accounts:
.RE
.PP
\fB\fCtldr linode\-cli account\fR
.RS
.IP \(bu 2
View documentation for managing Linodes:
.RE
.PP
\fB\fCtldr linode\-cli linodes\fR
.RS
.IP \(bu 2
View documentation for managing Linode Kubernetes Engine (LKE) clusters:
.RE
.PP
\fB\fCtldr linode\-cli lke\fR
.RS
.IP \(bu 2
View documentation for managing NodeBalancers:
.RE
.PP
\fB\fCtldr linode\-cli nodebalancers\fR
.RS
.IP \(bu 2
View documentation for managing Object Storage:
.RE
.PP
\fB\fCtldr linode\-cli object\-storage\fR
.RS
.IP \(bu 2
View documentation for managing DNS domains:
.RE
.PP
\fB\fCtldr linode\-cli domains\fR
.RS
.IP \(bu 2
View documentation for managing Linode Volumes:
.RE
.PP
\fB\fCtldr linode\-cli volumes\fR
