.TH linode\-cli domains
.PP
.RS
Manage Linode Domains and DNS configuration.
See also: \fB\fClinode\-cli\fR\&.
More information: \[la]https://www.linode.com/docs/products/tools/cli/guides/domains/\[ra]\&.
.RE
.RS
.IP \(bu 2
List all managed domains:
.RE
.PP
\fB\fClinode\-cli domains list\fR
.RS
.IP \(bu 2
Create a new managed domain:
.RE
.PP
\fB\fClinode\-cli domains create \-\-domain {{domain_name}} \-\-type {{master|slave}} \-\-soa\-email {{email}}\fR
.RS
.IP \(bu 2
View details of a specific domain:
.RE
.PP
\fB\fClinode\-cli domains view {{domain_id}}\fR
.RS
.IP \(bu 2
Delete a managed domain:
.RE
.PP
\fB\fClinode\-cli domains delete {{domain_id}}\fR
.RS
.IP \(bu 2
List records for a specific domain:
.RE
.PP
\fB\fClinode\-cli domains records\-list {{domain_id}}\fR
.RS
.IP \(bu 2
Add a DNS record to a domain:
.RE
.PP
\fB\fClinode\-cli domains records\-create {{domain_id}} \-\-type {{A|AAAA|CNAME|MX|...}} \-\-name {{subdomain}} \-\-target {{target_value}}\fR
.RS
.IP \(bu 2
Update a DNS record for a domain:
.RE
.PP
\fB\fClinode\-cli domains records\-update {{domain_id}} {{record_id}} \-\-target {{new_target_value}}\fR
.RS
.IP \(bu 2
Delete a DNS record from a domain:
.RE
.PP
\fB\fClinode\-cli domains records\-delete {{domain_id}} {{record_id}}\fR
