.TH linode\-cli lke
.PP
.RS
Manage Linode Kubernetes Engine (LKE) clusters.
See also: \fB\fClinode\-cli\fR\&.
More information: \[la]https://www.linode.com/docs/products/tools/cli/guides/linode-kubernetes-engine/\[ra]\&.
.RE
.RS
.IP \(bu 2
List all LKE clusters:
.RE
.PP
\fB\fClinode\-cli lke clusters list\fR
.RS
.IP \(bu 2
Create a new LKE cluster:
.RE
.PP
\fB\fClinode\-cli lke clusters create \-\-region {{region}} \-\-type {{type}} \-\-node\-type {{node_type}} \-\-nodes\-count {{count}}\fR
.RS
.IP \(bu 2
View details of a specific LKE cluster:
.RE
.PP
\fB\fClinode\-cli lke clusters view {{cluster_id}}\fR
.RS
.IP \(bu 2
Update an existing LKE cluster:
.RE
.PP
\fB\fClinode\-cli lke clusters update {{cluster_id}} \-\-node\-type {{new_node_type}}\fR
.RS
.IP \(bu 2
Delete an LKE cluster:
.RE
.PP
\fB\fClinode\-cli lke clusters delete {{cluster_id}}\fR
