.TH llvd
.PP
.RS
Linkedin Learning Video Downloader.
More information: \[la]https://github.com/knowbee/llvd\[ra]\&.
.RE
.RS
.IP \(bu 2
Download a [c]ourse using cookie\-based authentication:
.RE
.PP
\fB\fCllvd \-c {{course\-slug}} \-\-cookies\fR
.RS
.IP \(bu 2
Download a course at a specific [r]esolution:
.RE
.PP
\fB\fCllvd \-c {{course\-slug}} \-r 720\fR
.RS
.IP \(bu 2
Download a course with [ca]ptions (subtitles):
.RE
.PP
\fB\fCllvd \-c {{course\-slug}} \-\-caption\fR
.RS
.IP \(bu 2
Download a course [p]ath with [t]hrottling between 10 to 30 seconds:
.RE
.PP
\fB\fCllvd \-p {{path\-slug}} \-t {{10,30}} \-\-cookies\fR
