.TH llvm\-cat
.PP
.RS
Concatenate LLVM Bitcode (\fB\fC\&.bc\fR) files.
More information: \[la]https://github.com/llvm/llvm-project/blob/main/llvm/tools/llvm-cat/llvm-cat.cpp\[ra]\&.
.RE
.RS
.IP \(bu 2
Concatenate Bitcode files:
.RE
.PP
\fB\fCllvm\-cat {{path/to/file1.bc}} {{path/to/file2.bc}} \-o {{path/to/out.bc}}\fR
