.TH lolcat
.PP
.RS
Put a rainbow in everything you \fB\fCcat\fR to the console.
More information: \[la]https://github.com/busyloop/lolcat\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a file to the console in rainbow colors:
.RE
.PP
\fB\fClolcat {{path/to/file}}\fR
.RS
.IP \(bu 2
Print the result of a text\-producing command in rainbow colors:
.RE
.PP
\fB\fC{{fortune}} | lolcat\fR
.RS
.IP \(bu 2
Print a file to the console with animated rainbow colors:
.RE
.PP
\fB\fClolcat \-a {{path/to/file}}\fR
.RS
.IP \(bu 2
Print a file to the console with 24\-bit (truecolor) rainbow colors:
.RE
.PP
\fB\fClolcat \-t {{path/to/file}}\fR
