.TH lorem
.PP
.RS
Create more or less random lorem ipsum text.
More information: \[la]https://manned.org/lorem\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the specified number of words:
.RE
.PP
\fB\fClorem \-n {{20}}\fR
.RS
.IP \(bu 2
Print 10 lines of Goethe's Faust:
.RE
.PP
\fB\fClorem \-l {{10}} \-\-faust\fR
.RS
.IP \(bu 2
Print 5 sentences of Poe's Raven:
.RE
.PP
\fB\fClorem \-s {{5}} \-\-raven\fR
.RS
.IP \(bu 2
Print 40 random characters from Boccaccio's Decameron:
.RE
.PP
\fB\fClorem \-\-randomize \-c {{40}} \-\-decamerone\fR
