.TH lpinfo
.PP
.RS
List connected printers and installed drivers for the CUPS print server.
More information: \[la]https://www.cups.org/doc/man-lpinfo.html\[ra]\&.
.RE
.RS
.IP \(bu 2
List all the currently connected printers:
.RE
.PP
\fB\fClpinfo \-v\fR
.RS
.IP \(bu 2
List all the currently installed printer drivers:
.RE
.PP
\fB\fClpinfo \-m\fR
.RS
.IP \(bu 2
Search installed printer drivers by make and model:
.RE
.PP
\fB\fClpinfo \-\-make\-and\-model "{{printer_model}}" \-m\fR
