.TH lpstat
.PP
.RS
Show status information about printers.
More information: \[la]https://manned.org/lpstat\[ra]\&.
.RE
.RS
.IP \(bu 2
List printers present on the machine and whether they are enabled for printing:
.RE
.PP
\fB\fClpstat \-p\fR
.RS
.IP \(bu 2
Show the default printer:
.RE
.PP
\fB\fClpstat \-d\fR
.RS
.IP \(bu 2
Display all available status information:
.RE
.PP
\fB\fClpstat \-t\fR
.RS
.IP \(bu 2
Show a list of print jobs queued by the specified user:
.RE
.PP
\fB\fClpstat \-u {{user}}\fR
