.TH ls
.PP
.RS
List directory contents.
More information: \[la]https://www.gnu.org/software/coreutils/ls\[ra]\&.
.RE
.RS
.IP \(bu 2
List files one per line:
.RE
.PP
\fB\fCls \-1\fR
.RS
.IP \(bu 2
List all files, including hidden files:
.RE
.PP
\fB\fCls \-a\fR
.RS
.IP \(bu 2
List all files, with trailing \fB\fC/\fR added to directory names:
.RE
.PP
\fB\fCls \-F\fR
.RS
.IP \(bu 2
Long format list (permissions, ownership, size, and modification date) of all files:
.RE
.PP
\fB\fCls \-la\fR
.RS
.IP \(bu 2
Long format list with size displayed using human\-readable units (KiB, MiB, GiB):
.RE
.PP
\fB\fCls \-lh\fR
.RS
.IP \(bu 2
Long format list sorted by size (descending):
.RE
.PP
\fB\fCls \-lS\fR
.RS
.IP \(bu 2
Long format list of all files, sorted by modification date (oldest first):
.RE
.PP
\fB\fCls \-ltr\fR
.RS
.IP \(bu 2
Only list directories:
.RE
.PP
\fB\fCls \-d */\fR
