.TH lspath
.PP
.RS
List the contents of the \fB\fCPATH\fR environment variable, with optional paging.
More information: \[la]https://github.com/clementi/lspath\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the contents of the system \fB\fCPATH\fR variable, with one element per line:
.RE
.PP
\fB\fClspath\fR
.RS
.IP \(bu 2
Print the current contents of the system \fB\fCPATH\fR variable, with one element per line, with the output paged:
.RE
.PP
\fB\fClspath \-\-page\fR
