.TH lua
.PP
.RS
A powerful, light\-weight embeddable programming language.
More information: \[la]https://www.lua.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive Lua shell:
.RE
.PP
\fB\fClua\fR
.RS
.IP \(bu 2
Execute a Lua script:
.RE
.PP
\fB\fClua {{path/to/script.lua}} {{\-\-optional\-argument}}\fR
.RS
.IP \(bu 2
Execute a Lua expression:
.RE
.PP
\fB\fClua \-e '{{print("Hello World")}}'\fR
