.TH luajit
.PP
.RS
A just\-in\-time compiler (JIT) for the Lua programming language.
See also: \fB\fClua\fR\&.
More information: \[la]https://luajit.org/luajit.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive Lua shell:
.RE
.PP
\fB\fCluajit\fR
.RS
.IP \(bu 2
Execute a Lua script:
.RE
.PP
\fB\fCluajit {{path/to/script.lua}} {{\-\-optional\-argument}}\fR
.RS
.IP \(bu 2
Execute a Lua expression:
.RE
.PP
\fB\fCluajit \-e '{{print("Hello World")}}'\fR
