.TH lumen
.PP
.RS
A command\-line installer for the Lumen micro\-framework.
More information: \[la]https://lumen.laravel.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Lumen application:
.RE
.PP
\fB\fClumen new {{application_name}}\fR
.RS
.IP \(bu 2
List the available installer commands:
.RE
.PP
\fB\fClumen list\fR
