.TH lynx
.PP
.RS
Command\-line web browser.
More information: \[la]https://lynx.browser.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Visit a website:
.RE
.PP
\fB\fClynx {{example.com}}\fR
.RS
.IP \(bu 2
Apply restrictions for anonymous account:
.RE
.PP
\fB\fClynx \-anonymous {{example.com}}\fR
.RS
.IP \(bu 2
Turn on mouse support, if available:
.RE
.PP
\fB\fClynx \-use_mouse {{example.com}}\fR
.RS
.IP \(bu 2
Force color mode on, if available:
.RE
.PP
\fB\fClynx \-color {{example.com}}\fR
.RS
.IP \(bu 2
Open a link, using a specific file to read and write cookies:
.RE
.PP
\fB\fClynx \-cookie_file={{path/to/file}} {{example.com}}\fR
.RS
.IP \(bu 2
Navigate forwards and backwards through the links on a page:
.RE
.PP
\fB\fCUp arrow key, Down arrow key\fR
.RS
.IP \(bu 2
Go back to the previously displayed page:
.RE
.PP
\fB\fCLeft arrow key or u\fR
.RS
.IP \(bu 2
Exit:
.RE
.PP
\fB\fCq then y\fR
