.TH m4
.PP
.RS
Macro processor.
More information: \[la]https://www.gnu.org/software/m4\[ra]\&.
.RE
.RS
.IP \(bu 2
Process macros in a file:
.RE
.PP
\fB\fCm4 {{path/to/file}}\fR
.RS
.IP \(bu 2
Define a macro before processing files:
.RE
.PP
\fB\fCm4 \-D{{macro_name}}={{macro_value}} {{path/to/file}}\fR
