.TH macchina
.PP
.RS
Display information about your computer.
More information: \[la]https://github.com/Macchina-CLI/macchina\[ra]\&.
.RE
.RS
.IP \(bu 2
List out system information, with either default settings or those specified in your configuration file:
.RE
.PP
\fB\fCmacchina\fR
.RS
.IP \(bu 2
Specify a custom configuration file path:
.RE
.PP
\fB\fCmacchina \-\-config {{path/to/configuration_file}}\fR
.RS
.IP \(bu 2
List system information, but lengthen uptime, shell and kernel output:
.RE
.PP
\fB\fCmacchina \-\-long\-uptime \-\-long\-shell \-\-long\-kernel\fR
.RS
.IP \(bu 2
Check for any errors/system failures encountered when trying to fetch system information:
.RE
.PP
\fB\fCmacchina \-\-doctor\fR
.RS
.IP \(bu 2
List original artists of all the ASCII art:
.RE
.PP
\fB\fCmacchina \-\-ascii\-artists\fR
