.TH makebuildserver
.PP
.RS
Create an F\-Droid build server virtual machine.
More information: \[la]https://f-droid.org/en/docs/Build_Server_Setup/\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new virtual machine or update an existing one (if available):
.RE
.PP
\fB\fCmakebuildserver\fR
.RS
.IP \(bu 2
Force creating a fresh virtual machine:
.RE
.PP
\fB\fCmakebuildserver \-\-clean\fR
