.TH mat2
.PP
.RS
Anonymise various file formats by removing metadata.
More information: \[la]https://0xacab.org/jvoisin/mat2\[ra]\&.
.RE
.RS
.IP \(bu 2
List supported file formats:
.RE
.PP
\fB\fCmat2 \-\-list\fR
.RS
.IP \(bu 2
Remove metadata from a file:
.RE
.PP
\fB\fCmat2 {{path/to/file}}\fR
.RS
.IP \(bu 2
Remove metadata from a file and print detailed output to the console:
.RE
.PP
\fB\fCmat2 \-\-verbose {{path/to/file}}\fR
.RS
.IP \(bu 2
Show metadata in a file without removing it:
.RE
.PP
\fB\fCmat2 \-\-show {{path/to/file}}\fR
.RS
.IP \(bu 2
Partially remove metadata from a file:
.RE
.PP
\fB\fCmat2 \-\-lightweight {{path/to/file}}\fR
