.TH mate\-dictionary
.PP
.RS
Look up words on dictionaries.
More information: \[la]https://manned.org/mate-dictionary\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a specific word definition:
.RE
.PP
\fB\fCmate\-dictionary \-\-no\-window \-\-look\-up '{{word}}'\fR
.RS
.IP \(bu 2
Show similar words for a specific one in a new window:
.RE
.PP
\fB\fCmate\-dictionary \-\-match '{{word}}'\fR
