.TH matlab
.PP
.RS
Numerical computation environment by MathWorks.
More information: \[la]https://uk.mathworks.com/help/matlab/\[ra]\&.
.RE
.RS
.IP \(bu 2
Run without splash screen during startup:
.RE
.PP
\fB\fCmatlab \-nosplash\fR
.RS
.IP \(bu 2
Execute a MATLAB statement:
.RE
.PP
\fB\fCmatlab \-r "{{matlab_statement}}"\fR
.RS
.IP \(bu 2
Run a MATLAB script:
.RE
.PP
\fB\fCmatlab \-r "run({{path/to/script.m}})"\fR
