.TH maza
.PP
.RS
Local ad blocker. Like Pi\-hole but local and using the operating system.
More information: \[la]https://github.com/tanrax/maza-ad-blocking\[ra]\&.
.RE
.RS
.IP \(bu 2
Update the Maza database:
.RE
.PP
\fB\fCmaza update\fR
.RS
.IP \(bu 2
Start Maza:
.RE
.PP
\fB\fCsudo maza start\fR
.RS
.IP \(bu 2
Stop Maza:
.RE
.PP
\fB\fCsudo maza stop\fR
.RS
.IP \(bu 2
Show the status of Maza:
.RE
.PP
\fB\fCmaza status\fR
