.TH md5sum
.PP
.RS
Calculate MD5 cryptographic checksums.
More information: \[la]https://www.gnu.org/software/coreutils/md5sum\[ra]\&.
.RE
.RS
.IP \(bu 2
Calculate the MD5 checksum for one or more files:
.RE
.PP
\fB\fCmd5sum {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Calculate and save the list of MD5 checksums to a file:
.RE
.PP
\fB\fCmd5sum {{path/to/file1 path/to/file2 ...}} > {{path/to/file.md5}}\fR
.RS
.IP \(bu 2
Calculate an MD5 checksum from \fB\fCstdin\fR:
.RE
.PP
\fB\fC{{command}} | md5sum\fR
.RS
.IP \(bu 2
Read a file of MD5 sums and filenames and verify all files have matching checksums:
.RE
.PP
\fB\fCmd5sum \-\-check {{path/to/file.md5}}\fR
.RS
.IP \(bu 2
Only show a message for missing files or when verification fails:
.RE
.PP
\fB\fCmd5sum \-\-check \-\-quiet {{path/to/file.md5}}\fR
.RS
.IP \(bu 2
Only show a message when verification fails, ignoring missing files:
.RE
.PP
\fB\fCmd5sum \-\-ignore\-missing \-\-check \-\-quiet {{path/to/file.md5}}\fR
