.TH mdp
.PP
.RS
A command\-line based tool to make presentations from Markdown files.
More information: \[la]https://github.com/visit1985/mdp\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch a presentation in the terminal from a Markdown file:
.RE
.PP
\fB\fCmdp {{presentation.md}}\fR
.RS
.IP \(bu 2
Disable fading transitions:
.RE
.PP
\fB\fCmdp \-\-nofade {{presentation.md}}\fR
.RS
.IP \(bu 2
Invert font colors to use in terminals with light background:
.RE
.PP
\fB\fCmdp \-\-invert {{presentation.md}}\fR
.RS
.IP \(bu 2
Disable transparency in transparent terminals:
.RE
.PP
\fB\fCmdp \-\-notrans {{presentation.md}}\fR
