.TH mesg
.PP
.RS
Check or set a terminal's ability to receive messages from other users, usually from the write command.
See also \fB\fCwrite\fR\&.
More information: \[la]https://manned.org/mesg\[ra]\&.
.RE
.RS
.IP \(bu 2
Check terminal's openness to write messages:
.RE
.PP
\fB\fCmesg\fR
.RS
.IP \(bu 2
Disable receiving messages from the write command:
.RE
.PP
\fB\fCmesg n\fR
.RS
.IP \(bu 2
Enable receiving messages from the write command:
.RE
.PP
\fB\fCmesg y\fR
