.TH meteor
.PP
.RS
Full\-stack JavaScript platform for building web applications.
More information: \[la]https://meteor.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a meteor project from its root directory in development mode:
.RE
.PP
\fB\fCmeteor\fR
.RS
.IP \(bu 2
Create a project under the given directory:
.RE
.PP
\fB\fCmeteor create {{path/to/directory}}\fR
.RS
.IP \(bu 2
Display the list of packages the project is currently using:
.RE
.PP
\fB\fCmeteor list\fR
.RS
.IP \(bu 2
Add a package to the project:
.RE
.PP
\fB\fCmeteor add {{package}}\fR
.RS
.IP \(bu 2
Remove a package from the project:
.RE
.PP
\fB\fCmeteor remove {{package}}\fR
.RS
.IP \(bu 2
Create a production build of the project as a tarball under the given directory:
.RE
.PP
\fB\fCmeteor build {{path/to/directory}}\fR
