.TH mh_lint
.PP
.RS
Attempt to find bugs in MATLAB or Octave code.
Please note that this tool is neither sound nor complete.
More information: \[la]https://misshit.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Check the current directory:
.RE
.PP
\fB\fCmh_lint\fR
.RS
.IP \(bu 2
Check a specific directory recursively:
.RE
.PP
\fB\fCmh_lint {{path/to/directory}}\fR
.RS
.IP \(bu 2
Check a MATLAB file:
.RE
.PP
\fB\fCmh_lint {{path/to/file.m}}\fR
.RS
.IP \(bu 2
Check an Octave file:
.RE
.PP
\fB\fCmh_lint \-\-octave {{path/to/file.m}}\fR
