.TH minetest
.PP
.RS
Multiplayer infinite\-world block sandbox.
See also \fB\fCminetestserver\fR, the server\-only binary.
More information: \[la]https://wiki.minetest.net/Minetest\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Minetest in client mode:
.RE
.PP
\fB\fCminetest\fR
.RS
.IP \(bu 2
Start Minetest in server mode by hosting a specific world:
.RE
.PP
\fB\fCminetest \-\-server \-\-world {{name}}\fR
.RS
.IP \(bu 2
Write logs to a specific file:
.RE
.PP
\fB\fCminetest \-\-logfile {{path/to/file}}\fR
.RS
.IP \(bu 2
Only write errors to the console:
.RE
.PP
\fB\fCminetest \-\-quiet\fR
