.TH mix
.PP
.RS
Mix is a build tool that provides tasks for creating, compiling, and testing Elixir projects, managing its dependencies, and more.
More information: \[la]https://hexdocs.pm/mix\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute a particular file:
.RE
.PP
\fB\fCmix run {{my_script.exs}}\fR
.RS
.IP \(bu 2
Create a new project:
.RE
.PP
\fB\fCmix new {{project_name}}\fR
.RS
.IP \(bu 2
Compile project:
.RE
.PP
\fB\fCmix compile\fR
.RS
.IP \(bu 2
Run project tests:
.RE
.PP
\fB\fCmix test\fR
.RS
.IP \(bu 2
List all mix commands:
.RE
.PP
\fB\fCmix help\fR
