.TH mkdir
.PP
.RS
Create directories and set their permissions.
More information: \[la]https://www.gnu.org/software/coreutils/mkdir\[ra]\&.
.RE
.RS
.IP \(bu 2
Create specific directories:
.RE
.PP
\fB\fCmkdir {{path/to/directory1 path/to/directory2 ...}}\fR
.RS
.IP \(bu 2
Create specific directories and their [p]arents if needed:
.RE
.PP
\fB\fCmkdir \-p {{path/to/directory1 path/to/directory2 ...}}\fR
.RS
.IP \(bu 2
Create directories with specific permissions:
.RE
.PP
\fB\fCmkdir \-m {{rwxrw\-r\-\-}} {{path/to/directory1 path/to/directory2 ...}}\fR
