.TH mkdocs
.PP
.RS
Project documentation with Markdown.
More information: \[la]https://www.mkdocs.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new mkdocs project:
.RE
.PP
\fB\fCmkdocs new {{project_name}}\fR
.RS
.IP \(bu 2
Serve the project in the current directory using the mkdocs dev\-server:
.RE
.PP
\fB\fCmkdocs serve\fR
.RS
.IP \(bu 2
Build the documentation in the current directory:
.RE
.PP
\fB\fCmkdocs build\fR
.RS
.IP \(bu 2
Deploy the documentation in the current directory to GitHub pages:
.RE
.PP
\fB\fCmkdocs gh\-deploy\fR
