.TH moe
.PP
.RS
A WYSIWYG text editor for ISO\-8859\-15 encoded text.
More information: \[la]https://www.gnu.org/software/moe/moe.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Open moe and create a backup file (file~) when saving edits:
.RE
.PP
\fB\fCmoe {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a file as read\-only:
.RE
.PP
\fB\fCmoe \-\-read\-only {{path/to/file}}\fR
.RS
.IP \(bu 2
Edit a file without creating backups:
.RE
.PP
\fB\fCmoe \-\-no\-backup {{path/to/file}}\fR
.RS
.IP \(bu 2
Edit a file ignoring case in searches:
.RE
.PP
\fB\fCmoe \-\-ignore\-case {{path/to/file}}\fR
.RS
.IP \(bu 2
Save and Quit:
.RE
.PP
\fB\fCCtrl + X\fR
