.TH mongoimport
.PP
.RS
Imports content from a JSON, CSV, or TSV file into a MongoDB database.
More information: \[la]https://docs.mongodb.com/database-tools/mongoimport/\[ra]\&.
.RE
.RS
.IP \(bu 2
Import a JSON file into a specific collection:
.RE
.PP
\fB\fCmongoimport \-\-file={{path/to/file.json}} \-\-uri={{mongodb_uri}} \-\-collection={{collection_name}}\fR
.RS
.IP \(bu 2
Import a CSV file, using the first line of the file to determine field names:
.RE
.PP
\fB\fCmongoimport \-\-type={{csv}} \-\-file={{path/to/file.csv}} \-\-db={{database_name}} \-\-collection={{collection_name}}\fR
.RS
.IP \(bu 2
Import a JSON array, using each element as a separate document:
.RE
.PP
\fB\fCmongoimport \-\-jsonArray \-\-file={{path/to/file.json}}\fR
.RS
.IP \(bu 2
Import a JSON file using a specific mode and a query to match existing documents:
.RE
.PP
\fB\fCmongoimport \-\-file={{path/to/file.json}} \-\-mode={{delete|merge|upsert}} \-\-upsertFields="{{field1,field2,...}}"\fR
.RS
.IP \(bu 2
Import a CSV file, reading field names from a separate CSV file and ignoring fields with empty values:
.RE
.PP
\fB\fCmongoimport \-\-type={{csv}} \-\-file={{path/to/file.csv}} \-\-fieldFile={{path/to/field_file.csv}} \-\-ignoreBlanks\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCmongoimport \-\-help\fR
