.TH more
.PP
.RS
Open a file for interactive reading, allowing scrolling and search.
More information: \[la]https://manned.org/more\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a file:
.RE
.PP
\fB\fCmore {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a file displaying from a specific line:
.RE
.PP
\fB\fCmore +{{line_number}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCmore \-\-help\fR
.RS
.IP \(bu 2
Go to the next page:
.RE
.PP
\fB\fC<Space>\fR
.RS
.IP \(bu 2
Search for a string (press \fB\fCn\fR to go to the next match):
.RE
.PP
\fB\fC/{{something}}\fR
.RS
.IP \(bu 2
Exit:
.RE
.PP
\fB\fCq\fR
.RS
.IP \(bu 2
Display help about interactive commands:
.RE
.PP
\fB\fCh\fR
