.TH mozillavpn
.PP
.RS
A Virtual Private Network from the makers of Firefox.
More information: \[la]https://github.com/mozilla-mobile/mozilla-vpn-client/wiki/Command-line-interface\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in with an interactive prompt:
.RE
.PP
\fB\fCmozillavpn login\fR
.RS
.IP \(bu 2
Connect to Mozilla VPN:
.RE
.PP
\fB\fCmozillavpn activate\fR
.RS
.IP \(bu 2
Display the connection status:
.RE
.PP
\fB\fCmozillavpn status\fR
.RS
.IP \(bu 2
List available servers:
.RE
.PP
\fB\fCmozillavpn servers\fR
.RS
.IP \(bu 2
Select a specific server:
.RE
.PP
\fB\fCmozillavpn select {{server_name}}\fR
.RS
.IP \(bu 2
Disconnect from Mozilla VPN:
.RE
.PP
\fB\fCmozillavpn deactivate\fR
.RS
.IP \(bu 2
Log out:
.RE
.PP
\fB\fCmozillavpn logout\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCmozillavpn {{subcommand}} \-\-help\fR
