.TH mpc
.PP
.RS
Music Player Client.
Program for controlling the Music Player Daemon (MPD).
More information: \[la]https://www.musicpd.org/clients/mpc\[ra]\&.
.RE
.RS
.IP \(bu 2
Toggle play/pause:
.RE
.PP
\fB\fCmpc toggle\fR
.RS
.IP \(bu 2
Stop playing:
.RE
.PP
\fB\fCmpc stop\fR
.RS
.IP \(bu 2
Show information about the currently playing song:
.RE
.PP
\fB\fCmpc status\fR
.RS
.IP \(bu 2
Play next song:
.RE
.PP
\fB\fCmpc next\fR
.RS
.IP \(bu 2
Play previous song:
.RE
.PP
\fB\fCmpc prev\fR
.RS
.IP \(bu 2
Forward or rewind the currently playing song:
.RE
.PP
\fB\fCmpc [+\-]{{seconds}}\fR
