.TH mpd
.PP
.RS
Music Player Daemon.
More information: \[la]https://www.musicpd.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start MPD:
.RE
.PP
\fB\fCmpd\fR
.RS
.IP \(bu 2
Start MPD but don't read from the configuration file:
.RE
.PP
\fB\fCmpd \-\-no\-config\fR
.RS
.IP \(bu 2
Start MPD and don't detach it from the console:
.RE
.PP
\fB\fCmpd \-\-no\-daemon\fR
.RS
.IP \(bu 2
Kill the currently running MPD session:
.RE
.PP
\fB\fCmpd \-\-kill\fR
