.TH mplayer
.PP
.RS
Cross\-platform multimedia player.
More information: \[la]https://mplayerhq.hu/DOCS/HTML/en/commandline.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Play the specified file or URL:
.RE
.PP
\fB\fCmplayer {{path/to/file|url}}\fR
.RS
.IP \(bu 2
Play multiple files:
.RE
.PP
\fB\fCmplayer {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Play a specific file repeatedly:
.RE
.PP
\fB\fCmplayer \-loop {{0}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Pause playback:
.RE
.PP
\fB\fC<Space>\fR
.RS
.IP \(bu 2
Quit mplayer:
.RE
.PP
\fB\fC<Escape>\fR
.RS
.IP \(bu 2
Seek backward or forward 10 seconds:
.RE
.PP
\fB\fC<Left> or <Right>\fR
