.TH mr
.PP
.RS
Manage all of your version control repositories at once.
More information: \[la]https://myrepos.branchable.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Register a repository:
.RE
.PP
\fB\fCmr register\fR
.RS
.IP \(bu 2
Update repositories in 5 concurrent jobs:
.RE
.PP
\fB\fCmr \-j{{5}} update\fR
.RS
.IP \(bu 2
Print the status of all repositories:
.RE
.PP
\fB\fCmr status\fR
.RS
.IP \(bu 2
Checkout all repositories to the latest version:
.RE
.PP
\fB\fCmr checkout\fR
