.TH mullvad
.PP
.RS
CLI client for Mullvad VPN.
More information: \[la]https://mullvad.net/\[ra]\&.
.RE
.RS
.IP \(bu 2
Link your mullvad account with the specified account number:
.RE
.PP
\fB\fCmullvad account set {{account_number}}\fR
.RS
.IP \(bu 2
Enable LAN access while VPN is on:
.RE
.PP
\fB\fCmullvad lan set allow\fR
.RS
.IP \(bu 2
Establish the VPN tunnel:
.RE
.PP
\fB\fCmullvad connect\fR
.RS
.IP \(bu 2
Check status of VPN tunnel:
.RE
.PP
\fB\fCmullvad status\fR
