.TH mumble
.PP
.RS
Low\-latency, high quality voice chat software.
More information: \[la]https://www.mumble.info\[ra]\&.
.RE
.RS
.IP \(bu 2
Open Mumble:
.RE
.PP
\fB\fCmumble\fR
.RS
.IP \(bu 2
Open Mumble and immediately connect to a server:
.RE
.PP
\fB\fCmumble mumble://{{username}}@{{example.com}}\fR
.RS
.IP \(bu 2
Open Mumble and immediately connect to a password protected server:
.RE
.PP
\fB\fCmumble mumble://{{username}}:{{password}}@{{example.com}}\fR
.RS
.IP \(bu 2
Mute/unmute the microphone in a running Mumble instance:
.RE
.PP
\fB\fCmumble rpc {{mute|unmute}}\fR
.RS
.IP \(bu 2
Mute/unmute the microphone and the audio output of Mumble:
.RE
.PP
\fB\fCmumble rpc {{deaf|undeaf}}\fR
