.TH musl\-gcc
.PP
.RS
A wrapper around \fB\fCgcc\fR that automatically sets options for linking against musl libc.
All options specified are passed directly to \fB\fCgcc\fR\&.
More information: \[la]https://manned.org/musl-gcc\[ra]\&.
.RE
.RS
.IP \(bu 2
View documentation for \fB\fCgcc\fR:
.RE
.PP
\fB\fCtldr gcc\fR
