.TH mutool
.PP
.RS
Convert PDF files, query information and extract data.
More information: \[la]https://mupdf.readthedocs.io/en/latest/mupdf-command-line.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert pages 1\-10 into 10 PNGs (Note: \fB\fC%nd\fR in the output placeholder must be replaced with a print modifier like \fB\fC%d\fR or \fB\fC%2d\fR):
.RE
.PP
\fB\fCmutool convert \-o {{path/to/output%nd.png}} {{path/to/input.pdf}} {{1\-10}}\fR
.RS
.IP \(bu 2
Convert pages 2, 3 and 5 of a PDF into text in \fB\fCstdout\fR:
.RE
.PP
\fB\fCmutool draw \-F {{txt}} {{path/to/input.pdf}} {{2,3,5}}\fR
.RS
.IP \(bu 2
Concatenate multiple PDF files:
.RE
.PP
\fB\fCmutool merge \-o {{path/to/output.pdf}} {{path/to/input1.pdf path/to/input2.pdf ...}}\fR
.RS
.IP \(bu 2
Query information about all content embedded in a PDF:
.RE
.PP
\fB\fCmutool info {{path/to/input.pdf}}\fR
.RS
.IP \(bu 2
Extract all images, fonts and resources embedded in a PDF out into the current directory:
.RE
.PP
\fB\fCmutool extract {{path/to/input.pdf}}\fR
.RS
.IP \(bu 2
Print the outline (table of contents) of a PDF:
.RE
.PP
\fB\fCmutool show {{path/to/input.pdf}} outline\fR
