.TH n
.PP
.RS
Tool to manage multiple node versions.
More information: \[la]https://github.com/tj/n\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a given version of node. If the version is already installed, it will be activated:
.RE
.PP
\fB\fCn {{version}}\fR
.RS
.IP \(bu 2
Display installed versions and interactively activate one of them:
.RE
.PP
\fB\fCn\fR
.RS
.IP \(bu 2
Remove a version:
.RE
.PP
\fB\fCn rm {{version}}\fR
.RS
.IP \(bu 2
Execute a file with a given version:
.RE
.PP
\fB\fCn use {{version}} {{file.js}}\fR
.RS
.IP \(bu 2
Output binary path for a version:
.RE
.PP
\fB\fCn bin {{version}}\fR
