.TH nativefier
.PP
.RS
Command\-line tool to create a desktop app for any web site with minimal configuration.
More information: \[la]https://github.com/jiahaog/nativefier\[ra]\&.
.RE
.RS
.IP \(bu 2
Make a desktop app for a website:
.RE
.PP
\fB\fCnativefier {{url}}\fR
.RS
.IP \(bu 2
Create a desktop app with a custom name:
.RE
.PP
\fB\fCnativefier \-\-name {{name}} {{url}}\fR
.RS
.IP \(bu 2
Use a custom icon, should be a PNG:
.RE
.PP
\fB\fCnativefier \-\-icon {{path/to/icon.png}} {{url}}\fR
