.TH ncmpcpp
.PP
.RS
A command\-line music player client for the Music Player Daemon.
More information: \[la]https://rybczak.net/ncmpcpp\[ra]\&.
.RE
.RS
.IP \(bu 2
Connect to a music player daemon on a given host and port:
.RE
.PP
\fB\fCncmpcpp \-\-host {{ip}} \-\-port {{port}}\fR
.RS
.IP \(bu 2
Display metadata of the current song to console:
.RE
.PP
\fB\fCncmpcpp \-\-current\-song\fR
.RS
.IP \(bu 2
Use a specified configuration file:
.RE
.PP
\fB\fCncmpcpp \-\-config {{file}}\fR
.RS
.IP \(bu 2
Use a different set of key bindings from a file:
.RE
.PP
\fB\fCncmpcpp \-\-bindings {{file}}\fR
