.TH neomutt
.PP
.RS
NeoMutt command\-line email client.
More information: \[la]https://neomutt.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the specified mailbox:
.RE
.PP
\fB\fCneomutt \-f {{path/to/mailbox}}\fR
.RS
.IP \(bu 2
Start writing an email and specify a subject and a \fB\fCcc\fR recipient:
.RE
.PP
\fB\fCneomutt \-s "{{subject}}" \-c {{cc@example.com}} {{recipient@example.com}}\fR
.RS
.IP \(bu 2
Send an email with files attached:
.RE
.PP
\fB\fCneomutt \-a {{path/to/file1 path/to/file2 ...}} \-\- {{recipient@example.com}}\fR
.RS
.IP \(bu 2
Specify a file to include as the message body:
.RE
.PP
\fB\fCneomutt \-i {{path/to/file}} {{recipient@example.com}}\fR
.RS
.IP \(bu 2
Specify a draft file containing the header and the body of the message, in RFC 5322 format:
.RE
.PP
\fB\fCneomutt \-H {{path/to/file}} {{recipient@example.com}}\fR
