.TH neotoppm
.PP
.RS
Convert an Atari Neochrome NEO file into a PPM image.
More information: \[la]https://netpbm.sourceforge.net/doc/neotoppm.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate the PPM image as output for an Atari Neochrome NEO file as input:
.RE
.PP
\fB\fCneotoppm {{path/to/file.neo}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCneotoppm \-version\fR
