.TH nest
.PP
.RS
Command\-line tool to initialize, develop, and maintain Nest applications.
More information: \[la]https://docs.nestjs.com/cli/overview\[ra]\&.
.RE
.RS
.IP \(bu 2
Display information about installed nest version:
.RE
.PP
\fB\fCnest info\fR
.RS
.IP \(bu 2
Create a new NestJS project in a directory of the same name:
.RE
.PP
\fB\fCnest new {{project_name}}\fR
.RS
.IP \(bu 2
Build a specific NestJS project:
.RE
.PP
\fB\fCnest build {{project_name}}\fR
.RS
.IP \(bu 2
Run a specific NestJS project:
.RE
.PP
\fB\fCnest start {{project_name}}\fR
.RS
.IP \(bu 2
Import a library into the current NestJS project:
.RE
.PP
\fB\fCnest add {{library_name}}\fR
