.TH netlify
.PP
.RS
Deploy sites and configure continuous deployment to the Netlify platform.
More information: \[la]https://cli.netlify.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in to the Netlify account:
.RE
.PP
\fB\fCnetlify login\fR
.RS
.IP \(bu 2
Deploy the contents of a directory to Netlify:
.RE
.PP
\fB\fCnetlify deploy\fR
.RS
.IP \(bu 2
Configure continuous deployment for a new or an existing site:
.RE
.PP
\fB\fCnetlify init\fR
.RS
.IP \(bu 2
Start a local dev server:
.RE
.PP
\fB\fCnetlify dev\fR
