.TH next
.PP
.RS
React framework that uses server\-side rendering for building optimized web applications.
More information: \[la]https://nextjs.org/docs\[ra]\&.
.RE
.RS
.IP \(bu 2
Start the current application in development mode:
.RE
.PP
\fB\fCnext dev\fR
.RS
.IP \(bu 2
Start the current application and listen on a specific port:
.RE
.PP
\fB\fCnext dev \-\-port {{port}}\fR
.RS
.IP \(bu 2
Build the current application optimized for production:
.RE
.PP
\fB\fCnext build\fR
.RS
.IP \(bu 2
Start the compiled application in production mode:
.RE
.PP
\fB\fCnext start\fR
.RS
.IP \(bu 2
Start the compiled application and listen on a specific port:
.RE
.PP
\fB\fCnext start \-\-port {{port}}\fR
.RS
.IP \(bu 2
Export the current application to static HTML pages:
.RE
.PP
\fB\fCnext export\fR
.RS
.IP \(bu 2
Display the Next.js telemetry status:
.RE
.PP
\fB\fCnext telemetry\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCnext {{build|dev|export|start|telemetry}} \-\-help\fR
