.TH nf\-core
.PP
.RS
The nf\-core framework tools, to create, check and develop best\-practice guidelines for Nextflow.
More information: \[la]https://nf-co.re/tools\[ra]\&.
.RE
.RS
.IP \(bu 2
List existing pipelines on nf\-core:
.RE
.PP
\fB\fCnf\-core list\fR
.RS
.IP \(bu 2
Create a new pipeline skeleton:
.RE
.PP
\fB\fCnf\-core create\fR
.RS
.IP \(bu 2
Lint the pipeline code:
.RE
.PP
\fB\fCnf\-core lint {{path/to/directory}}\fR
.RS
.IP \(bu 2
Bump software versions in pipeline recipe:
.RE
.PP
\fB\fCnf\-core bump\-version {{path/to/directory}} {{new_version}}\fR
.RS
.IP \(bu 2
Launch an nf\-core pipeline:
.RE
.PP
\fB\fCnf\-core launch {{pipeline_name}}\fR
.RS
.IP \(bu 2
Download an nf\-core pipeline for offline use:
.RE
.PP
\fB\fCnf\-core download {{pipeline_name}}\fR
