.TH ng
.PP
.RS
Create and manage Angular applications.
More information: \[la]https://angular.io/cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Angular application inside a directory:
.RE
.PP
\fB\fCng new {{project_name}}\fR
.RS
.IP \(bu 2
Add a new component to one's application:
.RE
.PP
\fB\fCng generate component {{component_name}}\fR
.RS
.IP \(bu 2
Add a new class to one's application:
.RE
.PP
\fB\fCng generate class {{class_name}}\fR
.RS
.IP \(bu 2
Add a new directive to one's application:
.RE
.PP
\fB\fCng generate directive {{directive_name}}\fR
.RS
.IP \(bu 2
Run the application with the following command in its root directory:
.RE
.PP
\fB\fCng serve\fR
.RS
.IP \(bu 2
Build the application:
.RE
.PP
\fB\fCng build\fR
.RS
.IP \(bu 2
Run unit tests:
.RE
.PP
\fB\fCng test\fR
.RS
.IP \(bu 2
Check the version of your current Angular installation:
.RE
.PP
\fB\fCng version\fR
