.TH ngs
.PP
.RS
Scripting language created specifically for Ops.
More information: \[la]https://github.com/ngs-lang/ngs\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute a code snippet:
.RE
.PP
\fB\fCngs \-e "{{echo('ngs is executed')}}"\fR
.RS
.IP \(bu 2
Execute a script:
.RE
.PP
\fB\fCngs {{path/to/script.ngs}}\fR
.RS
.IP \(bu 2
Print the version:
.RE
.PP
\fB\fCngs \-\-version\fR
