.TH nice
.PP
.RS
Execute a program with a custom scheduling priority (niceness).
Niceness values range from \-20 (the highest priority) to 19 (the lowest).
More information: \[la]https://www.gnu.org/software/coreutils/nice\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch a program with altered priority:
.RE
.PP
\fB\fCnice \-n {{niceness_value}} {{command}}\fR
