.TH nimble
.PP
.RS
Package manager for the Nim programming language.
Manage Nim projects and their dependencies.
More information: \[la]https://github.com/nim-lang/nimble\[ra]\&.
.RE
.RS
.IP \(bu 2
Search for packages:
.RE
.PP
\fB\fCnimble search {{search_string}}\fR
.RS
.IP \(bu 2
Install a package:
.RE
.PP
\fB\fCnimble install {{package}}\fR
.RS
.IP \(bu 2
List installed packages:
.RE
.PP
\fB\fCnimble list \-i\fR
.RS
.IP \(bu 2
Create a new Nimble package in the current directory:
.RE
.PP
\fB\fCnimble init\fR
.RS
.IP \(bu 2
Build a Nimble package:
.RE
.PP
\fB\fCnimble build\fR
.RS
.IP \(bu 2
Install a Nimble package:
.RE
.PP
\fB\fCnimble install\fR
