.TH nload
.PP
.RS
A tool for visualizing network usage in the terminal.
More information: \[la]https://github.com/rolandriegel/nload\[ra]\&.
.RE
.RS
.IP \(bu 2
View all network traffic (use the arrow keys to switch interfaces):
.RE
.PP
\fB\fCnload\fR
.RS
.IP \(bu 2
View network traffic on specific interfaces (use the arrow keys to switch interfaces):
.RE
.PP
\fB\fCnload device {{interface_one}} {{interface_two}}\fR
