.TH nmblookup
.PP
.RS
Discover SMB shares.
More information: \[la]https://www.samba.org/samba/docs/current/man-html/nmblookup.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Find hosts in the local network with SMB shares:
.RE
.PP
\fB\fCnmblookup \-S '*'\fR
.RS
.IP \(bu 2
Find hosts in the local network with SMB shares run by SAMBA:
.RE
.PP
\fB\fCnmblookup \-\-status __SAMBA__\fR
