.TH nodenv
.PP
.RS
A tool to manage Node.js versions.
More information: \[la]https://github.com/nodenv/nodenv\[ra]\&.
.RE
.RS
.IP \(bu 2
Install a specific version of Node.js:
.RE
.PP
\fB\fCnodenv install {{version}}\fR
.RS
.IP \(bu 2
Display a list of available versions:
.RE
.PP
\fB\fCnodenv install \-\-list\fR
.RS
.IP \(bu 2
Use a specific version of Node.js across the whole system:
.RE
.PP
\fB\fCnodenv global {{version}}\fR
.RS
.IP \(bu 2
Use a specific version of Node.js with a directory:
.RE
.PP
\fB\fCnodenv local {{version}}\fR
.RS
.IP \(bu 2
Display the Node.js version for the current directory:
.RE
.PP
\fB\fCnodenv version\fR
.RS
.IP \(bu 2
Display the location of a Node.js installed command (e.g. \fB\fCnpm\fR):
.RE
.PP
\fB\fCnodenv which {{command}}\fR
