.TH now
.PP
.RS
Cloud platform for serverless deployment.
This command is deprecated. See \fB\fCvercel\fR, the updated version of this tool.
More information: \[la]https://zeit.co/now\[ra]\&.
.RE
.RS
.IP \(bu 2
Deploy the current directory:
.RE
.PP
\fB\fCnow\fR
.RS
.IP \(bu 2
Display a list of deployments:
.RE
.PP
\fB\fCnow list\fR
.RS
.IP \(bu 2
Display information related to a deployment:
.RE
.PP
\fB\fCnow inspect {{deployment_url}}\fR
.RS
.IP \(bu 2
Remove a deployment:
.RE
.PP
\fB\fCnow remove {{deployment_id}}\fR
.RS
.IP \(bu 2
Log in into an account or create a new one:
.RE
.PP
\fB\fCnow login\fR
.RS
.IP \(bu 2
Initialize an example project (a new directory will be created):
.RE
.PP
\fB\fCnow init\fR
