.TH npm fund
.PP
.RS
Retrieve funding information from packages.
More information: \[la]https://docs.npmjs.com/cli/v8/commands/npm-fund\[ra]\&.
.RE
.RS
.IP \(bu 2
List dependencies with funding URL for the project in the current directory:
.RE
.PP
\fB\fCnpm fund\fR
.RS
.IP \(bu 2
Open the funding URL for a specific package in the default web browser:
.RE
.PP
\fB\fCnpm fund {{package}}\fR
.RS
.IP \(bu 2
List dependencies with a funding URL for a specific [w]orkspace for the project in the current directory:
.RE
.PP
\fB\fCnpm fund \-w {{workspace}}\fR
