.TH npm\-name
.PP
.RS
Check whether a package or organization name is available on npm.
More information: \[la]https://github.com/sindresorhus/npm-name-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Check if a specific package name is available in the npm registry:
.RE
.PP
\fB\fCnpm\-name {{package}}\fR
.RS
.IP \(bu 2
Find similar package names in the npm registry:
.RE
.PP
\fB\fCnpm\-name \-\-similar {{package}}\fR
