.TH npm\-home
.PP
.RS
Open the npm page, Yarn page, or GitHub repository of a package in the web browser.
More information: \[la]https://github.com/sindresorhus/npm-home\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the npm page of a specific package in the web browser:
.RE
.PP
\fB\fCnpm\-home {{package}}\fR
.RS
.IP \(bu 2
Open the GitHub repository of a specific package in the web browser:
.RE
.PP
\fB\fCnpm\-home \-g {{package}}\fR
.RS
.IP \(bu 2
Open the Yarn page of a specific package in the web browser:
.RE
.PP
\fB\fCnpm\-home \-y {{package}}\fR
