.TH npm\-check
.PP
.RS
Check for outdated, incorrect, and unused npm package dependencies.
More information: \[la]https://github.com/dylang/npm-check\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a report of outdated, incorrect, and unused dependencies:
.RE
.PP
\fB\fCnpm\-check\fR
.RS
.IP \(bu 2
Interactively update out\-of\-date packages:
.RE
.PP
\fB\fCnpm\-check \-\-update\fR
.RS
.IP \(bu 2
Update everything without prompting:
.RE
.PP
\fB\fCnpm\-check \-\-update\-all\fR
.RS
.IP \(bu 2
Don't check for unused packages:
.RE
.PP
\fB\fCnpm\-check \-\-skip\-unused\fR
