.TH nproc
.PP
.RS
Print the number of processing units (normally CPUs) available.
More information: \[la]https://www.gnu.org/software/coreutils/nproc\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the number of available processing units:
.RE
.PP
\fB\fCnproc\fR
.RS
.IP \(bu 2
Display the number of installed processing units, including any inactive ones:
.RE
.PP
\fB\fCnproc \-\-all\fR
.RS
.IP \(bu 2
If possible, subtract a given number of units from the returned value:
.RE
.PP
\fB\fCnproc \-\-ignore {{count}}\fR
