.TH nrm
.PP
.RS
npm registry manager.
Helps to easily switch between different npm registries.
More information: \[la]https://github.com/Pana/nrm\[ra]\&.
.RE
.RS
.IP \(bu 2
List all registries:
.RE
.PP
\fB\fCnrm ls\fR
.RS
.IP \(bu 2
Change to a particular registry:
.RE
.PP
\fB\fCnrm use {{registry}}\fR
.RS
.IP \(bu 2
Show the response time for all registries:
.RE
.PP
\fB\fCnrm test\fR
.RS
.IP \(bu 2
Add a custom registry:
.RE
.PP
\fB\fCnrm add {{registry}} {{url}}\fR
.RS
.IP \(bu 2
Delete a registry:
.RE
.PP
\fB\fCnrm del {{registry}}\fR
