.TH nth
.PP
.RS
Name That Hash \- Instantly name the type of any hash.
More information: \[la]https://github.com/hashpals/name-that-hash\[ra]\&.
.RE
.RS
.IP \(bu 2
Name a hash:
.RE
.PP
\fB\fCnth \-t {{5f4dcc3b5aa765d61d8327deb882cf99}}\fR
.RS
.IP \(bu 2
Name hashes in a file:
.RE
.PP
\fB\fCnth \-f {{path/to/hashes}}\fR
.RS
.IP \(bu 2
Output in json format:
.RE
.PP
\fB\fCnth \-t {{5f4dcc3b5aa765d61d8327deb882cf99}} \-g\fR
.RS
.IP \(bu 2
Decode hash in Base64 before naming it:
.RE
.PP
\fB\fCnth \-t {{NWY0ZGNjM2I1YWE3NjVkNjFkODMyN2RlYjg4MmNmOTkK}} \-b64\fR
