.TH nudoku
.PP
.RS
Sudoku game in terminal.
More information: \[la]https://jubalh.github.io/nudoku/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a sudoku game:
.RE
.PP
\fB\fCnudoku\fR
.RS
.IP \(bu 2
Choose the difficulty of the game:
.RE
.PP
\fB\fCnudoku \-d {{easy|normal|hard}}\fR
.RS
.IP \(bu 2
Navigate the board:
.RE
.PP
\fB\fC{{h|j|k|l}} OR {{Left|Down|Up|Right}} arrow key\fR
.RS
.IP \(bu 2
Delete a number:
.RE
.PP
\fB\fC{{Backspace|x}}\fR
.RS
.IP \(bu 2
Get a hint:
.RE
.PP
\fB\fCH\fR
.RS
.IP \(bu 2
See the complete solution:
.RE
.PP
\fB\fCS\fR
.RS
.IP \(bu 2
Create a new puzzle:
.RE
.PP
\fB\fCN\fR
.RS
.IP \(bu 2
Quit the game:
.RE
.PP
\fB\fCQ\fR
