.TH obs
.PP
.RS
Open Broadcaster Software.
Video recording and livestreaming program.
More information: \[la]https://obsproject.com/\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch OBS:
.RE
.PP
\fB\fCobs\fR
.RS
.IP \(bu 2
Launch OBS in portable mode:
.RE
.PP
\fB\fCobs \-\-portable\fR
.RS
.IP \(bu 2
Automatically start recording a video on launch:
.RE
.PP
\fB\fCobs \-\-startrecording\fR
.RS
.IP \(bu 2
Automatically start the replay buffer on launch:
.RE
.PP
\fB\fCobs \-\-startreplaybuffer\fR
.RS
.IP \(bu 2
Automatically start streaming on launch:
.RE
.PP
\fB\fCobs \-\-startstreaming\fR
.RS
.IP \(bu 2
Minimise to the system tray on launch:
.RE
.PP
\fB\fCobs \-\-minimize\-to\-tray\fR
.RS
.IP \(bu 2
Make the log more verbose (for debugging):
.RE
.PP
\fB\fCobs \-\-verbose\fR
