.TH ocaml
.PP
.RS
The OCaml repl (read\-evaluate\-print\-loop).
Interprets Ocaml commands.
More information: \[la]https://ocaml.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Read OCaml commands from the user and execute them:
.RE
.PP
\fB\fCocaml\fR
.RS
.IP \(bu 2
Read OCaml commands from a file and execute them:
.RE
.PP
\fB\fCocaml {{path/to/file.ml}}\fR
.RS
.IP \(bu 2
Run OCaml script with modules:
.RE
.PP
\fB\fCocaml {{module1}} {{module2}} {{path/to/file.ml}}\fR
