.TH ocamlopt
.PP
.RS
The OCaml native code compiler.
Produces native executables, e.g. ELF on Linux.
More information: \[la]https://ocaml.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Compile a source file:
.RE
.PP
\fB\fCocamlopt \-o {{path/to/binary}} {{path/to/source_file.ml}}\fR
.RS
.IP \(bu 2
Compile with debugging enabled:
.RE
.PP
\fB\fCocamlopt \-g \-o {{path/to/binary}} {{path/to/source_file.ml}}\fR
