.TH octave
.PP
.RS
GNU Octave is a programming language for scientific computing.
More information: \[la]https://docs.octave.org/latest/Invoking-Octave-from-the-Command-Line.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive session:
.RE
.PP
\fB\fCoctave\fR
.RS
.IP \(bu 2
Execute a specific script file:
.RE
.PP
\fB\fCoctave {{path/to/script.m}}\fR
.RS
.IP \(bu 2
Execute a script file with specific arguments:
.RE
.PP
\fB\fCoctave {{path/to/script.m}} {{argument1 argument2 ...}}\fR
.RS
.IP \(bu 2
Start an interactive session with a GUI:
.RE
.PP
\fB\fCoctave \-\-gui\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCoctave \-\-help\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCoctave \-\-version\fR
