.TH od
.PP
.RS
Display file contents in octal, decimal or hexadecimal format.
Optionally display the byte offsets and/or printable representation for each line.
More information: \[la]https://www.gnu.org/software/coreutils/od\[ra]\&.
.RE
.RS
.IP \(bu 2
Display file using default settings: octal format, 8 bytes per line, byte offsets in octal, and duplicate lines replaced with \fB\fC*\fR:
.RE
.PP
\fB\fCod {{path/to/file}}\fR
.RS
.IP \(bu 2
Display file in verbose mode, i.e. without replacing duplicate lines with \fB\fC*\fR:
.RE
.PP
\fB\fCod \-v {{path/to/file}}\fR
.RS
.IP \(bu 2
Display file in hexadecimal format (2\-byte units), with byte offsets in decimal format:
.RE
.PP
\fB\fCod \-\-format={{x}} \-\-address\-radix={{d}} \-v {{path/to/file}}\fR
.RS
.IP \(bu 2
Display file in hexadecimal format (1\-byte units), and 4 bytes per line:
.RE
.PP
\fB\fCod \-\-format={{x1}} \-\-width={{4}} \-v {{path/to/file}}\fR
.RS
.IP \(bu 2
Display file in hexadecimal format along with its character representation, and do not print byte offsets:
.RE
.PP
\fB\fCod \-\-format={{xz}} \-\-address\-radix={{n}} \-v {{path/to/file}}\fR
.RS
.IP \(bu 2
Read only 100 bytes of a file starting from the 500th byte:
.RE
.PP
\fB\fCod \-\-read\-bytes {{100}} \-\-skip\-bytes={{500}} \-v {{path/to/file}}\fR
