.TH offlineimap
.PP
.RS
Synchronize a remote IMAP server with local Maildir folders.
More information: \[la]http://www.offlineimap.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Synchronize once, without enabling autorefresh:
.RE
.PP
\fB\fCofflineimap \-o\fR
.RS
.IP \(bu 2
Synchronize a specific account:
.RE
.PP
\fB\fCofflineimap \-a {{account}}\fR
.RS
.IP \(bu 2
Synchronize a specific folder:
.RE
.PP
\fB\fCofflineimap \-f {{folder}}\fR
