.TH ogrinfo
.PP
.RS
List information about an OGR\-supported data source.
More information: \[la]https://gdal.org/programs/ogrinfo.html\[ra]\&.
.RE
.RS
.IP \(bu 2
List supported formats:
.RE
.PP
\fB\fCogrinfo \-\-formats\fR
.RS
.IP \(bu 2
List layers of a data source:
.RE
.PP
\fB\fCogrinfo {{path/to/input.gpkg}}\fR
.RS
.IP \(bu 2
Get detailed information about a specific layer of a data source:
.RE
.PP
\fB\fCogrinfo {{path/to/input.gpkg}} {{layer_name}}\fR
.RS
.IP \(bu 2
Show summary information about a specific layer of a data source:
.RE
.PP
\fB\fCogrinfo \-so {{path/to/input.gpkg}} {{layer_name}}\fR
.RS
.IP \(bu 2
Show summary of all layers of the data source:
.RE
.PP
\fB\fCogrinfo \-so \-al {{path/to/input.gpkg}}\fR
.RS
.IP \(bu 2
Show detailed information of features matching a condition:
.RE
.PP
\fB\fCogrinfo \-where '{{attribute_name > 42}}' {{path/to/input.gpkg}} {{layer_name}}\fR
.RS
.IP \(bu 2
Update a layer in the data source with SQL:
.RE
.PP
\fB\fCogrinfo {{path/to/input.geojson}} \-dialect SQLite \-sql "{{UPDATE input SET attribute_name = 'foo'}}"\fR
