.TH okular
.PP
.RS
View documents.
More information: \[la]https://docs.kde.org/stable5/en/okular/okular/command-line-options.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch document viewer:
.RE
.PP
\fB\fCokular\fR
.RS
.IP \(bu 2
Open specific documents:
.RE
.PP
\fB\fCokular {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Open a document at a specific page:
.RE
.PP
\fB\fCokular \-\-page {{page_number}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a specific document in presentation mode:
.RE
.PP
\fB\fCokular \-\-presentation {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a specific document and start a print dialog:
.RE
.PP
\fB\fCokular \-\-print {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a document and search for a specific string:
.RE
.PP
\fB\fCokular \-\-find {{search_string}} {{path/to/file}}\fR
