.TH omf
.PP
.RS
Oh My Fish, the Fishshell Framework.
Install packages to extend and modify the fish shell.
More information: \[la]https://github.com/oh-my-fish/oh-my-fish\[ra]\&.
.RE
.RS
.IP \(bu 2
Install one or more packages:
.RE
.PP
\fB\fComf install {{name}}\fR
.RS
.IP \(bu 2
List installed packages:
.RE
.PP
\fB\fComf list\fR
.RS
.IP \(bu 2
List available themes:
.RE
.PP
\fB\fComf theme\fR
.RS
.IP \(bu 2
Apply a theme:
.RE
.PP
\fB\fComf theme {{name}}\fR
.RS
.IP \(bu 2
Remove a theme or package:
.RE
.PP
\fB\fComf remove {{name}}\fR
.RS
.IP \(bu 2
Uninstall Oh My Fish:
.RE
.PP
\fB\fComf destroy\fR
