.TH omz
.PP
.RS
Oh My Zsh command\-line tool.
More information: \[la]https://github.com/ohmyzsh/ohmyzsh\[ra]\&.
.RE
.RS
.IP \(bu 2
Update Oh My Zsh:
.RE
.PP
\fB\fComz update\fR
.RS
.IP \(bu 2
Print the changes from the latest update of Oh My Zsh:
.RE
.PP
\fB\fComz changelog\fR
.RS
.IP \(bu 2
Restart the current Zsh session and Oh My Zsh:
.RE
.PP
\fB\fComz reload\fR
.RS
.IP \(bu 2
List all available plugins:
.RE
.PP
\fB\fComz plugin list\fR
.RS
.IP \(bu 2
Enable/Disable an Oh My Zsh plugin:
.RE
.PP
\fB\fComz plugin {{enable|disable}} {{plugin}}\fR
.RS
.IP \(bu 2
List all available themes:
.RE
.PP
\fB\fComz theme list\fR
.RS
.IP \(bu 2
Set an Oh My Zsh theme in \fB\fC~/.zshrc\fR:
.RE
.PP
\fB\fComz theme set {{theme}}\fR
