.TH openssl
.PP
.RS
OpenSSL cryptographic toolkit.
Some subcommands such as \fB\fCopenssl req\fR have their own usage documentation.
More information: \[la]https://www.openssl.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a list of available subcommands:
.RE
.PP
\fB\fCopenssl help\fR
.RS
.IP \(bu 2
Print options for a specific subcommand:
.RE
.PP
\fB\fCopenssl help {{x509}}\fR
.RS
.IP \(bu 2
Print the version of OpenSSL:
.RE
.PP
\fB\fCopenssl version\fR
