.TH openssl dgst
.PP
.RS
OpenSSL command to generate digest values and perform signature operations.
More information: \[la]https://www.openssl.org/docs/manmaster/man1/openssl-dgst.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Calculate the SHA256 digest for a file, saving the result to a specific file:
.RE
.PP
\fB\fCopenssl dgst \-sha256 \-binary \-out {{output_file}} {{input_file}}\fR
.RS
.IP \(bu 2
Sign a file using an RSA key, saving the result to a specific file:
.RE
.PP
\fB\fCopenssl dgst \-sign {{private_key_file}} \-sha256 \-sigopt rsa_padding_mode:pss \-out {{output_file}} {{input_file}}\fR
.RS
.IP \(bu 2
Verify an RSA signature:
.RE
.PP
\fB\fCopenssl dgst \-verify {{public_key_file}} \-signature {{signature_file}} \-sigopt rsa_padding_mode:pss {{signature_message_file}}\fR
.RS
.IP \(bu 2
Sign a file using and ECDSA key:
.RE
.PP
\fB\fCopenssl dgst \-sign {{private_key_file}} \-sha256 \-out {{output_file}} {{input_file}}\fR
.RS
.IP \(bu 2
Verify an ECDSA signature:
.RE
.PP
\fB\fCopenssl dgst \-verify {{public_key_file}} \-signature {{signature_file}} {{signature_message_file}}\fR
