.TH openscad
.PP
.RS
Software for creating solid 3D CAD objects.
More information: \[la]https://openscad.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a file:
.RE
.PP
\fB\fCopenscad {{path/to/button.scad}}\fR
.RS
.IP \(bu 2
Convert a file to STL:
.RE
.PP
\fB\fCopenscad \-o {{path/to/button.stl}} {{path/to/button.scad}}\fR
.RS
.IP \(bu 2
Render a file to PNG in a specific colorscheme:
.RE
.PP
\fB\fCopenscad \-o {{path/to/button.png}} \-\-colorscheme {{Sunset}} {{path/to/button.scad}}\fR
