.TH open
.PP
.RS
\fB\fCopen\fR can refer to multiple commands with the same name.
.RE
.RS
.IP \(bu 2
View documentation for the command available in macOS:
.RE
.PP
\fB\fCtldr open \-p osx\fR
.RS
.IP \(bu 2
View documentation for the macOS command in older versions of \fB\fCtldr\fR command\-line client:
.RE
.PP
\fB\fCtldr open \-o osx\fR
.RS
.IP \(bu 2
View documentation for the command available through \fB\fCfish\fR:
.RE
.PP
\fB\fCtldr open.fish\fR
