.TH p10k
.PP
.RS
Manage configurations for powerlevel10k.
More information: \[la]https://github.com/romkatv/powerlevel10k\[ra]\&.
.RE
.RS
.IP \(bu 2
Configure powerlevel10k interactively:
.RE
.PP
\fB\fCp10k configure\fR
.RS
.IP \(bu 2
Reload powerlevel10k:
.RE
.PP
\fB\fCp10k reload\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCp10k help\fR
