.TH p5
.PP
.RS
Template builder and sketch manager for p5.js.
More information: \[la]https://github.com/chiunhau/p5-manager\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new p5 collection:
.RE
.PP
\fB\fCp5 new {{collection_name}}\fR
.RS
.IP \(bu 2
Generate a new p5 project (should be run from collection directory):
.RE
.PP
\fB\fCp5 generate {{project_name}}\fR
.RS
.IP \(bu 2
Run the p5 manager server:
.RE
.PP
\fB\fCp5 server\fR
.RS
.IP \(bu 2
Update libraries to their latest versions:
.RE
.PP
\fB\fCp5 update\fR
