.TH paci
.PP
.RS
A package manager for Bash scripts.
More information: \[la]https://github.com/tradebyte/paci\[ra]\&.
.RE
.RS
.IP \(bu 2
Update the list of available packages and versions (it's recommended to run this before other \fB\fCpaci\fR commands):
.RE
.PP
\fB\fCpaci refresh\fR
.RS
.IP \(bu 2
Configure its behaviour:
.RE
.PP
\fB\fCpaci configure\fR
.RS
.IP \(bu 2
Search for a given package:
.RE
.PP
\fB\fCpaci search {{package}}\fR
.RS
.IP \(bu 2
Install a package:
.RE
.PP
\fB\fCpaci install {{package}}\fR
.RS
.IP \(bu 2
Update a package:
.RE
.PP
\fB\fCpaci update {{package}}\fR
