.TH packtpub
.PP
.RS
Download freely offered books from packtpub.com.
More information: \[la]https://github.com/vladimyr/packtpub-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Download the daily offer book into the current directory with the specified book format (defaults to \fB\fCpdf\fR):
.RE
.PP
\fB\fCpacktpub download \-\-type {{pdf|ebup|mobi}}\fR
.RS
.IP \(bu 2
Download the daily offer book into the specified directory:
.RE
.PP
\fB\fCpacktpub download \-\-dir {{path/to/directory}}\fR
.RS
.IP \(bu 2
Start an interactive login to packtpub.com:
.RE
.PP
\fB\fCpacktpub login\fR
.RS
.IP \(bu 2
Log out from packtpub.com:
.RE
.PP
\fB\fCpacktpub logout\fR
.RS
.IP \(bu 2
Display the daily offer:
.RE
.PP
\fB\fCpacktpub view\-offer\fR
.RS
.IP \(bu 2
Open the daily offer in the default web browser:
.RE
.PP
\fB\fCpacktpub view\-offer\fR
.RS
.IP \(bu 2
Display the currently logged\-in user:
.RE
.PP
\fB\fCpacktpub whoami\fR
