.TH packer
.PP
.RS
Build automated machine images.
More information: \[la]https://www.packer.io/\[ra]\&.
.RE
.RS
.IP \(bu 2
Build an image:
.RE
.PP
\fB\fCpacker build {{path/to/config.json}}\fR
.RS
.IP \(bu 2
Check the syntax of a Packer image config:
.RE
.PP
\fB\fCpacker validate {{path/to/config.json}}\fR
.RS
.IP \(bu 2
Format a Packer image config:
.RE
.PP
\fB\fCpacker fmt {{path/to/config.pkr.hcl}}\fR
