.TH passwd
.PP
.RS
Passwd is a tool used to change a user's password.
More information: \[la]https://manned.org/passwd\[ra]\&.
.RE
.RS
.IP \(bu 2
Change the password of the current user interactively:
.RE
.PP
\fB\fCpasswd\fR
.RS
.IP \(bu 2
Change the password of a specific user:
.RE
.PP
\fB\fCpasswd {{username}}\fR
.RS
.IP \(bu 2
Get the current status of the user:
.RE
.PP
\fB\fCpasswd \-S\fR
.RS
.IP \(bu 2
Make the password of the account blank (it will set the named account passwordless):
.RE
.PP
\fB\fCpasswd \-d\fR
