.TH pbmlife
.PP
.RS
Apply Conway's Rules of Life to a PBM image.
More information: \[la]https://netpbm.sourceforge.net/doc/pbmlife.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Apply the Rules of Life to an input PBM image file for one generation and the output the result as a PBM image file:
.RE
.PP
\fB\fCpbmlife {{path/to/file.pbm}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCpbmlife \-version\fR
