.TH pdfinfo
.PP
.RS
Portable Document Format (PDF) file information viewer.
More information: \[la]https://www.xpdfreader.com/pdfinfo-man.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Print PDF file information:
.RE
.PP
\fB\fCpdfinfo {{path/to/file.pdf}}\fR
.RS
.IP \(bu 2
Specify user password for PDF file to bypass security restrictions:
.RE
.PP
\fB\fCpdfinfo \-upw {{password}} {{path/to/file.pdf}}\fR
.RS
.IP \(bu 2
Specify owner password for PDF file to bypass security restrictions:
.RE
.PP
\fB\fCpdfinfo \-opw {{password}} {{path/to/file.pdf}}\fR
