.TH pdfjam
.PP
.RS
Shell frontend for the LaTeX pdfpages package for mingling PDFs.
More information: \[la]https://github.com/rrthomas/pdfjam\[ra]\&.
.RE
.RS
.IP \(bu 2
Merge two (or more) PDFs:
.RE
.PP
\fB\fCpdfjam {{path/to/file1.pdf}} {{path/to/file2.pdf}} \-\-outfile {{path/to/output_file.pdf}}\fR
.RS
.IP \(bu 2
Merge the first page of each file together:
.RE
.PP
\fB\fCpdfjam {{files...}} 1 \-\-outfile {{path/to/output_file.pdf}}\fR
.RS
.IP \(bu 2
Merge subranges from two PDFs:
.RE
.PP
\fB\fCpdfjam {{path/to/file1.pdf 3\-5,1}} {{path/to/file2.pdf 4\-6}} \-\-outfile {{path/to/output_file.pdf}}\fR
.RS
.IP \(bu 2
Sign an A4 page (adjust delta to height for other formats) with a scanned signature by overlaying them:
.RE
.PP
\fB\fCpdfjam {{path/to/file.pdf}} {{path/to/signature}} \-\-fitpaper true \-\-outfile {{path/to/signed.pdf}} \-\-nup "{{1x2}}" \-\-delta "{{0 \-842pt}}"\fR
.RS
.IP \(bu 2
Arrange the pages from the input file into a fancy 2x2 grid:
.RE
.PP
\fB\fCpdfjam {{path/to/file.pdf}} \-\-nup {{2x2}} \-\-suffix {{4up}} \-\-preamble '{{\\usepackage{fancyhdr} \\pagestyle{fancy}}}'\fR
.RS
.IP \(bu 2
Reverse the order of pages within each given file and concatenate them:
.RE
.PP
\fB\fCpdfjam {{files...}} {{last\-1}} \-\-suffix {{reversed}}\fR
