.TH peco
.PP
.RS
Interactive filtering tool.
More information: \[la]https://github.com/peco/peco\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCpeco\fR on all files in the specified directory:
.RE
.PP
\fB\fCfind {{path/to/directory}} \-type f | peco\fR
.RS
.IP \(bu 2
Start \fB\fCpeco\fR for running processes:
.RE
.PP
\fB\fCps aux | peco\fR
.RS
.IP \(bu 2
Start \fB\fCpeco\fR with a specified query:
.RE
.PP
\fB\fCpeco \-\-query "{{query}}"\fR
