.TH peerindex
.PP
.RS
Inspect MRT TABLE_DUMPV2 Peer Index Table.
Can read files compressed with gzip, bzip2 and xz.
More information: \[la]https://codeberg.org/1414codeforge/ubgpsuite\[ra]\&.
.RE
.RS
.IP \(bu 2
Output all peers:
.RE
.PP
\fB\fCpeerindex {{master6.mrt}}\fR
.RS
.IP \(bu 2
Display all peers that have provided routing information:
.RE
.PP
\fB\fCpeerindex \-r {{master6.mrt}}\fR
