.TH php yii
.PP
.RS
Yii Framework's command\-line interface.
More information: \[la]https://yiiframework.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Display a list of all available commands:
.RE
.PP
\fB\fCphp yii {{help}}\fR
.RS
.IP \(bu 2
Start PHP's built\-in web server for the current Yii application:
.RE
.PP
\fB\fCphp yii {{serve}}\fR
.RS
.IP \(bu 2
Generate a controller, views and related files for the CRUD actions on the specified model class:
.RE
.PP
\fB\fCphp yii {{gii/crud}} \-\-modelClass={{ModelName}} \-\-controllerClass={{ControllerName}}\fR
