.TH php artisan
.PP
.RS
Laravel's Artisan command\-line interface.
More information: \[la]https://laravel.com/docs/artisan\[ra]\&.
.RE
.RS
.IP \(bu 2
Start PHP's built\-in web server for the current Laravel application:
.RE
.PP
\fB\fCphp artisan serve\fR
.RS
.IP \(bu 2
Start an interactive PHP command\-line interface:
.RE
.PP
\fB\fCphp artisan tinker\fR
.RS
.IP \(bu 2
Generate a new Eloquent model class with a migration, factory and resource controller:
.RE
.PP
\fB\fCphp artisan make:model {{ModelName}} \-\-all\fR
.RS
.IP \(bu 2
Display a list of all available commands:
.RE
.PP
\fB\fCphp artisan help\fR
