.TH phpdox
.PP
.RS
A PHP documentation generator.
More information: \[la]https://phpdox.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Display an annotated skeleton configuration XML file:
.RE
.PP
\fB\fCphpdox \-\-skel\fR
.RS
.IP \(bu 2
Generate documentation for the current working directory:
.RE
.PP
\fB\fCphpdox\fR
.RS
.IP \(bu 2
Generate documentation using a specific configuration file:
.RE
.PP
\fB\fCphpdox \-\-file {{path/to/phpdox.xml}}\fR
.RS
.IP \(bu 2
Only run the metadata collection process:
.RE
.PP
\fB\fCphpdox \-\-collector\fR
.RS
.IP \(bu 2
Only run the documentation generator process:
.RE
.PP
\fB\fCphpdox \-\-generator\fR
