.TH phpize
.PP
.RS
Prepare a PHP extension for compiling.
More information: \[la]https://www.php.net/manual/install.pecl.phpize\[ra]\&.
.RE
.RS
.IP \(bu 2
Prepare the PHP extension in the current directory for compiling:
.RE
.PP
\fB\fCphpize\fR
.RS
.IP \(bu 2
Delete files previously created by phpize:
.RE
.PP
\fB\fCphpize \-\-clean\fR
