.TH picard
.PP
.RS
Next generation MusicBrainz tagging application.
More information: \[la]https://picard.musicbrainz.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Picard:
.RE
.PP
\fB\fCpicard\fR
.RS
.IP \(bu 2
Open a set of files:
.RE
.PP
\fB\fCpicard {{path/to/file1.mp3}} {{path/to/file2.mp3}}\fR
.RS
.IP \(bu 2
Display the version of Picard installed:
.RE
.PP
\fB\fCpicard \-\-long\-version\fR
