.TH ping6
.PP
.RS
Send ICMP ECHO_REQUEST packets to network hosts via IPv6 address.
More information: \[la]https://manned.org/ping6\[ra]\&.
.RE
.RS
.IP \(bu 2
Ping a host:
.RE
.PP
\fB\fCping6 {{host}}\fR
.RS
.IP \(bu 2
Ping a host only a specific number of times:
.RE
.PP
\fB\fCping6 \-c {{count}} {{host}}\fR
.RS
.IP \(bu 2
Ping a host, specifying the interval in seconds between requests (default is 1 second):
.RE
.PP
\fB\fCping6 \-i {{seconds}} {{host}}\fR
.RS
.IP \(bu 2
Ping a host without trying to lookup symbolic names for addresses:
.RE
.PP
\fB\fCping6 \-n {{host}}\fR
.RS
.IP \(bu 2
Ping a host and ring the bell when a packet is received (if your terminal supports it):
.RE
.PP
\fB\fCping6 \-a {{host}}\fR
