.TH pinky
.PP
.RS
Print user information using the \fB\fCfinger\fR protocol.
More information: \[la]https://manned.org/pinky\[ra]\&.
.RE
.RS
.IP \(bu 2
Display details about the current user:
.RE
.PP
\fB\fCpinky\fR
.RS
.IP \(bu 2
Display details for a specific user:
.RE
.PP
\fB\fCpinky {{user}}\fR
.RS
.IP \(bu 2
Display details in the long format:
.RE
.PP
\fB\fCpinky {{user}} \-l\fR
.RS
.IP \(bu 2
Omit the user's home directory and shell in long format:
.RE
.PP
\fB\fCpinky {{user}} \-lb\fR
.RS
.IP \(bu 2
Omit the user's project file in long format:
.RE
.PP
\fB\fCpinky {{user}} \-lh\fR
.RS
.IP \(bu 2
Omit the column headings in short format:
.RE
.PP
\fB\fCpinky {{user}} \-f\fR
