.TH Pint
.PP
.RS
An opinionated PHP code style fixer based on PHP\-CS\-Fixer.
More information: \[la]https://laravel.com/docs/pint\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute code style fixing:
.RE
.PP
\fB\fCpint\fR
.RS
.IP \(bu 2
Display all files that are changed:
.RE
.PP
\fB\fCpint \-v\fR
.RS
.IP \(bu 2
Execute code style linting without applying changes:
.RE
.PP
\fB\fCpint \-\-test\fR
.RS
.IP \(bu 2
Execute code style fixes using a specific config file:
.RE
.PP
\fB\fCpint \-\-config {{path/to/pint.json}}\fR
.RS
.IP \(bu 2
Execute code style fixes using a specific preset:
.RE
.PP
\fB\fCpint \-\-preset {{psr12}}\fR
