.TH pinta
.PP
.RS
Pinta is a free, open source program for drawing and image editing.
More information: \[la]https://www.pinta-project.com/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Pinta:
.RE
.PP
\fB\fCpinta\fR
.RS
.IP \(bu 2
Open specific files:
.RE
.PP
\fB\fCpinta {{path/to/image1 path/to/image2 ...}}\fR
