.TH pio boards
.PP
.RS
List pre\-configured embedded boards available in PlatformIO.
More information: \[la]https://docs.platformio.org/en/latest/core/userguide/cmd_boards.html\[ra]\&.
.RE
.RS
.IP \(bu 2
List all available boards:
.RE
.PP
\fB\fCpio boards\fR
.RS
.IP \(bu 2
List only boards from installed platforms:
.RE
.PP
\fB\fCpio boards \-\-installed\fR
