.TH pio upgrade
.PP
.RS
Update PlatformIO to the latest version.
More information: \[la]https://docs.platformio.org/en/latest/core/userguide/cmd_upgrade.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Update PlatformIO to the latest version:
.RE
.PP
\fB\fCpio upgrade\fR
.RS
.IP \(bu 2
Update PlatformIO to the latest development (unstable) version:
.RE
.PP
\fB\fCpio upgrade \-\-dev\fR
