.TH pio lib
.PP
.RS
Manage PlatformIO libraries.
More information: \[la]https://docs.platformio.org/en/latest/core/userguide/lib/\[ra]\&.
.RE
.RS
.IP \(bu 2
List installed libraries:
.RE
.PP
\fB\fCpio lib list\fR
.RS
.IP \(bu 2
List built\-in libraries based on installed development platforms and their frameworks:
.RE
.PP
\fB\fCpio lib builtin\fR
.RS
.IP \(bu 2
Search for existing libraries:
.RE
.PP
\fB\fCpio lib search {{keyword}}\fR
.RS
.IP \(bu 2
Show details about a library:
.RE
.PP
\fB\fCpio lib show {{library}}\fR
.RS
.IP \(bu 2
Install a library:
.RE
.PP
\fB\fCpio lib install {{library}}\fR
.RS
.IP \(bu 2
Update installed libraries:
.RE
.PP
\fB\fCpio lib update\fR
.RS
.IP \(bu 2
Uninstall a library:
.RE
.PP
\fB\fCpio lib uninstall {{library}}\fR
.RS
.IP \(bu 2
Show PlatformIO library registry statistics:
.RE
.PP
\fB\fCpio lib stats\fR
