.TH pio settings
.PP
.RS
View and modify PlatformIO settings.
More information: \[la]https://docs.platformio.org/en/latest/core/userguide/cmd_settings.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the names, values and descriptions of all PlatformIO settings:
.RE
.PP
\fB\fCpio settings get\fR
.RS
.IP \(bu 2
Display the name, value and description of a specific PlatformIO setting:
.RE
.PP
\fB\fCpio settings get {{setting}}\fR
.RS
.IP \(bu 2
Set a specific setting value:
.RE
.PP
\fB\fCpio settings set {{setting}} {{value}}\fR
.RS
.IP \(bu 2
Reset the values of all modified settings to their factory defaults:
.RE
.PP
\fB\fCpio settings reset\fR
