.TH pio
.PP
.RS
Development environment for embedded boards.
Some subcommands such as \fB\fCpio run\fR have their own usage documentation.
More information: \[la]https://docs.platformio.org/en/latest/core/userguide/\[ra]\&.
.RE
.RS
.IP \(bu 2
Show help and list subcommands:
.RE
.PP
\fB\fCpio \-\-help\fR
.RS
.IP \(bu 2
Print the version number and exit:
.RE
.PP
\fB\fCpio \-\-version\fR
.RS
.IP \(bu 2
Show help for a specific subcommand:
.RE
.PP
\fB\fCpio {{subcommand}} \-\-help\fR
