.TH pip uninstall
.PP
.RS
Uninstall Python packages.
More information: \[la]https://pip.pypa.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Uninstall a package:
.RE
.PP
\fB\fCpip uninstall {{package}}\fR
.RS
.IP \(bu 2
Uninstall packages listed in a specific file:
.RE
.PP
\fB\fCpip uninstall \-\-requirement {{path/to/requirements.txt}}\fR
.RS
.IP \(bu 2
Uninstall package without asking for confirmation:
.RE
.PP
\fB\fCpip uninstall \-\-yes {{package}}\fR
