.TH pnmtopng
.PP
.RS
Converts a PNM image file to PNG image format.
More information: \[la]https://netpbm.sourceforge.net/doc/pnmtopng.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Read a PNM image as input and produce a PNG image as output:
.RE
.PP
\fB\fCpnmtopng {{path/to/file.pnm}} > {{path/to/file.png}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCpnmtopng \-version\fR
