.TH pnmtojpeg
.PP
.RS
Converts a PNM image file to the JPEG/JFIF/EXIF image format.
More information: \[la]https://netpbm.sourceforge.net/doc/pnmtojpeg.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Read a PNM image as input and produce a JPEG/JFIF/EXIF image as output:
.RE
.PP
\fB\fCpnmtojpeg {{path/to/file.pnm}} > {{path/to/file.jpg}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCpnmtojpeg \-version\fR
