.TH pnpx
.PP
.RS
Directly execute binaries from npm packages, using \fB\fCpnpm\fR instead of \fB\fCnpm\fR\&.
More information: \[la]https://pnpm.io/pnpx-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute the binary from a given npm module:
.RE
.PP
\fB\fCpnpx {{module_name}}\fR
.RS
.IP \(bu 2
Execute a specific binary from a given npm module, in case the module has multiple binaries:
.RE
.PP
\fB\fCpnpx \-\-package {{package_name}} {{module_name}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCpnpx \-\-help\fR
