.TH polybar
.PP
.RS
A fast and easy\-to\-use status bar.
More information: \[la]https://github.com/polybar/polybar/wiki\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Polybar (the bar name is optional if only one bar is defined in the config):
.RE
.PP
\fB\fCpolybar {{bar_name}}\fR
.RS
.IP \(bu 2
Start Polybar with the specified config:
.RE
.PP
\fB\fCpolybar \-\-config={{path/to/config.ini}} {{bar_name}}\fR
.RS
.IP \(bu 2
Start Polybar and reload the bar when the config file is modified:
.RE
.PP
\fB\fCpolybar \-\-reload {{bar_name}}\fR
