.TH pop
.PP
.RS
Send emails from your terminal.
More information: \[la]https://github.com/charmbracelet/pop\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the Text\-based User Interface:
.RE
.PP
\fB\fCpop\fR
.RS
.IP \(bu 2
Send an email using the content of a Markdown file as body:
.RE
.PP
\fB\fCpop < {{path/to/message.md}} \-\-from {{me@example.com}} \-\-to {{you@example.com}} \-\-subject "{{On the Subject of Ducks...}}" \-\-attach {{path/to/attachment}}\fR
.RS
.IP \(bu 2
Display help and exit:
.RE
.PP
\fB\fCpop \-\-help\fR
