.TH pretty\-bytes
.PP
.RS
Convert bytes to a human\-readable string.
More information: \[la]https://github.com/sindresorhus/pretty-bytes-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert numeric bytes value to a human\-readable string:
.RE
.PP
\fB\fCpretty\-bytes {{1337}}\fR
.RS
.IP \(bu 2
Convert numeric bytes value from \fB\fCstdin\fR to a human\-readable string:
.RE
.PP
\fB\fCecho {{1337}} | pretty\-bytes\fR
.RS
.IP \(bu 2
Display help and usage information:
.RE
.PP
\fB\fCpretty\-bytes \-\-help\fR
