.TH printenv
.PP
.RS
Print values of all or specific environment variables.
More information: \[la]https://www.gnu.org/software/coreutils/printenv\[ra]\&.
.RE
.RS
.IP \(bu 2
Display key\-value pairs of all environment variables:
.RE
.PP
\fB\fCprintenv\fR
.RS
.IP \(bu 2
Display the value of a specific variable:
.RE
.PP
\fB\fCprintenv {{HOME}}\fR
.RS
.IP \(bu 2
Display the value of a variable and end with NUL instead of newline:
.RE
.PP
\fB\fCprintenv \-\-null {{HOME}}\fR
