.TH progpilot
.PP
.RS
A PHP static analysis tool for detecting security vulnerabilities.
More information: \[la]https://github.com/designsecurity/progpilot\[ra]\&.
.RE
.RS
.IP \(bu 2
Analyze the current directory:
.RE
.PP
\fB\fCprogpilot\fR
.RS
.IP \(bu 2
Analyze a specific file or directory:
.RE
.PP
\fB\fCprogpilot {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Specify a custom configuration file:
.RE
.PP
\fB\fCprogpilot \-\-configuration {{path/to/configuration.yml}}\fR
