.TH ps\-nvm
.PP
.RS
PowerShell\-based utility to manage multiple Node.js versions, inspired by \fB\fCnvm\fR\&.
This tool provides multiple commands that all can only be run through PowerShell.
More information: \[la]https://github.com/aaronpowell/ps-nvm\[ra]\&.
.RE
.RS
.IP \(bu 2
View documentation for \fB\fCGet\-NodeInstallLocation\fR, a tool to get the current Node.js install location:
.RE
.PP
\fB\fCtldr get\-nodeinstalllocation\fR
.RS
.IP \(bu 2
View documentation for \fB\fCGet\-NodeVersions\fR, a tool to list all available and currently\-installed Node.js versions:
.RE
.PP
\fB\fCtldr get\-nodeversions\fR
.RS
.IP \(bu 2
View documentation for \fB\fCInstall\-NodeVersion\fR, a tool to install Node.js runtime versions:
.RE
.PP
\fB\fCtldr get\-nodeversion\fR
.RS
.IP \(bu 2
View documentation for \fB\fCRemove\-NodeVersion\fR, a tool to uninstall an existing Node.js version:
.RE
.PP
\fB\fCtldr remove\-nodeversion\fR
.RS
.IP \(bu 2
View documentation for \fB\fCSet\-NodeInstallLocation\fR, a tool to set the Node.js install location:
.RE
.PP
\fB\fCtldr set\-nodeinstalllocation\fR
.RS
.IP \(bu 2
View documentation for \fB\fCSet\-NodeVersion\fR, a tool to set the default version of Node.js:
.RE
.PP
\fB\fCtldr set\-nodeversion\fR
