.TH psysh
.PP
.RS
A runtime developer console, interactive debugger and REPL for PHP.
More information: \[la]https://psysh.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a shell in the current directory:
.RE
.PP
\fB\fCpsysh\fR
.RS
.IP \(bu 2
Open a shell in a specific directory:
.RE
.PP
\fB\fCpsysh \-\-cwd {{path/to/directory}}\fR
.RS
.IP \(bu 2
Use a specific configuration file:
.RE
.PP
\fB\fCpsysh \-\-config {{path/to/file}}\fR
