.TH ptpython
.PP
.RS
A better Python REPL.
More information: \[la]https://github.com/prompt-toolkit/ptpython\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a REPL (interactive shell):
.RE
.PP
\fB\fCptpython\fR
.RS
.IP \(bu 2
Execute a specific Python file:
.RE
.PP
\fB\fCptpython {{path/to/file.py}}\fR
.RS
.IP \(bu 2
Execute a specific Python file and start a REPL:
.RE
.PP
\fB\fCptpython \-i {{path/to/file.py}}\fR
.RS
.IP \(bu 2
Open the menu:
.RE
.PP
\fB\fCF2\fR
.RS
.IP \(bu 2
Open the history page:
.RE
.PP
\fB\fCF3\fR
.RS
.IP \(bu 2
Toggle paste mode:
.RE
.PP
\fB\fCF6\fR
.RS
.IP \(bu 2
Quit:
.RE
.PP
\fB\fCCtrl + D\fR
