.TH pueue completions
.PP
.RS
Generates shell completion files for Bash, Elvish, Fish, PowerShell, and Zsh.
More information: \[la]https://github.com/Nukesor/pueue\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate completions for Bash:
.RE
.PP
\fB\fCsudo pueue completions bash {{/usr/share/bash\-completion/completions/pueue.bash}}\fR
.RS
.IP \(bu 2
Generate completions for zsh:
.RE
.PP
\fB\fCsudo pueue completions zsh {{/usr/share/zsh/site\-functions}}\fR
.RS
.IP \(bu 2
Generate completions for fish:
.RE
.PP
\fB\fCsudo pueue completions fish {{/usr/share/fish/completions}}\fR
