.TH pueue clean
.PP
.RS
Remove all finished tasks from the list and clear logs.
More information: \[la]https://github.com/Nukesor/pueue\[ra]\&.
.RE
.RS
.IP \(bu 2
Remove finished tasks and clear logs:
.RE
.PP
\fB\fCpueue clean\fR
.RS
.IP \(bu 2
Only clean commands that finished successfully:
.RE
.PP
\fB\fCpueue clean \-\-successful\-only\fR
