.TH pueue remove
.PP
.RS
Remove tasks from the list. Running or paused tasks need to be killed first.
More information: \[la]https://github.com/Nukesor/pueue\[ra]\&.
.RE
.RS
.IP \(bu 2
Remove a killed or finished task:
.RE
.PP
\fB\fCpueue remove {{task_id}}\fR
.RS
.IP \(bu 2
Remove multiple tasks at once:
.RE
.PP
\fB\fCpueue remove {{task_id}} {{task_id}}\fR
