.TH pueue
.PP
.RS
A task management tool for sequential and parallel execution of long\-running tasks.
Some subcommands such as \fB\fCpueue add\fR have their own usage documentation.
More information: \[la]https://github.com/Nukesor/pueue\[ra]\&.
.RE
.RS
.IP \(bu 2
Show general help and available subcommands:
.RE
.PP
\fB\fCpueue \-\-help\fR
.RS
.IP \(bu 2
Check the version of pueue:
.RE
.PP
\fB\fCpueue \-\-version\fR
.RS
.IP \(bu 2
Execute a pueue subcommand:
.RE
.PP
\fB\fCpueue {{subcommand}}\fR
