.TH pueue status
.PP
.RS
Display the current status of all tasks.
More information: \[la]https://github.com/Nukesor/pueue\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the status of all tasks:
.RE
.PP
\fB\fCpueue status\fR
.RS
.IP \(bu 2
Show the status of a specific group:
.RE
.PP
\fB\fCpueue status \-\-group {{group_name}}\fR
