.TH pulumi
.PP
.RS
Define infrastructure on any cloud using familiar programming languages.
More information: \[la]https://www.pulumi.com/docs/reference/cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new project using a template:
.RE
.PP
\fB\fCpulumi new\fR
.RS
.IP \(bu 2
Create a new stack using an isolated deployment target:
.RE
.PP
\fB\fCpulumi stack init\fR
.RS
.IP \(bu 2
Configure variables (e.g. keys, regions, etc.) interactively:
.RE
.PP
\fB\fCpulumi config\fR
.RS
.IP \(bu 2
Preview and deploy changes to a program and/or infrastructure:
.RE
.PP
\fB\fCpulumi up\fR
.RS
.IP \(bu 2
Preview deployment changes without performing them (dry\-run):
.RE
.PP
\fB\fCpulumi preview\fR
.RS
.IP \(bu 2
Destroy a program and its infrastructure:
.RE
.PP
\fB\fCpulumi destroy\fR
