.TH puppet
.PP
.RS
Help to manage and automate the configuration of servers.
Some subcommands such as \fB\fCpuppet agent\fR have their own usage documentation.
More information: \[la]https://puppet.com/\[ra]\&.
.RE
.RS
.IP \(bu 2
Execute a Puppet subcommand:
.RE
.PP
\fB\fCpuppet {{subcommand}}\fR
.RS
.IP \(bu 2
Check the Puppet version:
.RE
.PP
\fB\fCpuppet \-\-version\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCpuppet \-\-help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCpuppet help {{subcommand}}\fR
