.TH pve\-firewall
.PP
.RS
Manage Proxmox VE Firewall.
More information: \[la]https://pve.proxmox.com/wiki/Firewall\[ra]\&.
.RE
.RS
.IP \(bu 2
Compile and print all firewall rules:
.RE
.PP
\fB\fCpve\-firewall compile\fR
.RS
.IP \(bu 2
Show information about the local network:
.RE
.PP
\fB\fCpve\-firewall localnet\fR
.RS
.IP \(bu 2
Restart the Proxmox VE Firewall service:
.RE
.PP
\fB\fCpve\-firewall restart\fR
.RS
.IP \(bu 2
Start the Proxmox VE Firewall service:
.RE
.PP
\fB\fCpve\-firewall start\fR
.RS
.IP \(bu 2
Stop the Proxmox VE Firewall service:
.RE
.PP
\fB\fCpve\-firewall stop\fR
.RS
.IP \(bu 2
Simulate all firewall rules:
.RE
.PP
\fB\fCpve\-firewall simulate\fR
.RS
.IP \(bu 2
Show the status of Proxmox VE Firewall:
.RE
.PP
\fB\fCpve\-firewall status\fR
