.TH pwgen
.PP
.RS
Generate pronounceable passwords.
More information: \[la]https://github.com/tytso/pwgen\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate random password with s[y]mbols:
.RE
.PP
\fB\fCpwgen \-y {{length}}\fR
.RS
.IP \(bu 2
Generate secure, hard\-to\-memorize passwords:
.RE
.PP
\fB\fCpwgen \-s {{length}}\fR
.RS
.IP \(bu 2
Generate password with at least one capital letter in them:
.RE
.PP
\fB\fCpwgen \-c {{length}}\fR
