.TH pyATS
.PP
.RS
A vendor agnostic test automation framework by Cisco Systems, used for network and systems testing.
More information: \[la]https://developer.cisco.com/pyats/\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a \fB\fCpyATS\fR subcommand:
.RE
.PP
\fB\fCpyats {{subcommand}}\fR
.RS
.IP \(bu 2
Display version:
.RE
.PP
\fB\fCpyats version check\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCpyats \-\-help\fR
.RS
.IP \(bu 2
Display help about a specific subcommand:
.RE
.PP
\fB\fCpyats {{subcommand}} \-\-help\fR
