.TH pyats shell
.PP
.RS
Start a pre\-loaded pyATS interactive Python Shell to save time in prototyping.
More information: \[la]https://pubhub.devnetcloud.com/media/genie-docs/docs/cli/genie_shell.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Open pyATS shell with a defined Testbed file:
.RE
.PP
\fB\fCpyats shell \-\-testbed\-file {{path/to/testbed.yaml}}\fR
.RS
.IP \(bu 2
Open pyATS shell with a defined Pickle file:
.RE
.PP
\fB\fCpyats shell \-\-pickle\-file {{path/to/pickle.file}}\fR
.RS
.IP \(bu 2
Open pyATS with IPython disabled:
.RE
.PP
\fB\fCpyats shell \-\-no\-ipython\fR
