.TH pyats version
.PP
.RS
View and upgrade the pyATS installation.
More information: \[la]https://developer.cisco.com/pyats/\[ra]\&.
.RE
.RS
.IP \(bu 2
Display version of all packages:
.RE
.PP
\fB\fCpyats version check\fR
.RS
.IP \(bu 2
Display outdated packages:
.RE
.PP
\fB\fCpyats version check \-\-outdated\fR
.RS
.IP \(bu 2
Update packages to the most recent version:
.RE
.PP
\fB\fCpyats version update\fR
.RS
.IP \(bu 2
Update or downgrade packages to a specific version:
.RE
.PP
\fB\fCpyats version update {{version}}\fR
