.TH pydoc
.PP
.RS
Display offline Python documentation.
More information: \[la]https://docs.python.org/3/library/pydoc.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Print documentation on a subject (Python keyword, topic, function, module, package, etc.):
.RE
.PP
\fB\fCpydoc {{subject}}\fR
.RS
.IP \(bu 2
Start an HTTP server on an arbitrary unused port and open a [b]rowser to see the documentation:
.RE
.PP
\fB\fCpydoc \-b\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCpydoc\fR
