.TH pyenv virtualenv
.PP
.RS
Create virtual environments based on one's installed Python distributions.
More information: \[la]https://github.com/pyenv/pyenv-virtualenv\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Python 3.6.6 virtual environment:
.RE
.PP
\fB\fCpyenv virtualenv {{3.6.6}} {{virtualenv_name}}\fR
.RS
.IP \(bu 2
List all existing virtual environments:
.RE
.PP
\fB\fCpyenv virtualenvs\fR
.RS
.IP \(bu 2
Activate a virtual environment:
.RE
.PP
\fB\fCpyenv activate {{virtualenv_name}}\fR
.RS
.IP \(bu 2
Deactivate the virtual environment:
.RE
.PP
\fB\fCpyenv deactivate\fR
