.TH pystun3
.PP
.RS
Classic STUN client written in Python.
More information: \[la]https://github.com/talkiq/pystun3\[ra]\&.
.RE
.RS
.IP \(bu 2
Make a STUN request:
.RE
.PP
\fB\fCpystun3\fR
.RS
.IP \(bu 2
Make a STUN request and specify the stun server:
.RE
.PP
\fB\fCpystun3 \-\-stun\-host {{stun.1und1.de}}\fR
.RS
.IP \(bu 2
Make a STUN request and specify the source port:
.RE
.PP
\fB\fCpystun3 \-\-source\-port {{7932}}\fR
