.TH qmmp
.PP
.RS
An audio player.
More information: \[la]http://qmmp.ylsoftware.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch qmmp:
.RE
.PP
\fB\fCqmmp\fR
.RS
.IP \(bu 2
Start or stop the currently playing audio:
.RE
.PP
\fB\fCqmmp \-\-play\-pause\fR
.RS
.IP \(bu 2
Seek forwards or backward a specific amount of time in seconds:
.RE
.PP
\fB\fCqmmp \-\-seek\-{{fwd|bwd}} {{time_in_seconds}}\fR
.RS
.IP \(bu 2
Play the next audio file:
.RE
.PP
\fB\fCqmmp \-\-next\fR
.RS
.IP \(bu 2
Play the previous audio file:
.RE
.PP
\fB\fCqmmp \-\-previous\fR
.RS
.IP \(bu 2
Print the current volume:
.RE
.PP
\fB\fCqmmp \-\-volume\-status\fR
.RS
.IP \(bu 2
Increase or decrease the volume of the currently playing audio by 5 steps:
.RE
.PP
\fB\fCqmmp \-\-volume\-{{inc|dec}}\fR
