.TH qtcreator
.PP
.RS
Cross\-platform IDE for Qt applications.
More information: \[la]https://doc.qt.io/qtcreator/creator-cli.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Qt Creator:
.RE
.PP
\fB\fCqtcreator\fR
.RS
.IP \(bu 2
Start Qt Creator and restore the last session:
.RE
.PP
\fB\fCqtcreator \-lastsession\fR
.RS
.IP \(bu 2
Start Qt Creator but don't load the specified plugin:
.RE
.PP
\fB\fCqtcreator \-noload {{plugin}}\fR
.RS
.IP \(bu 2
Start Qt Creator but don't load any plugins:
.RE
.PP
\fB\fCqtcreator \-noload {{all}}\fR
.RS
.IP \(bu 2
Start Qt Creator in presentation mode with pop\-ups for keyboard shortcuts:
.RE
.PP
\fB\fCqtcreator \-presentationMode\fR
.RS
.IP \(bu 2
Start Qt Creator and show the diff from a specific commit:
.RE
.PP
\fB\fCqtcreator \-git\-show {{commit}}\fR
