.TH railway
.PP
.RS
Connect code to a Railway project.
More information: \[la]https://railway.app/\[ra]\&.
.RE
.RS
.IP \(bu 2
Login to a Railway account:
.RE
.PP
\fB\fCrailway login\fR
.RS
.IP \(bu 2
Link to an existing Project under a Railway account or team:
.RE
.PP
\fB\fCrailway link {{projectId}}\fR
.RS
.IP \(bu 2
Create a new project:
.RE
.PP
\fB\fCrailway init\fR
.RS
.IP \(bu 2
Run a local command using variables from the active environment:
.RE
.PP
\fB\fCrailway run {{cmd}}\fR
.RS
.IP \(bu 2
Deploy the linked project directory (if running from a subdirectory, the project root is still deployed):
.RE
.PP
\fB\fCrailway up\fR
.RS
.IP \(bu 2
Open an interactive shell to a database:
.RE
.PP
\fB\fCrailway connect\fR
