.TH rails
.PP
.RS
A server\-side MVC framework written in Ruby.
Some subcommands such as \fB\fCrails generate\fR have their own usage documentation.
More information: \[la]https://guides.rubyonrails.org/command_line.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new rails project:
.RE
.PP
\fB\fCrails new "{{project_name}}"\fR
.RS
.IP \(bu 2
Start local server for current project on port 3000:
.RE
.PP
\fB\fCrails server\fR
.RS
.IP \(bu 2
Start local server for current project on a specified port:
.RE
.PP
\fB\fCrails server \-p "{{port}}"\fR
.RS
.IP \(bu 2
Open console to interact with application from command\-line:
.RE
.PP
\fB\fCrails console\fR
.RS
.IP \(bu 2
Check current version of rails:
.RE
.PP
\fB\fCrails \-\-version\fR
