.TH rainbowstream
.PP
.RS
Terminal\-based Twitter client supporting realtime tweetstream, trends, sending, search, favorites and user management.
Online help with \fB\fCh\fR, up and down arrows for history, tab to auto\-complete and 2\-tab for suggestion.
More information: \[la]https://github.com/orakaro/rainbowstream\[ra]\&.
.RE
.RS
.IP \(bu 2
Open RainbowStream:
.RE
.PP
\fB\fCrainbowstream\fR
.RS
.IP \(bu 2
Show your timeline (optional number of tweets to display, default is 5):
.RE
.PP
\fB\fChome [{{num_of_last_tweets}}]\fR
.RS
.IP \(bu 2
Show profile of a given user:
.RE
.PP
\fB\fCwhois @{{user}}\fR
.RS
.IP \(bu 2
Tweet the message as\-is:
.RE
.PP
\fB\fCt {{message}}\fR
.RS
.IP \(bu 2
Retweet the tweet with given ID (ID is beside the time):
.RE
.PP
\fB\fCrt {{tweet_id}}\fR
.RS
.IP \(bu 2
Favorite the tweet with given ID:
.RE
.PP
\fB\fCfav {{tweet_id}}\fR
.RS
.IP \(bu 2
Perform a search for a given word (with or without hashtag):
.RE
.PP
\fB\fCs {{word}}\fR
