.TH ranger
.PP
.RS
Console file manager with VI key bindings.
More information: \[la]https://github.com/ranger/ranger\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch ranger:
.RE
.PP
\fB\fCranger\fR
.RS
.IP \(bu 2
Show only directories:
.RE
.PP
\fB\fCranger \-\-show\-only\-dirs\fR
.RS
.IP \(bu 2
Change the configuration directory:
.RE
.PP
\fB\fCranger \-\-confdir={{path/to/directory}}\fR
.RS
.IP \(bu 2
Change the data directory:
.RE
.PP
\fB\fCranger \-\-datadir={{path/to/directory}}\fR
.RS
.IP \(bu 2
Print CPU usage statistics on exit:
.RE
.PP
\fB\fCranger \-\-profile\fR
