.TH rapper
.PP
.RS
The Raptor RDF parsing utility.
Part of the Raptor RDF Syntax Library.
More information: \[la]http://librdf.org/raptor/rapper.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert an RDF/XML document to Turtle:
.RE
.PP
\fB\fCrapper \-i rdfxml \-o turtle {{path/to/file}}\fR
.RS
.IP \(bu 2
Count the number of triples in a Turtle file:
.RE
.PP
\fB\fCrapper \-i turtle \-c {{path/to/file}}\fR
