.TH rarcrack
.PP
.RS
Password cracker for rar, zip and 7z archives.
.RE
.RS
.IP \(bu 2
Brute force the password for an archive (tries to guess the archive type):
.RE
.PP
\fB\fCrarcrack {{path/to/file.zip}}\fR
.RS
.IP \(bu 2
Specify the archive type:
.RE
.PP
\fB\fCrarcrack \-\-type {{rar|zip|7z}} {{path/to/file.zip}}\fR
.RS
.IP \(bu 2
Use multiple threads:
.RE
.PP
\fB\fCrarcrack \-\-threads {{6}} {{path/to/file.zip}}\fR
