.TH rbt
.PP
.RS
RBTools is a set of command\-line tools for working with Review Board and RBCommons.
More information: \[la]https://www.reviewboard.org/docs/rbtools/dev/\[ra]\&.
.RE
.RS
.IP \(bu 2
Post changes to Review Board:
.RE
.PP
\fB\fCrbt post {{change_number}}\fR
.RS
.IP \(bu 2
Display the diff that will be sent to Review Board:
.RE
.PP
\fB\fCrbt diff\fR
.RS
.IP \(bu 2
Land a change in a local branch or on a review request:
.RE
.PP
\fB\fCrbt land {{branch_name}}\fR
.RS
.IP \(bu 2
Patch your tree with a change on a review request:
.RE
.PP
\fB\fCrbt patch {{review_request_id}}\fR
.RS
.IP \(bu 2
Set up RBTool to talk to a repository:
.RE
.PP
\fB\fCrbt setup\-repo\fR
