.TH rc
.PP
.RS
A modern simplistic port listener & reverse shell.
Similar to \fB\fCnc\fR\&.
More information: \[la]https://github.com/robiot/rustcat/wiki/Basic-Usage\[ra]\&.
.RE
.RS
.IP \(bu 2
Start listening on a specific port:
.RE
.PP
\fB\fCrc \-lp {{port}}\fR
.RS
.IP \(bu 2
Start a reverse shell:
.RE
.PP
\fB\fCrc {{host}} {{port}} \-r {{shell}}\fR
