.TH react\-native
.PP
.RS
A framework for building native apps with React.
More information: \[la]https://reactnative.dev\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new React Native project in a directory of the same name:
.RE
.PP
\fB\fCreact\-native init {{project_name}}\fR
.RS
.IP \(bu 2
Start the metro bundler:
.RE
.PP
\fB\fCreact\-native start\fR
.RS
.IP \(bu 2
Start the metro bundler with a clean cache:
.RE
.PP
\fB\fCreact\-native start \-\-reset\-cache\fR
.RS
.IP \(bu 2
Build the current application and start it on a connected Android device or emulator:
.RE
.PP
\fB\fCreact\-native run\-android\fR
.RS
.IP \(bu 2
Build the current application and start it on an iOS simulator:
.RE
.PP
\fB\fCreact\-native run\-ios\fR
.RS
.IP \(bu 2
Build the current application in \fB\fCrelease\fR mode and start it on a connected Android device or emulator:
.RE
.PP
\fB\fCreact\-native run\-android \-\-variant={{release}}\fR
.RS
.IP \(bu 2
Start \fB\fClogkitty\fR and print logs to \fB\fCstdout\fR:
.RE
.PP
\fB\fCreact\-native log\-android\fR
.RS
.IP \(bu 2
Start \fB\fCtail system.log\fR for an iOS simulator and print logs to \fB\fCstdout\fR:
.RE
.PP
\fB\fCreact\-native log\-ios\fR
