.TH readlink
.PP
.RS
Follow symlinks and get symlink information.
More information: \[la]https://www.gnu.org/software/coreutils/readlink\[ra]\&.
.RE
.RS
.IP \(bu 2
Get the actual file to which the symlink points:
.RE
.PP
\fB\fCreadlink {{path/to/file}}\fR
.RS
.IP \(bu 2
Get the absolute path to a file:
.RE
.PP
\fB\fCreadlink \-f {{path/to/file}}\fR
