.TH rector
.PP
.RS
An automated tool for updating and refactoring PHP 5.3+ code.
More information: \[la]https://github.com/rectorphp/rector\[ra]\&.
.RE
.RS
.IP \(bu 2
Process a specific directory:
.RE
.PP
\fB\fCrector process {{path/to/directory}}\fR
.RS
.IP \(bu 2
Process a directory without applying changes (dry run):
.RE
.PP
\fB\fCrector process {{path/to/directory}} \-\-dry\-run\fR
.RS
.IP \(bu 2
Process a directory and apply coding standards:
.RE
.PP
\fB\fCrector process {{path/to/directory}} \-\-with\-style\fR
.RS
.IP \(bu 2
Display a list of available levels:
.RE
.PP
\fB\fCrector levels\fR
.RS
.IP \(bu 2
Process a directory with a specific level:
.RE
.PP
\fB\fCrector process {{path/to/directory}} \-\-level {{level_name}}\fR
