.TH resume
.PP
.RS
Easily setup a new resume.
More information: \[la]https://github.com/jsonresume/resume-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new \fB\fCresume.json\fR file in the current working directory:
.RE
.PP
\fB\fCresume init\fR
.RS
.IP \(bu 2
Validate a \fB\fCresume.json\fR against schema tests to ensure it complies with the standard:
.RE
.PP
\fB\fCresume validate\fR
.RS
.IP \(bu 2
Export a resume locally in a stylized HTML or PDF format:
.RE
.PP
\fB\fCresume export {{path/to/html_or_pdf}}\fR
.RS
.IP \(bu 2
Start a web server that serves a local \fB\fCresume.json\fR:
.RE
.PP
\fB\fCresume serve\fR
