.TH rfetch
.PP
.RS
A configurable fetch program to output system information.
More information: \[la]https://github.com/kamui-fin/rfetch\[ra]\&.
.RE
.RS
.IP \(bu 2
Display system information:
.RE
.PP
\fB\fCrfetch\fR
.RS
.IP \(bu 2
Display system [a]rchitecture:
.RE
.PP
\fB\fCrfetch \-a\fR
.RS
.IP \(bu 2
Display system up[t]ime:
.RE
.PP
\fB\fCrfetch \-t\fR
.RS
.IP \(bu 2
Display system [k]ernel:
.RE
.PP
\fB\fCrfetch \-k\fR
.RS
.IP \(bu 2
Display system [c]PU:
.RE
.PP
\fB\fCrfetch \-c\fR
.RS
.IP \(bu 2
Display Linux [D]istro:
.RE
.PP
\fB\fCrfetch \-D\fR
.RS
.IP \(bu 2
View [d]esktop environment:
.RE
.PP
\fB\fCrfetch \-d\fR
