.TH rmdir
.PP
.RS
Remove directories without files.
See also: \fB\fCrm\fR\&.
More information: \[la]https://www.gnu.org/software/coreutils/rmdir\[ra]\&.
.RE
.RS
.IP \(bu 2
Remove specific directories:
.RE
.PP
\fB\fCrmdir {{path/to/directory1 path/to/directory2 ...}}\fR
.RS
.IP \(bu 2
Remove specific nested directories recursively:
.RE
.PP
\fB\fCrmdir \-p {{path/to/directory1 path/to/directory2 ...}}\fR
