.TH robo
.PP
.RS
PHP task runner.
More information: \[la]https://robo.li/\[ra]\&.
.RE
.RS
.IP \(bu 2
List available commands:
.RE
.PP
\fB\fCrobo list\fR
.RS
.IP \(bu 2
Run a specific command:
.RE
.PP
\fB\fCrobo {{foo}}\fR
.RS
.IP \(bu 2
Simulate running a specific command:
.RE
.PP
\fB\fCrobo \-\-simulate {{foo}}\fR
