.TH rr
.PP
.RS
Debugging tool designed to record and replay program execution.
More information: \[la]https://rr-project.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Record an application:
.RE
.PP
\fB\fCrr record {{path/to/binary \-\-arg1 \-\-arg2}}\fR
.RS
.IP \(bu 2
Replay latest recorded execution:
.RE
.PP
\fB\fCrr replay\fR
