.TH rss2email
.PP
.RS
Tool for delivering news from RSS feeds to an email program.
More information: \[la]https://github.com/rss2email/rss2email\[ra]\&.
.RE
.RS
.IP \(bu 2
List all feeds:
.RE
.PP
\fB\fCr2e list\fR
.RS
.IP \(bu 2
Convert RSS entries to email:
.RE
.PP
\fB\fCr2e run\fR
.RS
.IP \(bu 2
Add a feed:
.RE
.PP
\fB\fCr2e add {{feed_address}}\fR
.RS
.IP \(bu 2
Add a feed with a specific email address:
.RE
.PP
\fB\fCr2e add {{feed_address}} {{new_email@example.com}}\fR
.RS
.IP \(bu 2
Delete a specific feed:
.RE
.PP
\fB\fCr2e delete {{number_of_feed_in_list}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCr2e \-h\fR
