.TH rtl_sdr
.PP
.RS
Raw data recorder for RTL\-SDR receivers.
Data is encoded using I/Q sampling (aka quadrature sampling).
More information: \[la]https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr\[ra]\&.
.RE
.RS
.IP \(bu 2
Save RAW data from a frequency (specified in Hz) to a file:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Pipe data to another program:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \- | {{aplay}}\fR
.RS
.IP \(bu 2
Read a specified number of samples:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-n {{20}} \-\fR
.RS
.IP \(bu 2
Specify the sample rate in Hz (ranges 225001\-300000 and 900001\-3200000):
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-s {{2400000}} \-\fR
.RS
.IP \(bu 2
Specify the device by its index:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-d {{0}} \-\fR
.RS
.IP \(bu 2
Specify the gain:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-g {{20}} \-\fR
.RS
.IP \(bu 2
Specify the output block size:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-b {{9999999}} \-\fR
.RS
.IP \(bu 2
Use synchronous output:
.RE
.PP
\fB\fCrtl_sdr \-f {{100000000}} \-S \-\fR
