.TH rtv
.PP
.RS
Reddit Terminal Viewer.
Use arrow keys to navigate. Right and Left to view and return from a submission, respectively.
More information: \[la]https://github.com/michael-lazar/rtv\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the front page:
.RE
.PP
\fB\fC/front\fR
.RS
.IP \(bu 2
Open a subreddit:
.RE
.PP
\fB\fC/r/{{subreddit_name}}\fR
.RS
.IP \(bu 2
Expand/collapse comments:
.RE
.PP
\fB\fC[space]\fR
.RS
.IP \(bu 2
Open link:
.RE
.PP
\fB\fCo\fR
.RS
.IP \(bu 2
Log in:
.RE
.PP
\fB\fCu\fR
.RS
.IP \(bu 2
Open the help screen:
.RE
.PP
\fB\fC?\fR
