.TH runsvdir
.PP
.RS
Run an entire directory of services.
More information: \[la]https://manpages.ubuntu.com/manpages/latest/man8/runsvdir.8.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start and manage all services in a directory as the current user:
.RE
.PP
\fB\fCrunsvdir {{path/to/services}}\fR
.RS
.IP \(bu 2
Start and manage all services in a directory as root:
.RE
.PP
\fB\fCsudo runsvdir {{path/to/services}}\fR
.RS
.IP \(bu 2
Start services in separate sessions:
.RE
.PP
\fB\fCrunsvdir \-P {{path/to/services}}\fR
