.TH runsv
.PP
.RS
Start and manage a runit service.
More information: \[la]https://manpages.ubuntu.com/manpages/latest/man8/runsv.8.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a runit service as the current user:
.RE
.PP
\fB\fCrunsv {{path/to/service}}\fR
.RS
.IP \(bu 2
Start a runit service as root:
.RE
.PP
\fB\fCsudo runsv {{path/to/service}}\fR
