.TH rustup component
.PP
.RS
Modify a toolchain's installed components.
Without the \fB\fC\-\-toolchain\fR option \fB\fCrustup\fR will use the default toolchain. See \fB\fCrustup help toolchain\fR for more information about toolchains.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Add a component to a toolchain:
.RE
.PP
\fB\fCrustup component add \-\-toolchain {{toolchain}} {{component}}\fR
.RS
.IP \(bu 2
Remove a component from a toolchain:
.RE
.PP
\fB\fCrustup component remove \-\-toolchain {{toolchain}} {{component}}\fR
.RS
.IP \(bu 2
List installed and available components for a toolchain:
.RE
.PP
\fB\fCrustup component list \-\-toolchain {{toolchain}}\fR
.RS
.IP \(bu 2
List installed components for a toolchain:
.RE
.PP
\fB\fCrustup component list \-\-toolchain {{toolchain}} \-\-installed\fR
