.TH rustup update
.PP
.RS
Update Rust toolchains and \fB\fCrustup\fR itself (if not installed using a package manager).
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Update all installed toolchains and \fB\fCrustup\fR:
.RE
.PP
\fB\fCrustup update\fR
.RS
.IP \(bu 2
Install or update a specific toolchain (see \fB\fCrustup help toolchain\fR for more information):
.RE
.PP
\fB\fCrustup update {{toolchain}}\fR
