.TH rustic
.PP
.RS
Create fast, encrypted, deduplicated backups powered by Rust.
More information: \[la]https://github.com/rustic-rs/rustic\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new repository:
.RE
.PP
\fB\fCrustic init \-\-repository {{/srv/rustic\-repo}}\fR
.RS
.IP \(bu 2
Create a new backup of a file/directory to a repository:
.RE
.PP
\fB\fCrustic backup \-\-repository {{/srv/rustic\-repo}} {{path/to/file_or_directory}}\fR
