.TH rustup doc
.PP
.RS
Open the offline Rust documentation for the current toolchain.
There are a lot more documentation pages not mentioned here. See \fB\fCrustup help doc\fR for more information.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the main page:
.RE
.PP
\fB\fCrustup doc\fR
.RS
.IP \(bu 2
Open the documentation for a specific topic (a module in the standard library, a type, a keyword, etc.):
.RE
.PP
\fB\fCrustup doc {{std::fs|usize|fn|...}}\fR
.RS
.IP \(bu 2
Open the Rust Programming Language book:
.RE
.PP
\fB\fCrustup doc \-\-book\fR
.RS
.IP \(bu 2
Open the Cargo book:
.RE
.PP
\fB\fCrustup doc \-\-cargo\fR
.RS
.IP \(bu 2
Open the Rust Reference:
.RE
.PP
\fB\fCrustup doc \-\-reference\fR
