.TH rustup man
.PP
.RS
View the man page for a given command managed by \fB\fCrustup\fR\&.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
View the man page for a given command from the default toolchain:
.RE
.PP
\fB\fCrustup man {{command}}\fR
.RS
.IP \(bu 2
View the man page for a given command from the specified toolchain:
.RE
.PP
\fB\fCrustup man \-\-toolchain {{command}}\fR
