.TH rustup help
.PP
.RS
Display help on \fB\fCrustup\fR and its subcommands.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Display general help:
.RE
.PP
\fB\fCrustup help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCrustup help {{subcommand}}\fR
