.TH rustup completions
.PP
.RS
Generate shell completions for \fB\fCrustup\fR and \fB\fCcargo\fR\&.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the completion script to \fB\fCstdout\fR:
.RE
.PP
\fB\fCrustup completions {{bash|elvish|fish|powershell|zsh}} {{rustup|cargo}}\fR
