.TH rustup run
.PP
.RS
Run a command with an environment configured for a given Rust toolchain.
Note: all commands managed by \fB\fCrustup\fR have a shorthand for this: for example, \fB\fCcargo +nightly build\fR is equivalent to \fB\fCrustup run nightly cargo build\fR\&.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a command using a given Rust toolchain (see \fB\fCrustup help toolchain\fR for more information):
.RE
.PP
\fB\fCrustup run {{toolchain}} {{command}}\fR
