.TH rustup show
.PP
.RS
Show installed toolchains, targets and the version of \fB\fCrustc\fR\&.
More information: \[la]https://rust-lang.github.io/rustup\[ra]\&.
.RE
.RS
.IP \(bu 2
Show all information:
.RE
.PP
\fB\fCrustup show\fR
.RS
.IP \(bu 2
Show the active toolchain:
.RE
.PP
\fB\fCrustup show active\-toolchain\fR
.RS
.IP \(bu 2
Show the rustup data directory:
.RE
.PP
\fB\fCrustup show home\fR
