.TH sails
.PP
.RS
Sails.js is a realtime enterprise level MVC framework built on top of Node.js.
More information: \[la]https://sailsjs.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Sails:
.RE
.PP
\fB\fCsails lift\fR
.RS
.IP \(bu 2
Create new Sails project:
.RE
.PP
\fB\fCsails new {{projectName}}\fR
.RS
.IP \(bu 2
Generate Sails API:
.RE
.PP
\fB\fCsails generate {{name}}\fR
.RS
.IP \(bu 2
Generate Sails Controller:
.RE
.PP
\fB\fCsails generate controller {{name}}\fR
.RS
.IP \(bu 2
Generate Sails Model:
.RE
.PP
\fB\fCsails generate model {{name}}\fR
