.TH salt\-run
.PP
.RS
Frontend for executing salt\-runners on minions.
More information: \[la]https://docs.saltstack.com/ref/cli/salt-run.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Show status of all minions:
.RE
.PP
\fB\fCsalt\-run manage.status\fR
.RS
.IP \(bu 2
Show all minions which are disconnected:
.RE
.PP
\fB\fCsalt\-run manage.up\fR
