.TH SC\-IM
.PP
.RS
A curses based, vim\-like spreadsheet calculator.
Use hjkl or arrow keys to navigate.
More information: \[la]https://github.com/andmarti1424/sc-im\[ra]\&.
.RE
.RS
.IP \(bu 2
Start SC\-IM:
.RE
.PP
\fB\fCscim {{path/to/file.csv}}\fR
.RS
.IP \(bu 2
Enter a string into the current cell:
.RE
.PP
\fB\fC< or >\fR
.RS
.IP \(bu 2
Enter a numeric constant into the current cell:
.RE
.PP
\fB\fC=\fR
.RS
.IP \(bu 2
Edit string in the current cell:
.RE
.PP
\fB\fCE\fR
.RS
.IP \(bu 2
Edit number in the current cell:
.RE
.PP
\fB\fCe\fR
.RS
.IP \(bu 2
Center align the current cell:
.RE
.PP
\fB\fC|\fR
