.TH scalafmt
.PP
.RS
Code formatter for Scala.
Configurations are stored in the \fB\fC\&.scalafmt.conf\fR file.
More information: \[la]https://scalameta.org/scalafmt\[ra]\&.
.RE
.RS
.IP \(bu 2
Reformat all \fB\fC\&.scala\fR files in the current directory recursively:
.RE
.PP
\fB\fCscalafmt\fR
.RS
.IP \(bu 2
Reformat specific files or directories with a custom formatting configuration:
.RE
.PP
\fB\fCscalafmt \-\-config {{path/to/.scalafmt.conf}} {{path/to/file_or_directory}} {{path/to/file_or_directory}} {{...}}\fR
.RS
.IP \(bu 2
Check if files are correctly formatted, returning \fB\fC0\fR if all files respect the formatting style:
.RE
.PP
\fB\fCscalafmt \-\-config {{path/to/.scalafmt.conf}} \-\-test\fR
.RS
.IP \(bu 2
Exclude files or directories:
.RE
.PP
\fB\fCscalafmt \-\-exclude {{path/to/file_or_directory}} {{...}}\fR
.RS
.IP \(bu 2
Format only files that were edited against the current Git branch:
.RE
.PP
\fB\fCscalafmt \-\-config {{path/to/.scalafmt.conf}} \-\-mode diff\fR
