.TH scan\-build
.PP
.RS
Command\-line utility to run a static analyzer over a codebase as part of performing a regular build.
More information: \[la]https://clang-analyzer.llvm.org/scan-build.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Build and analyze the project in the current directory:
.RE
.PP
\fB\fCscan\-build {{make}}\fR
.RS
.IP \(bu 2
Run a command and pass all subsequent options to it:
.RE
.PP
\fB\fCscan\-build {{command}} {{command_arguments}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCscan\-build\fR
