.TH screenfetch
.PP
.RS
Display system information.
More information: \[la]https://github.com/KittyKatt/screenFetch\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCscreenfetch\fR:
.RE
.PP
\fB\fCscreenfetch\fR
.RS
.IP \(bu 2
Take a screenshot (requires 'scrot'):
.RE
.PP
\fB\fCscreenfetch \-s\fR
.RS
.IP \(bu 2
Specify distribution logo:
.RE
.PP
\fB\fCscreenfetch \-A '{{distribution_name}}'\fR
.RS
.IP \(bu 2
Specify distribution logo and text:
.RE
.PP
\fB\fCscreenfetch \-D '{{distribution_name}}'\fR
.RS
.IP \(bu 2
Strip all color:
.RE
.PP
\fB\fCscreenfetch \-N\fR
