.TH sdkmanager
.PP
.RS
Tool to install packages for the Android SDK.
More information: \[la]https://developer.android.com/studio/command-line/sdkmanager\[ra]\&.
.RE
.RS
.IP \(bu 2
List available packages:
.RE
.PP
\fB\fCsdkmanager \-\-list\fR
.RS
.IP \(bu 2
Install a package:
.RE
.PP
\fB\fCsdkmanager {{package}}\fR
.RS
.IP \(bu 2
Update every installed package:
.RE
.PP
\fB\fCsdkmanager \-\-update\fR
.RS
.IP \(bu 2
Uninstall a package:
.RE
.PP
\fB\fCsdkmanager \-\-uninstall {{package}}\fR
