.TH secrethub
.PP
.RS
A tool to keep secrets out of config files.
More information: \[la]https://secrethub.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Print a secret to \fB\fCstdout\fR:
.RE
.PP
\fB\fCsecrethub read {{path/to/secret}}\fR
.RS
.IP \(bu 2
Generate a random value and store it as a new or updated secret:
.RE
.PP
\fB\fCsecrethub generate {{path/to/secret}}\fR
.RS
.IP \(bu 2
Store a value from the clipboard as a new or updated secret:
.RE
.PP
\fB\fCsecrethub write \-\-clip {{path/to/secret}}\fR
.RS
.IP \(bu 2
Store a value supplied on \fB\fCstdin\fR as a new or updated secret:
.RE
.PP
\fB\fCecho "{{secret_value}}" | secrethub write {{path/to/secret}}\fR
.RS
.IP \(bu 2
Audit a repository or secret:
.RE
.PP
\fB\fCsecrethub audit {{path/to/repo_or_secret}}\fR
