.TH Set\-NodeInstallLocation
.PP
.RS
Set the default Node.js installation directory for \fB\fCps\-nvm\fR\&.
This command is part of \fB\fCps\-nvm\fR and can only be run under PowerShell.
More information: \[la]https://github.com/aaronpowell/ps-nvm\[ra]\&.
.RE
.RS
.IP \(bu 2
Change the Node.js install location to a specified directory (\fB\fCps\-nvm\fR will create a new \fB\fC\&.nvm\fR subdirectory to install them):
.RE
.PP
\fB\fCSet\-NodeInstallLocation {{path/to/directory}}\fR
