.TH set
.PP
.RS
Display, set or unset values of shell attributes and positional parameters.
More information: \[la]https://manned.org/set\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the names and values of shell variables:
.RE
.PP
\fB\fCset\fR
.RS
.IP \(bu 2
Mark variables that are modified or created for export:
.RE
.PP
\fB\fCset \-a\fR
.RS
.IP \(bu 2
Notify of job termination immediately:
.RE
.PP
\fB\fCset \-b\fR
.RS
.IP \(bu 2
Set various options, e.g. enable \fB\fCvi\fR style line editing:
.RE
.PP
\fB\fCset \-o {{vi}}\fR
.RS
.IP \(bu 2
Set the shell to exit as soon as the first error is encountered (mostly used in scripts):
.RE
.PP
\fB\fCset \-e\fR
