.TH sh
.PP
.RS
Bourne shell, the standard command language interpreter.
See also \fB\fChistexpand\fR for history expansion.
More information: \[la]https://manned.org/sh\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive shell session:
.RE
.PP
\fB\fCsh\fR
.RS
.IP \(bu 2
Execute a command and then exit:
.RE
.PP
\fB\fCsh \-c "{{command}}"\fR
.RS
.IP \(bu 2
Execute a script:
.RE
.PP
\fB\fCsh {{path/to/script.sh}}\fR
.RS
.IP \(bu 2
Read and execute commands from \fB\fCstdin\fR:
.RE
.PP
\fB\fCsh \-s\fR
