.TH shards
.PP
.RS
Dependency management tool for the Crystal language.
More information: \[la]https://crystal-lang.org/reference/the_shards_command\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a skeleton \fB\fCshard.yml\fR file:
.RE
.PP
\fB\fCshards init\fR
.RS
.IP \(bu 2
Install dependencies from a \fB\fCshard.yml\fR file:
.RE
.PP
\fB\fCshards install\fR
.RS
.IP \(bu 2
Update all dependencies:
.RE
.PP
\fB\fCshards update\fR
.RS
.IP \(bu 2
List all installed dependencies:
.RE
.PP
\fB\fCshards list\fR
.RS
.IP \(bu 2
List version of dependency:
.RE
.PP
\fB\fCshards version {{path/to/dependency_directory}}\fR
