.TH shasum
.PP
.RS
Calculate SHA cryptographic checksums.
More information: \[la]https://manned.org/shasum\[ra]\&.
.RE
.RS
.IP \(bu 2
Calculate the SHA1 checksum for one or more files:
.RE
.PP
\fB\fCshasum {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Calculate the SHA256 checksum for one or more files:
.RE
.PP
\fB\fCshasum \-\-algorithm 256 {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Calculate the SHA512 checksum for one or more files:
.RE
.PP
\fB\fCshasum \-\-algorithm 512 {{path/to/file1 path/to/file2 ...}}\fR
.RS
.IP \(bu 2
Calculate a SHA1 checksum from \fB\fCstdin\fR:
.RE
.PP
\fB\fC{{command}} | shasum\fR
.RS
.IP \(bu 2
Calculate and save the list of SHA256 checksums to a file:
.RE
.PP
\fB\fCshasum \-\-algorithm 256 {{path/to/file1 path/to/file2 ...}} > {{path/to/file.sha256}}\fR
.RS
.IP \(bu 2
Read a file of SHA1 sums and filenames and verify all files have matching checksums:
.RE
.PP
\fB\fCshasum \-\-check {{path/to/file}}\fR
.RS
.IP \(bu 2
Only show a message for missing files or when verification fails:
.RE
.PP
\fB\fCshasum \-\-check \-\-quiet {{path/to/file}}\fR
.RS
.IP \(bu 2
Only show a message when verification fails, ignoring missing files:
.RE
.PP
\fB\fCshasum \-\-ignore\-missing \-\-check \-\-quiet {{path/to/file}}\fR
