.TH shift
.PP
.RS
Shell built\-in command that shifts the arguments passed to the calling function or script by a specified number of places.
More information: \[la]https://www.gnu.org/software/bash/manual/bash.html#index-shift\[ra]\&.
.RE
.RS
.IP \(bu 2
Move arguments by one place dropping the first argument:
.RE
.PP
\fB\fCshift\fR
.RS
.IP \(bu 2
Move arguments by N places dropping the first N arguments:
.RE
.PP
\fB\fCshift {{N}}\fR
