.TH showfigfonts
.PP
.RS
Display available figlet fonts.
See also \fB\fCfiglet\fR\&.
More information: \[la]https://manned.org/showfigfonts\[ra]\&.
.RE
.RS
.IP \(bu 2
Display available fonts:
.RE
.PP
\fB\fCshowfigfonts\fR
.RS
.IP \(bu 2
Display available fonts using a specific text:
.RE
.PP
\fB\fCshowfigfonts {{input_text}}\fR
