.TH skicka
.PP
.RS
Manage your Google Drive.
More information: \[la]https://github.com/google/skicka\[ra]\&.
.RE
.RS
.IP \(bu 2
Upload a file/folder to Google Drive:
.RE
.PP
\fB\fCskicka upload {{path/to/local}} {{path/to/remote}}\fR
.RS
.IP \(bu 2
Download a file/folder from Google Drive:
.RE
.PP
\fB\fCskicka download {{path/to/remote}} {{path/to/local}}\fR
.RS
.IP \(bu 2
List files:
.RE
.PP
\fB\fCskicka ls {{path/to/folder}}\fR
.RS
.IP \(bu 2
Show amount of space used by children folders:
.RE
.PP
\fB\fCskicka du {{path/to/parent/folder}}\fR
.RS
.IP \(bu 2
Create a folder:
.RE
.PP
\fB\fCskicka mkdir {{path/to/folder}}\fR
.RS
.IP \(bu 2
Delete a file:
.RE
.PP
\fB\fCskicka rm {{path/to/file}}\fR
