.TH sl
.PP
.RS
Steam locomotive running through your terminal.
More information: \[la]https://github.com/mtoyoda/sl\[ra]\&.
.RE
.RS
.IP \(bu 2
Let a steam locomotive run through your terminal:
.RE
.PP
\fB\fCsl\fR
.RS
.IP \(bu 2
The train burns, people scream:
.RE
.PP
\fB\fCsl \-a\fR
.RS
.IP \(bu 2
Let the train fly:
.RE
.PP
\fB\fCsl \-F\fR
.RS
.IP \(bu 2
Make the train little:
.RE
.PP
\fB\fCsl \-l\fR
.RS
.IP \(bu 2
Let the user exit (CTRL + C):
.RE
.PP
\fB\fCsl \-e\fR
