.TH sleep
.PP
.RS
Delay for a specified amount of time.
More information: \[la]https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sleep.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Delay in seconds:
.RE
.PP
\fB\fCsleep {{seconds}}\fR
.RS
.IP \(bu 2
Execute a specific command after 20 seconds delay:
.RE
.PP
\fB\fCsleep 20 && {{command}}\fR
