.TH slimrb
.PP
.RS
Convert Slim files to HTML.
More information: \[la]https://rdoc.info/gems/slim/frames#slim-command-slimrb\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert a Slim file to HTML:
.RE
.PP
\fB\fCslimrb {{input.slim}} {{output.html}}\fR
.RS
.IP \(bu 2
Convert a Slim file and output to prettified HTML:
.RE
.PP
\fB\fCslimrb \-\-pretty {{input.slim}} {{output.html}}\fR
.RS
.IP \(bu 2
Convert a Slim file to ERB:
.RE
.PP
\fB\fCslimrb \-\-erb {{input.slim}} {{output.erb}}\fR
