.TH snyk
.PP
.RS
Find vulnerabilities in your code and remediate risks.
More information: \[la]https://snyk.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Log in to your Snyk account:
.RE
.PP
\fB\fCsnyk auth\fR
.RS
.IP \(bu 2
Test your code for any known vulnerabilities:
.RE
.PP
\fB\fCsnyk test\fR
.RS
.IP \(bu 2
Test a local Docker image for any known vulnerabilities:
.RE
.PP
\fB\fCsnyk test \-\-docker {{docker_image}}\fR
.RS
.IP \(bu 2
Record the state of dependencies and any vulnerabilities on snyk.io:
.RE
.PP
\fB\fCsnyk monitor\fR
.RS
.IP \(bu 2
Auto patch and ignore vulnerabilities:
.RE
.PP
\fB\fCsnyk wizard\fR
