.TH source
.PP
.RS
Execute commands from a file in the current shell.
More information: \[la]https://manned.org/source\[ra]\&.
.RE
.RS
.IP \(bu 2
Evaluate contents of a given file:
.RE
.PP
\fB\fCsource {{path/to/file}}\fR
.RS
.IP \(bu 2
Evaluate contents of a given file (alternatively replacing \fB\fCsource\fR with \fB\fC\&.\fR):
.RE
.PP
\fB\fC\&. {{path/to/file}}\fR
