.TH spark
.PP
.RS
The Laravel Spark command\-line tool.
More information: \[la]https://spark.laravel.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Register your API token:
.RE
.PP
\fB\fCspark register {{token}}\fR
.RS
.IP \(bu 2
Display the currently registered API token:
.RE
.PP
\fB\fCspark token\fR
.RS
.IP \(bu 2
Create a new Spark project:
.RE
.PP
\fB\fCspark new {{project_name}}\fR
.RS
.IP \(bu 2
Create a new Spark project with Braintree stubs:
.RE
.PP
\fB\fCspark new {{project_name}} \-\-braintree\fR
.RS
.IP \(bu 2
Create a new Spark project with team\-based billing stubs:
.RE
.PP
\fB\fCspark new {{project_name}} \-\-team\-billing\fR
