.TH spectacle
.PP
.RS
KDE's screenshot utility.
More information: \[la]https://manned.org/spectacle\[ra]\&.
.RE
.RS
.IP \(bu 2
Capture a screenshot of the entire desktop:
.RE
.PP
\fB\fCspectacle\fR
.RS
.IP \(bu 2
Capture a screenshot of the active window:
.RE
.PP
\fB\fCspectacle \-\-activewindow\fR
.RS
.IP \(bu 2
Capture a screenshot of a specific region:
.RE
.PP
\fB\fCspectacle \-\-region\fR
