.TH speedcrunch
.PP
.RS
A high\-precision scientific calculator.
More information: \[la]https://www.speedcrunch.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start SpeedCrunch:
.RE
.PP
\fB\fCspeedcrunch\fR
.RS
.IP \(bu 2
Copy the result of the most recent calculation:
.RE
.PP
\fB\fCCtrl + R\fR
.RS
.IP \(bu 2
Open the formula book:
.RE
.PP
\fB\fCCtrl + 1\fR
.RS
.IP \(bu 2
Clear the calculator of recent calculations:
.RE
.PP
\fB\fCCtrl + N\fR
.RS
.IP \(bu 2
Wrap highlighted in parentheses (defaults to wrapping all if nothing selected):
.RE
.PP
\fB\fCCtrl + P\fR
.RS
.IP \(bu 2
Load a speedcrunch session:
.RE
.PP
\fB\fCCtrl + L\fR
.RS
.IP \(bu 2
Save a speedcrunch session:
.RE
.PP
\fB\fCCtrl + S\fR
.RS
.IP \(bu 2
Toggle keypad:
.RE
.PP
\fB\fCCtrl + K\fR
