.TH speed\-test
.PP
.RS
Test your internet connection speed and ping using \[la]https://speedtest.net\[ra]\&.
More information: \[la]https://github.com/sindresorhus/speed-test\[ra]\&.
.RE
.RS
.IP \(bu 2
Test your internet connection and ping speed:
.RE
.PP
\fB\fCspeed\-test\fR
.RS
.IP \(bu 2
Output the results as JSON:
.RE
.PP
\fB\fCspeed\-test \-\-json\fR
.RS
.IP \(bu 2
Output the results in megabytes per second (MBps):
.RE
.PP
\fB\fCspeed\-test \-\-bytes\fR
.RS
.IP \(bu 2
Output more detailed information:
.RE
.PP
\fB\fCspeed\-test \-\-verbose\fR
