.TH spicetify
.PP
.RS
Customize the Spotify client UI and functionality.
More information: \[la]https://spicetify.app\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate a configuration file on very first run and display help:
.RE
.PP
\fB\fCspicetify\fR
.RS
.IP \(bu 2
Backup and preprocess Spotify application files:
.RE
.PP
\fB\fCspicetify backup\fR
.RS
.IP \(bu 2
Print all configuration fields and values:
.RE
.PP
\fB\fCspicetify config\fR
.RS
.IP \(bu 2
Change the value of a configuration field:
.RE
.PP
\fB\fCspicetify config {{field}} {{value}}\fR
.RS
.IP \(bu 2
Apply the customization changes to Spotify:
.RE
.PP
\fB\fCspicetify apply\fR
.RS
.IP \(bu 2
Restore Spotify to its original state:
.RE
.PP
\fB\fCspicetify restore\fR
