.TH spike
.PP
.RS
A fully featured static website generator written in JavaScript.
More information: \[la]https://spike.js.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new project using the default template:
.RE
.PP
\fB\fCspike new {{project_name}}\fR
.RS
.IP \(bu 2
Compile your project, watch for changes, and auto\-reload the browser:
.RE
.PP
\fB\fCspike watch\fR
.RS
.IP \(bu 2
Compile your project once to the "public" directory:
.RE
.PP
\fB\fCspike compile\fR
.RS
.IP \(bu 2
Remove the output directory:
.RE
.PP
\fB\fCspike clean\fR
