.TH split
.PP
.RS
Split a file into pieces.
More information: \[la]https://www.gnu.org/software/coreutils/split\[ra]\&.
.RE
.RS
.IP \(bu 2
Split a file, each split having 10 lines (except the last split):
.RE
.PP
\fB\fCsplit \-l {{10}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Split a file into 5 files. File is split such that each split has same size (except the last split):
.RE
.PP
\fB\fCsplit \-n {{5}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Split a file with 512 bytes in each split (except the last split; use 512k for kilobytes and 512m for megabytes):
.RE
.PP
\fB\fCsplit \-b {{512}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Split a file with at most 512 bytes in each split without breaking lines:
.RE
.PP
\fB\fCsplit \-C {{512}} {{path/to/file}}\fR
