.TH sshuttle
.PP
.RS
Transparent proxy server that tunnels traffic over an SSH connection.
Doesn't require root or any special setup on the remote SSH server, though root access on the local machine is prompted for.
More information: \[la]https://manned.org/sshuttle\[ra]\&.
.RE
.RS
.IP \(bu 2
Forward all IPv4 TCP traffic via a remote SSH server:
.RE
.PP
\fB\fCsshuttle \-\-remote={{username}}@{{sshserver}} {{0.0.0.0/0}}\fR
.RS
.IP \(bu 2
Also forward all DNS traffic to the server's default DNS resolver:
.RE
.PP
\fB\fCsshuttle \-\-dns \-\-remote={{username}}@{{sshserver}} {{0.0.0.0/0}}\fR
.RS
.IP \(bu 2
Forward all traffic except that which is bound for a specific subnet:
.RE
.PP
\fB\fCsshuttle \-\-remote={{username}}@{{sshserver}} {{0.0.0.0/0}} \-\-exclude {{192.168.0.1/24}}\fR
.RS
.IP \(bu 2
Use the tproxy method to forward all IPv4 and IPv6 traffic:
.RE
.PP
\fB\fCsshuttle \-\-method=tproxy \-\-remote={{username}}@{{sshserver}} {{0.0.0.0/0}} {{::/0}} \-\-exclude={{your_local_ip_address}} \-\-exclude={{ssh_server_ip_address}}\fR
