.TH st\-info
.PP
.RS
Provides information about connected STLink and STM32 devices.
More information: \[la]https://github.com/texane/stlink\[ra]\&.
.RE
.RS
.IP \(bu 2
Display amount of program memory available:
.RE
.PP
\fB\fCst\-info \-\-flash\fR
.RS
.IP \(bu 2
Display amount of SRAM memory available:
.RE
.PP
\fB\fCst\-info \-\-sram\fR
.RS
.IP \(bu 2
Display summarized information of the device:
.RE
.PP
\fB\fCst\-info \-\-probe\fR
