.TH steam
.PP
.RS
Video game platform by Valve.
More information: \[la]https://developer.valvesoftware.com/wiki/Command_Line_Options\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch Steam, printing debug messages to \fB\fCstdout\fR:
.RE
.PP
\fB\fCsteam\fR
.RS
.IP \(bu 2
Launch Steam and enable its in\-app debug console tab:
.RE
.PP
\fB\fCsteam \-console\fR
.RS
.IP \(bu 2
Enable and open the Steam console tab in a running Steam instance:
.RE
.PP
\fB\fCsteam steam://open/console\fR
.RS
.IP \(bu 2
Log into Steam with the specified credentials:
.RE
.PP
\fB\fCsteam \-login {{username}} {{password}}\fR
.RS
.IP \(bu 2
Launch Steam in Big Picture Mode:
.RE
.PP
\fB\fCsteam \-tenfoot\fR
.RS
.IP \(bu 2
Exit Steam:
.RE
.PP
\fB\fCsteam \-shutdown\fR
