.TH sublist3r
.PP
.RS
Fast subdomains enumeration tool for penetration testers.
More information: \[la]https://github.com/aboul3la/Sublist3r\[ra]\&.
.RE
.RS
.IP \(bu 2
Find subdomains for a domain:
.RE
.PP
\fB\fCsublist3r \-\-domain {{domain_name}}\fR
.RS
.IP \(bu 2
Find subdomains for a domain, also enabling brute force search:
.RE
.PP
\fB\fCsublist3r \-\-domain {{domain_name}} \-\-bruteforce\fR
.RS
.IP \(bu 2
Save the found subdomains to a text file:
.RE
.PP
\fB\fCsublist3r \-\-domain {{domain_name}} \-\-output {{path/to/output_file}}\fR
.RS
.IP \(bu 2
Output all available options:
.RE
.PP
\fB\fCsublist3r \-\-help\fR
