.TH subl
.PP
.RS
Sublime Text editor.
More information: \[la]https://www.sublimetext.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the current directory in Sublime Text:
.RE
.PP
\fB\fCsubl {{.}}\fR
.RS
.IP \(bu 2
Open a file or directory in Sublime Text:
.RE
.PP
\fB\fCsubl {{path/to/file_or_directory}}\fR
.RS
.IP \(bu 2
Open a file and jump to a specific line number:
.RE
.PP
\fB\fCsubl {{path/to/file}}:{{line_number}}\fR
.RS
.IP \(bu 2
Open a file or directory in the currently open window:
.RE
.PP
\fB\fCsubl \-a {{path/to/file}}\fR
.RS
.IP \(bu 2
Open a file or directory in a new window:
.RE
.PP
\fB\fCsubl \-n {{path/to/file}}\fR
