.TH supervisord
.PP
.RS
Supervisor is a client/server system for controlling some processes on UNIX\-like operating systems.
Supervisord is the server part of supervisor; it is primarily managed via a configuration file.
More information: \[la]http://supervisord.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCsupervisord\fR with specified configuration file:
.RE
.PP
\fB\fCsupervisord \-c {{path/to/file}}\fR
.RS
.IP \(bu 2
Run supervisord in the foreground:
.RE
.PP
\fB\fCsupervisord \-n\fR
