.TH svgcleaner
.PP
.RS
SVG optimizing utility.
More information: \[la]https://github.com/RazrFalcon/svgcleaner\[ra]\&.
.RE
.RS
.IP \(bu 2
Optimize an SVG:
.RE
.PP
\fB\fCsvgcleaner {{input.svg}} {{output.svg}}\fR
.RS
.IP \(bu 2
Optimize an SVG multiple times:
.RE
.PP
\fB\fCsvgcleaner \-\-multipass {{input.svg}} {{output.svg}}\fR
