.TH swift
.PP
.RS
Create, run and build Swift projects.
More information: \[la]https://swift.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a REPL (interactive shell):
.RE
.PP
\fB\fCswift\fR
.RS
.IP \(bu 2
Execute a program:
.RE
.PP
\fB\fCswift {{file.swift}}\fR
.RS
.IP \(bu 2
Start a new project with the package manager:
.RE
.PP
\fB\fCswift package init\fR
.RS
.IP \(bu 2
Generate an Xcode project file:
.RE
.PP
\fB\fCswift package generate\-xcodeproj\fR
.RS
.IP \(bu 2
Update dependencies:
.RE
.PP
\fB\fCswift package update\fR
.RS
.IP \(bu 2
Compile project for release:
.RE
.PP
\fB\fCswift build \-c release\fR
