.TH swipl
.PP
.RS
SWI\-Prolog \- A comprehensive free Prolog environment.
More information: \[la]https://www.swi-prolog.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive session:
.RE
.PP
\fB\fCswipl\fR
.RS
.IP \(bu 2
Execute a command without showing any output:
.RE
.PP
\fB\fCswipl \-\-quiet \-t "{{command}}"\fR
.RS
.IP \(bu 2
Execute a script:
.RE
.PP
\fB\fCswipl {{path/to/file.pl}}\fR
.RS
.IP \(bu 2
Print all shell configuration variables:
.RE
.PP
\fB\fCswipl \-\-dump\-runtime\-variables\fR
.RS
.IP \(bu 2
Print the version:
.RE
.PP
\fB\fCswipl \-\-version\fR
