.TH symfony
.PP
.RS
The console component for the Symfony framework.
More information: \[la]https://symfony.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Symfony project:
.RE
.PP
\fB\fCsymfony new {{name}}\fR
.RS
.IP \(bu 2
Run a local web server:
.RE
.PP
\fB\fCsymfony serve\fR
.RS
.IP \(bu 2
Stop the local web server:
.RE
.PP
\fB\fCsymfony server:stop\fR
.RS
.IP \(bu 2
Check for security issues in the project's dependencies:
.RE
.PP
\fB\fCsymfony security:check\fR
