.TH syncthing
.PP
.RS
Continuous bidirectional decentralised folder synchronisation tool.
More information: \[la]https://docs.syncthing.net/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start Syncthing:
.RE
.PP
\fB\fCsyncthing\fR
.RS
.IP \(bu 2
Start Syncthing without opening a web browser:
.RE
.PP
\fB\fCsyncthing \-no\-browser\fR
.RS
.IP \(bu 2
Print the device ID:
.RE
.PP
\fB\fCsyncthing \-device\-id\fR
.RS
.IP \(bu 2
Change the home directory:
.RE
.PP
\fB\fCsyncthing \-home={{path/to/directory}}\fR
.RS
.IP \(bu 2
Force a full index exchange:
.RE
.PP
\fB\fCsyncthing \-reset\-deltas\fR
.RS
.IP \(bu 2
Change the address upon which the web interface listens:
.RE
.PP
\fB\fCsyncthing \-gui\-address={{ip_address:port|path/to/socket.sock}}\fR
.RS
.IP \(bu 2
Show filepaths to the files used by Syncthing:
.RE
.PP
\fB\fCsyncthing \-paths\fR
.RS
.IP \(bu 2
Disable the Syncthing monitor process:
.RE
.PP
\fB\fCsyncthing \-no\-restart\fR
