.TH sync
.PP
.RS
Flushes all pending write operations to the appropriate disks.
More information: \[la]https://www.gnu.org/software/coreutils/sync\[ra]\&.
.RE
.RS
.IP \(bu 2
Flush all pending write operations on all disks:
.RE
.PP
\fB\fCsync\fR
.RS
.IP \(bu 2
Flush all pending write operations on a single file to disk:
.RE
.PP
\fB\fCsync {{path/to/file}}\fR
