.TH telegram\-desktop
.PP
.RS
Instant messenger with open source clients, chats and stickers.
More information: \[la]https://telegram.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Start GUI:
.RE
.PP
\fB\fCtelegram\-desktop\fR
.RS
.IP \(bu 2
Run GUI as an autostart if allowed:
.RE
.PP
\fB\fCtelegram\-desktop \-autostart\fR
.RS
.IP \(bu 2
Run GUI minimized to tray:
.RE
.PP
\fB\fCtelegram\-desktop \-startintray\fR
