.TH telnet
.PP
.RS
Connect to a specified port of a host using the telnet protocol.
More information: \[la]https://manned.org/telnet\[ra]\&.
.RE
.RS
.IP \(bu 2
Telnet to the default port of a host:
.RE
.PP
\fB\fCtelnet {{host}}\fR
.RS
.IP \(bu 2
Telnet to a specific port of a host:
.RE
.PP
\fB\fCtelnet {{ip_address}} {{port}}\fR
.RS
.IP \(bu 2
Exit a telnet session:
.RE
.PP
\fB\fCquit\fR
.RS
.IP \(bu 2
Emit the default escape character combination for terminating the session:
.RE
.PP
\fB\fCCtrl + ]\fR
.RS
.IP \(bu 2
Start \fB\fCtelnet\fR with "x" as the session termination character:
.RE
.PP
\fB\fCtelnet \-e {{x}} {{ip_address}} {{port}}\fR
.RS
.IP \(bu 2
Telnet to Star Wars animation:
.RE
.PP
\fB\fCtelnet {{towel.blinkenlights.nl}}\fR
