.TH termdown
.PP
.RS
Countdown timer and stopwatch for the command\-line.
More information: \[la]https://github.com/trehn/termdown\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a stopwatch:
.RE
.PP
\fB\fCtermdown\fR
.RS
.IP \(bu 2
Start a 1 minute and 30 seconds countdown:
.RE
.PP
\fB\fCtermdown {{1m30s}}\fR
.RS
.IP \(bu 2
Start a 1 minute 30 seconds countdown with blinking the terminal at the end:
.RE
.PP
\fB\fCtermdown {{1m30s}} \-\-blink\fR
.RS
.IP \(bu 2
Show a title above countdown:
.RE
.PP
\fB\fCtermdown {{1m30s}} \-\-title "{{Interesting title}}"\fR
.RS
.IP \(bu 2
Display current time:
.RE
.PP
\fB\fCtermdown \-\-time\fR
