.TH terminalizer
.PP
.RS
Utility program which records the terminal and generate animated GIFs or share a video.
More information: \[la]https://terminalizer.com\[ra]\&.
.RE
.RS
.IP \(bu 2
Create the global config directory:
.RE
.PP
\fB\fCterminalizer init\fR
.RS
.IP \(bu 2
Record the terminal and create a recording file:
.RE
.PP
\fB\fCterminalizer record {{path/to/file}}\fR
.RS
.IP \(bu 2
Play a recorded file on the terminal:
.RE
.PP
\fB\fCterminalizer play {{path/to/file}}\fR
.RS
.IP \(bu 2
Render a recording file as an animated GIF image:
.RE
.PP
\fB\fCterminalizer render {{path/to/file}}\fR
.RS
.IP \(bu 2
Upload a video to terminalizer.com:
.RE
.PP
\fB\fCterminalizer share {{path/to/file}}\fR
