.TH terraform
.PP
.RS
Create and deploy infrastructure as code to cloud providers.
More information: \[la]https://www.terraform.io/\[ra]\&.
.RE
.RS
.IP \(bu 2
Initialize a new or existing Terraform configuration:
.RE
.PP
\fB\fCterraform init\fR
.RS
.IP \(bu 2
Verify that the configuration files are syntactically valid:
.RE
.PP
\fB\fCterraform validate\fR
.RS
.IP \(bu 2
Format configuration according to Terraform language style conventions:
.RE
.PP
\fB\fCterraform fmt\fR
.RS
.IP \(bu 2
Generate and show an execution plan:
.RE
.PP
\fB\fCterraform plan\fR
.RS
.IP \(bu 2
Build or change infrastructure:
.RE
.PP
\fB\fCterraform apply\fR
.RS
.IP \(bu 2
Destroy Terraform\-managed infrastructure:
.RE
.PP
\fB\fCterraform destroy\fR
