.TH terragrunt
.PP
.RS
Keep your Terraform CLI arguments DRY.
More information: \[la]https://terragrunt.gruntwork.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate and show an execution plan:
.RE
.PP
\fB\fCterragrunt plan\fR
.RS
.IP \(bu 2
Build or change infrastructure:
.RE
.PP
\fB\fCterragrunt apply\fR
.RS
.IP \(bu 2
Show current deployment (from state):
.RE
.PP
\fB\fCterragrunt show\fR
.RS
.IP \(bu 2
Show module output values:
.RE
.PP
\fB\fCterragrunt output\fR
.RS
.IP \(bu 2
Destroy Terraform\-managed infrastructure:
.RE
.PP
\fB\fCterragrunt destroy\fR
.RS
.IP \(bu 2
Build or change infrastructure from a tree of Terragrunt modules (stack):
.RE
.PP
\fB\fCterragrunt run\-all apply\fR
