.TH test
.PP
.RS
Check file types and compare values.
Returns 0 if the condition evaluates to true, 1 if it evaluates to false.
More information: \[la]https://www.gnu.org/software/coreutils/test\[ra]\&.
.RE
.RS
.IP \(bu 2
Test if a given variable is equal to a given string:
.RE
.PP
\fB\fCtest "{{$MY_VAR}}" == "{{/bin/zsh}}"\fR
.RS
.IP \(bu 2
Test if a given variable is empty:
.RE
.PP
\fB\fCtest \-z "{{$GIT_BRANCH}}"\fR
.RS
.IP \(bu 2
Test if a file exists:
.RE
.PP
\fB\fCtest \-f "{{path/to/file_or_directory}}"\fR
.RS
.IP \(bu 2
Test if a directory does not exist:
.RE
.PP
\fB\fCtest ! \-d "{{path/to/directory}}"\fR
.RS
.IP \(bu 2
If A is true, then do B, or C in the case of an error (notice that C may run even if A fails):
.RE
.PP
\fB\fCtest {{condition}} && {{echo "true"}} || {{echo "false"}}\fR
