.TH texdoc
.PP
.RS
Search for appropriate documentation for (La)TeX commands or packages.
More information: \[la]https://texdoc.org/index.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the first search result in the default PDF viewer:
.RE
.PP
\fB\fCtexdoc {{search}}\fR
.RS
.IP \(bu 2
List the best search results:
.RE
.PP
\fB\fCtexdoc \-\-list {{search}}\fR
.RS
.IP \(bu 2
Open full documentation of texdoc:
.RE
.PP
\fB\fCtexdoc {{texdoc}}\fR
