.TH thunderbird
.PP
.RS
Email client and RSS reader.
More information: \[la]https://thunderbird.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Open thunderbird:
.RE
.PP
\fB\fCthunderbird\fR
.RS
.IP \(bu 2
Use a specific user profile:
.RE
.PP
\fB\fCthunderbird \-P {{profile_name}}\fR
.RS
.IP \(bu 2
Use a specific user profile directory:
.RE
.PP
\fB\fCthunderbird \-\-profile {{path/to/profile/directory}}\fR
