.TH timew
.PP
.RS
A time tracking tool used to measure the duration of activities.
More information: \[la]https://timewarrior.net/docs\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a new stopwatch, giving a tag name to the activity being tracked:
.RE
.PP
\fB\fCtimew start {{activity_tag}}\fR
.RS
.IP \(bu 2
View running stopwatches:
.RE
.PP
\fB\fCtimew\fR
.RS
.IP \(bu 2
Stop the stopwatch with a given tag name:
.RE
.PP
\fB\fCtimew stop {{activity_tag}}\fR
.RS
.IP \(bu 2
Stop all running stopwatches:
.RE
.PP
\fB\fCtimew stop\fR
.RS
.IP \(bu 2
View tracked items:
.RE
.PP
\fB\fCtimew summary\fR
