.TH tldr\-lint
.PP
.RS
Lint and format \fB\fCtldr\fR pages.
More information: \[la]https://github.com/tldr-pages/tldr-lint\[ra]\&.
.RE
.RS
.IP \(bu 2
Lint all pages:
.RE
.PP
\fB\fCtldr\-lint {{pages_directory}}\fR
.RS
.IP \(bu 2
Format a specific page to \fB\fCstdout\fR:
.RE
.PP
\fB\fCtldr\-lint \-\-format {{page.md}}\fR
.RS
.IP \(bu 2
Format all pages in place:
.RE
.PP
\fB\fCtldr\-lint \-\-format \-\-in\-place {{pages_directory}}\fR
