.TH tldr
.PP
.RS
Display simple help pages for command\-line tools from the tldr\-pages project.
More information: \[la]https://tldr.sh\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the tldr page for a specific command (hint: this is how you got here!):
.RE
.PP
\fB\fCtldr {{command}}\fR
.RS
.IP \(bu 2
Print the tldr page for a specific subcommand:
.RE
.PP
\fB\fCtldr {{command}}\-{{subcommand}}\fR
.RS
.IP \(bu 2
Print the tldr page for a command for a specific [p]latform:
.RE
.PP
\fB\fCtldr \-p {{android|linux|osx|sunos|windows}} {{command}}\fR
.RS
.IP \(bu 2
[u]pdate the local cache of tldr pages:
.RE
.PP
\fB\fCtldr \-u\fR
