.TH tlmgr dump\-tlpdb
.PP
.RS
Dump the TeX Live package database.
More information: \[la]https://www.tug.org/texlive/tlmgr.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Dump the local package database:
.RE
.PP
\fB\fCtlmgr dump\-tlpdb \-\-local\fR
.RS
.IP \(bu 2
Dump the remote package database:
.RE
.PP
\fB\fCtlmgr dump\-tlpdb \-\-remote\fR
.RS
.IP \(bu 2
Dump the local package database as JSON:
.RE
.PP
\fB\fCtlmgr dump\-tlpdb \-\-local \-\-json\fR
