.TH tlmgr shell
.PP
.RS
Start an interactive shell of the native TeX Live manager.
More information: \[la]https://www.tug.org/texlive/tlmgr.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Start an interactive shell of \fB\fCtlmgr\fR:
.RE
.PP
\fB\fCtlmgr shell\fR
.RS
.IP \(bu 2
Run any \fB\fCtlmgr\fR sub\-command in the interactive shell:
.RE
.PP
\fB\fC{{sub_command}} {{arguments}}\fR
.RS
.IP \(bu 2
Quit the interactive shell:
.RE
.PP
\fB\fCquit\fR
.RS
.IP \(bu 2
List all TeX Live variables:
.RE
.PP
\fB\fCget\fR
.RS
.IP \(bu 2
Get the value of a TeX Live variable:
.RE
.PP
\fB\fCget {{variable}}\fR
.RS
.IP \(bu 2
Set the value of a TeX Live variable:
.RE
.PP
\fB\fCset {{variable}} {{value}}\fR
.RS
.IP \(bu 2
Restart the interactive shell:
.RE
.PP
\fB\fCrestart\fR
.RS
.IP \(bu 2
Print the version of the current protocol:
.RE
.PP
\fB\fCprotocol\fR
