.TH tlmgr candidates
.PP
.RS
Get available candidate repositories from which a TeX Live package can be installed.
More information: \[la]https://www.tug.org/texlive/tlmgr.html\[ra]\&.
.RE
.RS
.IP \(bu 2
List all available repositories from which a package can be installed:
.RE
.PP
\fB\fCtlmgr candidates {{package}}\fR
