.TH tlmgr path
.PP
.RS
Add or remove symlinks for TeX Live executables, man pages and info pages.
This command has to be re\-run for files added in the future.
More information: \[la]https://www.tug.org/texlive/tlmgr.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Add symlinks to TeX Live files:
.RE
.PP
\fB\fCsudo tlmgr path add\fR
.RS
.IP \(bu 2
Remove symlinks to TeX Live files:
.RE
.PP
\fB\fCsudo tlmgr path remove\fR
