.TH tlmgr recreate\-tlpdb
.PP
.RS
Recreate the TeX Live package database.
This command has a lack of documentation and should be used with caution.
More information: \[la]https://www.tug.org/texlive/tlmgr.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Recreate the \fB\fCtexlive.tlpdb\fR database file and dump it to \fB\fCstdout\fR:
.RE
.PP
\fB\fCsudo tlmgr recreate\-tlpdb\fR
