.TH tmuxinator
.PP
.RS
Create and manage tmux sessions easily.
More information: \[la]https://github.com/tmuxinator/tmuxinator\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new project:
.RE
.PP
\fB\fCtmuxinator new {{project}}\fR
.RS
.IP \(bu 2
Edit a project:
.RE
.PP
\fB\fCtmuxinator edit {{project}}\fR
.RS
.IP \(bu 2
List projects:
.RE
.PP
\fB\fCtmuxinator list\fR
.RS
.IP \(bu 2
Start a tmux session based on project:
.RE
.PP
\fB\fCtmuxinator start {{project}}\fR
.RS
.IP \(bu 2
Stop a project's tmux session:
.RE
.PP
\fB\fCtmuxinator stop {{project}}\fR
