.TH todoman
.PP
.RS
A simple, standards\-based, cli todo manager.
\fB\fCtodoman\fR is a common name for the command \fB\fCtodo\fR, but not a command itself.
More information: \[la]https://todoman.readthedocs.io/\[ra]\&.
.RE
.RS
.IP \(bu 2
View documentation for the original command:
.RE
.PP
\fB\fCtldr todo\fR
