.TH topgrade
.PP
.RS
Update all applications on the system.
More information: \[la]https://github.com/r-darwish/topgrade\[ra]\&.
.RE
.RS
.IP \(bu 2
Run updates:
.RE
.PP
\fB\fCtopgrade\fR
.RS
.IP \(bu 2
Say yes to all updates:
.RE
.PP
\fB\fCtopgrade \-y\fR
.RS
.IP \(bu 2
Cleanup temporary/old files:
.RE
.PP
\fB\fCtopgrade \-c\fR
.RS
.IP \(bu 2
Disable a certain update operation:
.RE
.PP
\fB\fCtopgrade \-\-disable {{operation}}\fR
.RS
.IP \(bu 2
Only perform a certain update operation:
.RE
.PP
\fB\fCtopgrade \-\-only {{operation}}\fR
.RS
.IP \(bu 2
Edit the config file with default editor:
.RE
.PP
\fB\fCtopgrade \-\-edit\-config\fR
