.TH tpp
.PP
.RS
Command\-Line based presentation tool.
More information: \[la]https://github.com/cbbrowne/tpp\[ra]\&.
.RE
.RS
.IP \(bu 2
View a presentation:
.RE
.PP
\fB\fCtpp {{path/to/file}}\fR
.RS
.IP \(bu 2
Output a presentation:
.RE
.PP
\fB\fCtpp \-t {{type}} \-o {{path/to/output}} {{path/to/file}}\fR
