.TH traefik
.PP
.RS
An HTTP reverse proxy and load balancer.
More information: \[la]https://traefik.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Start server with default config:
.RE
.PP
\fB\fCtraefik\fR
.RS
.IP \(bu 2
Start server with a custom config file:
.RE
.PP
\fB\fCtraefik \-\-c {{config_file}}.toml\fR
.RS
.IP \(bu 2
Start server with cluster mode enabled:
.RE
.PP
\fB\fCtraefik \-\-cluster\fR
.RS
.IP \(bu 2
Start server with web UI enabled:
.RE
.PP
\fB\fCtraefik \-\-web\fR
