.TH transmission\-edit
.PP
.RS
Modify announce URLs from torrent files.
See also: \fB\fCtransmission\fR\&.
More information: \[la]https://manned.org/transmission-edit\[ra]\&.
.RE
.RS
.IP \(bu 2
Add or remove a URL from a torrent's announce list:
.RE
.PP
\fB\fCtransmission\-edit \-\-{{add|delete}} {{http://example.com}} {{path/to/file.torrent}}\fR
.RS
.IP \(bu 2
Update a tracker's passcode in a torrent file:
.RE
.PP
\fB\fCtransmission\-edit \-\-replace {{old\-passcode}} {{new\-passcode}} {{path/to/file.torrent}}\fR
