.TH transmission
.PP
.RS
Transmission is a simple torrent client.
Transmission isn't a command, but a set of commands. See the pages below.
More information: \[la]https://transmissionbt.com/\[ra]\&.
.RE
.RS
.IP \(bu 2
Show the tldr page for running Transmission's daemon:
.RE
.PP
\fB\fCtldr transmission\-daemon\fR
.RS
.IP \(bu 2
Show the tldr page for interacting with the daemon:
.RE
.PP
\fB\fCtldr transmission\-remote\fR
.RS
.IP \(bu 2
Show the tldr page for creating torrent files:
.RE
.PP
\fB\fCtldr transmission\-create\fR
.RS
.IP \(bu 2
Show the tldr page for modifying torrent files:
.RE
.PP
\fB\fCtldr transmission\-edit\fR
.RS
.IP \(bu 2
Show the tldr page for getting info about torrent files:
.RE
.PP
\fB\fCtldr transmission\-show\fR
.RS
.IP \(bu 2
Show the tldr page for the deprecated method for interacting with the daemon:
.RE
.PP
\fB\fCtldr transmission\-cli\fR
