.TH transmission\-show
.PP
.RS
Get information about a torrent file.
See also: \fB\fCtransmission\fR\&.
More information: \[la]https://manned.org/transmission-show\[ra]\&.
.RE
.RS
.IP \(bu 2
Display metadata for a specific torrent:
.RE
.PP
\fB\fCtransmission\-show {{path/to/file.torrent}}\fR
.RS
.IP \(bu 2
Generate a magnet link for a specific torrent:
.RE
.PP
\fB\fCtransmission\-show \-\-magnet {{path/to/file.torrent}}\fR
.RS
.IP \(bu 2
Query a torrent's trackers and print the current number of peers:
.RE
.PP
\fB\fCtransmission\-show \-\-scrape {{path/to/file.torrent}}\fR
