.TH trash\-cli
.PP
.RS
A command\-line interface to the trashcan APIs.
More information: \[la]https://github.com/andreafrancia/trash-cli\[ra]\&.
.RE
.RS
.IP \(bu 2
Trash specific files and directories into the current trashcan:
.RE
.PP
\fB\fCtrash\-put {{path/to/file_or_directory1 path/to/file_or_directory2 ...}}\fR
.RS
.IP \(bu 2
Remove specific files from the current trashcan:
.RE
.PP
\fB\fCtrash\-rm {{path/to/file_or_directory1 path/to/file_or_directory2 ...}}\fR
.RS
.IP \(bu 2
Empty the current trashcan:
.RE
.PP
\fB\fCtrash\-empty\fR
.RS
.IP \(bu 2
List trashed files and directories in the current trashcan:
.RE
.PP
\fB\fCtrash\-list\fR
.RS
.IP \(bu 2
Restore a specific file or directory by a number from the displayed list from the current trashcan:
.RE
.PP
\fB\fCtrash\-restore\fR
