.TH trawl
.PP
.RS
Prints out network interface information to the console, much like ifconfig/ipconfig/ip/ifdata.
More information: \[la]https://github.com/robphoenix/trawl\[ra]\&.
.RE
.RS
.IP \(bu 2
Show column names:
.RE
.PP
\fB\fCtrawl \-n\fR
.RS
.IP \(bu 2
Filter interface names using a case\-insensitive regular expression:
.RE
.PP
\fB\fCtrawl \-f wi\fR
.RS
.IP \(bu 2
Get a list of available interfaces:
.RE
.PP
\fB\fCtrawl \-i\fR
.RS
.IP \(bu 2
Include the loopback interface:
.RE
.PP
\fB\fCtrawl \-l\fR
