.TH tred
.PP
.RS
Compute the transitive reduction of directed graphs.
Graphviz filters: \fB\fCacyclic\fR, \fB\fCbcomps\fR, \fB\fCcomps\fR, \fB\fCedgepaint\fR, \fB\fCgvcolor\fR, \fB\fCgvpack\fR, \fB\fCmingle\fR, \fB\fCnop\fR, \fB\fCsccmap\fR, \fB\fCtred\fR, & \fB\fCunflatten\fR\&.
More information: \[la]https://www.graphviz.org/pdf/tred.1.pdf\[ra]\&.
.RE
.RS
.IP \(bu 2
Construct the transitive reduction graph of one or more directed graphs:
.RE
.PP
\fB\fCtred {{path/to/input1.gv}} {{path/to/input2.gv ...}} > {{path/to/output.gv}}\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCtred \-?\fR
