.TH truffle
.PP
.RS
A tool for developing smart contracts for running services on the Ethereum blockchain.
More information: \[la]https://www.trufflesuite.com/docs/truffle/reference/truffle-commands\[ra]\&.
.RE
.RS
.IP \(bu 2
Download a pre\-built Truffle project (Truffle Box):
.RE
.PP
\fB\fCtruffle unbox {{box_name}}\fR
.RS
.IP \(bu 2
Compile contract source files in the current directory:
.RE
.PP
\fB\fCtruffle compile\fR
.RS
.IP \(bu 2
Run JavaScript and Solidity tests:
.RE
.PP
\fB\fCtruffle test\fR
.RS
.IP \(bu 2
Run migrations to deploy contracts:
.RE
.PP
\fB\fCtruffle migrate\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCtruffle help {{subcommand}}\fR
