.TH tslint
.PP
.RS
A pluggable linting utility for TypeScript.
More information: \[la]https://palantir.github.io/tslint\[ra]\&.
.RE
.RS
.IP \(bu 2
Create TSLint config:
.RE
.PP
\fB\fCtslint \-\-init\fR
.RS
.IP \(bu 2
Lint on a given set of files:
.RE
.PP
\fB\fCtslint {{path/to/file1.js path/to/file2.js ...}}\fR
.RS
.IP \(bu 2
Fix lint issues:
.RE
.PP
\fB\fCtslint \-\-fix\fR
.RS
.IP \(bu 2
Lint with the config file in the project root:
.RE
.PP
\fB\fCtslint \-\-project {{path/to/project_root}}\fR
