.TH tt
.PP
.RS
A terminal based typing test.
More information: \[la]https://github.com/lemnos/tt\[ra]\&.
.RE
.RS
.IP \(bu 2
Start quote mode with the builtin quote list in English:
.RE
.PP
\fB\fCtt \-quotes {{en}}\fR
.RS
.IP \(bu 2
Produce a test consisting of 50 randomly drawn words in 5 groups of 10 words each:
.RE
.PP
\fB\fCtt \-n {{10}} \-g {{5}}\fR
.RS
.IP \(bu 2
Start a timed test lasting 10 seconds:
.RE
.PP
\fB\fCtt \-t {{10}}\fR
.RS
.IP \(bu 2
Start \fB\fCtt\fR with no theming and showing your WPM as you type:
.RE
.PP
\fB\fCtt \-showwpm \-notheme\fR
