.TH tuir
.PP
.RS
A text user\-interface (TUI) to view and interact with Reddit from your terminal.
Navigate with the Vim keys.
More information: \[la]https://gitlab.com/ajak/tuir\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch tuir:
.RE
.PP
\fB\fCtuir\fR
.RS
.IP \(bu 2
Open a subreddit:
.RE
.PP
\fB\fC/{{subreddit_name}}\fR
.RS
.IP \(bu 2
Open a link:
.RE
.PP
\fB\fCo\fR
.RS
.IP \(bu 2
Open a specific subreddit on launch:
.RE
.PP
\fB\fCtuir \-s {{subreddit_name}}\fR
.RS
.IP \(bu 2
Open external links using programs defined in the mailcap config:
.RE
.PP
\fB\fCtuir \-\-enable\-media\fR
