.TH twm
.PP
.RS
A window manager for the X Window system.
More information: \[la]https://gitlab.freedesktop.org/xorg/app/twm\[ra]\&.
.RE
.RS
.IP \(bu 2
Connect to the default X server:
.RE
.PP
\fB\fCtwm\fR
.RS
.IP \(bu 2
Connect to a specific X server:
.RE
.PP
\fB\fCtwm \-display {{display}}\fR
.RS
.IP \(bu 2
Only manage the default screen:
.RE
.PP
\fB\fCtwm \-s\fR
.RS
.IP \(bu 2
Use a specific startup file:
.RE
.PP
\fB\fCtwm \-f {{path/to/file}}\fR
.RS
.IP \(bu 2
Enable verbose mode and print unexpected errors in X:
.RE
.PP
\fB\fCtwm \-v\fR
