.TH tye
.PP
.RS
Developer tool that makes developing, testing, and deploying microservices and distributed applications easier.
More information: \[la]https://github.com/dotnet/tye\[ra]\&.
.RE
.RS
.IP \(bu 2
Scaffold a \fB\fCtye.yaml\fR file representing the application:
.RE
.PP
\fB\fCtye init\fR
.RS
.IP \(bu 2
Run an application locally:
.RE
.PP
\fB\fCtye run\fR
.RS
.IP \(bu 2
Build an application's containers:
.RE
.PP
\fB\fCtye build\fR
.RS
.IP \(bu 2
Push an application's containers:
.RE
.PP
\fB\fCtye push\fR
.RS
.IP \(bu 2
Deploy an application to Kubernetes:
.RE
.PP
\fB\fCtye deploy\fR
.RS
.IP \(bu 2
Remove a deployed application from Kubernetes:
.RE
.PP
\fB\fCtye undeploy\fR
