.TH type
.PP
.RS
Display the type of command the shell will execute.
More information: \[la]https://manned.org/type\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the type of a command:
.RE
.PP
\fB\fCtype {{command}}\fR
.RS
.IP \(bu 2
Display all locations containing the specified executable:
.RE
.PP
\fB\fCtype \-a {{command}}\fR
.RS
.IP \(bu 2
Display the name of the disk file that would be executed:
.RE
.PP
\fB\fCtype \-p {{command}}\fR
