.TH u3d
.PP
.RS
A set of tools to interact with Unity.
More information: \[la]https://github.com/DragonBox/u3d\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the project in the current directory using the correct Unity version:
.RE
.PP
\fB\fCu3d\fR
.RS
.IP \(bu 2
List installed versions of Unity:
.RE
.PP
\fB\fCu3d list\fR
.RS
.IP \(bu 2
List available versions of Unity that can be downloaded:
.RE
.PP
\fB\fCu3d available\fR
.RS
.IP \(bu 2
Download and install latest stable Unity version:
.RE
.PP
\fB\fCu3d install latest_stable\fR
.RS
.IP \(bu 2
Download and install Unity version and editor [p]ackages:
.RE
.PP
\fB\fCu3d install {{2021.2.0f1}} \-p {{Unity,iOS,Android}}\fR
