.TH uname
.PP
.RS
Print details about the current machine and the operating system running on it.
See also \fB\fClsb_release\fR\&.
More information: \[la]https://www.gnu.org/software/coreutils/uname\[ra]\&.
.RE
.RS
.IP \(bu 2
Print kernel name:
.RE
.PP
\fB\fCuname\fR
.RS
.IP \(bu 2
Print system architecture and processor information:
.RE
.PP
\fB\fCuname \-\-machine \-\-processor\fR
.RS
.IP \(bu 2
Print kernel name, kernel release and kernel version:
.RE
.PP
\fB\fCuname \-\-kernel\-name \-\-kernel\-release \-\-kernel\-version\fR
.RS
.IP \(bu 2
Print system hostname:
.RE
.PP
\fB\fCuname \-\-nodename\fR
.RS
.IP \(bu 2
Print all available system information:
.RE
.PP
\fB\fCuname \-\-all\fR
