.TH uptime
.PP
.RS
Tell how long the system has been running and other information.
More information: \[la]https://www.gnu.org/software/coreutils/uptime\[ra]\&.
.RE
.RS
.IP \(bu 2
Print current time, uptime, number of logged\-in users and other information:
.RE
.PP
\fB\fCuptime\fR
.RS
.IP \(bu 2
Show only the amount of time the system has been booted for:
.RE
.PP
\fB\fCuptime \-\-pretty\fR
.RS
.IP \(bu 2
Print the date and time the system booted up at:
.RE
.PP
\fB\fCuptime \-\-since\fR
.RS
.IP \(bu 2
Show version information:
.RE
.PP
\fB\fCuptime \-\-version\fR
