.TH upx
.PP
.RS
Compress or decompress executables.
More information: \[la]https://upx.github.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Compress executable:
.RE
.PP
\fB\fCupx {{path/to/file}}\fR
.RS
.IP \(bu 2
Decompress executable:
.RE
.PP
\fB\fCupx \-d {{path/to/file}}\fR
.RS
.IP \(bu 2
Detailed help:
.RE
.PP
\fB\fCupx \-\-help\fR
