.TH users
.PP
.RS
Display a list of logged in users.
See also: \fB\fCuseradd\fR, \fB\fCuserdel\fR, \fB\fCusermod\fR\&.
More information: \[la]https://www.gnu.org/software/coreutils/users\[ra]\&.
.RE
.RS
.IP \(bu 2
Print logged in usernames:
.RE
.PP
\fB\fCusers\fR
.RS
.IP \(bu 2
Print logged in usernames according to a given file:
.RE
.PP
\fB\fCusers {{/var/log/wmtp}}\fR
