.TH uudecode
.PP
.RS
Decode files encoded by \fB\fCuuencode\fR\&.
More information: \[la]https://manned.org/uudecode\[ra]\&.
.RE
.RS
.IP \(bu 2
Decode a file that was encoded with \fB\fCuuencode\fR and print the result to \fB\fCstdout\fR:
.RE
.PP
\fB\fCuudecode {{path/to/encoded_file}}\fR
.RS
.IP \(bu 2
Decode a file that was encoded with \fB\fCuuencode\fR and write the result to a file:
.RE
.PP
\fB\fCuudecode \-o {{path/to/decoded_file}} {{path/to/encoded_file}}\fR
