.TH vala
.PP
.RS
Vala code runner.
Tutorial: \[la]https://wiki.gnome.org/Projects/Vala/Tutorial\[ra]\&.
More information: \[la]https://valadoc.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Run a vala file, with gtk+:
.RE
.PP
\fB\fCvala {{path/to/file.vala}} \-\-pkg {{gtk+\-3.0}}\fR
.RS
.IP \(bu 2
Display version info:
.RE
.PP
\fB\fCvala \-\-version\fR
.RS
.IP \(bu 2
Display helper message:
.RE
.PP
\fB\fCvala \-\-help\fR
