.TH valac
.PP
.RS
Vala code compiler.
Tutorial: \[la]https://wiki.gnome.org/Projects/Vala/Tutorial\[ra]\&.
More information: \[la]https://valadoc.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Compile a vala file, with gtk+:
.RE
.PP
\fB\fCvalac {{path/to/file.vala}} \-\-pkg {{gtk+\-3.0}}\fR
.RS
.IP \(bu 2
Display version info:
.RE
.PP
\fB\fCvalac \-\-version\fR
.RS
.IP \(bu 2
Display helper message:
.RE
.PP
\fB\fCvalac \-\-help\fR
