.TH venv
.PP
.RS
Create lightweight virtual environments in python.
More information: \[la]https://docs.python.org/3/library/venv.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a python virtual environment:
.RE
.PP
\fB\fCpython \-m venv {{path/to/virtual_environment}}\fR
.RS
.IP \(bu 2
Activate the virtual environment (Linux and Mac OS):
.RE
.PP
\fB\fCsource {{path/to/virtual_environment}}/bin/activate\fR
.RS
.IP \(bu 2
Activate the virtual environment (Windows):
.RE
.PP
\fB\fC{{path\\to\\virtual_environment}}\\Scripts\\activate.bat\fR
.RS
.IP \(bu 2
Deactivate the virtual environment:
.RE
.PP
\fB\fCdeactivate\fR
