.TH vifm
.PP
.RS
Vifm (VI File Manager) is a command\-line file manager.
More information: \[la]https://github.com/vifm/vifm\[ra]\&.
.RE
.RS
.IP \(bu 2
Open the current directory:
.RE
.PP
\fB\fCvifm .\fR
.RS
.IP \(bu 2
Open specified directories on left or right plane:
.RE
.PP
\fB\fCvifm {{path/to/directory1 path/to/directory2 ...}}\fR
