.TH vimtutor
.PP
.RS
Vim tutor, teaching the basic vim commands.
See also \fB\fCvim\fR, \fB\fCvimdiff\fR, \fB\fCnvim\fR\&.
More information: \[la]https://manned.org/vimtutor\[ra]\&.
.RE
.RS
.IP \(bu 2
Launch the vim tutor using the given language (en, fr, de, ...):
.RE
.PP
\fB\fCvimtutor {{language}}\fR
.RS
.IP \(bu 2
Exit the tutor:
.RE
.PP
\fB\fC<Esc> :q <Enter>\fR
