.TH virsh pool\-destroy
.PP
.RS
Stop an active virtual machine storage pool.
See also: \fB\fCvirsh\fR, \fB\fCvirsh\-pool\-delete\fR\&.
More information: \[la]https://manned.org/virsh\[ra]\&.
.RE
.RS
.IP \(bu 2
Stop a storage pool specified by name or UUID (determine using \fB\fCvirsh pool\-list\fR):
.RE
.PP
\fB\fCvirsh pool\-destroy \-\-pool {{name|uuid}}\fR
