.TH virsh\-help
.PP
.RS
Display information about \fB\fCvirsh\fR commands or command groups.
See also: \fB\fCvirsh\fR\&.
More information: \[la]https://manned.org/virsh\[ra]\&.
.RE
.RS
.IP \(bu 2
List the \fB\fCvirsh\fR commands grouped into related categories:
.RE
.PP
\fB\fCvirsh help\fR
.RS
.IP \(bu 2
List the command categories:
.RE
.PP
\fB\fCvirsh help | grep "keyword"\fR
.RS
.IP \(bu 2
List the commands in a category:
.RE
.PP
\fB\fCvirsh help {{category_keyword}}\fR
.RS
.IP \(bu 2
Show help for a command:
.RE
.PP
\fB\fCvirsh help {{command}}\fR
