.TH virsh pool\-autostart
.PP
.RS
Enable or disable autostart for a virtual machine storage pool.
See also: \fB\fCvirsh\fR\&.
More information: \[la]https://manned.org/virsh\[ra]\&.
.RE
.RS
.IP \(bu 2
Enable autostart for the storage pool specified by name or UUID (determine using \fB\fCvirsh pool\-list\fR):
.RE
.PP
\fB\fCvirsh pool\-autostart \-\-pool {{name|uuid}}\fR
.RS
.IP \(bu 2
Disable autostart for the storage pool specified by name or UUID:
.RE
.PP
\fB\fCvirsh pool\-autostart \-\-pool {{name|uuid}} \-\-disable\fR
