.TH Vite
.PP
.RS
Create a Vite project.
Used to build JavaScript projects.
Available templates: vanilla, vanilla\-ts, vue, vue\-ts, react, react\-ts, react\-swc, react\-swc\-ts, preact, preact\-ts, lit, lit\-ts, svelte, svelte\-ts.
More information: \[la]https://vitejs.dev/guide\[ra]\&.
.RE
.RS
.IP \(bu 2
Setup using \fB\fCnpm\fR 6.x:
.RE
.PP
\fB\fCnpm create vite@latest my\-react\-app \-\-template react\-ts\fR
.RS
.IP \(bu 2
Setup using \fB\fCnpm\fR 7+, extra double\-dash is needed:
.RE
.PP
\fB\fCnpm create vite@latest my\-react\-app \-\- \-\-template react\-ts\fR
.RS
.IP \(bu 2
Setup using \fB\fCyarn\fR:
.RE
.PP
\fB\fCyarn create vite my\-react\-app \-\-template react\-ts\fR
.RS
.IP \(bu 2
Setup using \fB\fCpnpm\fR:
.RE
.PP
\fB\fCpnpm create vite my\-react\-app \-\-template react\-ts\fR
