.TH vlc
.PP
.RS
Cross\-platform multimedia player.
More information: \[la]https://wiki.videolan.org/Documentation:Command_line/\[ra]\&.
.RE
.RS
.IP \(bu 2
Play a file:
.RE
.PP
\fB\fCvlc {{path/to/file}}\fR
.RS
.IP \(bu 2
Play in fullscreen:
.RE
.PP
\fB\fCvlc \-\-fullscreen {{path/to/file}}\fR
.RS
.IP \(bu 2
Play muted:
.RE
.PP
\fB\fCvlc \-\-no\-audio {{path/to/file}}\fR
.RS
.IP \(bu 2
Play repeatedly:
.RE
.PP
\fB\fCvlc \-\-loop {{path/to/file}}\fR
.RS
.IP \(bu 2
Play video from a URL:
.RE
.PP
\fB\fCvlc {{https://www.youtube.com/watch?v=oHg5SJYRHA0}}\fR
