.TH volta
.PP
.RS
A JavaScript Tool Manager that installs Node.js runtimes, npm and Yarn package managers, or any binaries from npm.
More information: \[la]https://volta.sh\[ra]\&.
.RE
.RS
.IP \(bu 2
List all installed tools:
.RE
.PP
\fB\fCvolta list\fR
.RS
.IP \(bu 2
Install the latest version of a tool:
.RE
.PP
\fB\fCvolta install {{node|npm|yarn|package_name}}\fR
.RS
.IP \(bu 2
Install a specific version of a tool:
.RE
.PP
\fB\fCvolta install {{node|npm|yarn}}@version\fR
.RS
.IP \(bu 2
Choose a tool version for a project (will store it in \fB\fCpackage.json\fR):
.RE
.PP
\fB\fCvolta pin {{node|npm|yarn}}@version\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCvolta help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCvolta help {{fetch|install|uninstall|pin|list|completions|which|setup|run|help}}\fR
