.TH vue serve
.PP
.RS
A subcommand provided by \fB\fC@vue/cli\fR and \fB\fC@vue/cli\-service\-global\fR that enables quick prototyping.
More information: \[la]https://cli.vuejs.org/guide/prototyping.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Serve a \fB\fC\&.js\fR or \fB\fC\&.vue\fR file in development mode with zero config:
.RE
.PP
\fB\fCvue serve {{filename}}\fR
