.TH vue init
.PP
.RS
Legacy project initialization subcommand of the Vue.js framework.
More information: \[la]https://cli.vuejs.org/guide/creating-a-project.html#pulling-2-x-templates-legacy\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new project using one of the default templates:
.RE
.PP
\fB\fCvue init {{webpack|webpack\-simple|browserify|browserify\-simple|simple}} {{project_name}}\fR
.RS
.IP \(bu 2
Create a new project using a local template:
.RE
.PP
\fB\fCvue init {{path/to/template_directory}} {{project_name}}\fR
.RS
.IP \(bu 2
Create a new project using a template from GitHub:
.RE
.PP
\fB\fCvue init {{username}}/{{repo}} {{project_name}}\fR
