.TH vue
.PP
.RS
Multi\-purpose CLI for Vue.js.
Some subcommands such as \fB\fCvue build\fR have their own usage documentation.
More information: \[la]https://cli.vuejs.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a new Vue project interactively:
.RE
.PP
\fB\fCvue create {{project_name}}\fR
.RS
.IP \(bu 2
Create a new project with web UI:
.RE
.PP
\fB\fCvue ui\fR
