.TH w
.PP
.RS
Show who is logged on and what they are doing.
Print user login, TTY, remote host, login time, idle time, current process.
More information: \[la]https://manned.org/w\[ra]\&.
.RE
.RS
.IP \(bu 2
Show logged\-in users info:
.RE
.PP
\fB\fCw\fR
.RS
.IP \(bu 2
Show logged\-in users info without a header:
.RE
.PP
\fB\fCw \-h\fR
