.TH w3m
.PP
.RS
A text\-based web browser.
Supports SSL and mouse input, even over SSH.
More information: \[la]https://w3m.sourceforge.net\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a URL:
.RE
.PP
\fB\fCw3m {{https://example.com}}\fR
.RS
.IP \(bu 2
Open a URL in monochrome mode:
.RE
.PP
\fB\fCw3m {{https://example.com}} \-M\fR
.RS
.IP \(bu 2
Open a URL without mouse support:
.RE
.PP
\fB\fCw3m {{https://example.com}} \-no\-mouse\fR
.RS
.IP \(bu 2
Open a new browser tab:
.RE
.PP
\fB\fCShift + T\fR
.RS
.IP \(bu 2
Display your browser history:
.RE
.PP
\fB\fCCtrl + H\fR
.RS
.IP \(bu 2
Quit w3m:
.RE
.PP
\fB\fC\&'q' followed by 'y'\fR
