.TH wait
.PP
.RS
Wait for a process to complete before proceeding.
More information: \[la]https://manned.org/wait\[ra]\&.
.RE
.RS
.IP \(bu 2
Wait for a process to finish given its process ID (PID) and return its exit status:
.RE
.PP
\fB\fCwait {{pid}}\fR
.RS
.IP \(bu 2
Wait for all processes known to the invoking shell to finish:
.RE
.PP
\fB\fCwait\fR
