.TH wal
.PP
.RS
A tool to create color schemes based on the dominant colors of a wallpaper.
More information: \[la]https://github.com/dylanaraps/pywal\[ra]\&.
.RE
.RS
.IP \(bu 2
Preview color scheme:
.RE
.PP
\fB\fCwal \-\-preview {{image.png}}\fR
.RS
.IP \(bu 2
Create color scheme:
.RE
.PP
\fB\fCwal \-i {{image.png}}\fR
.RS
.IP \(bu 2
Create a light color scheme:
.RE
.PP
\fB\fCwal \-i {{image.png}} \-l\fR
.RS
.IP \(bu 2
Skip setting the desktop wallpaper:
.RE
.PP
\fB\fCwal \-i {{image.png}} \-n\fR
.RS
.IP \(bu 2
Skip setting the terminal colors:
.RE
.PP
\fB\fCwal \-i {{image.png}} \-s\fR
.RS
.IP \(bu 2
Restore the previously generated color scheme and wallpaper:
.RE
.PP
\fB\fCwal \-R\fR
