.TH warp\-cli
.PP
.RS
Official command\-line client for Cloudflare's WARP service.
More information: \[la]https://developers.cloudflare.com/warp-client/\[ra]\&.
.RE
.RS
.IP \(bu 2
Register the current device to WARP (must be run before first connection):
.RE
.PP
\fB\fCwarp\-cli register\fR
.RS
.IP \(bu 2
Connect to WARP:
.RE
.PP
\fB\fCwarp\-cli connect\fR
.RS
.IP \(bu 2
Disconnect from WARP:
.RE
.PP
\fB\fCwarp\-cli disconnect\fR
.RS
.IP \(bu 2
Display the WARP connection status:
.RE
.PP
\fB\fCwarp\-cli status\fR
.RS
.IP \(bu 2
Display help:
.RE
.PP
\fB\fCwarp\-cli help\fR
.RS
.IP \(bu 2
Display help for a subcommand:
.RE
.PP
\fB\fCwarp\-cli help {{subcommand}}\fR
