.TH wasm2wat
.PP
.RS
Convert a file from the WebAssembly binary format to the text format.
More information: \[la]https://github.com/WebAssembly/wabt\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert a file to the text format and display it to the console:
.RE
.PP
\fB\fCwasm2wat {{file.wasm}}\fR
.RS
.IP \(bu 2
Write the output to a given file:
.RE
.PP
\fB\fCwasm2wat {{file.wasm}} \-o {{file.wat}}\fR
