.TH watson
.PP
.RS
A wonderful CLI to track your time.
More information: \[la]https://github.com/TailorDev/Watson\[ra]\&.
.RE
.RS
.IP \(bu 2
Start monitoring time in project:
.RE
.PP
\fB\fCwatson start {{project}}\fR
.RS
.IP \(bu 2
Start monitoring time in project with tags:
.RE
.PP
\fB\fCwatson start {{project}} +{{tag}}\fR
.RS
.IP \(bu 2
Stop monitoring time for the current project:
.RE
.PP
\fB\fCwatson stop\fR
.RS
.IP \(bu 2
Display the latest working sessions:
.RE
.PP
\fB\fCwatson log\fR
.RS
.IP \(bu 2
Edit most recent frame:
.RE
.PP
\fB\fCwatson edit\fR
.RS
.IP \(bu 2
Remove most recent frame:
.RE
.PP
\fB\fCwatson remove\fR
