.TH weechat
.PP
.RS
Command\-line internet relay chat client with various features.
More information: \[la]https://weechat.org/doc\[ra]\&.
.RE
.RS
.IP \(bu 2
Start WeeChat:
.RE
.PP
\fB\fCweechat\fR
.RS
.IP \(bu 2
Do not load any 
.BR plugin (s) 
on startup:
.RE
.PP
\fB\fCweechat \-\-no\-plugin\fR
.RS
.IP \(bu 2
Do not load any 
.BR script (s) 
on startup:
.RE
.PP
\fB\fCweechat \-\-no\-script\fR
.RS
.IP \(bu 2
Do not connect to servers automatically:
.RE
.PP
\fB\fCweechat \-\-no\-connect\fR
.RS
.IP \(bu 2
Write default terminal colors to \fB\fCstdout\fR:
.RE
.PP
\fB\fCweechat \-\-colors\fR
