.TH wfuzz
.PP
.RS
A web application bruteforcer.
More information: \[la]https://wfuzz.readthedocs.io/en/latest/user/basicusage.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Directory and file bruteforce using the specified wordlist and also proxying the traffic:
.RE
.PP
\fB\fCwfuzz \-w {{path/to/file}} \-p {{127.0.0.1:8080}} {{http://example.com/FUZZ}}\fR
.RS
.IP \(bu 2
Save the results to a file:
.RE
.PP
\fB\fCwfuzz \-w {{path/to/file}} \-f {{filename}} {{http://example.com/FUZZ}}\fR
.RS
.IP \(bu 2
Show colorized output while only showing the declared response codes in the output:
.RE
.PP
\fB\fCwfuzz \-c \-w {{path/to/file}} \-\-sc {{200,301,302}} {{http://example.com/FUZZ}}\fR
.RS
.IP \(bu 2
Use a custom header to fuzz subdomains while hiding specific response codes and word counts. Increase the threads to 100 and include the target ip/domain:
.RE
.PP
\fB\fCwfuzz \-w {{path/to/file}} \-H {{"Host: FUZZ.example.com"}} \-\-hc {{301}} \-\-hw {{222}} \-t {{100}} {{example.com}}\fR
