.TH which
.PP
.RS
Locate a program in the user's path.
More information: \[la]https://manned.org/which\[ra]\&.
.RE
.RS
.IP \(bu 2
Search the PATH environment variable and display the location of any matching executables:
.RE
.PP
\fB\fCwhich {{executable}}\fR
.RS
.IP \(bu 2
If there are multiple executables which match, display all:
.RE
.PP
\fB\fCwhich \-a {{executable}}\fR
