.TH whois
.PP
.RS
Command\-line client for the WHOIS (RFC 3912) protocol.
More information: \[la]https://github.com/rfc1036/whois\[ra]\&.
.RE
.RS
.IP \(bu 2
Get information about a domain name:
.RE
.PP
\fB\fCwhois {{example.com}}\fR
.RS
.IP \(bu 2
Get information about an IP address:
.RE
.PP
\fB\fCwhois {{8.8.8.8}}\fR
.RS
.IP \(bu 2
Get abuse contact for an IP address:
.RE
.PP
\fB\fCwhois \-b {{8.8.8.8}}\fR
