.TH wipeclean
.PP
.RS
Clear the terminal screen using an animated wiper.
More information: \[la]https://github.com/JeanJouliaCode/wipeClean\[ra]\&.
.RE
.RS
.IP \(bu 2
Clear the terminal screen:
.RE
.PP
\fB\fCwipeclean\fR
.RS
.IP \(bu 2
Set the animation speed in frames per second (defaults to 150):
.RE
.PP
\fB\fCwipeclean \-\-speed {{speed}}\fR
