.TH wordgrinder
.PP
.RS
Command\-line word processor.
More information: \[la]https://cowlark.com/wordgrinder\[ra]\&.
.RE
.RS
.IP \(bu 2
Start WordGrinder (loads a blank document by default):
.RE
.PP
\fB\fCwordgrinder\fR
.RS
.IP \(bu 2
Open a given file:
.RE
.PP
\fB\fCwordgrinder {{filename}}\fR
.RS
.IP \(bu 2
Show the menu:
.RE
.PP
\fB\fCAlt + M\fR
