.TH wormhole
.PP
.RS
Get things from one computer to another, safely.
More information: \[la]https://magic-wormhole.readthedocs.io\[ra]\&.
.RE
.RS
.IP \(bu 2
Send a file:
.RE
.PP
\fB\fCwormhole send {{path/to/file}}\fR
.RS
.IP \(bu 2
Receive a file:
.RE
.PP
\fB\fCwormhole receive {{wormhole_code}}\fR
.RS
.IP \(bu 2
Send raw text:
.RE
.PP
\fB\fCwormhole send\fR
