.TH wpa_supplicant
.PP
.RS
Manage protected wireless networks.
More information: \[la]https://manned.org/wpa_supplicant.1\[ra]\&.
.RE
.RS
.IP \(bu 2
Join a protected wireless network:
.RE
.PP
\fB\fCwpa_supplicant \-i {{interface}} \-c {{path/to/wpa_supplicant_conf.conf}}\fR
.RS
.IP \(bu 2
Join a protected wireless network and run it in a daemon:
.RE
.PP
\fB\fCwpa_supplicant \-B \-i {{interface}} \-c {{path/to/wpa_supplicant_conf.conf}}\fR
