.TH wpm
.PP
.RS
Typeracer\-like console app for measuring your WPM.
More information: \[la]https://github.com/cslarsen/wpm\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCwpm\fR:
.RE
.PP
\fB\fCwpm\fR
.RS
.IP \(bu 2
Start \fB\fCwpm\fR with short texts:
.RE
.PP
\fB\fCwpm \-\-short\fR
.RS
.IP \(bu 2
Start \fB\fCwpm\fR using a specific text file:
.RE
.PP
\fB\fCwpm \-\-load {{path/to/file.txt}}\fR
.RS
.IP \(bu 2
Tag your race scores:
.RE
.PP
\fB\fCwpm \-\-tag {{tag_name}}\fR
.RS
.IP \(bu 2
Show score statistics grouped by tags:
.RE
.PP
\fB\fCwpm \-\-stats\fR
.RS
.IP \(bu 2
Start \fB\fCwpm\fR with monochrome colors:
.RE
.PP
\fB\fCwpm \-\-monochrome\fR
