.TH wuzz
.PP
.RS
Tool to interactively inspect HTTP requests and responses.
More information: \[la]https://github.com/asciimoo/wuzz\[ra]\&.
.RE
.RS
.IP \(bu 2
Start \fB\fCwuzz\fR:
.RE
.PP
\fB\fCwuzz\fR
.RS
.IP \(bu 2
Display help information:
.RE
.PP
\fB\fCF1\fR
.RS
.IP \(bu 2
Send an HTTP request:
.RE
.PP
\fB\fCCtrl + R\fR
.RS
.IP \(bu 2
Switch to the next view:
.RE
.PP
\fB\fCCtrl + J, Tab\fR
.RS
.IP \(bu 2
Switch to the previous view:
.RE
.PP
\fB\fCCtrl + K, Shift + Tab\fR
