.TH xar
.PP
.RS
Manage .xar archives.
More information: \[la]https://manned.org/xar\[ra]\&.
.RE
.RS
.IP \(bu 2
Create a xar archive of all files in a given directory:
.RE
.PP
\fB\fCxar \-cf {{archive.xar}} {{path/to/directory}}\fR
.RS
.IP \(bu 2
List the contents of a given xar archive:
.RE
.PP
\fB\fCxar \-tf {{archive.xar}}\fR
.RS
.IP \(bu 2
Extract the contents of a given xar archive to the current directory:
.RE
.PP
\fB\fCxar \-xf {{archive.xar}}\fR
