.TH xcv
.PP
.RS
Cut, copy, and paste in the command\-line.
More information: \[la]https://github.com/busterc/xcv\[ra]\&.
.RE
.RS
.IP \(bu 2
Cut a file:
.RE
.PP
\fB\fCxcv x {{input_file}}\fR
.RS
.IP \(bu 2
Copy a file:
.RE
.PP
\fB\fCxcv c {{input_file}}\fR
.RS
.IP \(bu 2
Paste a file:
.RE
.PP
\fB\fCxcv v {{output_file}}\fR
.RS
.IP \(bu 2
List files available for pasting:
.RE
.PP
\fB\fCxcv l\fR
