.TH xkcdpass
.PP
.RS
A flexible and scriptable password generator which generates strong passphrases.
Inspired by XKCD 936.
More information: \[la]https://github.com/redacted/XKCD-password-generator\[ra]\&.
.RE
.RS
.IP \(bu 2
Generate one passphrase with the default options:
.RE
.PP
\fB\fCxkcdpass\fR
.RS
.IP \(bu 2
Generate one passphrase whose first letters of each word match the provided argument:
.RE
.PP
\fB\fCxkcdpass \-a {{acrostic}}\fR
.RS
.IP \(bu 2
Generate passwords interactively:
.RE
.PP
\fB\fCxkcdpass \-i\fR
