.TH xml list
.PP
.RS
List a directory's contents (like \fB\fCls\fR) in XML format.
More information: \[la]http://xmlstar.sourceforge.net/docs.php\[ra]\&.
.RE
.RS
.IP \(bu 2
Write the current directory's listing to an XML document:
.RE
.PP
\fB\fCxml list > {{path/to/dir_list.xml}}\fR
.RS
.IP \(bu 2
Write the specified directory's listing to an XML document:
.RE
.PP
\fB\fCxml list {{path/to/directory}} > {{path/to/dir_list.xml}}\fR
.RS
.IP \(bu 2
Display help for the \fB\fClist\fR subcommand:
.RE
.PP
\fB\fCxml list \-\-help\fR
