.TH xo
.PP
.RS
A pluggable, zero\-configuration linting utility for JavaScript.
More information: \[la]https://github.com/xojs/xo\[ra]\&.
.RE
.RS
.IP \(bu 2
Lint files in the "src" directory:
.RE
.PP
\fB\fCxo\fR
.RS
.IP \(bu 2
Lint a given set of files:
.RE
.PP
\fB\fCxo {{file1}}.js {{file2}}.js\fR
.RS
.IP \(bu 2
Automatically fix any lint issues found:
.RE
.PP
\fB\fCxo \-\-fix\fR
.RS
.IP \(bu 2
Lint using spaces as indentation instead of tabs:
.RE
.PP
\fB\fCxo \-\-space\fR
.RS
.IP \(bu 2
Lint using the "prettier" code style:
.RE
.PP
\fB\fCxo \-\-prettier\fR
