.TH xprop
.PP
.RS
A tool for displaying window and font properties in an X server.
More information: \[la]https://manned.org/xprop\[ra]\&.
.RE
.RS
.IP \(bu 2
Display the name of the root window:
.RE
.PP
\fB\fCxprop \-root WM_NAME\fR
.RS
.IP \(bu 2
Display the window manager hints for a window:
.RE
.PP
\fB\fCxprop \-name "{{window_name}}" WM_HINTS\fR
.RS
.IP \(bu 2
Display the point size of a font:
.RE
.PP
\fB\fCxprop \-font "{{font_name}}" POINT_SIZE\fR
.RS
.IP \(bu 2
Display all the properties of the window with the id 0x200007:
.RE
.PP
\fB\fCxprop \-id {{0x200007}}\fR
