.TH xsp
.PP
.RS
Mono ASP.NET Web Server.
More information: \[la]https://www.mono-project.com/docs/web/aspnet/\[ra]\&.
.RE
.RS
.IP \(bu 2
Listen on all interfaces (\fB\fC0.0.0.0\fR) and port \fB\fC8080\fR:
.RE
.PP
\fB\fCxsp\fR
.RS
.IP \(bu 2
Listen on a specific IP address and port:
.RE
.PP
\fB\fCxsp \-\-address {{127.0.0.1}} \-\-port {{8000}}\fR
