.TH xzcmp
.PP
.RS
Invokes \fB\fCcmp\fR on files compressed with \fB\fCxz\fR, \fB\fClzma\fR, \fB\fCgzip\fR, \fB\fCbzip2\fR, \fB\fClzop\fR, or \fB\fCzstd\fR\&.
All options specified are passed directly to \fB\fCcmp\fR\&.
More information: \[la]https://manned.org/xzcmp\[ra]\&.
.RE
.RS
.IP \(bu 2
Compare two specific files:
.RE
.PP
\fB\fCxzcmp {{path/to/file1}} {{path/to/file2}}\fR
