.TH xzmore
.PP
.RS
Display text from \fB\fCxz\fR or \fB\fClzma\fR compressed files.
Almost equivalent to \fB\fCxzless\fR, except it respects the \fB\fCPAGER\fR environment variable, uses \fB\fCmore\fR by default and you cannot pass options to the pager.
More information: \[la]https://manned.org/xzmore\[ra]\&.
.RE
.RS
.IP \(bu 2
View a compressed file:
.RE
.PP
\fB\fCxzmore {{path/to/file}}\fR
