.TH yard
.PP
.RS
Documentation tool for Ruby.
More information: \[la]https://yardoc.org/\[ra]\&.
.RE
.RS
.IP \(bu 2
Create the documentation:
.RE
.PP
\fB\fCyard\fR
.RS
.IP \(bu 2
Create the documentation and save it to one file:
.RE
.PP
\fB\fCyard \-\-one\-file\fR
.RS
.IP \(bu 2
List all undocumented objects:
.RE
.PP
\fB\fCyard stats \-\-list\-undoc\fR
