.TH ykinfo
.PP
.RS
Get basic information from a YubiKey.
More information: \[la]https://developers.yubico.com/yubikey-personalization/Manuals/ykinfo.1.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Display all information from YubiKey:
.RE
.PP
\fB\fCykinfo \-a\fR
.RS
.IP \(bu 2
Get only serial in decimal from YubiKey:
.RE
.PP
\fB\fCykinfo \-s \-q\fR
.RS
.IP \(bu 2
Get capabilities from YubiKey:
.RE
.PP
\fB\fCykinfo \-c\fR
