.TH youtube\-viewer
.PP
.RS
Command\-line application for searching and playing videos from YouTube.
More information: \[la]https://github.com/trizen/youtube-viewer\[ra]\&.
.RE
.RS
.IP \(bu 2
Search for a video:
.RE
.PP
\fB\fCyoutube\-viewer {{search_term}}\fR
.RS
.IP \(bu 2
Log in to your YouTube account:
.RE
.PP
\fB\fCyoutube\-viewer \-\-login\fR
.RS
.IP \(bu 2
Watch a video with a specific URL in VLC:
.RE
.PP
\fB\fCyoutube\-viewer \-\-player={{vlc}} {{https://youtube.com/watch?v=dQw4w9WgXcQ}}\fR
.RS
.IP \(bu 2
Display a search prompt and play the selected video in 720p:
.RE
.PP
\fB\fCyoutube\-viewer \-{{7}}\fR
