.TH yt\-dlp
.PP
.RS
A youtube\-dl fork with additional features and fixes.
Download videos from YouTube and other websites.
More information: \[la]https://github.com/yt-dlp/yt-dlp\[ra]\&.
.RE
.RS
.IP \(bu 2
Download a video or playlist (with the default options from command below):
.RE
.PP
\fB\fCyt\-dlp "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"\fR
.RS
.IP \(bu 2
List the available downloadable formats for a video:
.RE
.PP
\fB\fCyt\-dlp \-\-list\-formats "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"\fR
.RS
.IP \(bu 2
Download a video with a defined format, in this case the best mp4 video available (default is "bv*+ba/b"):
.RE
.PP
\fB\fCyt\-dlp \-\-format "{{bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]}}" "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"\fR
.RS
.IP \(bu 2
Extract audio from a video (requires ffmpeg or ffprobe):
.RE
.PP
\fB\fCyt\-dlp \-\-extract\-audio "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"\fR
.RS
.IP \(bu 2
Specify audio format and audio quality of extracted audio (between 0 (best) and 10 (worst), default = 5):
.RE
.PP
\fB\fCyt\-dlp \-\-extract\-audio \-\-audio\-format {{mp3}} \-\-audio\-quality {{0}} "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"\fR
.RS
.IP \(bu 2
Download all playlists of YouTube channel/user keeping each playlist in separate directory:
.RE
.PP
\fB\fCyt\-dlp \-o "{{%(uploader)s/%(playlist)s/%(playlist_index)s \- %(title)s.%(ext)s}}" "{{https://www.youtube.com/user/TheLinuxFoundation/playlists}}"\fR
.RS
.IP \(bu 2
Download Udemy course keeping each chapter in separate directory under MyVideos directory in your home:
.RE
.PP
\fB\fCyt\-dlp \-u {{user}} \-p {{password}} \-P "{{~/MyVideos}}" \-o "{{%(playlist)s/%(chapter_number)s \- %(chapter)s/%(title)s.%(ext)s}}" "{{https://www.udemy.com/java\-tutorial}}"\fR
.RS
.IP \(bu 2
Download entire series season keeping each series and each season in separate directory under C:/MyVideos:
.RE
.PP
\fB\fCyt\-dlp \-P "{{C:/MyVideos}}" \-o "{{%(series)s/%(season_number)s \- %(season)s/%(episode_number)s \- %(episode)s.%(ext)s}}" "{{https://videomore.ru/kino_v_detalayah/5_sezon/367617}}"\fR
