.TH zcat
.PP
.RS
Print data from gzip compressed files.
More information: \[la]https://www.gnu.org/software/gzip/manual/gzip.html\[ra]\&.
.RE
.RS
.IP \(bu 2
Print the uncompressed contents of a gzipped file to \fB\fCstdout\fR:
.RE
.PP
\fB\fCzcat {{file.txt.gz}}\fR
.RS
.IP \(bu 2
Print compression details of a gzipped file to \fB\fCstdout\fR:
.RE
.PP
\fB\fCzcat \-l {{file.txt.gz}}\fR
