.TH zcmp
.PP
.RS
Compare compressed files.
More information: \[la]https://manned.org/zcmp\[ra]\&.
.RE
.RS
.IP \(bu 2
Invoke \fB\fCcmp\fR on two files compressed via \fB\fCgzip\fR:
.RE
.PP
\fB\fCzcmp {{path/to/file1.gz}} {{path/to/file2.gz}}\fR
.RS
.IP \(bu 2
Compare a file to its gzipped version (assuming \fB\fC\&.gz\fR exists already):
.RE
.PP
\fB\fCzcmp {{path/to/file}}\fR
