.TH zdb
.PP
.RS
ZFS debugger.
More information: \[la]https://manned.org/zdb\[ra]\&.
.RE
.RS
.IP \(bu 2
Show detailed configuration of all mounted ZFS zpools:
.RE
.PP
\fB\fCzdb\fR
.RS
.IP \(bu 2
Show detailed configuration for a specific ZFS pool:
.RE
.PP
\fB\fCzdb \-C {{poolname}}\fR
.RS
.IP \(bu 2
Show statistics about number, size and deduplication of blocks:
.RE
.PP
\fB\fCzdb \-b {{poolname}}\fR
