.TH zeisstopnm
.PP
.RS
Convert a Zeiss confocal file to Netbpm format.
More information: \[la]https://manned.org/zeisstopnm.1\[ra]\&.
.RE
.RS
.IP \(bu 2
Convert a Zeiss cofocal file into either \fB\fC\&.pgm\fR or \fB\fC\&.ppm\fR format:
.RE
.PP
\fB\fCzeisstopnm {{path/to/file}}\fR
.RS
.IP \(bu 2
Convert a Zeiss cofocal file to Netbpm format while explicitly specifying the target file type:
.RE
.PP
\fB\fCzeisstopnm \-{{pgm|ppm}} {{path/to/file}}\fR
