.TH zellij
.PP
.RS
Terminal multiplexer with batteries included.
See also \fB\fCtmux\fR and \fB\fCscreen\fR\&.
More information: \[la]https://zellij.dev/documentation/\[ra]\&.
.RE
.RS
.IP \(bu 2
Start a new named session:
.RE
.PP
\fB\fCzellij \-\-session {{name}}\fR
.RS
.IP \(bu 2
List existing sessions:
.RE
.PP
\fB\fCzellij list\-sessions\fR
.RS
.IP \(bu 2
Attach to the most recently used session:
.RE
.PP
\fB\fCzellij attach\fR
.RS
.IP \(bu 2
Open a new pane (inside a zellij session):
.RE
.PP
\fB\fCAlt + N\fR
.RS
.IP \(bu 2
Detach from the current session (inside a zellij session):
.RE
.PP
\fB\fCCtrl + O, D\fR
