.TH zfgrep
.PP
.RS
Matches fixed strings in possibly compressed files.
Equivalent to \fB\fCgrep \-F\fR with input decompressed first if necessary.
More information: \[la]https://manned.org/zfgrep\[ra]\&.
.RE
.RS
.IP \(bu 2
Search for an exact string in a file:
.RE
.PP
\fB\fCzfgrep {{search_string}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Count the number of lines that match the given string in a file:
.RE
.PP
\fB\fCzfgrep \-\-count {{search_string}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Show the line number in the file along with the matching lines:
.RE
.PP
\fB\fCzfgrep \-\-line\-number {{search_string}} {{path/to/file}}\fR
.RS
.IP \(bu 2
Display all lines except those that contain the search string:
.RE
.PP
\fB\fCzfgrep \-\-invert\-match {{search_string}} {{path/to/file}}\fR
.RS
.IP \(bu 2
List only filenames whose content matches the search string at least once:
.RE
.PP
\fB\fCzfgrep \-\-files\-with\-matches {{search_string}} {{path/to/file1 path/to/file2 ...}}\fR
