.TH zig
.PP
.RS
The Zig compiler and toolchain.
More information: \[la]https://ziglang.org\[ra]\&.
.RE
.RS
.IP \(bu 2
Compile the project in the current directory:
.RE
.PP
\fB\fCzig build\fR
.RS
.IP \(bu 2
Compile and run the project in the current directory:
.RE
.PP
\fB\fCzig build run\fR
.RS
.IP \(bu 2
Initialize a \fB\fCzig build\fR application:
.RE
.PP
\fB\fCzig init\-exe\fR
.RS
.IP \(bu 2
Initialize a \fB\fCzig build\fR library:
.RE
.PP
\fB\fCzig init\-lib\fR
.RS
.IP \(bu 2
Create and run a test build:
.RE
.PP
\fB\fCzig test {{path/to/file.zig}}\fR
.RS
.IP \(bu 2
Reformat Zig source into canonical form:
.RE
.PP
\fB\fCzig fmt {{path/to/file.zig}}\fR
.RS
.IP \(bu 2
Use Zig as a drop\-in C compiler:
.RE
.PP
\fB\fCzig cc {{path/to/file.c}}\fR
.RS
.IP \(bu 2
Use Zig as a drop\-in C++ compiler:
.RE
.PP
\fB\fCzig c++ {{path/to/file.cpp}}\fR
