.TH zipinfo
.PP
.RS
List detailed information about the contents of a \fB\fC\&.zip\fR file.
More information: \[la]https://manned.org/zipinfo\[ra]\&.
.RE
.RS
.IP \(bu 2
List all files in a \fB\fC\&.zip\fR file in long format (permissions, ownership, size, and modification date):
.RE
.PP
\fB\fCzipinfo {{path/to/archive.zip}}\fR
.RS
.IP \(bu 2
List all files in a \fB\fC\&.zip\fR file:
.RE
.PP
\fB\fCzipinfo \-1 {{path/to/archive.zip}}\fR
