.TH zm
.PP
.RS
A tool for managing articles of newspapers and blogs.
More information: \[la]https://github.com/ZERMZeitung/zm2\[ra]\&.
.RE
.RS
.IP \(bu 2
Make a new draft:
.RE
.PP
\fB\fCzm new\fR
.RS
.IP \(bu 2
Edit a draft:
.RE
.PP
\fB\fCzm edit\fR
.RS
.IP \(bu 2
Publish a draft and commit it with git:
.RE
.PP
\fB\fCzm publish\fR
