.TH zmore
.PP
.RS
View gzip compressed files with \fB\fCmore\fR\&.
More information: \[la]https://manned.org/zmore\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a compressed file:
.RE
.PP
\fB\fCzmore {{path/to/file.txt.gz}}\fR
.RS
.IP \(bu 2
Display the next page of the file:
.RE
.PP
\fB\fC<Space>\fR
.RS
.IP \(bu 2
Search for a pattern in the file (press \fB\fCn\fR to go to next match):
.RE
.PP
\fB\fC/{{regular_expression}}\fR
.RS
.IP \(bu 2
Exit:
.RE
.PP
\fB\fCq\fR
.RS
.IP \(bu 2
Display interactive command help:
.RE
.PP
\fB\fCh\fR
