.TH zopflipng
.PP
.RS
PNG compression utility.
More information: \[la]https://github.com/google/zopfli\[ra]\&.
.RE
.RS
.IP \(bu 2
Optimize a PNG:
.RE
.PP
\fB\fCzopflipng {{input.png}} {{output.png}}\fR
.RS
.IP \(bu 2
Optimize several PNGs and save with given prefix:
.RE
.PP
\fB\fCzopflipng \-\-prefix={{prefix}} {{image1.png}} {{image2.png}} {{image3.png}}\fR
