.TH zotero
.PP
.RS
Manage your bibliographies.
More information: \[la]https://www.zotero.org/support\[ra]\&.
.RE
.RS
.IP \(bu 2
Run with the GUI:
.RE
.PP
\fB\fCzotero\fR
.RS
.IP \(bu 2
Run in headless mode:
.RE
.PP
\fB\fCzotero \-\-headless\fR
.RS
.IP \(bu 2
Run with a specific profile:
.RE
.PP
\fB\fCzotero \-P {{profile}}\fR
.RS
.IP \(bu 2
Run the Migration Assistant:
.RE
.PP
\fB\fCzotero \-\-migration\fR
