.TH zstdless
.PP
.RS
Open a \fB\fCzstd\fR compressed file for interactive reading, allowing scrolling and search.
See also: \fB\fCzstd\fR, \fB\fCless\fR\&.
More information: \[la]https://manned.org/zstdless\[ra]\&.
.RE
.RS
.IP \(bu 2
Open a \fB\fCzstd\fR compressed file:
.RE
.PP
\fB\fCzstdless {{path/to/file.zst}}\fR
