-- [nfnl] Compiled from fnl/plugins/config/diffview.fnl by https://github.com/Olical/nfnl, do not edit.
local config = {}
local function cb(str)
  return (require("diffview.config")).diffview_callback(str)
end
config.setup = function()
  return (require("diffview")).setup({file_history_panel = {win_config = {height = 21, position = "bottom", width = 35}}, file_panel = {listing_style = "tree", tree_options = {flatten_dirs = true, folder_statuses = "always"}, win_config = {height = 10, position = "left", width = 35}}, icons = {folder_closed = "\238\151\191", folder_open = "\238\151\190"}, key_bindings = {file_history_panel = {["<2-LeftMouse>"] = cb("select_entry"), ["<C-d>"] = cb("open_in_diffview"), ["<C-w><C-f>"] = cb("goto_file_split"), ["<C-w>gf"] = cb("goto_file_tab"), ["<cr>"] = cb("select_entry"), ["<down>"] = cb("next_entry"), ["<leader>b"] = cb("toggle_files"), ["<leader>e"] = cb("focus_files"), ["<s-tab>"] = cb("select_prev_entry"), ["<tab>"] = cb("select_next_entry"), ["<up>"] = cb("prev_entry"), ["g!"] = cb("options"), gf = cb("goto_file"), j = cb("next_entry"), k = cb("prev_entry"), o = cb("select_entry"), zM = cb("close_all_folds"), zR = cb("open_all_folds")}, file_panel = {["-"] = cb("toggle_stage_entry"), ["<2-LeftMouse>"] = cb("select_entry"), ["<C-w><C-f>"] = cb("goto_file_split"), ["<C-w>gf"] = cb("goto_file_tab"), ["<cr>"] = cb("select_entry"), ["<down>"] = cb("next_entry"), ["<leader>b"] = cb("toggle_files"), ["<leader>e"] = cb("focus_files"), ["<s-tab>"] = cb("select_prev_entry"), ["<tab>"] = cb("select_next_entry"), ["<up>"] = cb("prev_entry"), R = cb("refresh_files"), S = cb("stage_all"), U = cb("unstage_all"), X = cb("restore_entry"), f = cb("toggle_flatten_dirs"), gf = cb("goto_file"), i = cb("listing_style"), j = cb("next_entry"), k = cb("prev_entry"), o = cb("select_entry")}, option_panel = {["<tab>"] = cb("select"), q = cb("close")}, view = {["<C-w><C-f>"] = cb("goto_file_split"), ["<C-w>gf"] = cb("goto_file_tab"), ["<leader>b"] = cb("toggle_files"), ["<leader>e"] = cb("focus_files"), ["<s-tab>"] = cb("select_prev_entry"), ["<tab>"] = cb("select_next_entry"), gf = cb("goto_file")}, disable_defaults = false}, signs = {fold_closed = "\239\145\160", fold_open = "\239\145\188"}, use_icons = true, enhanced_diff_hl = false, diff_binaries = false})
end
return config
